extends Node3D

#class_name TaskData
# x is inline with the elevator doors smaller way from the the elevator
# y is up and down
# z is right and left of the elevator doors lager closer to the elevator
# Embedded JSON data converted from your CSV
const TASKS_JSON := [
	{
		"task_name": "First There Was Code",
		"lookup_name": "first_code",
		"description": "First There Was Code transforms a featureless void into a fully interactive VR world through a gradual, animated unveiling of digital structures and interfaces.",
		"start_string": "First there was nothing",
		"x_position": -8.6, 
		"y_position": 0.5,
		"z_position": 14.8,
		"success_string": "Griding",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/FirstThereWasCode/first_there_was_code.tscn"
 	},
	{
		"task_name": "Init Grid",
		"lookup_name": "init_grid",
		"description": "First There Was Code transforms a featureless void into a fully interactive VR world through a gradual, animated unveiling of digital structures and interfaces.",
		"start_string": "First there was nothing",
		"x_position": -8.6, 
		"y_position": 0.5,
		"z_position": 14.8,
		"success_string": "Griding",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/Cubes/cube_sequence_array.tscn"
 	},
	{
		"task_name": "Grid array",
		"lookup_name": "grid_array",
		"description": "First There Was Code transforms a featureless void into a fully interactive VR world through a gradual, animated unveiling of digital structures and interfaces.",
		"start_string": "First there was nothing",
		"x_position": -8.6, 
		"y_position": 0.5,
		"z_position": 14.8,
		"success_string": "Griding",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/Cubes/cube_sequence_array_explained.tscn"
 	},
	{
		"task_name": "Mondrian 2d",
		"lookup_name": "mondrian_2d",
		"description": "First There Was Code transforms a featureless void into a fully interactive VR world through a gradual, animated unveiling of digital structures and interfaces.",
		"start_string": "First there was nothing",
		"x_position": -8.6, 
		"y_position": 0.5,
		"z_position": 14.8,
		"success_string": "Griding",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/CombineGrids/Mondrian2d/mondrian_2d.tscn"
 	},
	{
		"task_name": "Zelda Tilemap",
		"lookup_name": "zelda_tilemap",
		"description": "First There Was Code transforms a featureless void into a fully interactive VR world through a gradual, animated unveiling of digital structures and interfaces.",
		"start_string": "First there was nothing",
		"x_position": -8.6, 
		"y_position": 0.5,
		"z_position": 14.8,
		"success_string": "Griding",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/CombineGrids/ZeldaTilemap/zelda_tilemap.tscn"
 	},
		{
		"task_name": "Pick Up Cube",
		"lookup_name": "pick_up_cube",
		"description": "First There Was Code transforms a featureless void into a fully interactive VR world through a gradual, animated unveiling of digital structures and interfaces.",
		"start_string": "First there was nothing",
		"x_position": -8.6, 
		"y_position": 0.5,
		"z_position": 14.8,
		"success_string": "Griding",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/Cubes/cube_sequence_pickup.tscn"
 	},
	{
		"task_name": "Grid Control",
		"lookup_name": "grid_control",
		"description": "As algorithms permeate every aspect of our lives, are we increasingly confined to invisible grids of control?",
		"start_string": "Ponder the data grid",
		"x_position": -8.6, 
		"y_position": 0.5,
		"z_position": 14.8,
		"success_string": "Griding",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
 	},
	{
		"task_name": "Moving Panels",
		"lookup_name": "moving_panels",
		"description": "These panels embody a paradoxical dance of attraction and repulsion—drawn to face the player with magnetic fascination yet recoiling with delicate apprehension when approached too closely, creating an ever-shifting field of responsive entities that mirror human social dynamics.",
		"start_string": "Attracted yet shyly retreating.",
		"x_position": -8.6, 
		"y_position": 0.5,
		"z_position": 14.8,
		"success_string": "Griding",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_grid_control.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/MovingPanels/moving_panels.tscn"
 	},
	{
		"task_name": "Random Wood Boxes",
		"lookup_name": "random_wood_boxes",
		"description": "continuously creates wooden cube objects at a fixed position until reaching a maximum limit, after which it replaces random existing cubes with new ones",
		"start_string": "Read ClipBoard",
		"x_position": -14.5, 
		"y_position": 0.5,
		"z_position": 5.5,
		"success_string": "Red ClipBoard about access",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_get_access.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_get_access.mp3",
		"scene": "res://adaresearch/Algorithms/Randomness/ProceduralRandomness/GeometryBased/Scenes/random_object_spawner.tscn"
	},
	{
		"task_name": "Random Walk Collection",
		"lookup_name": "random_walk_collection",
		"description": "continuously creates wooden cube objects at a fixed position until reaching a maximum limit, after which idynamically generated visualization of various random walk patterns that evolve when the object is picked up and stops when dropped",
		"start_string": "Read ClipBoard",
		"x_position": -14.5, 
		"y_position": 0.5,
		"z_position": 5.5,
		"success_string": "Red ClipBoard about access",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_get_access.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_get_access.mp3",
		"scene": "res://adaresearch/Algorithms/Randomness/RandomWalk/Scenes/random_walk_collection.tscn"
	},
	{
		"task_name": "Tune the radio",
		"lookup_name": "tune_radio",
		"description": "Tune the frequencies, Find the hidden message or some nice music.",
		"start_string": "Begin tuning!",
		"x_position": -12.5, 
		"y_position": 0.5,
		"z_position": 2.5,
		"success_string": "Task: Radio tuned -ok",
		"task_space": "RadioSpace",
		"target_object": "RadioObject",
		"amount_required": 100,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_task_tuneradio.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_task_tuneradio.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	},
	{
		"task_name": "Arrange sticker notes",
		"lookup_name": "arrange_stickers",
		"description": "Organize the sticker notes by color",
		"start_string": "Start arranging!",
		"x_position": -17.0,
		"y_position": 0.5,
		"z_position": -2.5,
		"success_string": "Task: Stickers arranged!",
		"task_space": "DeskSpace",
		"target_object": "StickerObject",
		"amount_required": 10,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_task_stickernotes.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_task_stickernotes.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	},
	{
		"task_name": "Explore research images",
		"lookup_name": "explore_images",
		"description": "Look closely at the research images",
		"start_string": "Explore now!",
		"x_position": -17.0,
		"y_position": 0.5,
		"z_position": 3.0,
		"success_string": "Task: Images explored complete",
		"task_space": "GallerySpace",
		"target_object": "ImageObject",
		"amount_required": 5,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_cost_of_complexity.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_cost_of_complexity.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	},
	{
		"task_name": "Draw a Circle",
		"lookup_name": "draw_circle",
		"description": "Create a perfect circle on the canvas",
		"start_string": "Start drawing!",
		"x_position": -18.5,
		"y_position": 0.5,
		"z_position": 0.5,
		"success_string": "Circle drawn!",
		"task_space": "CanvasSpace",
		"target_object": "PenObject",
		"amount_required": 10,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_draw_a_circle.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_draw_a_circle.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	}, 
	{
		"task_name": "See the Queer Eye",
		"lookup_name": "see_queer_eye",
		"description": "Discover the queer perspective through the lens",
		"start_string": "Begin discovery!",
		"x_position": -10.5,
		"y_position": 0.5,
		"z_position": 1.8,
		"success_string": "Perspective seen!",
		"task_space": "LensSpace",
		"target_object": "LensObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_queer_edges.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_queer_edges.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	}, 
	{
		"task_name": "Queer Edge of Entropy",
		"lookup_name": "queer_edge_entropy",
		"description": "Explore the boundaries of order and chaos to discover new edges in a queer world.",
		"start_string": "Step into the edge!",
		"x_position": -8.6,
		"y_position": 0.5,
		"z_position": 0.5,
		"success_string": "New edges discovered!",
		"task_space": "EntropySpace",
		"target_object": "EdgeObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_queer_edge.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_entropy_complete.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	},
	{
		"task_name": "Randomness and Its Limits",
		"lookup_name": "randomness_limits",
		"description": "Investigate the limits and frameworks surrounding randomness in time and space.",
		"start_string": "Begin your exploration!",
		"x_position": -5.5,
		"y_position": 0.5,
		"z_position": 2.0,
		"success_string": "Frameworks uncovered!",
		"task_space": "RandomSpace",
		"target_object": "FrameworkObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_randomness_intro_limits.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_randomness_intro_limits.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	},
	{
		"task_name": "Small Change in Scale and Rotation",
		"lookup_name": "scale_rotation_change",
		"description": "Use minor adjustments in scale and rotation to mimic organic growth.",
		"start_string": "Start scaling!",
		"x_position": -1.0,
		"y_position": 0.5,
		"z_position": 1.5,
		"success_string": "Growth simulated!",
		"task_space": "GrowthSpace",
		"target_object": "GrowthObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_random_scale_rotation_growth.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_random_scale_rotation_growth.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	},
	{
		"task_name": "Randomness and Decay",
		"lookup_name": "randomness_decay",
		"description": "Observe how randomness introduces decay and increases entropy over time.",
		"start_string": "Begin decay!",
		"x_position": -5.8,
		"y_position": 0.5,
		"z_position": -0.6,
		"success_string": "Decay observed!",
		"task_space": "DecaySpace",
		"target_object": "DecayObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_randomness_decay.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_randomness_decay.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	}, 
	{
		"task_name": "Randomness Walk",
		"lookup_name": "randomness_walk",
		"description": "Explore how a random walk creates life-like structures through simple rules of randomness.",
		"start_string": "Begin the walk!",
		"x_position": 0.3,
		"y_position": 0.5,
		"z_position": -0.5,
		"success_string": "Life-like structure discovered!",
		"task_space": "GrowthSpace",
		"target_object": "WalkObject",
		"amount_required": 1,
		"amount_tick": 1.0,
		"amount_multiplier": 1.0,
		"audio_start_file_path": "res://Common/Audio/Instructions/Sarah_random_walk.mp3",
		"audio_complete_file_path": "res://Common/Audio/Instructions/Sarah_random_walk_complete.mp3",
		"scene": "res://adaresearch/Common/Scenes/Context/GridControl/the_grid_point.tscn"
	}

]
