extends Node3D
# endless_museum.gd — the endless museum corridor (fast loop, v1).
#
# Streams museum-template segments ahead of the walker: each segment stamps one
# principal template extracted from a real floor plan (commons/data/
# template_patterns.json, museum-tagged entries) and fills its slots from the
# artifact registries in seeded order. Walk forward (+z) and the next museum
# opens; segments three behind are freed. Valid by construction — no pathfinder
# at runtime; the templates were validated at extraction (entry-to-exit path,
# stop pocket per slot).
#
# Standalone and additive: no GridSystem, no shipped map touched.
#   Walk:  godot --path . res://commons/scenes/endless_museum.tscn -- --em-seed=46
#   Proof: ... -- --em-shot=user://em_proof.png --em-segments=3 (build, shoot, quit)
#          --em-shot-at=<z> moves the shot camera (negative z stands before the
#          first threshold and tilts up at its banner)
#   Walkthrough gate: ... -- --em-autopilot=3  (BFS-plan over the stamped cells,
#          execute with move_and_slide, verdict + heartbeat in
#          ada_run/em_autopilot.json; exit 1 on stall — plan/physics disagreement)
#
# THE POOL IS THE CURRICULUM (v2, the handover's wire). By default artifacts are
# dealt in SPINE ORDER from commons/data/spine_artifact_order.json (generated by
# tools/build_spine_artifact_order.py: sequence order -> map order -> first
# appearance) — the museum is the book walked through eight real buildings.
# --em-order=shuffle restores the v1 seeded shuffle; spine mode also falls back
# to the shuffle when the manifest is missing, so the corridor never opens empty.
#
# v1 debt PAID (2026-07-31): the walker is a CharacterBody3D — walls, podiums
# and hero plinths carry collision boxes (one StaticBody3D per segment), so the
# corridor pushes back instead of being glided through; the threshold banner is
# the canonical TextScreen (framed, baked-albedo, headless-safe), which also
# retires the mirrored-text bug — from behind you see a panel's back, not
# reversed words.

const TEMPLATES := "res://commons/data/template_patterns.json"
const REGISTRY_DIR := "res://commons/artifacts/registry"
const SPINE_ORDER := "res://commons/data/spine_artifact_order.json"
# DECLARED ORDER POLICIES (unification step 4): who decides the order of the
# walk. Same row shape as the spine manifest, so --em-order=dig|size|text reads
# them through one loader. `text` is the book's own order — the order the
# writing first names each artifact, which measures tau -0.13 against the
# curriculum: the page and the corridor genuinely disagree about what comes
# first, and that disagreement is now walkable instead of theoretical.
const ORDER_POLICIES := "res://commons/data/artifact_order_policies.json"
# THE CROWNS (ruled 2026-08-01): chapters whose champion template is a museum.
# A crowned chapter is dealt into its crowned building; uncrowned chapters
# keep the em_order rotation.
const CROWNS := "res://commons/data/museum_crowns.json"
const TextScreenRes = preload("res://commons/ui/text_screen.gd")
const EYE := 1.65
const WALK_SPEED := 4.0
const BUILD_AHEAD_M := 24.0
const KEEP_BEHIND_M := 70.0
const MAX_ARTIFACTS_PER_SEGMENT := 8
# THE VESTIBULE (v3). Collision exposed what the gliding camera never felt:
# each template's exit gap and the next template's entry gap sit at different x,
# so the chain was walkable per-template but not BETWEEN templates. Every
# segment now opens with a short lobby the width of the widest template —
# closing strips seal width jumps — so any exit gap funnels into any entry gap.
# Real museums have these rooms too; the banner hangs there.
const VESTIBULE_H := 4
const LOBBY_W := 17

var _museums: Array = []          # [{key,label,museum,w,h,tile,walk_rule}]
var _crowns: Dictionary = {}      # sequence -> crowned template key
var _rot_i: int = 0               # rotation cursor for uncrowned chapters
var _pool: Array = []             # [{lookup, scene}]
var _pool_i: int = 0
var _seed: int = 46
var _order_mode: String = "spine"  # spine | shuffle
var _shot_path: String = ""
var _shot_segments: int = 3
var _shot_z: float = 1.0
var _test_collision: bool = false
var _test_frames: int = 0
# autopilot: walk through N museums end-to-end under real physics. The plan
# comes from the SAME data the builder stamped; the body executes it with
# move_and_slide. Anywhere plan and physics disagree, the walker stalls and
# the verdict says where.
var _autopilot: int = 0
var _walk_cells: Dictionary = {}   # Vector2i(x, z_cell) -> true
var _auto_path: Array = []
var _auto_goal_z: float = -1.0
var _auto_replan: bool = true
var _auto_stall_t: float = 0.0
var _auto_last_pos: Vector3 = Vector3.ZERO
var _auto_beat_t: float = 0.0
var _auto_t: float = 0.0
var _auto_learned: int = 0
var _segments: Array = []         # [{node, z0, z1, index}]
var _next_z: float = 0.0
var _seg_index: int = 0
var _prev_w: int = -1             # width of the previous segment's tile (lobby seals the jump)
var _first_key: String = ""       # --em-first=<key> rotates the dealing order
var _banner_pos: Vector3 = Vector3.ZERO   # where the first segment hung its sign
var _player: CharacterBody3D
var _cam: Camera3D
var _yaw: float = 0.0
var _pitch: float = 0.0

# ── AAA RENDER MODULES (commons/scenes/em/*.gd) ──────────────────────────────
# Loaded at RUNTIME, never preloaded. A preload of a module that fails to parse
# is a parse error in THIS file and takes the whole museum down with it;
# load() returns null instead, so a broken or absent module degrades to the v1
# flat-box look rather than to a black screen. Every call site is guarded.
const EM_DIR := "res://commons/scenes/em/"
var _mod_mats = null
var _mod_light = null
var _mod_env = null
var _mod_detail = null
var _mod_feel = null
var _mod_audio = null
var _feel: Node = null
var _surf: Dictionary = {}         # role -> Material; empty when the library is absent
var _detail_mats: Dictionary = {}  # the four roles em_detail probes for
var _audio_seg: int = -1           # which segment's acoustic the bed is tuned to
var _mod_warned: Dictionary = {}

func _ready() -> void:
	_parse_args()
	_load_modules()
	_load_museums()
	_load_crowns()
	_load_pool()
	if _museums.is_empty():
		push_error("endless_museum: no museum-tagged templates in %s" % TEMPLATES)
		return
	_setup_world()
	var preload_n: int = _shot_segments if _shot_path != "" else 2
	for i in range(preload_n):
		_build_segment()
	if _shot_path != "":
		_take_proof_shot()

func _parse_args() -> void:
	var args := OS.get_cmdline_user_args()
	if args.is_empty():
		args = OS.get_cmdline_args()
	for a in args:
		if a.begins_with("--em-seed="):
			_seed = int(a.substr(10))
		elif a.begins_with("--em-order="):
			_order_mode = a.substr(11)
		elif a.begins_with("--em-shot="):
			_shot_path = a.substr(10)
		elif a.begins_with("--em-shot-at="):
			_shot_z = float(a.substr(13))
		elif a.begins_with("--em-segments="):
			_shot_segments = int(a.substr(14))
		elif a == "--em-test-collision":
			_test_collision = true
		elif a.begins_with("--em-autopilot="):
			_autopilot = int(a.substr(15))
		elif a.begins_with("--em-first="):
			_first_key = a.substr(11)

## ── MODULE LOADING ───────────────────────────────────────────────────────────
## Six render modules, six independent failure domains. Anything that does not
## load is simply absent for the rest of the run.
func _load_modules() -> void:
	_mod_mats = _load_module("em_materials.gd")
	_mod_light = _load_module("em_lighting.gd")
	_mod_env = _load_module("em_environment.gd")
	_mod_detail = _load_module("em_detail.gd")
	_mod_feel = _load_module("em_feel.gd")
	_mod_audio = _load_module("em_audio.gd")
	print("[endless_museum] modules: mats=%s light=%s env=%s detail=%s feel=%s audio=%s" % [
		_mod_mats != null, _mod_light != null, _mod_env != null,
		_mod_detail != null, _mod_feel != null, _mod_audio != null])
	_build_surfaces()

func _load_module(fname: String):
	var p: String = EM_DIR + fname
	if not ResourceLoader.exists(p):
		push_warning("endless_museum: module absent %s — degrading to v1 for it" % p)
		return null
	var s = load(p)
	if s == null:
		push_warning("endless_museum: module failed to parse %s — degrading to v1 for it" % p)
	return s

## Guarded static dispatch onto a loaded GDScript. Warns once per missing entry
## point so a renamed API shows up in stdout instead of vanishing.
func _mod_has(m, fn: String) -> bool:
	if m == null:
		return false
	if (m as Object).has_method(fn):
		return true
	var key: String = str(m) + "::" + fn
	if not _mod_warned.has(key):
		_mod_warned[key] = true
		push_warning("endless_museum: module has no `%s` — skipping that stage" % fn)
	return false

## One material per role, resolved once. A getter that is missing leaves its
## role null, and _box() then falls back to the flat v1 colour for that role
## alone — the degrade is per-surface, not all-or-nothing.
func _build_surfaces() -> void:
	if _mod_mats == null:
		return
	if _mod_has(_mod_mats, "warm_up"):
		_mod_mats.call("warm_up")
	_surf["floor"] = _mat_of("floor_stone", [])
	# circulation is the floor that gets walked on. soil 0.15 was in the library
	# from the start and had never once been passed non-zero by anybody.
	_surf["deck"] = _mat_of("floor_terrazzo", [Color.WHITE, 0.15])
	_surf["wall"] = _mat_of("wall_plaster", [])
	_surf["podium"] = _mat_of("podium_marble", [])
	_surf["plinth"] = _mat_of("trim_oak", [])
	_surf["ceiling"] = _mat_of("ceiling_plaster", [])
	_surf["trim"] = _mat_of("travertine", [])
	_surf["brass"] = _mat_of("accent_brass", [0.35])
	# THE 130 mm CONTACT STRIP. em_materials.skirting() existed with no callers in
	# the whole repo; it is the library's one real light-reactive edge-darkening
	# mechanism and it was dead code while every frame showed a wall meeting a
	# floor at an indistinguishable value step.
	_surf["skirting"] = _mat_of("skirting", [&"plaster", Color.WHITE])
	# A JOINT IS A SHADOW, NOT A LIGHT. The floor seams used to be drawn in aged
	# brass — metallic, roughness ~0.27 in the high spots, so every strip mirrored
	# whatever spot was overhead and blew to 0.75-0.95 against a 0.03 floor. The
	# least important element in the building (a 5 mm joint) was doing all the
	# leading-line work. A dark soiled stone reads by shadow instead.
	_surf["joint"] = _mat_of("skirting", [&"floor_stone", Color.WHITE])
	for k in _surf.keys():
		if _surf[k] == null:
			_surf.erase(k)
	# em_detail probes a Dictionary of Materials by role name — the plainest of
	# the four shapes it accepts, so no method-name guessing is involved.
	_detail_mats = {}
	for pair in [["wall", "wall"], ["trim", "trim"], ["accent", "joint"],
			["ceiling", "ceiling"], ["skirting", "skirting"]]:
		var role: String = String(pair[0])
		var src: String = String(pair[1])
		if _surf.has(src):
			_detail_mats[role] = _surf[src]
	print("[endless_museum] surfaces: %d roles from em_materials" % _surf.size())

func _mat_of(fn: String, args: Array) -> Material:
	if not _mod_has(_mod_mats, fn):
		return null
	var r = _mod_mats.callv(fn, args)
	if r is Material:
		return r
	return null

func _load_museums() -> void:
	var f := FileAccess.open(TEMPLATES, FileAccess.READ)
	if f == null:
		return
	var data: Variant = JSON.parse_string(f.get_as_text())
	if not (data is Dictionary):
		return
	var patterns: Dictionary = data.get("patterns", {})
	for key in patterns:
		var p: Dictionary = patterns[key]
		if p.has("museum"):  # only the extracted museum templates
			# challengers (edited-lineage tiles not yet adopted) stay out of the
			# corridor rotation — they exist to be judged, not walked, until ruled
			if p.get("challenger", false):
				continue
			_museums.append({"key": key, "label": p.get("label", key),
				"museum": p.get("museum", ""), "w": int(p.get("w", 15)),
				"h": int(p.get("h", 30)), "tile": p.get("tile", []),
				"walk_rule": p.get("walk_rule", ""),
				"color": String(p.get("color", "#888888")),
				"em_order": int(p.get("em_order", 99))})
	# the dealing order is DATA (em_order on the pattern, a proposal not a
	# ruling); alphabetical keys are only the tiebreak. --em-first rotates a
	# chosen museum to the front for proof shots.
	_museums.sort_custom(func(a, b):
		if int(a["em_order"]) != int(b["em_order"]):
			return int(a["em_order"]) < int(b["em_order"])
		return String(a["key"]) < String(b["key"]))
	if _first_key != "":
		for i in range(_museums.size()):
			if String(_museums[i]["key"]) == _first_key:
				var head: Array = _museums.slice(i)
				head.append_array(_museums.slice(0, i))
				_museums = head
				break

func _load_crowns() -> void:
	var f := FileAccess.open(CROWNS, FileAccess.READ)
	if f == null:
		return
	var data: Variant = JSON.parse_string(f.get_as_text())
	if not (data is Dictionary):
		return
	var crowns: Dictionary = data.get("crowns", {})
	for seq in crowns:
		_crowns[String(seq)] = String((crowns[seq] as Dictionary).get("template", ""))
	if not _crowns.is_empty():
		print("[endless_museum] %d crowned chapters loaded" % _crowns.size())

func _load_pool() -> void:
	# the registry decides what is ALIVE (map_ready + scene on disk); the order
	# mode decides how the living are dealt
	var live: Dictionary = {}  # lookup -> {scene, fp}
	var dir := DirAccess.open(REGISTRY_DIR)
	if dir == null:
		return
	for fname in dir.get_files():
		if not fname.ends_with(".json"):
			continue
		var f := FileAccess.open(REGISTRY_DIR + "/" + fname, FileAccess.READ)
		if f == null:
			continue
		var data: Variant = JSON.parse_string(f.get_as_text())
		if not (data is Dictionary):
			continue
		var arts: Dictionary = data.get("artifacts", {})
		for lookup in arts:
			var a: Dictionary = arts[lookup]
			var scene: String = String(a.get("scene", ""))
			if scene != "" and a.get("map_ready", false) and ResourceLoader.exists(scene):
				live[String(lookup)] = {"scene": scene, "fp": _footprint_of(a)}
	if _order_mode == "spine" and _load_spine_pool(live):
		return
	if _order_mode != "shuffle" and _load_policy_pool(live, _order_mode):
		return
	# v1 fallback: alphabetical, then seeded shuffle
	for lookup in live:
		_pool.append({"lookup": lookup, "scene": live[lookup]["scene"],
			"fp": live[lookup]["fp"], "sequence": ""})
	_pool.sort_custom(func(a, b): return String(a["lookup"]) < String(b["lookup"]))
	var rng := RandomNumberGenerator.new()
	rng.seed = _seed
	for i in range(_pool.size() - 1, 0, -1):
		var j := rng.randi_range(0, i)
		var tmp: Variant = _pool[i]
		_pool[i] = _pool[j]
		_pool[j] = tmp
	print("[endless_museum] pool: shuffle, %d artifacts, seed %d" % [_pool.size(), _seed])

## A DECLARED policy as the dealing order (step 4): dig, size, text — anything
## commons/data/artifact_order_policies.json carries. Additive by construction:
## spine and shuffle never reach here, an unknown policy name falls through to
## the seeded shuffle rather than failing the walk, and every row keeps the
## `why` that put it where it is.
func _load_policy_pool(live: Dictionary, policy: String) -> bool:
	var f := FileAccess.open(ORDER_POLICIES, FileAccess.READ)
	if f == null:
		push_warning("endless_museum: --em-order=%s but %s is missing (run tools/build_order_policies.py); falling back to shuffle" % [policy, ORDER_POLICIES])
		return false
	var data: Variant = JSON.parse_string(f.get_as_text())
	if not (data is Dictionary):
		return false
	var all: Dictionary = (data as Dictionary).get("policies", {})
	if not all.has(policy):
		push_warning("endless_museum: no order policy `%s` (have %s); falling back to shuffle" % [policy, str(all.keys())])
		return false
	var rows: Array = all[policy]
	var skipped := 0
	for row in rows:
		var lookup := String((row as Dictionary).get("lookup", ""))
		if live.has(lookup):
			_pool.append({"lookup": lookup, "scene": live[lookup]["scene"],
				"fp": live[lookup]["fp"],
				"sequence": String((row as Dictionary).get("sequence", ""))})
		else:
			skipped += 1
	if _pool.is_empty():
		return false
	print("[endless_museum] pool: ORDER POLICY `%s`, %d of %d alive (%d not map_ready/on disk); opens with %s" % [
		policy, _pool.size(), rows.size(), skipped, String(_pool[0]["lookup"])])
	return true

## The curriculum as the dealing order. Reads the generated manifest and keeps
## only artifacts the registry says are alive, in manifest order — so the first
## hero slot of the first museum receives the first artifact of the spine.
func _load_spine_pool(live: Dictionary) -> bool:
	var f := FileAccess.open(SPINE_ORDER, FileAccess.READ)
	if f == null:
		push_warning("endless_museum: --em-order=spine but %s is missing (run tools/build_spine_artifact_order.py); falling back to shuffle" % SPINE_ORDER)
		return false
	var data: Variant = JSON.parse_string(f.get_as_text())
	if not (data is Dictionary):
		return false
	var rows: Array = data.get("order", [])
	var skipped := 0
	for row in rows:
		var lookup := String((row as Dictionary).get("lookup", ""))
		if live.has(lookup):
			_pool.append({"lookup": lookup, "scene": live[lookup]["scene"],
				"fp": live[lookup]["fp"],
				"sequence": String((row as Dictionary).get("sequence", ""))})
		else:
			skipped += 1
	if _pool.is_empty():
		return false
	print("[endless_museum] pool: SPINE ORDER, %d of %d curriculum artifacts alive (%d not map_ready/on disk)" % [
		_pool.size(), rows.size(), skipped])
	return true

## Widest horizontal footprint dimension declared for an artifact (cells).
func _footprint_of(entry: Dictionary) -> int:
	var params: Dictionary = entry.get("parameters", {})
	var fp: Variant = params.get("footprint", null)
	if fp is Array and (fp as Array).size() >= 3:
		return maxi(1, maxi(int((fp as Array)[0]), int((fp as Array)[2])))
	return 1

## Deal the next artifact for a slot rank, spine order preserved up to a local
## 16-deep swap: the hero plinth prefers the chapter's large piece, a podium
## needs a compact one, a floor slot takes anything short of a giant — so a
## building never perches on a pedestal and giants wait for the plinth.
func _pick_pool(rank: int) -> Dictionary:
	var n := _pool.size()
	if n == 0:
		return {}
	var want_min := 1
	var want_max := 99
	match rank:
		0: want_min = 2
		1: want_max = 1
		2: want_max = 2
	for off in range(mini(16, n)):
		var idx := (_pool_i + off) % n
		var fp := int(_pool[idx].get("fp", 1))
		if fp >= want_min and fp <= want_max:
			if off > 0:
				var cur := _pool_i % n
				var tmp: Variant = _pool[cur]
				_pool[cur] = _pool[idx]
				_pool[idx] = tmp
			break
	var e: Dictionary = _pool[_pool_i % n]
	_pool_i += 1
	return e

func _setup_world() -> void:
	# the walker is a body, not a gliding camera: a capsule the walls and
	# podiums can push back on. No gravity — the deck is flat by construction,
	# so y is clamped instead of simulated. Built FIRST now, because the
	# environment binds its camera attributes to the camera.
	_player = CharacterBody3D.new()
	_player.name = "Walker"
	_player.position = Vector3(7.5, 0.0, 1.5)
	_yaw = PI  # segments extend along +z; face into the museum
	_player.rotation = Vector3(0.0, _yaw, 0.0)
	var col := CollisionShape3D.new()
	var cap := CapsuleShape3D.new()
	cap.radius = 0.32
	cap.height = 1.5
	col.shape = cap
	col.position = Vector3(0, 0.95, 0)
	_player.add_child(col)
	add_child(_player)
	_cam = Camera3D.new()
	_cam.position = Vector3(0, EYE, 0)
	_cam.fov = 90.0
	_player.add_child(_cam)
	_cam.make_current()
	var lit := _setup_environment()
	# The sun. With em_lighting's rig and em_detail's ceiling in place the
	# directional is no longer the interior's light source — it is the shaft
	# through the ceiling slots, and em_lighting's ENV_CONTRACT caps it at 0.35.
	# With no rig it is still the ONLY light, so it keeps its v1 energy.
	var sun := DirectionalLight3D.new()
	sun.name = "Sun"
	sun.rotation_degrees = Vector3(-55.0, 30.0, 0.0)
	sun.light_energy = 0.35 if lit else 1.1
	sun.shadow_enabled = true
	add_child(sun)
	_setup_feel()
	_setup_audio()

## The environment. Returns true when the AAA environment installed, so the sun
## knows whether it is a shaft or the only light in the building.
func _setup_environment() -> bool:
	var have_rig: bool = _mod_light != null
	if _mod_env != null and have_rig and _mod_has(_mod_env, "install"):
		# a headless gate run cannot afford SSIL + SSR + SDFGI + volumetric fog:
		# the walk would slow under the watchdog's stall window and a timing
		# artefact would be reported as a corridor failure.
		if (_autopilot > 0 or _test_collision) and _mod_has(_mod_env, "set_tier"):
			_mod_env.call("set_tier", "perf")
		var we = _mod_env.call("install", self, _cam)
		if we != null:
			if _mod_has(_mod_env, "apply_render_quality"):
				_mod_env.call("apply_render_quality")
			return true
	# v1 fallback: sky background, flat sky ambient, no post.
	var env := WorldEnvironment.new()
	var e := Environment.new()
	e.background_mode = Environment.BG_SKY
	e.sky = Sky.new()
	e.sky.sky_material = ProceduralSkyMaterial.new()
	e.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	e.ambient_light_energy = 1.2
	env.environment = e
	add_child(env)
	return false

## The movement feel. Only for the interactive walk — the proof shot, the
## collision test and the autopilot all aim the body themselves and must not be
## fought over, so the node is not even created for them.
func _setup_feel() -> void:
	if _mod_feel == null or _shot_path != "" or _autopilot > 0 or _test_collision:
		return
	var n = _mod_feel.new()
	if not (n is Node):
		push_warning("endless_museum: em_feel did not instance a Node — keeping v1 movement")
		return
	_feel = n as Node
	_feel.name = "Feel"
	_feel.add_to_group("em_feel")
	add_child(_feel)
	if not _feel.has_method("configure"):
		push_warning("endless_museum: em_feel has no configure() — keeping v1 movement")
		remove_child(_feel)
		_feel.queue_free()
		_feel = null
		return
	_feel.call("configure", _player, _cam)

## Audio. The module's own guard makes every capture and headless run a no-op,
## so this call is safe on every path.
func _setup_audio() -> void:
	if not _mod_has(_mod_audio, "install"):
		return
	_mod_audio.call("install", self)
	if _feel != null and _mod_has(_mod_audio, "bind_footsteps"):
		_mod_audio.call("bind_footsteps", _feel, "footstep")

func _mat(color: Color) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_color = color
	return m

## One role out of the resolved library, or null when the library never
## produced it.
func _sm(role: String) -> Material:
	var v = _surf.get(role, null)
	if v is Material:
		return v
	return null

## `mat` wins when the material library gave us one for this role; `color` is
## the v1 flat fallback, kept per-surface so a partially loaded library still
## dresses what it can.
func _box(parent: Node3D, pos: Vector3, size: Vector3, color: Color, mat: Material = null) -> void:
	var mi := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = size
	mi.mesh = bm
	mi.material_override = mat if mat != null else _mat(color)
	mi.position = pos
	parent.add_child(mi)

func _add_col(body: StaticBody3D, pos: Vector3, size: Vector3) -> void:
	var cs := CollisionShape3D.new()
	var bs := BoxShape3D.new()
	bs.size = size
	cs.shape = bs
	cs.position = pos
	body.add_child(cs)

func _build_segment() -> void:
	# a crowned chapter gets its crowned building (the ruling made live);
	# uncrowned chapters walk the em_order rotation. --em-first still forces
	# the front for proof shots.
	var spec: Dictionary = _museums[_rot_i % _museums.size()]
	var next_seq := ""
	if not _pool.is_empty():
		next_seq = String(_pool[_pool_i % _pool.size()].get("sequence", ""))
	var crowned := String(_crowns.get(next_seq, ""))
	var use_crown := false
	if crowned != "" and (_first_key == "" or _seg_index > 0):
		for m in _museums:
			if String(m["key"]) == crowned:
				spec = m
				use_crown = true
				break
	if not use_crown:
		_rot_i += 1
	var w: int = spec["w"]
	var h: int = spec["h"]
	var tile: Array = spec["tile"]
	var seg := Node3D.new()
	seg.name = "Seg%d_%s" % [_seg_index, spec["key"]]
	seg.position = Vector3(0, 0, _next_z)
	add_child(seg)
	# one static body per segment carries every collision box — walls, podiums,
	# hero plinths — so the whole museum frees with its segment node
	var solid := StaticBody3D.new()
	solid.name = "Collision"
	seg.add_child(solid)
	# — the vestibule: an open lobby joining the previous museum's exit gap to
	# this one's entry gap. Closing strips seal the width jump on both edges
	# (a fully sealed strip at the very first segment, where nothing is behind).
	var pw: int = _prev_w if _prev_w > 0 else 1
	var zbase := int(_next_z)
	var wall_col := Color(0.32, 0.32, 0.36)
	# the material library replaces the flat albedos role by role; a role the
	# library never produced stays on its v1 colour
	var m_wall: Material = _sm("wall")
	var m_deck: Material = _sm("deck")
	var m_floor: Material = _sm("floor")
	var m_podium: Material = _sm("podium")
	var m_plinth: Material = _sm("plinth")
	for zr in range(VESTIBULE_H):
		for x in range(LOBBY_W):
			_box(seg, Vector3(x + 0.5, -0.1, zr + 0.5), Vector3(1, 0.2, 1), Color(0.13, 0.13, 0.16), m_deck)
			if x > 0 and x < LOBBY_W - 1 and not (zr == 0 and x >= pw - 1) and not (zr == VESTIBULE_H - 1 and x >= w - 1):
				_walk_cells[Vector2i(x, zbase + zr)] = true
	for zr in range(VESTIBULE_H):
		for sx in [0, LOBBY_W - 1]:
			_box(seg, Vector3(sx + 0.5, 1.5, zr + 0.5), Vector3(1, 3.0, 1), wall_col, m_wall)
			_add_col(solid, Vector3(sx + 0.5, 1.5, zr + 0.5), Vector3(1, 3.0, 1))
	for x in range(pw - 1, LOBBY_W):        # seal beyond the previous tile's width
		_box(seg, Vector3(x + 0.5, 1.5, 0.5), Vector3(1, 3.0, 1), wall_col, m_wall)
		_add_col(solid, Vector3(x + 0.5, 1.5, 0.5), Vector3(1, 3.0, 1))
	for x in range(w - 1, LOBBY_W):         # seal beyond this tile's width
		_box(seg, Vector3(x + 0.5, 1.5, VESTIBULE_H - 0.5), Vector3(1, 3.0, 1), wall_col, m_wall)
		_add_col(solid, Vector3(x + 0.5, 1.5, VESTIBULE_H - 0.5), Vector3(1, 3.0, 1))
	# outer skin: an implicit wall just beyond both side columns of the tile, so
	# free-plan templates with a walkable rim (Kanazawa, Neue Nationalgalerie)
	# cannot leak the walker off the edge of the world
	for y_skin in range(tile.size()):
		for sx2 in [-1, w]:
			_box(seg, Vector3(sx2 + 0.5, 1.5, y_skin + VESTIBULE_H + 0.5), Vector3(1, 3.0, 1), wall_col, m_wall)
			_add_col(solid, Vector3(sx2 + 0.5, 1.5, y_skin + VESTIBULE_H + 0.5), Vector3(1, 3.0, 1))
	# collect slots first so the artifact budget prefers hero > podium > floor
	var slots: Array = []
	for y in range(tile.size()):
		var row: Array = tile[y]
		var z := y + VESTIBULE_H
		for x in range(row.size()):
			var c := String(row[x])
			match c:
				"1", "1s":
					_box(seg, Vector3(x + 0.5, -0.1, z + 0.5), Vector3(1, 0.2, 1), Color(0.16, 0.16, 0.19), m_floor)
					_walk_cells[Vector2i(x, zbase + z)] = true
				"2", "2s":
					_box(seg, Vector3(x + 0.5, 0.1, z + 0.5), Vector3(1, 0.6, 1), Color(0.23, 0.23, 0.28), m_podium)
					_add_col(solid, Vector3(x + 0.5, 0.1, z + 0.5), Vector3(1, 0.6, 1))
				"3s":
					_box(seg, Vector3(x + 0.5, 0.3, z + 0.5), Vector3(1, 1.0, 1), Color(0.35, 0.27, 0.16), m_plinth)
					_add_col(solid, Vector3(x + 0.5, 0.3, z + 0.5), Vector3(1, 1.0, 1))
				"4":
					_box(seg, Vector3(x + 0.5, 1.5, z + 0.5), Vector3(1, 3.0, 1), wall_col, m_wall)
					_add_col(solid, Vector3(x + 0.5, 1.5, z + 0.5), Vector3(1, 3.0, 1))
			if c == "1s":
				slots.append({"x": x, "y": z, "top": 0.0, "rank": 2})
			elif c == "2s":
				slots.append({"x": x, "y": z, "top": 0.4, "rank": 1})
			elif c == "3s":
				slots.append({"x": x, "y": z, "top": 0.8, "rank": 0})
	slots.sort_custom(func(a, b): return int(a["rank"]) < int(b["rank"]))
	var placed := 0
	var seg_seq := ""
	for s in slots:
		if placed >= MAX_ARTIFACTS_PER_SEGMENT or _pool.is_empty():
			break
		var entry: Dictionary = _pick_pool(int(s["rank"]))
		if entry.is_empty():
			break
		# chapter alignment: a museum houses ONE sequence. When the spine order
		# crosses into the next sequence mid-museum (and this museum already
		# holds a real showing), the chapter opener is handed back and the NEXT
		# museum opens with it — the book's chapters get buildings.
		var sq := String(entry.get("sequence", ""))
		if seg_seq == "":
			seg_seq = sq
		elif sq != seg_seq and sq != "" and placed >= 4:
			_pool_i -= 1
			break
		var ps: PackedScene = load(String(entry["scene"])) as PackedScene
		if ps == null:
			continue
		var node: Node3D = ps.instantiate() as Node3D
		if node == null:
			continue
		node.set_meta("artifact_lookup_name", entry["lookup"])
		node.position = Vector3(float(s["x"]) + 0.5, float(s["top"]), float(s["y"]) + 0.5)
		seg.add_child(node)
		# an occupied floor slot leaves the walk map: some artifact scenes carry
		# their own collision, and the autopilot must not plan through them
		if int(s["rank"]) == 2:
			_walk_cells.erase(Vector2i(int(s["x"]), zbase + int(s["y"])))
		# a LARGE hero overhangs its plinth — clear the surrounding ring too, so
		# the planner routes around the piece instead of hugging it (Chichu's
		# hero chamber is also its through-passage; found by the autopilot)
		if int(s["rank"]) == 0 and int(entry.get("fp", 1)) >= 2:
			for dz in range(-1, 2):
				for dx in range(-1, 2):
					_walk_cells.erase(Vector2i(int(s["x"]) + dx, zbase + int(s["y"]) + dz))
		placed += 1
	# museum banner at the threshold — the canonical TextScreen (framed panel,
	# baked albedo, headless-safe). Properties set before add_child so the one
	# _ready() rebuild builds the right sign.
	# each museum wears its own colour: the pattern's hex tints the banner title
	# and an ember strip across the threshold floor.
	#
	# THE PALETTE WAS A CHART LEGEND. template_patterns.json's museum colours are
	# #946b3d, #3d6b94, #6b943d, #943d6b ... the same three bytes (0x94/0x6b/0x3d)
	# rotated through the RGB channels: a qualitative palette generated so twenty
	# templates could be told apart in a legend on a data board. Fed straight into
	# architectural light and emissive trim it put a full-width HOT MAGENTA stripe
	# across the Soane's floor — the highest-chroma pixels in the frame, leading
	# the eye, and no architectural surface in a museum is magenta. The legend hue
	# is now translated to a plausible building material (brass, bronze, patinated
	# copper, oxidised steel, warm stone) which keeps the museums distinguishable
	# and takes the chroma out. The raw legend colour survives ONLY as the sign's
	# text tint, where it is ink on a panel rather than light on a wall.
	var legend := Color.html(String(spec.get("color", "#888888")))
	var accent := legend
	if _mod_has(_mod_detail, "architectural_accent"):
		accent = _mod_detail.call("architectural_accent", legend)
	# THE SIGN COMES OFF THE VANISHING POINT. At (w/2, 2.45, VESTIBULE_H-0.45) a
	# 2.8 m panel (TextScreen ASPECT 0.62 -> 1.74 m tall, so 1.58..3.32) sat dead
	# on the one-point vanishing point and covered the top third of the portal —
	# the single thing a 30 m axial vista exists to show was behind a black
	# rectangle in all three corridor shots. It also had no thickness, no frame
	# return, no mounting and no contact shadow, so it read as world-space UI.
	# A real museum mounts its sign on the wall BESIDE the opening. So does this
	# one now: west lobby wall, 2.2 m wide, on a 90 mm oak surround that leaves a
	# 50 mm reveal all round to catch a shadow gap.
	const BANNER_X := 1.06
	const BANNER_Z := 2.30
	const BANNER_Y := 1.95
	const BANNER_W := 2.2
	var banner: Node3D = TextScreenRes.new()
	banner.mode = TextScreenRes.Mode.SCREEN
	banner.title = String(spec["label"])
	# the banner names the building AND the chapter it houses
	banner.body = ("%s\n\n%s" % [spec["museum"], seg_seq]) if seg_seq != "" else String(spec["museum"])
	banner.title_color = legend.lightened(0.35)   # ink on a panel, not light on a wall
	banner.width_m = BANNER_W
	banner.position = Vector3(BANNER_X, BANNER_Y, BANNER_Z)
	# TextScreen faces its own local +Z; yaw +90 turns that to world +X, i.e. off
	# the west wall into the lobby
	banner.rotation_degrees = Vector3(0, 90, 0)
	seg.add_child(banner)
	# the surround: buried in the wall, 50 mm proud, so the sign sits IN a reveal
	# and throws a real shadow instead of floating
	_box(seg, Vector3(1.005, BANNER_Y, BANNER_Z),
		Vector3(0.09, BANNER_W * 0.62 + 0.18, BANNER_W + 0.18),
		Color(0.25, 0.17, 0.10), m_plinth)
	if _banner_pos == Vector3.ZERO:
		_banner_pos = Vector3(BANNER_X, BANNER_Y, BANNER_Z + _next_z)
	var ember := MeshInstance3D.new()
	var ebm := BoxMesh.new()
	ebm.size = Vector3(w - 2.0, 0.02, 0.08)
	ember.mesh = ebm
	# 1.1, down from 1.8. The strip runs edge to edge at the exact horizontal
	# centre of every axial shot; at 1.8 it was the brightest line in the frame
	# and it bisected the composition. It is an ember, not a light fitting.
	var emat: Material = _mat_of("emissive_accent", [accent, 1.1])
	if emat == null:
		var fallback := StandardMaterial3D.new()
		fallback.albedo_color = accent
		fallback.emission_enabled = true
		fallback.emission = accent
		fallback.emission_energy_multiplier = 1.6
		emat = fallback
	ember.material_override = emat
	ember.position = Vector3(w / 2.0, 0.02, VESTIBULE_H - 0.15)
	seg.add_child(ember)
	# ── the AAA passes, in the order they depend on each other ───────────────
	# 1. architectural detail: skirting, cornice, shadow gap, door reveals, a
	#    coffered ceiling with open daylight slots, floor seams. Adds NO
	#    collision and never touches _walk_cells, so the autopilot's BFS plan is
	#    bit-identical with and without it.
	if _mod_has(_mod_detail, "dress_segment"):
		_mod_detail.call("dress_segment", seg, tile, w, h, _detail_mats, _prev_w)
	# 1b. FURNITURE. em_detail is contractually forbidden to add collision, and a
	#     bench you can walk through is worse than no bench — so the one fixture
	#     family that occupies floor lives here, where the segment's StaticBody3D
	#     and the walk map are both in scope.
	_dress_fixtures(seg, solid, tile, w, zbase)
	# 2. the light rig: ambient floor, north daylight down the axis, keys on the
	#    hero and podium slots, cove and accent grazer at the threshold, wall
	#    wash, floor fill. Capped at 24 lights / 6 shadow casters per segment.
	if _mod_has(_mod_light, "rig_segment"):
		_mod_light.call("rig_segment", seg, w, h, accent, slots, {"tile": tile})
	_segments.append({"node": seg, "z0": _next_z, "z1": _next_z + float(h) + float(VESTIBULE_H), "index": _seg_index, "w": w})
	_next_z += float(h) + float(VESTIBULE_H)
	_seg_index += 1
	_prev_w = w
	_auto_replan = true
	if _autopilot > 0 and _seg_index == _autopilot:
		_auto_goal_z = float(_segments[-1]["z1"])
	var n_lights: int = 0
	if _mod_has(_mod_light, "lights_installed"):
		n_lights = int(_mod_light.call("lights_installed", seg))
	print("[endless_museum] seg %d = %s (%s) chapter=%s placed %d, z %.0f..%.0f, lights %d" % [
		_seg_index - 1, spec["key"], spec["museum"], seg_seq if seg_seq != "" else "-",
		placed, _segments[-1]["z0"], _segments[-1]["z1"], n_lights])

## THERE WAS NOTHING IN THE ROOM. Measured on the proof shots: a band 520 px
## tall across the full 1800 px width — 24% of the frame — with no bench, no
## vitrine, no stanchion, no wall card, no door furniture, nothing at all. A
## museum interior earns its read from object density at BODY scale: something
## the eye can measure a human against every three or four metres. Materials and
## lighting cannot supply that; an empty box lit perfectly is still an empty box.
##
## em_detail supplies the wall cards (no collision needed, 25 mm proud). This
## supplies the one fixture that stands on the floor, and it is deliberately
## conservative, because every collider added here is a chance to seal a corridor
## and fail the autopilot:
##   * only against a wall face, never free-standing;
##   * only where the walker can still get past on the far side AND both
##     neighbours along the wall are open floor, so a bench never plugs a 1-cell
##     passage or a doorway;
##   * at most MAX_BENCHES per segment, at least 5 cells apart;
##   * the occupied cell is REMOVED from _walk_cells, so the BFS plan routes
##     around it exactly the way it already routes around a podium.
## Deterministic — a fixed iteration order and no randf(), so the same seed builds
## the same room and two proof shots of one museum are the same photograph.
const MAX_BENCHES := 5
const BENCH_H := 0.44
const BENCH_D := 0.42
const BENCH_L := 0.95

func _dress_fixtures(seg: Node3D, solid: StaticBody3D, tile: Array, w: int, zbase: int) -> void:
	var m_bench: Material = _sm("plinth")
	var placed := 0
	var last_z: int = -99
	for y in range(tile.size()):
		if placed >= MAX_BENCHES:
			break
		if y - last_z < 5:
			continue
		if not (tile[y] is Array):
			continue
		var row: Array = tile[y]
		var z: int = y + VESTIBULE_H
		for x in range(row.size()):
			if String(row[x]) != "1":
				continue
			# which side is the wall, and is the far side still walkable?
			var side := 0
			if _solid_at(tile, x - 1, y, w) and not _solid_at(tile, x + 1, y, w):
				side = -1
			elif _solid_at(tile, x + 1, y, w) and not _solid_at(tile, x - 1, y, w):
				side = 1
			if side == 0:
				continue
			# never plug a passage: both neighbours along the wall must be floor,
			# and so must the cell the walker will squeeze past on
			if String(_tile_at(tile, x, y - 1)) != "1" or String(_tile_at(tile, x, y + 1)) != "1":
				continue
			if String(_tile_at(tile, x - side, y)) != "1":
				continue
			var face: float = float(x) + (0.0 if side < 0 else 1.0)
			var cx: float = face + float(-side) * BENCH_D * 0.5
			_box(seg, Vector3(cx, BENCH_H * 0.5, float(z) + 0.5),
				Vector3(BENCH_D, BENCH_H, BENCH_L), Color(0.30, 0.22, 0.14), m_bench)
			_add_col(solid, Vector3(cx, BENCH_H * 0.5, float(z) + 0.5),
				Vector3(BENCH_D, BENCH_H, BENCH_L))
			_walk_cells.erase(Vector2i(x, zbase + z))
			placed += 1
			last_z = y
			break
	if placed > 0:
		print("[endless_museum]   fixtures: %d benches" % placed)


## A cell that stops a walker: a template wall, or the outer skin the scene
## stamps at x = -1 and x = w.
func _solid_at(tile: Array, x: int, y: int, w: int) -> bool:
	if x < 0 or x >= w:
		return true
	return String(_tile_at(tile, x, y)) == "4"


func _tile_at(tile: Array, x: int, y: int) -> String:
	if y < 0 or y >= tile.size() or not (tile[y] is Array):
		return ""
	var row: Array = tile[y]
	if x < 0 or x >= row.size():
		return ""
	return String(row[x])


func _process(_delta: float) -> void:
	if _cam == null or _shot_path != "":
		return
	# stream: open the next museum as the walker nears the built edge
	if _cam.global_position.z > _next_z - BUILD_AHEAD_M:
		_build_segment()
	# free far-behind segments (keep the museum endless, not the node tree)
	while _segments.size() > 2 and float(_segments[0]["z1"]) < _cam.global_position.z - KEEP_BEHIND_M:
		var old: Dictionary = _segments.pop_front()
		var n: Node3D = old["node"]
		n.queue_free()
	_track_acoustic()

## The room the walker is actually standing in decides the reverb. Crossing a
## threshold retunes the bed and fires the doorway whoosh; the module is a
## no-op on every headless and capture path, so this costs nothing there.
func _track_acoustic() -> void:
	if not _mod_has(_mod_audio, "set_space"):
		return
	var z: float = _cam.global_position.z
	for s in _segments:
		var sd: Dictionary = s
		if z < float(sd["z0"]) or z >= float(sd["z1"]):
			continue
		var idx: int = int(sd["index"])
		if idx == _audio_seg:
			return
		_audio_seg = idx
		var sw: int = int(sd.get("w", 12))
		var kind: String = "hall"
		if sw <= 8:
			kind = "corridor"
		elif sw <= 14:
			kind = "gallery"
		_mod_audio.call("set_space", kind)
		return

func _physics_process(_delta: float) -> void:
	if _player == null or _shot_path != "":
		return
	if _test_collision:
		_run_collision_test()
		return
	if _autopilot > 0:
		_run_autopilot(_delta)
		return
	# walk — as a body: move_and_slide lets the walls and podiums push back
	var dir := Vector3.ZERO
	if Input.is_key_pressed(KEY_W):
		dir -= _player.global_transform.basis.z
	if Input.is_key_pressed(KEY_S):
		dir += _player.global_transform.basis.z
	if Input.is_key_pressed(KEY_A):
		dir -= _player.global_transform.basis.x
	if Input.is_key_pressed(KEY_D):
		dir += _player.global_transform.basis.x
	dir.y = 0.0
	if _feel != null and is_instance_valid(_feel):
		# em_feel owns the curve: accel/decel asymmetry, launch bite, head bob,
		# footstep cadence, strafe roll, sprint FOV. It only returns a velocity —
		# the body is still moved here.
		var v = _feel.call("step", _delta, dir, Input.is_key_pressed(KEY_SHIFT))
		if v is Vector3:
			_player.velocity = v
		else:
			_player.velocity = Vector3.ZERO
	elif dir.length() > 0.01:
		var speed := WALK_SPEED * (2.5 if Input.is_key_pressed(KEY_SHIFT) else 1.0)
		_player.velocity = dir.normalized() * speed
	else:
		_player.velocity = Vector3.ZERO
	_player.move_and_slide()
	# the deck is flat by construction — clamp rather than simulate gravity
	_player.position.y = 0.0

func _input(event: InputEvent) -> void:
	if _shot_path != "":
		return
	if event is InputEventMouseButton and event.pressed:
		Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
	elif event is InputEventKey and event.pressed and event.keycode == KEY_ESCAPE:
		Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
	elif event is InputEventMouseMotion and Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:
		# em_feel buffers raw motion and drains it at render rate (18 ms lag,
		# ~1 frame at 60 Hz) so look and bob update on the same clock.
		if _feel != null and is_instance_valid(_feel):
			_feel.call("look", (event as InputEventMouseMotion).relative)
			return
		_yaw -= event.relative.x * 0.002
		_pitch = clampf(_pitch - event.relative.y * 0.002, -1.2, 1.2)
		_player.rotation = Vector3(0.0, _yaw, 0.0)
		_cam.rotation = Vector3(_pitch, 0.0, 0.0)

## The negative test: drive the walker straight at the west wall for two
## seconds. A gliding camera sails through x=1.0 into the void; a body stops at
## the wall face plus its capsule radius. Verdict lands in
## ada_run/em_collision_test.json so the watchdog has a file to expect.
func _run_collision_test() -> void:
	_test_frames += 1
	_player.velocity = Vector3(-WALK_SPEED, 0.0, 0.0)
	_player.move_and_slide()
	_player.position.y = 0.0
	if _test_frames < 120:
		return
	var x := _player.position.x
	var free_x := 7.5 - WALK_SPEED * 2.0   # where a collisionless glide would stand
	var blocked := x > 0.9                  # wall inner face 1.0 minus a little slide
	var verdict := {
		"start_x": 7.5, "final_x": x, "free_glide_x": free_x,
		"wall_inner_face_x": 1.0, "capsule_radius": 0.32,
		"blocked_by_wall": blocked,
	}
	var f := FileAccess.open("res://ada_run/em_collision_test.json", FileAccess.WRITE)
	if f:
		f.store_string(JSON.stringify(verdict, " "))
	print("[endless_museum] collision test: final_x=%.2f (free glide would be %.2f) -> %s" % [
		x, free_x, "BLOCKED" if blocked else "PASSED THROUGH"])
	get_tree().quit(0 if blocked else 1)

## ── AUTOPILOT ────────────────────────────────────────────────────────────────
## The strongest gate the museum has: walk through N museums end-to-end. The
## plan is BFS over the cells the builder actually stamped; the execution is
## the same CharacterBody3D a player drives. If they disagree anywhere — a wall
## where the data says floor, a sealed lobby, an artifact's own collision — the
## walker stalls and the verdict names the coordinates. Heartbeats rewrite the
## verdict file every second so the 16-second watchdog sees a live run.
func _run_autopilot(delta: float) -> void:
	_auto_t += delta
	_auto_beat_t += delta
	if _auto_beat_t >= 1.0:
		_auto_beat_t = 0.0
		_auto_write(false, true)
	if _auto_goal_z > 0.0 and _player.position.z >= _auto_goal_z:
		_auto_write(true, true)
		print("[endless_museum] AUTOPILOT PASS: %d museums crossed, z=%.1f in %.1fs" % [
			_autopilot, _player.position.z, _auto_t])
		get_tree().quit(0)
		return
	if _player.position.distance_to(_auto_last_pos) > 0.4:
		_auto_last_pos = _player.position
		_auto_stall_t = 0.0
	else:
		_auto_stall_t += delta
		if _auto_stall_t > 1.2:
			# physics teaches the planner: the cell ahead is not actually
			# passable (an artifact's own collision, usually) — unlearn it and
			# route around. A bounded budget keeps honesty: a corridor that
			# needs endless unlearning is a broken corridor.
			if not _auto_path.is_empty():
				var blocked := Vector2i(int(floor(_auto_path[0].x)), int(floor(_auto_path[0].z)))
				_walk_cells.erase(blocked)
			_auto_learned += 1
			_auto_stall_t = 0.0
			_auto_replan = true
			if _auto_learned > 25:
				_auto_write(true, false)
				print("[endless_museum] AUTOPILOT FAIL: %d cells unlearned and still stuck at (%.1f, %.1f), %.1f m short of goal %.1f" % [
					_auto_learned, _player.position.x, _player.position.z,
					_auto_goal_z - _player.position.z, _auto_goal_z])
				get_tree().quit(1)
				return
	if _auto_replan or _auto_path.is_empty():
		_auto_replan = false
		_auto_plan()
	if _auto_path.is_empty():
		_player.velocity = Vector3.ZERO
		return
	var wp: Vector3 = _auto_path[0]
	var to := wp - _player.position
	to.y = 0.0
	if to.length() < 0.35:
		_auto_path.pop_front()
		return
	_player.velocity = to.normalized() * WALK_SPEED
	_player.move_and_slide()
	_player.position.y = 0.0

## BFS over the stamped cells from the walker's cell to the deepest-z cell the
## built world can reach; the path replans on every new segment and on stalls.
func _auto_plan() -> void:
	var start := Vector2i(int(floor(_player.position.x)), int(floor(_player.position.z)))
	if not _walk_cells.has(start):
		var found := false
		for r in range(1, 4):
			for dz in range(-r, r + 1):
				for dx in range(-r, r + 1):
					var c0 := Vector2i(start.x + dx, start.y + dz)
					if _walk_cells.has(c0):
						start = c0
						found = true
						break
				if found:
					break
			if found:
				break
		if not found:
			return
	var prev: Dictionary = {}
	var q: Array = [start]
	prev[start] = start
	var best := start
	var qi := 0
	while qi < q.size():
		var c: Vector2i = q[qi]
		qi += 1
		if c.y > best.y:
			best = c
		for d in [Vector2i(1, 0), Vector2i(-1, 0), Vector2i(0, 1), Vector2i(0, -1)]:
			var n: Vector2i = c + d
			if _walk_cells.has(n) and not prev.has(n):
				prev[n] = c
				q.append(n)
	if best == start:
		return
	var path: Array = []
	var c := best
	while c != start:
		path.push_front(Vector3(float(c.x) + 0.5, 0.0, float(c.y) + 0.5))
		c = prev[c]
	_auto_path = path

func _auto_write(done: bool, ok: bool) -> void:
	var f := FileAccess.open("res://ada_run/em_autopilot.json", FileAccess.WRITE)
	if f:
		f.store_string(JSON.stringify({
			"done": done, "ok": ok, "museums_target": _autopilot,
			"goal_z": _auto_goal_z, "z": _player.position.z, "x": _player.position.x,
			"segments_built": _seg_index, "elapsed_s": _auto_t,
			"cells_unlearned": _auto_learned,
		}, " "))

## THE SHOT IS COMPOSED, NOT AIMED. Three of the four proof stills were the same
## picture: perfect one-point perspective, vanishing point dead centre in both
## axes, no foreground occluder, no diagonal, no framing element entering a frame
## edge, and the horizon on the exact half-line. The fourth (--em-shot-at=20)
## was the only good one, and the only thing it did differently was stand where
## a near jamb entered the frame as a foreground plane.
##
## So: step 1.7 m off the axis and yaw ~9 degrees back onto it. The vista is kept
## and a near jamb or pilaster enters one edge as a foreground value anchor. Eye
## drops to 1.62 and the camera pitches ~2 degrees down, which puts the horizon
## at about 0.55 of frame height instead of bisecting it.
func _take_proof_shot() -> void:
	var spec: Dictionary = _museums[0]
	_cam.position = Vector3(0, 1.62, 0)
	if _shot_z >= 0.0:
		var cx: float = float(spec["w"]) / 2.0
		_player.position = Vector3(cx + 1.7, 0.0, _shot_z)
		# forward is (-sin y, 0, -cos y): y just under PI turns back toward -x,
		# i.e. back onto the axis we just stepped off
		_player.rotation = Vector3(0.0, PI - 0.16, 0.0)
		_cam.rotation = Vector3(-0.035, 0.0, 0.0)
		_shoot_deferred()
		return
	# negative --em-shot-at is the banner shot. The sign is no longer on the axis,
	# so this can no longer be "stand at the mouth and tilt up" — stand off the
	# west wall and turn to face the sign, aiming at where it was actually built
	# rather than at a hardcoded guess.
	# NOT at z 0.85. The very first segment has no museum behind it, so its near
	# seal runs the FULL lobby width across z 0..1 — a camera at 0.85 stands
	# inside that wall box and half the frame is the inside of a plaster slab.
	# Stand deep in the lobby instead, near the portal, and look back across it:
	# 4.7 m out at 15 degrees off the sign's normal.
	var bp: Vector3 = _banner_pos if _banner_pos != Vector3.ZERO else Vector3(1.06, 1.95, 2.30)
	var eye: Vector3 = Vector3(bp.x + 4.55, 1.62, bp.z + 1.20)
	_player.position = Vector3(eye.x, 0.0, eye.z)
	var d: Vector3 = (bp - eye).normalized()
	_player.rotation = Vector3(0.0, atan2(-d.x, -d.z), 0.0)
	_cam.rotation = Vector3(asin(clampf(d.y, -1.0, 1.0)), 0.0, 0.0)
	_shoot_deferred()

func _shoot_deferred() -> void:
	var frames := 90
	var t := get_tree()
	var counter := {"n": 0}
	var cb: Callable
	cb = func() -> void:
		counter["n"] += 1
		if counter["n"] >= frames:
			t.process_frame.disconnect(cb)
			var img := get_viewport().get_texture().get_image()
			img.save_png(_shot_path)
			print("[endless_museum] proof shot -> %s" % _shot_path)
			t.quit()
	t.process_frame.connect(cb)
