extends Node3D
# endless_museum.gd — the endless museum corridor (fast loop, v1).
#
# Streams museum-template segments ahead of the walker: each segment stamps one
# principal template extracted from a real floor plan (commons/data/
# template_patterns.json, museum-tagged entries) and fills its slots from the
# artifact registries in seeded order. Walk forward (+z) and the next museum
# opens; segments three behind are freed. Valid by construction — no pathfinder
# at runtime; the templates were validated at extraction (entry-to-exit path,
# stop pocket per slot).
#
# Standalone and additive: no GridSystem, no shipped map touched.
#   Walk:  godot --path . res://commons/scenes/endless_museum.tscn -- --em-seed=46
#   Proof: ... -- --em-shot=user://em_proof.png --em-segments=3 (build, shoot, quit)
#          --em-shot-at=<z> moves the shot camera (negative z stands before the
#          first threshold and tilts up at its banner)
#
# THE POOL IS THE CURRICULUM (v2, the handover's wire). By default artifacts are
# dealt in SPINE ORDER from commons/data/spine_artifact_order.json (generated by
# tools/build_spine_artifact_order.py: sequence order -> map order -> first
# appearance) — the museum is the book walked through eight real buildings.
# --em-order=shuffle restores the v1 seeded shuffle; spine mode also falls back
# to the shuffle when the manifest is missing, so the corridor never opens empty.
#
# v1 debt PAID (2026-07-31): the walker is a CharacterBody3D — walls, podiums
# and hero plinths carry collision boxes (one StaticBody3D per segment), so the
# corridor pushes back instead of being glided through; the threshold banner is
# the canonical TextScreen (framed, baked-albedo, headless-safe), which also
# retires the mirrored-text bug — from behind you see a panel's back, not
# reversed words.

const TEMPLATES := "res://commons/data/template_patterns.json"
const REGISTRY_DIR := "res://commons/artifacts/registry"
const SPINE_ORDER := "res://commons/data/spine_artifact_order.json"
const TextScreenRes = preload("res://commons/ui/text_screen.gd")
const EYE := 1.65
const WALK_SPEED := 4.0
const BUILD_AHEAD_M := 24.0
const KEEP_BEHIND_M := 70.0
const MAX_ARTIFACTS_PER_SEGMENT := 8
# THE VESTIBULE (v3). Collision exposed what the gliding camera never felt:
# each template's exit gap and the next template's entry gap sit at different x,
# so the chain was walkable per-template but not BETWEEN templates. Every
# segment now opens with a short lobby the width of the widest template —
# closing strips seal width jumps — so any exit gap funnels into any entry gap.
# Real museums have these rooms too; the banner hangs there.
const VESTIBULE_H := 4
const LOBBY_W := 17

var _museums: Array = []          # [{key,label,museum,w,h,tile,walk_rule}]
var _pool: Array = []             # [{lookup, scene}]
var _pool_i: int = 0
var _seed: int = 46
var _order_mode: String = "spine"  # spine | shuffle
var _shot_path: String = ""
var _shot_segments: int = 3
var _shot_z: float = 1.0
var _test_collision: bool = false
var _test_frames: int = 0
var _segments: Array = []         # [{node, z0, z1, index}]
var _next_z: float = 0.0
var _seg_index: int = 0
var _prev_w: int = -1             # width of the previous segment's tile (lobby seals the jump)
var _first_key: String = ""       # --em-first=<key> rotates the dealing order
var _player: CharacterBody3D
var _cam: Camera3D
var _yaw: float = 0.0
var _pitch: float = 0.0

func _ready() -> void:
	_parse_args()
	_load_museums()
	_load_pool()
	if _museums.is_empty():
		push_error("endless_museum: no museum-tagged templates in %s" % TEMPLATES)
		return
	_setup_world()
	var preload_n: int = _shot_segments if _shot_path != "" else 2
	for i in range(preload_n):
		_build_segment()
	if _shot_path != "":
		_take_proof_shot()

func _parse_args() -> void:
	var args := OS.get_cmdline_user_args()
	if args.is_empty():
		args = OS.get_cmdline_args()
	for a in args:
		if a.begins_with("--em-seed="):
			_seed = int(a.substr(10))
		elif a.begins_with("--em-order="):
			_order_mode = a.substr(11)
		elif a.begins_with("--em-shot="):
			_shot_path = a.substr(10)
		elif a.begins_with("--em-shot-at="):
			_shot_z = float(a.substr(13))
		elif a.begins_with("--em-segments="):
			_shot_segments = int(a.substr(14))
		elif a == "--em-test-collision":
			_test_collision = true
		elif a.begins_with("--em-first="):
			_first_key = a.substr(11)

func _load_museums() -> void:
	var f := FileAccess.open(TEMPLATES, FileAccess.READ)
	if f == null:
		return
	var data: Variant = JSON.parse_string(f.get_as_text())
	if not (data is Dictionary):
		return
	var patterns: Dictionary = data.get("patterns", {})
	for key in patterns:
		var p: Dictionary = patterns[key]
		if p.has("museum"):  # only the extracted museum templates
			_museums.append({"key": key, "label": p.get("label", key),
				"museum": p.get("museum", ""), "w": int(p.get("w", 15)),
				"h": int(p.get("h", 30)), "tile": p.get("tile", []),
				"walk_rule": p.get("walk_rule", ""),
				"color": String(p.get("color", "#888888")),
				"em_order": int(p.get("em_order", 99))})
	# the dealing order is DATA (em_order on the pattern, a proposal not a
	# ruling); alphabetical keys are only the tiebreak. --em-first rotates a
	# chosen museum to the front for proof shots.
	_museums.sort_custom(func(a, b):
		if int(a["em_order"]) != int(b["em_order"]):
			return int(a["em_order"]) < int(b["em_order"])
		return String(a["key"]) < String(b["key"]))
	if _first_key != "":
		for i in range(_museums.size()):
			if String(_museums[i]["key"]) == _first_key:
				var head: Array = _museums.slice(i)
				head.append_array(_museums.slice(0, i))
				_museums = head
				break

func _load_pool() -> void:
	# the registry decides what is ALIVE (map_ready + scene on disk); the order
	# mode decides how the living are dealt
	var live: Dictionary = {}  # lookup -> {scene, fp}
	var dir := DirAccess.open(REGISTRY_DIR)
	if dir == null:
		return
	for fname in dir.get_files():
		if not fname.ends_with(".json"):
			continue
		var f := FileAccess.open(REGISTRY_DIR + "/" + fname, FileAccess.READ)
		if f == null:
			continue
		var data: Variant = JSON.parse_string(f.get_as_text())
		if not (data is Dictionary):
			continue
		var arts: Dictionary = data.get("artifacts", {})
		for lookup in arts:
			var a: Dictionary = arts[lookup]
			var scene: String = String(a.get("scene", ""))
			if scene != "" and a.get("map_ready", false) and ResourceLoader.exists(scene):
				live[String(lookup)] = {"scene": scene, "fp": _footprint_of(a)}
	if _order_mode == "spine" and _load_spine_pool(live):
		return
	# v1 fallback: alphabetical, then seeded shuffle
	for lookup in live:
		_pool.append({"lookup": lookup, "scene": live[lookup]["scene"],
			"fp": live[lookup]["fp"], "sequence": ""})
	_pool.sort_custom(func(a, b): return String(a["lookup"]) < String(b["lookup"]))
	var rng := RandomNumberGenerator.new()
	rng.seed = _seed
	for i in range(_pool.size() - 1, 0, -1):
		var j := rng.randi_range(0, i)
		var tmp: Variant = _pool[i]
		_pool[i] = _pool[j]
		_pool[j] = tmp
	print("[endless_museum] pool: shuffle, %d artifacts, seed %d" % [_pool.size(), _seed])

## The curriculum as the dealing order. Reads the generated manifest and keeps
## only artifacts the registry says are alive, in manifest order — so the first
## hero slot of the first museum receives the first artifact of the spine.
func _load_spine_pool(live: Dictionary) -> bool:
	var f := FileAccess.open(SPINE_ORDER, FileAccess.READ)
	if f == null:
		push_warning("endless_museum: --em-order=spine but %s is missing (run tools/build_spine_artifact_order.py); falling back to shuffle" % SPINE_ORDER)
		return false
	var data: Variant = JSON.parse_string(f.get_as_text())
	if not (data is Dictionary):
		return false
	var rows: Array = data.get("order", [])
	var skipped := 0
	for row in rows:
		var lookup := String((row as Dictionary).get("lookup", ""))
		if live.has(lookup):
			_pool.append({"lookup": lookup, "scene": live[lookup]["scene"],
				"fp": live[lookup]["fp"],
				"sequence": String((row as Dictionary).get("sequence", ""))})
		else:
			skipped += 1
	if _pool.is_empty():
		return false
	print("[endless_museum] pool: SPINE ORDER, %d of %d curriculum artifacts alive (%d not map_ready/on disk)" % [
		_pool.size(), rows.size(), skipped])
	return true

## Widest horizontal footprint dimension declared for an artifact (cells).
func _footprint_of(entry: Dictionary) -> int:
	var params: Dictionary = entry.get("parameters", {})
	var fp: Variant = params.get("footprint", null)
	if fp is Array and (fp as Array).size() >= 3:
		return maxi(1, maxi(int((fp as Array)[0]), int((fp as Array)[2])))
	return 1

## Deal the next artifact for a slot rank, spine order preserved up to a local
## 16-deep swap: the hero plinth prefers the chapter's large piece, a podium
## needs a compact one, a floor slot takes anything short of a giant — so a
## building never perches on a pedestal and giants wait for the plinth.
func _pick_pool(rank: int) -> Dictionary:
	var n := _pool.size()
	if n == 0:
		return {}
	var want_min := 1
	var want_max := 99
	match rank:
		0: want_min = 2
		1: want_max = 1
		2: want_max = 2
	for off in range(mini(16, n)):
		var idx := (_pool_i + off) % n
		var fp := int(_pool[idx].get("fp", 1))
		if fp >= want_min and fp <= want_max:
			if off > 0:
				var cur := _pool_i % n
				var tmp: Variant = _pool[cur]
				_pool[cur] = _pool[idx]
				_pool[idx] = tmp
			break
	var e: Dictionary = _pool[_pool_i % n]
	_pool_i += 1
	return e

func _setup_world() -> void:
	var env := WorldEnvironment.new()
	var e := Environment.new()
	e.background_mode = Environment.BG_SKY
	e.sky = Sky.new()
	e.sky.sky_material = ProceduralSkyMaterial.new()
	e.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	e.ambient_light_energy = 1.2
	env.environment = e
	add_child(env)
	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-55.0, 30.0, 0.0)
	sun.light_energy = 1.1
	sun.shadow_enabled = true
	add_child(sun)
	# the walker is a body now, not a gliding camera: a capsule the walls and
	# podiums can push back on. No gravity — the deck is flat by construction,
	# so y is clamped instead of simulated.
	_player = CharacterBody3D.new()
	_player.name = "Walker"
	_player.position = Vector3(7.5, 0.0, 1.5)
	_yaw = PI  # segments extend along +z; face into the museum
	_player.rotation = Vector3(0.0, _yaw, 0.0)
	var col := CollisionShape3D.new()
	var cap := CapsuleShape3D.new()
	cap.radius = 0.32
	cap.height = 1.5
	col.shape = cap
	col.position = Vector3(0, 0.95, 0)
	_player.add_child(col)
	add_child(_player)
	_cam = Camera3D.new()
	_cam.position = Vector3(0, EYE, 0)
	_cam.fov = 90.0
	_player.add_child(_cam)
	_cam.make_current()

func _mat(color: Color) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_color = color
	return m

func _box(parent: Node3D, pos: Vector3, size: Vector3, color: Color) -> void:
	var mi := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = size
	mi.mesh = bm
	mi.material_override = _mat(color)
	mi.position = pos
	parent.add_child(mi)

func _add_col(body: StaticBody3D, pos: Vector3, size: Vector3) -> void:
	var cs := CollisionShape3D.new()
	var bs := BoxShape3D.new()
	bs.size = size
	cs.shape = bs
	cs.position = pos
	body.add_child(cs)

func _build_segment() -> void:
	var spec: Dictionary = _museums[_seg_index % _museums.size()]
	var w: int = spec["w"]
	var h: int = spec["h"]
	var tile: Array = spec["tile"]
	var seg := Node3D.new()
	seg.name = "Seg%d_%s" % [_seg_index, spec["key"]]
	seg.position = Vector3(0, 0, _next_z)
	add_child(seg)
	# one static body per segment carries every collision box — walls, podiums,
	# hero plinths — so the whole museum frees with its segment node
	var solid := StaticBody3D.new()
	solid.name = "Collision"
	seg.add_child(solid)
	# — the vestibule: an open lobby joining the previous museum's exit gap to
	# this one's entry gap. Closing strips seal the width jump on both edges
	# (a fully sealed strip at the very first segment, where nothing is behind).
	var pw: int = _prev_w if _prev_w > 0 else 1
	var wall_col := Color(0.32, 0.32, 0.36)
	for zr in range(VESTIBULE_H):
		for x in range(LOBBY_W):
			_box(seg, Vector3(x + 0.5, -0.1, zr + 0.5), Vector3(1, 0.2, 1), Color(0.13, 0.13, 0.16))
	for zr in range(VESTIBULE_H):
		for sx in [0, LOBBY_W - 1]:
			_box(seg, Vector3(sx + 0.5, 1.5, zr + 0.5), Vector3(1, 3.0, 1), wall_col)
			_add_col(solid, Vector3(sx + 0.5, 1.5, zr + 0.5), Vector3(1, 3.0, 1))
	for x in range(pw - 1, LOBBY_W):        # seal beyond the previous tile's width
		_box(seg, Vector3(x + 0.5, 1.5, 0.5), Vector3(1, 3.0, 1), wall_col)
		_add_col(solid, Vector3(x + 0.5, 1.5, 0.5), Vector3(1, 3.0, 1))
	for x in range(w - 1, LOBBY_W):         # seal beyond this tile's width
		_box(seg, Vector3(x + 0.5, 1.5, VESTIBULE_H - 0.5), Vector3(1, 3.0, 1), wall_col)
		_add_col(solid, Vector3(x + 0.5, 1.5, VESTIBULE_H - 0.5), Vector3(1, 3.0, 1))
	# outer skin: an implicit wall just beyond both side columns of the tile, so
	# free-plan templates with a walkable rim (Kanazawa, Neue Nationalgalerie)
	# cannot leak the walker off the edge of the world
	for y_skin in range(tile.size()):
		for sx2 in [-1, w]:
			_box(seg, Vector3(sx2 + 0.5, 1.5, y_skin + VESTIBULE_H + 0.5), Vector3(1, 3.0, 1), wall_col)
			_add_col(solid, Vector3(sx2 + 0.5, 1.5, y_skin + VESTIBULE_H + 0.5), Vector3(1, 3.0, 1))
	# collect slots first so the artifact budget prefers hero > podium > floor
	var slots: Array = []
	for y in range(tile.size()):
		var row: Array = tile[y]
		var z := y + VESTIBULE_H
		for x in range(row.size()):
			var c := String(row[x])
			match c:
				"1", "1s":
					_box(seg, Vector3(x + 0.5, -0.1, z + 0.5), Vector3(1, 0.2, 1), Color(0.16, 0.16, 0.19))
				"2", "2s":
					_box(seg, Vector3(x + 0.5, 0.1, z + 0.5), Vector3(1, 0.6, 1), Color(0.23, 0.23, 0.28))
					_add_col(solid, Vector3(x + 0.5, 0.1, z + 0.5), Vector3(1, 0.6, 1))
				"3s":
					_box(seg, Vector3(x + 0.5, 0.3, z + 0.5), Vector3(1, 1.0, 1), Color(0.35, 0.27, 0.16))
					_add_col(solid, Vector3(x + 0.5, 0.3, z + 0.5), Vector3(1, 1.0, 1))
				"4":
					_box(seg, Vector3(x + 0.5, 1.5, z + 0.5), Vector3(1, 3.0, 1), wall_col)
					_add_col(solid, Vector3(x + 0.5, 1.5, z + 0.5), Vector3(1, 3.0, 1))
			if c == "1s":
				slots.append({"x": x, "y": z, "top": 0.0, "rank": 2})
			elif c == "2s":
				slots.append({"x": x, "y": z, "top": 0.4, "rank": 1})
			elif c == "3s":
				slots.append({"x": x, "y": z, "top": 0.8, "rank": 0})
	slots.sort_custom(func(a, b): return int(a["rank"]) < int(b["rank"]))
	var placed := 0
	var seg_seq := ""
	for s in slots:
		if placed >= MAX_ARTIFACTS_PER_SEGMENT or _pool.is_empty():
			break
		var entry: Dictionary = _pick_pool(int(s["rank"]))
		if entry.is_empty():
			break
		# chapter alignment: a museum houses ONE sequence. When the spine order
		# crosses into the next sequence mid-museum (and this museum already
		# holds a real showing), the chapter opener is handed back and the NEXT
		# museum opens with it — the book's chapters get buildings.
		var sq := String(entry.get("sequence", ""))
		if seg_seq == "":
			seg_seq = sq
		elif sq != seg_seq and sq != "" and placed >= 4:
			_pool_i -= 1
			break
		var ps: PackedScene = load(String(entry["scene"])) as PackedScene
		if ps == null:
			continue
		var node: Node3D = ps.instantiate() as Node3D
		if node == null:
			continue
		node.set_meta("artifact_lookup_name", entry["lookup"])
		node.position = Vector3(float(s["x"]) + 0.5, float(s["top"]), float(s["y"]) + 0.5)
		seg.add_child(node)
		placed += 1
	# museum banner at the threshold — the canonical TextScreen (framed panel,
	# baked albedo, headless-safe). Properties set before add_child so the one
	# _ready() rebuild builds the right sign.
	# each museum wears its own colour: the pattern's hex tints the banner title
	# and an ember strip across the threshold floor
	var accent := Color.html(String(spec.get("color", "#888888")))
	var banner: Node3D = TextScreenRes.new()
	banner.mode = TextScreenRes.Mode.SCREEN
	banner.title = String(spec["label"])
	# the banner names the building AND the chapter it houses
	banner.body = ("%s\n\n%s" % [spec["museum"], seg_seq]) if seg_seq != "" else String(spec["museum"])
	banner.title_color = accent.lightened(0.35)
	banner.width_m = 2.8
	# the banner hangs in the vestibule, over the museum's entry
	banner.position = Vector3(w / 2.0, 2.45, VESTIBULE_H - 0.45)
	banner.rotation_degrees = Vector3(0, 180, 0)
	seg.add_child(banner)
	var ember := MeshInstance3D.new()
	var ebm := BoxMesh.new()
	ebm.size = Vector3(w - 2.0, 0.02, 0.08)
	ember.mesh = ebm
	var emat := StandardMaterial3D.new()
	emat.albedo_color = accent
	emat.emission_enabled = true
	emat.emission = accent
	emat.emission_energy_multiplier = 1.6
	ember.material_override = emat
	ember.position = Vector3(w / 2.0, 0.02, VESTIBULE_H - 0.15)
	seg.add_child(ember)
	_segments.append({"node": seg, "z0": _next_z, "z1": _next_z + float(h) + float(VESTIBULE_H), "index": _seg_index})
	_next_z += float(h) + float(VESTIBULE_H)
	_seg_index += 1
	_prev_w = w
	print("[endless_museum] seg %d = %s (%s) chapter=%s placed %d, z %.0f..%.0f" % [
		_seg_index - 1, spec["key"], spec["museum"], seg_seq if seg_seq != "" else "-",
		placed, _segments[-1]["z0"], _segments[-1]["z1"]])

func _process(_delta: float) -> void:
	if _cam == null or _shot_path != "":
		return
	# stream: open the next museum as the walker nears the built edge
	if _cam.global_position.z > _next_z - BUILD_AHEAD_M:
		_build_segment()
	# free far-behind segments (keep the museum endless, not the node tree)
	while _segments.size() > 2 and float(_segments[0]["z1"]) < _cam.global_position.z - KEEP_BEHIND_M:
		var old: Dictionary = _segments.pop_front()
		var n: Node3D = old["node"]
		n.queue_free()

func _physics_process(_delta: float) -> void:
	if _player == null or _shot_path != "":
		return
	if _test_collision:
		_run_collision_test()
		return
	# walk — as a body: move_and_slide lets the walls and podiums push back
	var dir := Vector3.ZERO
	if Input.is_key_pressed(KEY_W):
		dir -= _player.global_transform.basis.z
	if Input.is_key_pressed(KEY_S):
		dir += _player.global_transform.basis.z
	if Input.is_key_pressed(KEY_A):
		dir -= _player.global_transform.basis.x
	if Input.is_key_pressed(KEY_D):
		dir += _player.global_transform.basis.x
	dir.y = 0.0
	if dir.length() > 0.01:
		var speed := WALK_SPEED * (2.5 if Input.is_key_pressed(KEY_SHIFT) else 1.0)
		_player.velocity = dir.normalized() * speed
	else:
		_player.velocity = Vector3.ZERO
	_player.move_and_slide()
	# the deck is flat by construction — clamp rather than simulate gravity
	_player.position.y = 0.0

func _input(event: InputEvent) -> void:
	if _shot_path != "":
		return
	if event is InputEventMouseButton and event.pressed:
		Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
	elif event is InputEventKey and event.pressed and event.keycode == KEY_ESCAPE:
		Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
	elif event is InputEventMouseMotion and Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:
		_yaw -= event.relative.x * 0.002
		_pitch = clampf(_pitch - event.relative.y * 0.002, -1.2, 1.2)
		_player.rotation = Vector3(0.0, _yaw, 0.0)
		_cam.rotation = Vector3(_pitch, 0.0, 0.0)

## The negative test: drive the walker straight at the west wall for two
## seconds. A gliding camera sails through x=1.0 into the void; a body stops at
## the wall face plus its capsule radius. Verdict lands in
## ada_run/em_collision_test.json so the watchdog has a file to expect.
func _run_collision_test() -> void:
	_test_frames += 1
	_player.velocity = Vector3(-WALK_SPEED, 0.0, 0.0)
	_player.move_and_slide()
	_player.position.y = 0.0
	if _test_frames < 120:
		return
	var x := _player.position.x
	var free_x := 7.5 - WALK_SPEED * 2.0   # where a collisionless glide would stand
	var blocked := x > 0.9                  # wall inner face 1.0 minus a little slide
	var verdict := {
		"start_x": 7.5, "final_x": x, "free_glide_x": free_x,
		"wall_inner_face_x": 1.0, "capsule_radius": 0.32,
		"blocked_by_wall": blocked,
	}
	var f := FileAccess.open("res://ada_run/em_collision_test.json", FileAccess.WRITE)
	if f:
		f.store_string(JSON.stringify(verdict, " "))
	print("[endless_museum] collision test: final_x=%.2f (free glide would be %.2f) -> %s" % [
		x, free_x, "BLOCKED" if blocked else "PASSED THROUGH"])
	get_tree().quit(0 if blocked else 1)

func _take_proof_shot() -> void:
	# stand at the first segment's entry (or --em-shot-at=<z>), look down the
	# corridor, settle, save
	var spec: Dictionary = _museums[0]
	# negative --em-shot-at means "the banner shot": stand at the lobby's mouth
	# and tilt up at the vestibule sign instead of down the axis
	var z: float = _shot_z if _shot_z >= 0.0 else 0.7
	_player.position = Vector3(float(spec["w"]) / 2.0, 0.0, z)
	_player.rotation = Vector3(0.0, PI, 0.0)  # scene +z runs away from entry; face along it
	_cam.rotation = Vector3(-0.05 if _shot_z >= 0.0 else 0.18, 0.0, 0.0)
	_shoot_deferred()

func _shoot_deferred() -> void:
	var frames := 90
	var t := get_tree()
	var counter := {"n": 0}
	var cb: Callable
	cb = func() -> void:
		counter["n"] += 1
		if counter["n"] >= frames:
			t.process_frame.disconnect(cb)
			var img := get_viewport().get_texture().get_image()
			img.save_png(_shot_path)
			print("[endless_museum] proof shot -> %s" % _shot_path)
			t.quit()
	t.process_frame.connect(cb)
