## LIVE PORT — generated by tools/port_wcn_probes_live.py from probe_wcn_intro.gd. Do not edit;
## edit the SceneTree probe and regenerate. Runs under project startup (probe_live.tscn
## with --probe=intro), so the project's autoloads exist and XR Tools pickables compile.
## Outputs carry a _live suffix.
extends Node
## WaveFunctions_Intro pilot (doc/research/waves-chance-noise, 2026-09-10):
## can a visitor release the pendulum, and does the room show two visits to the
## centre with opposite angular velocities?
##
## Stands up the ACTUAL museum hall with its artifacts (the pattern of
## probe_wave_platform_recovery.gd), finds the ControlPendulum, checks the
## reference and the readout it was placed with, drives the bob through the
## pickable's own picked_up / dropped signals — EMITTED PROGRAMMATICALLY, no
## tracked hand — and records the centre_crossed signals it emits. Measures the
## installation bounds and the swing envelope against the hall's collision.
##
##   godot --rendering-method gl_compatibility --path . --xr-mode off --script res://commons/testing/probe_wcn_intro.gd -- --capture
##
## Writes res://ada_run/waves_chance_noise/WaveFunctions_Intro/probe_intro.json
## (and probe_intro.png under --capture). A complete pass requires the bob in
## the tree, pickup/drop exercised and centre crossings with opposite signs.
## If the script startup omits required autoloads, retain diagnostics but fail
## the required release contract; an autonomous swing is only partial evidence.
## What it cannot prove: that a tracked hand reaches the bob. Headset acceptance
## is separate and is recorded as such in the report.
var checks := 0
var failures: Array[String] = []
var measurements: Dictionary = {}
var crossings: Array = []
var release_exercised := false
var skipped: Array[String] = []
var t0 := 0.0
const MAP := "WaveFunctions_Intro"
const OUT := "res://ada_run/waves_chance_noise/WaveFunctions_Intro/"

func _ready() -> void: run.call_deferred()

## True under the live harness (probe_live.tscn, project startup with autoloads);
## false under --script, where the desktop rig cannot compile.
func _live() -> bool:
	return str(get_script().resource_path).ends_with("_live.gd")

func check(ok: bool, message: String) -> void:
	checks += 1
	if not ok: failures.append(message)
	print("[wcn-intro] ", "PASS " if ok else "FAIL ", message)

func run() -> void:
	if "--capture" in OS.get_cmdline_user_args() and DisplayServer.get_name() == "headless":
		check(false, "PNG capture requires a rendered window; omit --headless, or omit --capture for logic only")
		_finish()
		return
	var em: Node3D = load("res://commons/scenes/endless_museum.tscn").instantiate()
	var ctl := "res://ada_run/waves_chance_noise/wcn-probe-control.json"
	em.set("EM_CONTROL", ctl); em.set("_overrides_path", ctl + ".unused"); em.set("_hand_path", ctl + ".unused-hand")
	em.set("start_chapter", "wavefunctions"); em.set("start_map", MAP)
	var layout: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://commons/data/em_layout.json"))
	layout.get_or_add("stream", {})["bodies"] = 1
	em.set("_layout", layout)
	var f := FileAccess.open(ctl, FileAccess.WRITE)
	f.store_string(JSON.stringify({"first_chapter": "wavefunctions", "dollhouse": 0, "grid_pack": 1})); f.close()
	# CATCH THE BOB LEAVING (diagnostic, 2026-09-10): every node entering or leaving the
	# tree passes the SceneTree's own signals; a BobSphere leaving is recorded with its
	# parent's state and the call stack (empty without a debugger, kept anyway).
	var leave_log: Array = []
	get_tree().node_added.connect(func(n: Node):
		if n.name == "BobSphere":
			var p: Node = n.get_parent()
			leave_log.append({"event": "added", "frame": Engine.get_process_frames(), "parent": str(p.name) if p else "none",
				"parent_ready": p.is_node_ready() if p else false, "parent_in_tree": p.is_inside_tree() if p else false})
			n.tree_exiting.connect(func():
				var pp: Node = n.get_parent()
				var kids: Array = []
				if pp != null:
					for c in pp.get_children(): kids.append(c.name)
				leave_log.append({"event": "exiting", "frame": Engine.get_process_frames(), "parent": str(pp.name) if pp else "none",
					"parent_ready": pp.is_node_ready() if pp else false, "parent_kids": kids, "stack": get_stack()})))
	get_tree().node_removed.connect(func(n: Node):
		if n.name == "BobSphere":
			leave_log.append({"event": "removed", "frame": Engine.get_process_frames(), "queued_for_deletion": n.is_queued_for_deletion()}))
	measurements["bob_tree_events"] = leave_log
	get_tree().root.add_child(em); get_tree().current_scene = em
	# WATCH THE BOB FROM FRAME ZERO (diagnostic, 2026-09-10): the grab sphere is built
	# in the pendulum's _ready and is gone from the tree by the time the checks run.
	# Record the frame it leaves and what the pendulum looked like at that moment.
	var watch_pend: Node3D = null
	var watch_bob: Node = null
	var detached_at := -1
	for fr in range(90):
		await get_tree().process_frame
		if watch_pend == null:
			for n in em.find_children("*", "Node3D", true, false):
				if n is ControlPendulum: watch_pend = n; break
			if watch_pend != null:
				measurements["pendulum_found_at_frame"] = fr
				watch_bob = watch_pend.find_child("BobSphere", true, false)
				measurements["bob_present_when_found"] = watch_bob != null
				if watch_bob == null:
					var bv0: Variant = watch_pend.get("_bob_sphere")
					if bv0 is Node: watch_bob = bv0
		elif watch_bob != null and detached_at < 0 and not (watch_bob as Node).is_inside_tree():
			detached_at = fr
			var names0: Array = []
			for c in watch_pend.get_children(): names0.append(c.name)
			measurements["bob_detached_at_frame"] = fr
			measurements["pendulum_children_at_detach"] = names0
			measurements["pendulum_grabbed_at_detach"] = watch_pend.get("_is_grabbed")
			measurements["pendulum_in_tree_at_detach"] = watch_pend.is_inside_tree()
			measurements["pendulum_parent_at_detach"] = str(watch_pend.get_parent().name) if watch_pend.get_parent() != null else "none"
	em.set_process(false); em.call("flush_stamps")
	var player: Node = em.get("_player")
	if player != null: player.set_process(false); player.set_physics_process(false)
	var seg: Node3D
	for rec: Dictionary in em.get("_segments"):
		if rec.node.get_meta("em_map", "") == MAP: seg = rec.node; break
	check(seg != null, "the hall exists in the active museum")
	if seg == null:
		_finish(); return
	for i in range(30): await get_tree().process_frame

	# ── 1. the pendulum, as placed ────────────────────────────────────────────
	var pend: Node3D
	for n in seg.find_children("*", "Node3D", true, false):
		if n is ControlPendulum: pend = n; break
	check(pend != null, "control_pendulum is built in the hall")
	if pend == null:
		_finish(); return
	check(str(pend.get("reference")) == "plumb", "placed with reference=plumb (token config reached the artifact)")
	check(str(pend.get("evidence")) == "trace", "placed with evidence=trace")
	check(str(pend.get("regime")) == "free", "regime is the shipped free")
	check(pend.get_node_or_null("Reference/RestRing") != null, "the rest ring exists")
	check(pend.get_node_or_null("Reference/Plumb") != null, "the plumb line exists")
	# the visual pass of 12 September: a slate behind the swing and a cased readout beside it
	check(pend.get_node_or_null("Reference/Slate") != null, "a dark slate stands behind the swing plane")
	check(pend.get_node_or_null("Reference/LabelPlate") != null, "the state readout is cased beside the pivot")
	var lbl_ref: Label3D = pend.get("_label")
	check(lbl_ref != null and lbl_ref.font_size >= 22 and lbl_ref.position.x > 0.5, "the readout is enlarged and out of the swing (font %d, x %.2f)" % [lbl_ref.font_size if lbl_ref != null else -1, lbl_ref.position.x if lbl_ref != null else 0.0])
	check(pend.get_node_or_null("Evidence/Theta") != null, "the predicted theta(t) is drawn")
	var bob: Node3D = pend.find_child("BobSphere", true, false)
	if bob == null:
		# diagnostic (2026-09-10): bare instantiation has BobSphere as a direct child in both
		# configuration orders; in the museum it is absent. Record what stands where.
		var names: Array = []
		for c in pend.get_children(): names.append(c.name + ":" + c.get_class())
		measurements["pendulum_children"] = names
		measurements["bob_var"] = str(pend.get("_bob_sphere"))
		var elsewhere: Array = []
		for n in seg.find_children("*", "", true, false):
			if n.get_script() != null and str(n.get_script().resource_path).ends_with("grab_sphere.gd"):
				elsewhere.append(str(n.get_path()).right(80))
		for n in em.find_children("BobSphere*", "", true, false):
			elsewhere.append("em:" + str(n.get_path()).right(80))
		measurements["grab_spheres_elsewhere"] = elsewhere
		var bv: Variant = pend.get("_bob_sphere")
		if bv is Node:
			var bn: Node = bv
			measurements["bob_in_tree"] = bn.is_inside_tree()
			measurements["bob_parent"] = str(bn.get_parent().get_path()) if bn.get_parent() != null else "none"
			measurements["bob_valid"] = is_instance_valid(bn)
			if bn.is_inside_tree():
				bob = bn   # it exists; it was reparented — follow it
	# THE RELEASE PATH CANNOT BE EXERCISED FROM A SceneTree PROBE (found 2026-09-10 with
	# --log-file): grab_sphere.gd names TextManager and XR Tools' pickable.gd names
	# XRToolsUserSettings at compile time; without the autoloads both fail to COMPILE, the
	# grab sphere instantiates as a bare RigidBody3D, control_pendulum's _create_grabbable_bob
	# aborts on `alter_freeze` and the bob never enters the tree. project.godot declares
	# the required autoloads; verify construction and release through that startup.
	# The swing, crossings and readout remain partial evidence, not a release test.
	var release_testable: bool = bob != null and bob.has_signal("picked_up") and bob.has_signal("dropped")
	if not release_testable:
		# Still a FAILURE, by the 12 September ruling: a script-only run must not pass the
		# release contract. It now says where the contract IS exercised.
		var reason := "Required pickup/release was not exercised in this lane: under --script the grab sphere cannot compile without its autoloads, so the bob never enters the tree. The release is exercised through the desktop pointer's right-click in the live lane (probe_intro_live.json)."
		measurements["release_path"] = reason
		skipped.append(reason)
		check(false, reason)
	else:
		check(bob.has_signal("picked_up") and bob.has_signal("dropped"), "the bob carries the pickable's picked_up/dropped signals")
	var rest_local: Vector3 = seg.to_local(pend.call("rest_world_position"))
	measurements["rest_point_local"] = [rest_local.x, rest_local.y, rest_local.z]
	check(rest_local.y > 0.6 and rest_local.y < 1.6, "the rest point is at hand height (%.2f m above the deck)" % rest_local.y)
	var L: float = float(pend.get("pendulum_length"))
	for side in [-1.0, 1.0]:
		var release := pend.to_global(Vector3(sin(0.6) * L * side, -cos(0.6) * L, 0.0))
		var rl := seg.to_local(release)
		check(rl.y > 0.5 and rl.y < 1.8, "release position %s is reachable (%.2f m)" % ["left" if side < 0 else "right", rl.y])
		check(not _solid_at(seg, release, 0.09), "release position %s is clear of the hall's collision" % ["left" if side < 0 else "right"])
	# the swing envelope: a box the full width of the swing under the pivot
	var env := BoxShape3D.new()
	env.size = Vector3(2.0 * L + 0.3, L + 0.3, 0.3)
	var q := PhysicsShapeQueryParameters3D.new()
	q.shape = env; q.transform = Transform3D(Basis.IDENTITY, pend.to_global(Vector3(0, -L * 0.5, 0)))
	var hits: Array = seg.get_world_3d().direct_space_state.intersect_shape(q, 8)
	var solid_hits := 0
	for h in hits:
		if h.collider == seg.get_node_or_null("Collision"): solid_hits += 1
	check(solid_hits == 0, "the complete swing is clear of walls and platforms (%d solid hits)" % solid_hits)
	measurements["installation_aabb"] = _aabb(pend)

	# ── 2. the real signal path: pick up, move, drop ──────────────────────────
	var crossings_before_observation: int = int(pend.call("crossings"))
	pend.connect("centre_crossed", func(d: int, w: float): crossings.append({"dir": d, "omega": w, "t": Time.get_ticks_msec() / 1000.0 - t0}))
	t0 = Time.get_ticks_msec() / 1000.0
	if release_testable:
		var first: Dictionary = await _release(pend, bob, 0.6)
		release_exercised = true
		check(float(first.get("release_omega", 0.0)) > 0.0, "a hand moving toward increasing angle releases in that direction")
		check(not bool(pend.call("is_grabbed")), "the artifact answered dropped: not grabbed after release")
		check(absf(float(first.get("angle", 0.0)) - 0.6) < 0.15, "the release angle came from the bob's position (%.2f rad)" % float(first.get("angle", 0.0)))
	# (without a release the pendulum swings from START_ANGLE on its own; the crossings below are that swing's)
	await get_tree().create_timer(4.0).timeout
	var n1 := crossings.size()
	check(n1 >= 2, "at least two centre crossings during the observation (%d)" % n1)
	if n1 >= 2:
		check(int(crossings[0]["dir"]) != int(crossings[1]["dir"]), "the first two crossings travel in opposite directions (%d then %d)" % [int(crossings[0]["dir"]), int(crossings[1]["dir"])])
		check(signf(float(crossings[0]["omega"])) != signf(float(crossings[1]["omega"])), "their angular velocities have opposite signs (%+.2f, %+.2f rad/s)" % [float(crossings[0]["omega"]), float(crossings[1]["omega"])])
	check(int(pend.call("crossings")) - crossings_before_observation == n1, "the count advances by the observed crossings; earlier motion is retained")
	var lbl: Label3D = pend.get_node_or_null("Label3D") if pend.get_node_or_null("Label3D") else null
	for c in pend.get_children():
		if c is Label3D: lbl = c
	check(lbl != null and (lbl.text.contains("ω +") or lbl.text.contains("ω -")), "the readout prints a SIGNED angular velocity")
	# ── 3. release from the other side ────────────────────────────────────────
	if release_testable:
		var before := crossings.size()
		var dir_first: int = int(crossings[0]["dir"]) if n1 > 0 else 0
		await _release(pend, bob, -0.6)
		await get_tree().create_timer(2.5).timeout
		check(crossings.size() > before, "a second release crosses the centre again")
		if crossings.size() > before and n1 > 0:
			check(int(crossings[before]["dir"]) != dir_first, "released from the other side, the first crossing goes the other way")
	# ── 4. the driven cube listens to this pendulum ───────────────────────────
	var cube: Node = null
	for n in seg.find_children("*", "Node3D", true, false):
		if n.get_script() != null and str(n.get_script().resource_path).ends_with("oscillation_controlled_cube.gd"): cube = n; break
	check(cube != null, "oscillation_controlled_cube stands in the hall")
	if cube != null:
		check(cube.get("_pendulum") == pend, "the driven cube found THIS pendulum (one signal, three transformations)")
	measurements["crossings"] = crossings
	measurements["scale"] = [pend.scale.x, pend.scale.y, pend.scale.z]
	check(pend.scale.is_equal_approx(Vector3.ONE), "the subject's scale is what the map asked (1)")

	# ── ACTUAL DESKTOP INPUT (live harness only): grab, carry, release, from both sides ──
	# The pilot aimed at the bob and right-clicked, and recorded "nothing" — but its hover
	# read the INTERACTION ray, which cannot see layer 3, and its bob position was whatever
	# the integrator had just written, because nothing had told the pendulum the bob was
	# held. Since 2026-09-13 the pointer's carry reaches the pendulum's own pickup and drop
	# handlers (desktop_hook_target). This lane exercises exactly that path.
	if _live() and release_testable:
		var drv: Node = load("res://commons/testing/wcn_desktop_driver.gd").new()
		get_tree().root.add_child(drv)   # a SceneTree has no add_child; the port maps root. to get_tree().root.
		# 1.15 m in front of the swing plane: the driven cube stands two cells behind the
		# pendulum at (2,13), and the pilot's 1.5 m stand put the rig inside it.
		var stand: Vector3 = pend.to_global(Vector3(0.0, 0.0, 1.15))
		stand.y = seg.to_global(Vector3(0, 0, 0)).y
		drv.call("spawn", stand, em)
		await get_tree().create_timer(0.5).timeout
		var ptr: Node = drv.get("pointer")
		var rig: Node3D = drv.get("rig")
		var di := {"stand_asked": _v(seg.to_local(stand)), "stand_after_spawn": _v(seg.to_local(rig.global_position))}
		measurements["desktop_release"] = di
		check(ptr != null and ptr.has_method("is_holding"), "the rig carries the pointer that grabs (%s)" % (str(ptr.get_path()).right(50) if ptr != null else "none"))
		check(rig.global_position.distance_to(stand) < 0.15, "and it stands where it was put, not pushed off a neighbour (%.2f m)" % rig.global_position.distance_to(stand))
		if ptr != null and ptr.has_method("is_holding"):
			var releases: Array = []
			for side in [1.0, -1.0]:
				var g: Dictionary = await _desktop_grab(drv, ptr, pend)
				var rec := {"side": side, "grab": g}
				var name_side: String = "right" if side > 0.0 else "left"
				check(bool(g.get("held", false)), "%s release: the pointer's right-click holds the bob (attempt %d, grab ray %s)" % [name_side, int(g.get("attempt", -1)), str(g.get("grab_ray", "-"))])
				check(bool(g.get("pendulum_knows", false)), "%s release: and the PENDULUM knows it is held — the desktop grab reached its own pickup handler" % name_side)
				if not bool(g.get("held", false)):
					releases.append(rec)
					continue
				var c: Dictionary = await _desktop_carry_and_drop(drv, ptr, pend, 0.6 * side, name_side)
				rec["carry"] = c
				check(float(c.get("bob_to_target_m", 9.0)) < 0.12, "%s release: the carried bob reached the release position (%.2f m away)" % [name_side, float(c.get("bob_to_target_m", 9.0))])
				check(signf(float(c.get("held_angle", 0.0))) == side and absf(float(c.get("held_angle", 0.0))) > 0.35,
					"%s release: the pendulum read its angle off the carried bob (%+.2f rad)" % [name_side, float(c.get("held_angle", 0.0))])
				check(bool(c.get("released", false)), "%s release: the right-click drop reached its release handler — not grabbed, pointer empty" % name_side)
				check(bool(c.get("released_signal_heard", false)), "%s release: the pendulum's own released signal fired" % name_side)
				check(absf(float(c.get("release_omega", 9.0))) < 0.3, "%s release: a still hand releases from rest — omega %+.2f rad/s at the release handler, angle %+.2f rad" % [name_side, float(c.get("release_omega", 9.0)), float(c.get("release_angle", 9.0))])
				var n0: int = crossings.size()
				var samples: Array = []
				var turns: Array = []
				var prev_w: float = float(pend.call("angular_velocity"))
				for fr in range(210):
					await get_tree().physics_frame
					var bp: Vector3 = pend.call("bob_world_position")
					samples.append(seg.to_local(bp))
					var w: float = float(pend.call("angular_velocity"))
					# a TURNING POINT: omega changes sign away from the centre. The pointer's
					# own grab ray is cast at the bob there, at both sides of the swing.
					if signf(w) != signf(prev_w) and absf(float(pend.call("angle"))) > 0.15 and turns.size() < 2:
						turns.append({"angle": float(pend.call("angle")), "ray": _grab_ray_to(drv, bp)})
					prev_w = w
				var after: Array = crossings.slice(n0)
				rec["crossings"] = after
				rec["turns"] = turns
				rec["swing_x"] = _swing_x(samples)
				releases.append(rec)
				check(after.size() >= 2, "%s release: at least two centre crossings follow (%d)" % [name_side, after.size()])
				if after.size() >= 2:
					check(signf(float(after[0]["omega"])) != signf(float(after[1]["omega"])),
						"%s release: the first two cross the same point with opposite angular velocities (%+.2f, %+.2f rad/s)" % [name_side, float(after[0]["omega"]), float(after[1]["omega"])])
					check(int(after[0]["dir"]) == -int(side), "%s release: and the first goes back toward the centre from the %s (dir %d)" % [name_side, name_side, int(after[0]["dir"])])
				var hits_bob := 0
				for t in turns:
					if str((t as Dictionary).get("ray", "")).contains("BobSphere"): hits_bob += 1
				check(turns.size() == 2 and hits_bob == 2, "%s release: the pointer's grab ray finds the bob at both turning points of the swing (%d of %d)" % [name_side, hits_bob, turns.size()])
			di["releases"] = releases
			if releases.size() == 2 and (releases[0] as Dictionary).has("crossings") and (releases[1] as Dictionary).has("crossings"):
				var a0: Array = (releases[0] as Dictionary)["crossings"]
				var b0: Array = (releases[1] as Dictionary)["crossings"]
				if a0.size() > 0 and b0.size() > 0:
					check(int(a0[0]["dir"]) != int(b0[0]["dir"]),
						"released from the other side, the first crossing goes the other way (%d then %d)" % [int(a0[0]["dir"]), int(b0[0]["dir"])])
					# the energy of the first crossing: two from-rest releases at equal and opposite
					# angles must arrive at the centre equally fast, which no late read can fake
					var wa: float = absf(float(a0[0]["omega"]))
					var wb: float = absf(float(b0[0]["omega"]))
					check(absf(wa - wb) < 0.05 * maxf(wa, wb), "and the two first crossings arrive equally fast: |omega| %.3f and %.3f rad/s" % [wa, wb])
			# PLAYER CLEARANCE DURING A SWING, from the bob's own sampled positions. The aisle
			# at the pendulum's row runs from the west wall (x = 1) to the raised strip (x = 4).
			var xmin := 99.0
			var xmax := -99.0
			for r in releases:
				if (r as Dictionary).has("swing_x"):
					xmin = minf(xmin, float((r as Dictionary)["swing_x"][0]))
					xmax = maxf(xmax, float((r as Dictionary)["swing_x"][1]))
			var br: float = float(pend.get("bob_radius"))
			var gap_w: float = (xmin - br) - 1.0
			var gap_e: float = 4.0 - (xmax + br)
			var Lp: float = float(pend.get("pendulum_length"))
			var clamp_reach: float = sin(PI * 0.45) * Lp + br
			var px: float = seg.to_local(pend.global_position).x
			di["clearance"] = {"swing_x": [snappedf(xmin, 0.01), snappedf(xmax, 0.01)], "gap_west_m": snappedf(gap_w, 0.01), "gap_east_m": snappedf(gap_e, 0.01),
				"worst_case_at_clamp": {"gap_west_m": snappedf((px - clamp_reach) - 1.0, 0.01), "gap_east_m": snappedf(4.0 - (px + clamp_reach), 0.01)}}
			note("clearance " + JSON.stringify(di["clearance"]))
			check(gap_w >= 0.44 and gap_e >= 0.44, "a walking body passes the swing on either side: %.2f m west, %.2f m east (a 0.22 m capsule needs 0.44)" % [gap_w, gap_e])
			if "--capture" in OS.get_cmdline_user_args():
				await get_tree().create_timer(0.2, true, false, true).timeout
				get_viewport().get_texture().get_image().save_png(OUT + "probe_intro_desktop_primary_live.png")
		await drv.call("teardown")
		di["log"] = drv.get("log")
		di["walker_cam_guard_stopped"] = drv.get("walker_cam_guard_stopped")
		await get_tree().process_frame
	if "--capture" in OS.get_cmdline_user_args():
		var cam := Camera3D.new(); em.add_child(cam); cam.fov = 60
		cam.global_position = pend.to_global(Vector3(0.9, 0.2, 1.9)); cam.look_at(pend.to_global(Vector3(0, -0.3, 0)))
		for i in range(30): cam.make_current(); await get_tree().process_frame
		await get_tree().create_timer(0.3, true, false, true).timeout
		get_viewport().get_texture().get_image().save_png(OUT + "probe_intro_live.png")
	_finish()

## The pickable's own signal path, emitted programmatically: picked_up, the bob
## carried to the release angle over a few physics frames (so the artifact's
## velocity samples see a hand moving), then dropped.
func _release(pend: Node3D, bob: Node3D, angle: float) -> Dictionary:
	var L: float = float(pend.get("pendulum_length"))
	bob.emit_signal("picked_up", bob)
	await get_tree().physics_frame
	var start: Vector3 = bob.global_position
	var target: Vector3 = pend.to_global(Vector3(sin(angle) * L, -cos(angle) * L, 0.0))
	for i in range(12):
		bob.global_position = start.lerp(target, float(i + 1) / 12.0)
		await get_tree().physics_frame
	bob.global_position = target
	await get_tree().physics_frame
	var a: float = float(pend.call("angle"))
	bob.emit_signal("dropped", bob)
	var release_omega: float = float(pend.call("angular_velocity"))
	await get_tree().physics_frame
	return {"angle": a, "omega": float(pend.call("angular_velocity")), "release_omega": release_omega}

## A grab by the desktop pointer, timed to a turning point: the bob is slowest there, so the
## aim taken now and the click a frame or two later still agree on where it is.
func _desktop_grab(drv: Node, ptr: Node, pend: Node3D, tries: int = 8) -> Dictionary:
	for attempt in range(tries):
		var waited := 0
		while absf(float(pend.call("angular_velocity"))) > 0.25 and waited < 240:
			await get_tree().physics_frame
			waited += 1
		var at: Vector3 = pend.call("bob_world_position")
		drv.call("aim_at", at)
		var ray: String = _grab_ray_to(drv, at)
		await drv.call("click", MOUSE_BUTTON_RIGHT)
		for i in range(4): await get_tree().physics_frame
		var held: bool = bool(ptr.call("is_holding"))
		var knows: bool = bool(pend.call("is_grabbed"))
		if held and knows:
			return {"held": true, "pendulum_knows": true, "attempt": attempt, "grab_ray": ray, "waited_frames": waited}
		if held and not knows:
			# the pointer took something that is not this bob, or the hook did not fire
			var other: Variant = ptr.get("_held")
			await drv.call("click", MOUSE_BUTTON_RIGHT)
			for i in range(3): await get_tree().physics_frame
			return {"held": true, "pendulum_knows": false, "attempt": attempt, "grab_ray": ray,
				"held_instead": (str((other as Node).name) if other is Node else "?")}
	return {"held": false, "pendulum_knows": false, "attempt": tries, "grab_ray": "exhausted"}


## Carry the held bob to `angle` on this pendulum, hold still, drop. The pointer eases the
## carried body 0.4 of the way to the aim each frame, so 45 physics frames leave the hand's
## last motion samples still: this is a release from rest at the held angle.
func _desktop_carry_and_drop(drv: Node, ptr: Node, pend: Node3D, angle: float, name_side: String) -> Dictionary:
	var L: float = float(pend.get("pendulum_length"))
	var target: Vector3 = pend.to_global(Vector3(sin(angle) * L, -cos(angle) * L, 0.0))
	drv.call("aim_at", target)
	for i in range(30): await get_tree().physics_frame
	# The photograph comes BEFORE the hold settles. Taken between the hold and the drop, its
	# stall made the frame that processed the click run catch-up physics with the bob already
	# released (first run, 2026-09-13: a from-rest release read at omega -1.63).
	if name_side == "right" and "--capture" in OS.get_cmdline_user_args():
		await get_tree().create_timer(0.15, true, false, true).timeout
		get_viewport().get_texture().get_image().save_png(OUT + "probe_intro_desktop_hold_live.png")
	for i in range(45): await get_tree().physics_frame
	var held_angle: float = float(pend.call("angle"))
	var bob_at: Vector3 = pend.call("bob_world_position")
	var still_held: bool = bool(pend.call("is_grabbed"))
	# READ THE RELEASE WHERE IT HAPPENS. _on_bob_dropped emits `released` synchronously after
	# computing omega from the hand's samples and before any physics step integrates it.
	var at_release := {"omega": 99.0, "angle": 99.0, "heard": false}
	var on_release := func():
		at_release["omega"] = float(pend.call("angular_velocity"))
		at_release["angle"] = float(pend.call("angle"))
		at_release["heard"] = true
	pend.connect("released", on_release, CONNECT_ONE_SHOT)
	await drv.call("click", MOUSE_BUTTON_RIGHT)
	for i in range(2): await get_tree().physics_frame
	return {"target": _v(target), "bob_to_target_m": snappedf(bob_at.distance_to(target), 0.01),
		"held_angle": snappedf(held_angle, 0.001), "held_until_drop": still_held,
		"released": (not bool(pend.call("is_grabbed"))) and not bool(ptr.call("is_holding")),
		"released_signal_heard": bool(at_release["heard"]),
		"release_omega": snappedf(float(at_release["omega"]), 0.001),
		"release_angle": snappedf(float(at_release["angle"]), 0.001)}


## What the pointer's own grab ray meets on the way to `at` — the same mask and the same kind
## of query DesktopInteractionPointer._find_grabbable casts.
func _grab_ray_to(drv: Node, at: Vector3) -> String:
	var cam: Camera3D = drv.get("cam")
	if cam == null:
		return "no camera"
	var from: Vector3 = cam.global_position
	var q := PhysicsRayQueryParameters3D.create(from, from + (at - from).normalized() * 5.0, 393220)
	q.collide_with_bodies = true
	q.collide_with_areas = false
	var hit: Dictionary = cam.get_world_3d().direct_space_state.intersect_ray(q)
	if hit.is_empty():
		return "nothing"
	var c: Node = hit.get("collider")
	return str(c.name) if c != null else "?"


func _swing_x(samples: Array) -> Array:
	var lo := 99.0
	var hi := -99.0
	for s in samples:
		lo = minf(lo, (s as Vector3).x)
		hi = maxf(hi, (s as Vector3).x)
	return [lo, hi]


func _v(p: Vector3) -> Array:
	return [snappedf(p.x, 0.01), snappedf(p.y, 0.01), snappedf(p.z, 0.01)]


func note(message: String) -> void:
	print("[wcn-intro] note: ", message)

func _solid_at(seg: Node3D, p: Vector3, r: float) -> bool:
	var s := SphereShape3D.new(); s.radius = r
	var q := PhysicsShapeQueryParameters3D.new(); q.shape = s; q.transform = Transform3D(Basis.IDENTITY, p)
	for h in seg.get_world_3d().direct_space_state.intersect_shape(q, 8):
		if h.collider == seg.get_node_or_null("Collision"): return true
	return false

func _aabb(node: Node) -> Array:
	var merged := AABB(); var first := true
	for n in node.find_children("*", "MeshInstance3D", true, false):
		var box: AABB = (n as MeshInstance3D).global_transform * (n as MeshInstance3D).get_aabb()
		merged = box if first else merged.merge(box); first = false
	return [snappedf(merged.size.x, 0.01), snappedf(merged.size.y, 0.01), snappedf(merged.size.z, 0.01)]

func _finish() -> void:
	var report := {"map": MAP, "checks": checks, "failures": failures, "measurements": measurements,
		# SAY WHICH LANE RAN. _live() is a filename test: the whole pointer block can be
		# skipped in silence while every other check stays green.
		"lanes": {"model_lane": "picked_up/dropped emitted on the bob pickable, the bob moved by setting its position",
			"pointer_lane_expected": _live(), "pointer_lane_ran": measurements.has("desktop_release")},
		"control_path": (("the bob grabbed, carried and released through the desktop pointer's right-click from both sides, the pendulum hearing it through its own pickup and drop handlers; the model lane emits the pickable's signals" if measurements.has("desktop_release")
			else "model lane in this run: picked_up/dropped emitted on the bob pickable, no pointer; the live lane grabs, carries and releases the bob through the desktop pointer from both sides") if release_exercised
			else ("pickup/release NOT exercised in this lane: under --script the pickable cannot compile without its autoloads; the live lane grabs, carries and releases the bob through the desktop pointer from both sides" if not _live()
				else "pickup/release NOT exercised; autonomous motion observations only")),
		"skipped": skipped, "release_exercised": release_exercised,
		"status": ("passed" if failures.is_empty() and release_exercised else "incomplete_or_failed"),
		"headset_verified": false, "engine": Engine.get_version_info().string,
		"physics_fps": Engine.physics_ticks_per_second}
	var f := FileAccess.open(OUT + "probe_intro_live.json", FileAccess.WRITE)
	f.store_string(JSON.stringify(report, "  ")); f.close()
	print("[wcn-intro] ", checks, " checks; ", failures.size(), " failures")
	get_tree().quit(0 if failures.is_empty() else 1)
