extends SceneTree
func _initialize() -> void: call_deferred("run")
func run() -> void:
	var demo = load("res://algorithms/randomness/seed_replay/seed_replay_demo.tscn").instantiate()
	demo.apply_grid_config({"display":"wall","comparison":"replicas","stand":"table"})
	root.add_child(demo)
	assert(demo.cube_size==0.14)
	assert(demo.column_colors(0)==demo.column_colors(1))
	var before = demo.raw_prefix(0,25)
	assert(demo.raw_prefix(0)==demo.raw_prefix(1))
	demo.toggle_extra_draw()
	var shifted = demo.raw_prefix(1)
	for i in range(24): assert(is_equal_approx(before[i+1],shifted[i]))
	assert(demo.column_colors(0)!=demo.column_colors(1))
	demo.replay()
	assert(shifted==demo.raw_prefix(1))
	demo.toggle_extra_draw()
	assert(demo.column_colors(0)==demo.column_colors(1))
	print("SEED WALL: scale, replicas, 24 shifted draws, replay and restoration passed")
	quit()
