## LIVE PORT — generated by tools/port_wcn_probes_live.py from probe_wcn_air_music.gd. Do not edit;
## edit the SceneTree probe and regenerate. Runs under project startup (probe_live.tscn
## with --probe=air_music), so the project's autoloads exist and XR Tools pickables compile.
## Outputs carry a _live suffix.
extends Node
## WaveFunctions_AirMusic, batch W3 (doc/research/waves-chance-noise, 2026-09-11, Astra's
## thread: one oscillation changes another sound; a strike sets a response continuing after
## the hand leaves; two decays can overlap): what continues after your hand has left?
##
## Stands up the ACTUAL museum hall with its artifacts (the pattern of probe_wcn_pendulum.gd),
## hands the museum the REAL necklace hand file, finds the resonating_metallophone staged on
## its table, and measures: the staging (the table, the cradle, the striker in it, the Hz
## labels on the front, the wave and its readout above the row), the strike through the
## STRIKER'S OWN COLLISION PATH (the stick body moved into a bar: body_entered → the note),
## the striker's speed reaching the bar, a bar that stays put when struck, two voices ringing
## and decaying together, a re-struck bar starting again, the sound's length and its end,
## the striker returning to its cradle, the combined wave as geometry, walks, the museum's
## verdicts, and streaming. strike_bar() from code is used only where noted, apart.
##
##   godot --rendering-method gl_compatibility --path . --xr-mode off --script res://commons/testing/probe_wcn_air_music.gd -- --capture
##   godot --headless --path . --xr-mode off --script res://commons/testing/probe_wcn_air_music.gd
##
## Writes res://ada_run/waves_chance_noise/WaveFunctions_AirMusic/probe_air_music.json
## (and probe_air_music*.png under --capture). Exit code 1 on any failed check.
var checks := 0
var failures: Array[String] = []
var measurements: Dictionary = {}
const MAP := "WaveFunctions_AirMusic"
const OUT := "res://ada_run/waves_chance_noise/WaveFunctions_AirMusic/"
const MAP_CELL := Vector2i(5, 9)
var _hits: Array = []
var _last_stick_speed: float = -1.0
var _rig_basis: Basis = Basis.IDENTITY
var _rest_pos: Vector3 = Vector3.ZERO
var _stick_rest_t: Transform3D = Transform3D.IDENTITY   # the striker's rest pose in the rig's frame

func _ready() -> void: run.call_deferred()

func _live() -> bool:
	return str(get_script().resource_path).ends_with("_live.gd")

func check(ok: bool, message: String) -> void:
	checks += 1
	if not ok: failures.append(message)
	print("[wcn-air-music] ", "PASS " if ok else "FAIL ", message)

func run() -> void:
	if "--capture" in OS.get_cmdline_user_args() and DisplayServer.get_name() == "headless":
		check(false, "PNG capture requires a rendered window; omit --headless, or omit --capture for logic only")
		_finish(); return
	var em: Node3D = load("res://commons/scenes/endless_museum.tscn").instantiate()
	var ctl := "res://ada_run/waves_chance_noise/wcn-probe-control.json"
	em.set("EM_CONTROL", ctl); em.set("_overrides_path", ctl + ".unused")
	em.set("_hand_path", "res://ada_run/necklace_hand.json")   # the REAL hand, on purpose
	em.set("start_chapter", "wavefunctions"); em.set("start_map", MAP)
	var layout: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://commons/data/em_layout.json"))
	layout.get_or_add("stream", {})["bodies"] = 1
	em.set("_layout", layout)
	var f := FileAccess.open(ctl, FileAccess.WRITE)
	f.store_string(JSON.stringify({"first_chapter": "wavefunctions", "dollhouse": 0, "grid_pack": 1})); f.close()
	get_tree().root.add_child(em); get_tree().current_scene = em
	await get_tree().create_timer(1.0).timeout
	em.set_process(false); em.call("flush_stamps")
	var player: Node = em.get("_player")
	if player != null: player.set_process(false); player.set_physics_process(false)
	var seg: Node3D
	for rec: Dictionary in em.get("_segments"):
		if rec.node.get_meta("em_map", "") == MAP: seg = rec.node; break
	check(seg != null, "the hall exists in the active museum")
	if seg == null:
		_finish(); return
	for i in range(30): await get_tree().process_frame
	var vest: int = int(em.get("VESTIBULE_H"))
	var capture: bool = "--capture" in OS.get_cmdline_user_args()
	var cam: Camera3D
	if capture:
		var wc: Camera3D = em.get("_cam")
		if wc != null and is_instance_valid(wc):
			for c in wc.get_children():
				if c is Timer: (c as Timer).stop()
		cam = Camera3D.new(); em.add_child(cam); cam.fov = 62

	# ── 1. built where the map put it, on the table, turned to the south strip ───
	var rig: Node3D
	var rig_cell: Array = []
	for record: Dictionary in em.get("_edit_records"):
		var node: Node = record.get("node")
		if node != null and seg.is_ancestor_of(node) and node.get_script() != null and str(node.get_script().resource_path).ends_with("ResonatingMetallophone.gd"):
			rig = node; rig_cell = record.get("tile_cell", [])
	if rig == null:
		for n in seg.find_children("*", "Node3D", true, false):
			if n.get_script() != null and str(n.get_script().resource_path).ends_with("ResonatingMetallophone.gd"): rig = n; break
	check(rig != null, "resonating_metallophone is built in the hall")
	if rig == null:
		_finish(); return
	if rig_cell.size() >= 2:
		check(int(rig_cell[0]) == MAP_CELL.x and int(rig_cell[1]) == MAP_CELL.y, "built at the map's cell (5,9) (got %s)" % str(rig_cell))
	var lo: Vector3 = seg.to_local(rig.global_position)
	measurements["origin_local"] = [lo.x, lo.y, lo.z - vest]
	check(absf(lo.x - 5.5) < 0.6 and absf(lo.z - (9.5 + vest)) < 0.6, "the instrument stands on its cell (%.1f, %.1f)" % [lo.x, lo.z - vest])
	check(absf(lo.y) < 0.05, "the deck is the origin: the rig stands ON the floor (y %.2f)" % lo.y)
	var front: Vector3 = seg.global_transform.basis.inverse() * (rig.global_transform.basis * Vector3(0, 0, 1))
	check(front.z > 0.9, "the front (+z: cradle, labels) faces south, the standing strip on row 10 (z %.2f)" % front.z)
	check(str(rig.get("stand")) == "table", "the token's #stand:table reached the artifact (stand = %s)" % str(rig.get("stand")))
	check(str(rig.get("tuning")) == "pentatonic", "the row is cut to the shipped pentatonic (tuning = %s)" % str(rig.get("tuning")))
	check(rig.scale.is_equal_approx(Vector3.ONE), "the subject's scale is what the map asked (1)")

	# ── 2. the staging ──────────────────────────────────────────────────────────
	var table: Node3D = rig.get_node_or_null("Staging/Table")
	check(table != null and table is StaticBody3D, "the table is a solid support (StaticBody3D)")
	if table != null:
		var top: float = seg.to_local(table.global_position).y + 0.425
		measurements["table_top"] = top
		check(absf(top - 0.85) < 0.02, "the table top is at 0.85 m (%.2f)" % top)
	check(rig.get_node_or_null("Staging/CradleL") != null and rig.get_node_or_null("Staging/CradleR") != null, "the cradle's two blocks stand at the table's left end (12 September; they stood on the front edge, across the row)")
	if rig.get_node_or_null("Staging/CradleL") != null:
		var cl: Vector3 = (rig.get_node_or_null("Staging/CradleL") as Node3D).position
		check(cl.x < -0.6 and abs(cl.z) > 0.1, "…beside the first bar, front to back (%.2f, %.2f)" % [cl.x, cl.z])
	check(rig.get_node_or_null("Staging/FrontRail") != null and rig.get_node_or_null("Staging/BackKerb") != null, "the playable edge carries a pale rail and the back edge a dark kerb")
	var bars: Array = rig.get("bars")
	check(bars.size() == 8, "eight bars (%d)" % bars.size())
	if bars.size() < 8:
		_finish(); return
	var bar_y: Array = []
	var bar_len: Array = []
	for b in bars:
		bar_y.append(snappedf(seg.to_local((b as Node3D).global_position).y, 0.001))
		bar_len.append(snappedf((b.get("bar_size") as Vector3).z, 0.001))
	measurements["bar_heights"] = bar_y
	measurements["bar_lengths"] = bar_len
	var all_on_table := true
	for y in bar_y:
		if absf(float(y) - 0.875) > 0.02: all_on_table = false
	check(all_on_table, "every bar lies on the table at 0.875 m (%s)" % str(bar_y))
	check(absf(float(bar_len[0]) - 0.30) < 0.005 and absf(float(bar_len[7]) - 0.189) < 0.005 and float(bar_len[7]) < float(bar_len[3]) and float(bar_len[3]) < float(bar_len[0]),
		"the bars shorten with pitch: 0.30 m at C4 down to 0.19 m at E5 (a scale you can see)")
	var stick: Node3D = rig.call("get_stick")
	check(stick != null, "the striker exists")
	if stick == null:
		_finish(); return
	var rest: Vector3 = rig.call("stick_rest_position")
	_rig_basis = rig.global_transform.basis
	_rest_pos = rest
	_stick_rest_t = rig.get("_stick_rest")
	measurements["stick_rest_local"] = [seg.to_local(rest).x, seg.to_local(rest).y, seg.to_local(rest).z - vest]
	check(stick.global_position.distance_to(rest) < 0.15, "the striker starts in its cradle (%.2f m from the rest)" % stick.global_position.distance_to(rest))
	check(absf(seg.to_local(stick.global_position).y - 0.94) < 0.05, "…at hand height on the table's front edge (%.2f m)" % seg.to_local(stick.global_position).y)
	var hz_labels: Array = []
	for n in rig.find_children("*", "Label3D", false, false):
		if str((n as Label3D).text).ends_with("Hz"): hz_labels.append(n)
	measurements["hz_labels"] = hz_labels.size()
	var labels_front := hz_labels.size() == 8
	for n in hz_labels:
		var l: Vector3 = seg.to_local((n as Node3D).global_position)
		if absf(l.y - 0.75) > 0.04 or l.z - vest < 9.7: labels_front = false
	check(labels_front, "the eight Hz labels sit on the table's front face, not through the bars")
	var instr: Label3D = rig.get_node_or_null("Instruction")
	check(instr != null and instr.text.begins_with("strike a bar") and seg.to_local(instr.global_position).y > 0.5, "the instruction reads from the front of the table, above the floor")
	var vis: Node3D = rig.get_node_or_null("CombinedWaveVisualizer")
	check(vis != null, "the combined wave visualiser exists")
	var wave_mesh: MeshInstance3D = vis.get("_wave_mesh") if vis != null else null
	var status: Label3D = vis.get("_status_label") if vis != null else null
	if wave_mesh != null:
		var wy: float = seg.to_local(wave_mesh.global_position).y
		measurements["wave_height"] = wy
		check(wy > 1.2 and wy < 1.5, "the combined wave hangs above the row, below a standing eye (%.2f m)" % wy)
	check(status != null and status.text.begins_with("silent"), "the readout says silent before any strike (%s)" % (status.text if status != null else "none"))
	var bar0: RigidBody3D = bars[0]
	var bar4: RigidBody3D = bars[4]
	check(bar0.axis_lock_linear_x and bar0.axis_lock_linear_y and bar0.axis_lock_linear_z, "the bars are locked in place on the table")
	measurements["sound_seconds"] = float(bar0.call("_sound_seconds"))
	var stream_len: float = float((bar0.get("audio_player") as AudioStreamPlayer3D).stream.data.size()) / 2.0 / 44100.0
	measurements["stream_seconds"] = stream_len
	check(absf(stream_len - 7.5) < 0.05, "each bar's note is 2.5 decays long, 7.5 s at a 3 s decay (%.2f s)" % stream_len)
	var sd: PackedByteArray = (bar0.get("audio_player") as AudioStreamPlayer3D).stream.data
	var last: int = sd[sd.size() - 2] | (sd[sd.size() - 1] << 8)
	if last >= 32768: last -= 65536
	check(absf(float(last) / 32767.0) < 0.002, "…and it ends at silence, not on a cut (last sample %.4f)" % (float(last) / 32767.0))

	# ── 3. one strike, through the striker's own collision path ────────────────
	for b in bars:
		(b as RigidBody3D).connect("hit", func(freq: float, amp: float): _hits.append([freq, amp]))
	var stand_cam := func():
		if capture:
			cam.global_position = seg.to_global(Vector3(5.5, 1.55, 10.9 + vest)); cam.look_at(seg.to_global(Vector3(5.5, 1.0, 9.4 + vest)))
	stand_cam.call()
	if capture:
		for i in range(20): cam.make_current(); await get_tree().process_frame
	var bar0_pos_before: Vector3 = bar0.global_position
	var struck: bool = await _strike_with_stick(stick, bar0, 10)
	var bar0_vel: float = float(bar0.get("hit_velocity"))
	measurements["strike_1"] = {"through_collision": struck, "hit_velocity": bar0_vel, "stick_speed_before_contact": _last_stick_speed, "hits_seen": _hits.size(), "held_like": "frozen kinematic, mask 0, layer picked_up_layer"}
	check(struck, "moving the striker into a bar rings it through body_entered: the real strike path (hits %d)" % _hits.size())
	if not struck:
		rig.call("strike_bar", 0, 1.0)
		await get_tree().process_frame
		measurements["strike_1"]["fallback"] = "strike_bar() from code, apart from the collision path"
	check(bool(bar0.get("is_resonating")), "the bar resonates after the strike")
	check((bar0.get("audio_player") as AudioStreamPlayer3D).playing, "…and its note is playing")
	check(bar0_vel > 0.9, "a fast strike (about 1.7 m/s) lands at full strength: the striker's speed reaches the bar (hit_velocity %.2f)" % bar0_vel)
	var mat0: StandardMaterial3D = bar0.get("material")
	check(mat0 != null and mat0.emission.r > 0.1, "the struck bar glows")
	await get_tree().create_timer(1.0).timeout
	var moved: float = bar0.global_position.distance_to(bar0_pos_before)
	measurements["bar_displacement_after_strike"] = moved
	check(moved < 0.002, "the struck bar stays where it lies (%.4f m)" % moved)
	var amp_a: float = float(bar0.get("current_amplitude"))
	await get_tree().create_timer(1.0).timeout
	var amp_b: float = float(bar0.get("current_amplitude"))
	measurements["decay_ratio_per_second"] = amp_b / maxf(amp_a, 0.0001)
	check(absf(amp_b / maxf(amp_a, 0.0001) - exp(-1.0 / 3.0)) < 0.08, "the response decays as e^(−t/3 s): %.2f of itself a second later" % (amp_b / maxf(amp_a, 0.0001)))

	# ── 4. two voices: a second bar, slowly, while the first still rings ────────
	var struck2: bool = await _strike_with_stick(stick, bar4, 60)
	var bar4_vel: float = float(bar4.get("hit_velocity"))
	measurements["strike_2"] = {"through_collision": struck2, "hit_velocity": bar4_vel}
	check(struck2, "a second bar struck through the collision path")
	if not struck2:
		rig.call("strike_bar", 4, 0.5)
		await get_tree().process_frame
	check(bar4_vel < bar0_vel, "a slow strike lands softer than a fast one (%.2f < %.2f)" % [bar4_vel, bar0_vel])
	var voices: Array = rig.call("get_active_voices")
	measurements["voices_after_second_strike"] = voices
	check(voices.size() == 2, "two voices ring at once (%d)" % voices.size())
	await get_tree().process_frame
	check(bool(bar0.get("is_resonating")) and (bar0.get("audio_player") as AudioStreamPlayer3D).playing, "the first note was not stolen by the second: still ringing, still playing")
	check(status != null and status.text.begins_with("2 voices"), "the readout names two voices with their Hz, level and age (%s)" % (status.text if status != null else ""))
	if wave_mesh != null and wave_mesh.mesh != null:
		var im: ImmediateMesh = wave_mesh.mesh
		var nverts: int = 0
		if im.get_surface_count() > 0:
			nverts = (im.surface_get_arrays(0)[Mesh.ARRAY_VERTEX] as PackedVector3Array).size()
		measurements["wave_vertices"] = nverts
		check(nverts > 100, "the combined wave is drawn as a ribbon of triangles (%d vertices), not a one-pixel line" % nverts)
	if capture:
		for i in range(6): cam.make_current(); await get_tree().process_frame
		await get_tree().create_timer(0.3, true, false, true).timeout
		get_viewport().get_texture().get_image().save_png(OUT + "probe_air_music_two_voices_live.png")
		measurements["captures"] = {"two_voices": _cam_pose(cam)}
	# the same bar again: it starts again, no third voice
	var t_before: float = float(bar0.get("resonance_time"))
	var struck3: bool = await _strike_with_stick(stick, bar0, 10)
	check(struck3 and float(bar0.get("resonance_time")) < t_before, "striking the ringing bar again starts it again (its clock %.2f → %.2f s)" % [t_before, float(bar0.get("resonance_time"))])
	voices = rig.call("get_active_voices")
	check(voices.size() == 2, "…and adds no third voice (%d): only a second bar adds a voice" % voices.size())

	# ── 5. the striker comes back ───────────────────────────────────────────────
	var returns_before: int = int(rig.get("stick_returns"))
	stick.global_position = rest + seg.global_transform.basis * Vector3(1.2, -0.7, 0.4)
	await get_tree().create_timer(3.8).timeout
	measurements["stick_return"] = {"returns": int(rig.get("stick_returns")) - returns_before, "distance_from_rest": stick.global_position.distance_to(rest)}
	check(int(rig.get("stick_returns")) > returns_before and stick.global_position.distance_to(rest) < 0.1, "left 1.4 m away and not held, the striker returns to its cradle within four seconds (%.2f m from the rest)" % stick.global_position.distance_to(rest))

	# ── 6. what else sounds, and the museum's verdicts ──────────────────────────
	await get_tree().create_timer(0.5).timeout
	var others: Array = []
	for n in seg.find_children("*", "AudioStreamPlayer3D", true, false):
		var pl: AudioStreamPlayer3D = n
		if rig.is_ancestor_of(pl) or not pl.playing: continue
		others.append([str(pl.get_path()).right(50), snappedf(pl.global_position.distance_to(rig.global_position), 0.1)])
	measurements["other_players_playing"] = others
	var severed: Array = em.get("_seg_severed") if em.get("_seg_severed") != null else []
	var sev_tokens: Array = []
	for s2 in severed: sev_tokens.append(str((s2 as Dictionary).get("token", "")))
	measurements["museum_severed_tokens"] = sev_tokens
	var walk_sev: Array = em.get("_walk_severed") if em.get("_walk_severed") != null else []
	var mine_sev: Array = []
	for e in walk_sev:
		if str((e as Dictionary).get("hall", "")).contains(MAP): mine_sev.append(e)
	measurements["museum_walk_severed"] = mine_sev
	check(mine_sev.is_empty(), "the museum walks this hall door to door (local seals: %s)" % str(sev_tokens))
	var plinths: Array = []
	for n in seg.find_children("ArtPlinth*", "", true, false):
		var pl2: Vector3 = seg.to_local((n as Node3D).global_position)
		plinths.append([n.name, int(floor(pl2.x)), int(floor(pl2.z)) - vest])
	measurements["plinths"] = plinths
	var rows: Array = em.get("_built") if em.get("_built") != null else []
	for r in rows:
		if str((r as Dictionary).get("map", "")) == MAP:
			measurements["built_seals"] = r.get("seals", []); measurements["built_severed"] = r.get("severed", [])

	# ── 7. walks: the ring round the basin, the strip, the doors, into the table ─
	var pspace := seg.get_world_3d().direct_space_state
	var capsule := CapsuleShape3D.new(); capsule.radius = 0.22; capsule.height = 1.6
	var wq := PhysicsShapeQueryParameters3D.new(); wq.shape = capsule
	var aisle_fracs: Array = []
	for route in [["the west aisle down the basin", Vector3(1.5, 0.81, 2.5), Vector3(0, 0, 7.0), false],
			["the east aisle down the basin", Vector3(8.5, 0.81, 2.5), Vector3(0, 0, 7.0), false],
			["row 10 from the west to the table's front", Vector3(1.5, 0.81, 10.5), Vector3(4.0, 0, 0), true],
			["row 10 from the east to the table's front", Vector3(9.5, 0.81, 10.5), Vector3(-3.5, 0, 0), true],
			["from the table's front to the south door", Vector3(5.5, 0.81, 10.5), Vector3(1.0, 0, 1.0), true]]:
		wq.transform = Transform3D(Basis.IDENTITY, seg.to_global(Vector3(route[1].x, route[1].y, route[1].z + vest)))
		wq.motion = route[2]
		var frac: float = pspace.cast_motion(wq)[0]
		measurements["walk_" + str(route[0]).replace(" ", "_").replace("'", "")] = frac
		if route[3]:
			check(frac > 0.99, "a body walks %s (%.2f of the way)" % [route[0], frac])
		else:
			aisle_fracs.append(frac)
			print("[wcn-air-music] measured: %s %.2f of the way" % [route[0], frac])
	# the drone rack (1,8), lifted a metre, stands in the west aisle; the museum's own walk
	# is the verdict on the route, this is the aisles as a body meets them
	check(aisle_fracs.max() > 0.99, "at least one aisle runs the length of the basin (west %.2f, east %.2f)" % [aisle_fracs[0], aisle_fracs[1]])
	wq.transform = Transform3D(Basis.IDENTITY, seg.to_global(Vector3(5.5, 0.81, 10.6 + vest)))
	wq.motion = Vector3(0, 0, -1.2)
	var into: float = pspace.cast_motion(wq)[0]
	measurements["walk_into_the_table"] = into
	check(into < 0.8, "the table is solid: a body walking into it from the strip is stopped (%.2f of 1.2 m)" % into)
	# reach: from a standing eye on the strip to the farthest bar
	var eye: Vector3 = seg.to_global(Vector3(5.5, 1.55, 10.4 + vest))
	var far_bar: float = 0.0
	for b in bars: far_bar = maxf(far_bar, eye.distance_to((b as Node3D).global_position))
	measurements["reach_to_farthest_bar"] = far_bar
	check(far_bar < 1.3, "every bar is within an arm and a stick of the standing spot (farthest %.2f m from the eye)" % far_bar)

	# ── ACTUAL DESKTOP INPUT (live harness only) ─────────────────────────────
	if _live():
		var drv: Node = load("res://commons/testing/wcn_desktop_driver.gd").new()
		get_tree().root.add_child(drv)   # a SceneTree has no add_child; the port maps root. to get_tree().root.
		var stand: Vector3 = seg.to_global(Vector3(5.5, 0.0, 10.55 + vest))
		drv.call("spawn", stand, em)
		await get_tree().create_timer(0.5).timeout
		drv.call("aim_at", stick.global_position)
		var seen: Node = await drv.call("hover_target")
		await drv.call("click", MOUSE_BUTTON_RIGHT)
		await get_tree().create_timer(0.3).timeout
		var held: bool = stick.has_method("is_picked_up") and bool(stick.call("is_picked_up"))
		measurements["desktop_input"] = {"carry_hover": (str(seen.get_path()).right(50) if seen != null else "nothing"), "stick_held_after_rmb": held,
			"note": "the desktop rig's RMB carry never calls an XR Tools pickable's pick_up; the striker is a hand's instrument — a headset lane"}
		check(not held, "recorded: the desktop carry does not pick up the striker (a hand does)")
		if capture:
			drv.call("aim_at", rig.to_global(Vector3(0.0, 1.0, 0.0)))
			for i in range(12): await get_tree().process_frame
			await get_tree().create_timer(0.3, true, false, true).timeout
			get_viewport().get_texture().get_image().save_png(OUT + "probe_air_music_desktop_front_live.png")
			measurements["desktop_input"]["front_capture_pose"] = drv.call("pose")
		# the strip: walk it east on ui_up; then into the table
		drv.get("rig").global_position = seg.to_global(Vector3(2.0, 0.05, 10.5 + vest))
		await get_tree().physics_frame
		drv.call("aim_at", seg.to_global(Vector3(7.0, 1.2, 10.5 + vest)))
		var moved_v: Vector3 = await drv.call("walk", "ui_up", 30)
		var ml: Vector3 = seg.global_transform.basis.inverse() * moved_v
		measurements["desktop_input"]["walk_strip_east"] = [snappedf(ml.x, 0.01), snappedf(ml.z, 0.01)]
		check(ml.x > 2.0, "the rig walks the strip east on ui_up (%.2f m in half a second)" % ml.x)
		drv.get("rig").global_position = seg.to_global(Vector3(5.5, 0.05, 10.6 + vest))
		await get_tree().physics_frame
		drv.call("aim_at", seg.to_global(Vector3(5.5, 1.0, 9.0 + vest)))
		moved_v = await drv.call("walk", "ui_up", 20)
		ml = seg.global_transform.basis.inverse() * moved_v
		measurements["desktop_input"]["walk_into_the_table"] = [snappedf(ml.x, 0.01), snappedf(ml.z, 0.01)]
		check(ml.z > -0.6, "walking north from the strip, the rig is stopped by the table (%.2f m of a possible 1.67)" % -ml.z)
		await drv.call("teardown")
		measurements["desktop_input"]["log"] = drv.get("log")
		measurements["desktop_input"]["walker_cam_guard_stopped"] = drv.get("walker_cam_guard_stopped")
		await get_tree().process_frame

	# ── captures ─────────────────────────────────────────────────────────────
	if capture:
		await get_tree().create_timer(2.0).timeout
		stand_cam.call()
		for i in range(20): cam.make_current(); await get_tree().process_frame
		await get_tree().create_timer(0.3, true, false, true).timeout
		get_viewport().get_texture().get_image().save_png(OUT + "probe_air_music_live.png")
		measurements["captures"]["primary"] = _cam_pose(cam)
		if status != null:
			cam.global_position = status.global_position + seg.global_transform.basis * Vector3(0.0, 0.0, 1.05); cam.look_at(status.global_position)
			for i in range(15): cam.make_current(); await get_tree().process_frame
			await get_tree().create_timer(0.3, true, false, true).timeout
			get_viewport().get_texture().get_image().save_png(OUT + "probe_air_music_readout_live.png")
			measurements["captures"]["readout"] = _cam_pose(cam)
		cam.global_position = seg.to_global(Vector3(6.5, 2.2, 0.8 + vest)); cam.look_at(seg.to_global(Vector3(5.5, 0.9, 9.5 + vest)))
		for i in range(15): cam.make_current(); await get_tree().process_frame
		await get_tree().create_timer(0.3, true, false, true).timeout
		get_viewport().get_texture().get_image().save_png(OUT + "probe_air_music_overview_live.png")
		measurements["captures"]["overview"] = _cam_pose(cam)
		cam.queue_free()

	# ── MUSEUM STREAMING: free the hall, rebuild it ──────────────────────────────
	var seg_i: int = -1
	var segs: Array = em.get("_segments")
	for i in range(segs.size()):
		if (segs[i] as Dictionary).get("node") == seg: seg_i = i
	if seg_i >= 0 and em.has_method("_stream_free"):
		var z0: float = seg.global_position.z
		var rig_ref: WeakRef = weakref(rig)
		var pl_ref: WeakRef = weakref(bar0.get("audio_player"))
		em.call("_stream_free", seg_i, "south")
		for i in range(5): await get_tree().process_frame
		var freed: bool = rig_ref.get_ref() == null and pl_ref.get_ref() == null
		check(freed, "the museum's streamer frees the hall, the instrument and its bars' players with it")
		var rec: Dictionary = {}
		for r in em.get("_freed"):
			if absf(float((r as Dictionary).get("z0", -1e9)) - z0) < 0.01: rec = r
		if rec.is_empty():
			for r in em.get("_freed"): rec = r
		measurements["streaming"] = {"freed": freed, "rebuildable": rec.has("snap")}
		if rec.has("snap"):
			em.call("_stream_rebuild", rec)
			await get_tree().create_timer(1.5).timeout
			var seg2: Node3D
			for rec2: Dictionary in em.get("_segments"):
				if rec2.node.get_meta("em_map", "") == MAP: seg2 = rec2.node
			var rig2: Node3D
			if seg2 != null:
				for n in seg2.find_children("*", "Node3D", true, false):
					if n.get_script() != null and str(n.get_script().resource_path).ends_with("ResonatingMetallophone.gd"): rig2 = n; break
			check(rig2 != null and (rig2.get("bars") as Array).size() == 8 and rig2.call("get_stick") != null and rig2.get_node_or_null("Staging/Table") != null, "the rebuilt hall has its instrument again: eight bars, the striker, the table")
			if rig2 != null:
				rig2.call("strike_bar", 2, 1.0)
				await get_tree().process_frame
				check((rig2.call("get_active_voices") as Array).size() == 1, "the rebuilt instrument rings (strike_bar from code)")
				# quitting with a bar's note still playing ended in a signal 11 at shutdown
				# (2026-09-11 08:20–08:35, after the JSON was written): let it stop first
				await get_tree().create_timer(0.4).timeout
				rig2.call("stop_all_resonances")
				await get_tree().create_timer(0.3).timeout
	_finish()

## The striker's own path: the stick body (a frozen XR Tools pickable, moved by its
## transform as a hand would) is turned across the row and brought down onto one bar over
## `frames` physics frames; the bar's contact monitor reports body_entered. Returns whether
## that bar's hit signal fired.
func _strike_with_stick(stick: Node3D, bar: RigidBody3D, frames: int) -> bool:
	var hits_before: int = _hits.size()
	var target: Vector3 = bar.global_position
	var across := Basis(Vector3.UP, PI * 0.5)   # the rod along z, over one bar only
	# the part of the stick that meets a bar is its tip (Blade/Top/TrackBall), 0.6 m from the
	# origin the hand holds: bring the TIP down onto the bar, the way a hand does
	var tip: Node3D = stick.get_node_or_null("Blade/Top/TrackBall")
	var tip_local: Vector3 = stick.global_transform.affine_inverse() * tip.global_position if tip != null else Vector3.ZERO
	var from: Vector3 = target + Vector3(0, 0.30, 0) - across * tip_local
	var to: Vector3 = target + Vector3(0, 0.02, 0) - across * tip_local
	measurements["strike_tip_offset_local"] = [snappedf(tip_local.x, 0.01), snappedf(tip_local.y, 0.01), snappedf(tip_local.z, 0.01)]
	# exactly what XR Tools does to a pickable in a hand (pickable.gd pick_up): frozen,
	# kinematic, its mask cleared, its layer the pick-up layer, moved by its transform
	var rb: RigidBody3D = stick as RigidBody3D
	var was_layer: int = rb.collision_layer
	var was_mask: int = rb.collision_mask
	var was_mode: int = rb.freeze_mode
	rb.freeze = true
	rb.freeze_mode = RigidBody3D.FREEZE_MODE_KINEMATIC
	rb.collision_layer = int(rb.get("picked_up_layer")) if "picked_up_layer" in rb else was_layer
	rb.collision_mask = 0
	for k in range(frames + 1):
		var t: float = float(k) / float(frames)
		stick.global_transform = Transform3D(across, from.lerp(to, t))
		await get_tree().physics_frame
		if k == frames - 1: _last_stick_speed = float(stick.get_meta("speed", -1.0))
	for i in range(3): await get_tree().physics_frame
	rb.collision_layer = was_layer
	rb.collision_mask = was_mask
	rb.freeze_mode = was_mode
	var rang: bool = _hits.size() > hits_before and bool(bar.get("is_resonating"))
	# and put it back IN ITS REST POSE, as a hand does after a strike (the return rule is
	# tested on its own). The rest lies front to back at the table's left end since 12
	# September: putting the stick back with the rig's basis laid the rod along the row and
	# rang a fifth bar in passing (587 Hz, 0.1 s after the first strike).
	stick.transform = _stick_rest_t
	await get_tree().physics_frame
	return rang

## Which camera the viewport draws from at a capture, and where it stands and looks.
func _cam_pose(cam: Camera3D) -> Dictionary:
	var cur: Camera3D = get_viewport().get_camera_3d()
	var fwd: Vector3 = -cam.global_transform.basis.z
	return {"current_camera": str(cur.get_path()).right(50) if cur != null else "none", "is_ours": cur == cam,
		"at": [snappedf(cam.global_position.x, 0.01), snappedf(cam.global_position.y, 0.01), snappedf(cam.global_position.z, 0.01)],
		"forward": [snappedf(fwd.x, 0.01), snappedf(fwd.y, 0.01), snappedf(fwd.z, 0.01)]}

func _finish() -> void:
	var report := {"map": MAP, "checks": checks, "failures": failures, "measurements": measurements,
		"control_path": "strikes through the striker's collision path (the stick body moved into a bar, body_entered → the note), strike_bar() from code only where the JSON says so; no tracked hand",
		"hand_file": "ada_run/necklace_hand.json (real)", "headset_verified": false, "heard_by_a_person": false,
		"engine": Engine.get_version_info().string, "physics_fps": Engine.physics_ticks_per_second}
	var f := FileAccess.open(OUT + "probe_air_music_live.json", FileAccess.WRITE)
	f.store_string(JSON.stringify(report, "  ")); f.close()
	print("[wcn-air-music] ", checks, " checks; ", failures.size(), " failures")
	get_tree().quit(0 if failures.is_empty() else 1)
