## LIVE PORT — generated by tools/port_wcn_probes_live.py from probe_wcn_intro.gd. Do not edit;
## edit the SceneTree probe and regenerate. Runs under project startup (probe_live.tscn
## with --probe=intro), so the project's autoloads exist and XR Tools pickables compile.
## Outputs carry a _live suffix.
extends Node
## WaveFunctions_Intro pilot (doc/research/waves-chance-noise, 2026-09-10):
## can a visitor release the pendulum, and does the room show two visits to the
## centre with opposite angular velocities?
##
## Stands up the ACTUAL museum hall with its artifacts (the pattern of
## probe_wave_platform_recovery.gd), finds the ControlPendulum, checks the
## reference and the readout it was placed with, drives the bob through the
## pickable's own picked_up / dropped signals — EMITTED PROGRAMMATICALLY, no
## tracked hand — and records the centre_crossed signals it emits. Measures the
## installation bounds and the swing envelope against the hall's collision.
##
##   godot --rendering-method gl_compatibility --path . --xr-mode off --script res://commons/testing/probe_wcn_intro.gd -- --capture
##
## Writes res://ada_run/waves_chance_noise/WaveFunctions_Intro/probe_intro.json
## (and probe_intro.png under --capture). A complete pass requires the bob in
## the tree, pickup/drop exercised and centre crossings with opposite signs.
## If the script startup omits required autoloads, retain diagnostics but fail
## the required release contract; an autonomous swing is only partial evidence.
## What it cannot prove: that a tracked hand reaches the bob. Headset acceptance
## is separate and is recorded as such in the report.
var checks := 0
var failures: Array[String] = []
var measurements: Dictionary = {}
var crossings: Array = []
var release_exercised := false
var skipped: Array[String] = []
var t0 := 0.0
const MAP := "WaveFunctions_Intro"
const OUT := "res://ada_run/waves_chance_noise/WaveFunctions_Intro/"

func _ready() -> void: run.call_deferred()

## True under the live harness (probe_live.tscn, project startup with autoloads);
## false under --script, where the desktop rig cannot compile.
func _live() -> bool:
	return str(get_script().resource_path).ends_with("_live.gd")

func check(ok: bool, message: String) -> void:
	checks += 1
	if not ok: failures.append(message)
	print("[wcn-intro] ", "PASS " if ok else "FAIL ", message)

func run() -> void:
	if "--capture" in OS.get_cmdline_user_args() and DisplayServer.get_name() == "headless":
		check(false, "PNG capture requires a rendered window; omit --headless, or omit --capture for logic only")
		_finish()
		return
	var em: Node3D = load("res://commons/scenes/endless_museum.tscn").instantiate()
	var ctl := "res://ada_run/waves_chance_noise/wcn-probe-control.json"
	em.set("EM_CONTROL", ctl); em.set("_overrides_path", ctl + ".unused"); em.set("_hand_path", ctl + ".unused-hand")
	em.set("start_chapter", "wavefunctions"); em.set("start_map", MAP)
	var layout: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://commons/data/em_layout.json"))
	layout.get_or_add("stream", {})["bodies"] = 1
	em.set("_layout", layout)
	var f := FileAccess.open(ctl, FileAccess.WRITE)
	f.store_string(JSON.stringify({"first_chapter": "wavefunctions", "dollhouse": 0, "grid_pack": 1})); f.close()
	# CATCH THE BOB LEAVING (diagnostic, 2026-09-10): every node entering or leaving the
	# tree passes the SceneTree's own signals; a BobSphere leaving is recorded with its
	# parent's state and the call stack (empty without a debugger, kept anyway).
	var leave_log: Array = []
	get_tree().node_added.connect(func(n: Node):
		if n.name == "BobSphere":
			var p: Node = n.get_parent()
			leave_log.append({"event": "added", "frame": Engine.get_process_frames(), "parent": str(p.name) if p else "none",
				"parent_ready": p.is_node_ready() if p else false, "parent_in_tree": p.is_inside_tree() if p else false})
			n.tree_exiting.connect(func():
				var pp: Node = n.get_parent()
				var kids: Array = []
				if pp != null:
					for c in pp.get_children(): kids.append(c.name)
				leave_log.append({"event": "exiting", "frame": Engine.get_process_frames(), "parent": str(pp.name) if pp else "none",
					"parent_ready": pp.is_node_ready() if pp else false, "parent_kids": kids, "stack": get_stack()})))
	get_tree().node_removed.connect(func(n: Node):
		if n.name == "BobSphere":
			leave_log.append({"event": "removed", "frame": Engine.get_process_frames(), "queued_for_deletion": n.is_queued_for_deletion()}))
	measurements["bob_tree_events"] = leave_log
	get_tree().root.add_child(em); get_tree().current_scene = em
	# WATCH THE BOB FROM FRAME ZERO (diagnostic, 2026-09-10): the grab sphere is built
	# in the pendulum's _ready and is gone from the tree by the time the checks run.
	# Record the frame it leaves and what the pendulum looked like at that moment.
	var watch_pend: Node3D = null
	var watch_bob: Node = null
	var detached_at := -1
	for fr in range(90):
		await get_tree().process_frame
		if watch_pend == null:
			for n in em.find_children("*", "Node3D", true, false):
				if n is ControlPendulum: watch_pend = n; break
			if watch_pend != null:
				measurements["pendulum_found_at_frame"] = fr
				watch_bob = watch_pend.find_child("BobSphere", true, false)
				measurements["bob_present_when_found"] = watch_bob != null
				if watch_bob == null:
					var bv0: Variant = watch_pend.get("_bob_sphere")
					if bv0 is Node: watch_bob = bv0
		elif watch_bob != null and detached_at < 0 and not (watch_bob as Node).is_inside_tree():
			detached_at = fr
			var names0: Array = []
			for c in watch_pend.get_children(): names0.append(c.name)
			measurements["bob_detached_at_frame"] = fr
			measurements["pendulum_children_at_detach"] = names0
			measurements["pendulum_grabbed_at_detach"] = watch_pend.get("_is_grabbed")
			measurements["pendulum_in_tree_at_detach"] = watch_pend.is_inside_tree()
			measurements["pendulum_parent_at_detach"] = str(watch_pend.get_parent().name) if watch_pend.get_parent() != null else "none"
	em.set_process(false); em.call("flush_stamps")
	var player: Node = em.get("_player")
	if player != null: player.set_process(false); player.set_physics_process(false)
	var seg: Node3D
	for rec: Dictionary in em.get("_segments"):
		if rec.node.get_meta("em_map", "") == MAP: seg = rec.node; break
	check(seg != null, "the hall exists in the active museum")
	if seg == null:
		_finish(); return
	for i in range(30): await get_tree().process_frame

	# ── 1. the pendulum, as placed ────────────────────────────────────────────
	var pend: Node3D
	for n in seg.find_children("*", "Node3D", true, false):
		if n is ControlPendulum: pend = n; break
	check(pend != null, "control_pendulum is built in the hall")
	if pend == null:
		_finish(); return
	check(str(pend.get("reference")) == "plumb", "placed with reference=plumb (token config reached the artifact)")
	check(str(pend.get("evidence")) == "trace", "placed with evidence=trace")
	check(str(pend.get("regime")) == "free", "regime is the shipped free")
	check(pend.get_node_or_null("Reference/RestRing") != null, "the rest ring exists")
	check(pend.get_node_or_null("Reference/Plumb") != null, "the plumb line exists")
	# the visual pass of 12 September: a slate behind the swing and a cased readout beside it
	check(pend.get_node_or_null("Reference/Slate") != null, "a dark slate stands behind the swing plane")
	check(pend.get_node_or_null("Reference/LabelPlate") != null, "the state readout is cased beside the pivot")
	var lbl_ref: Label3D = pend.get("_label")
	check(lbl_ref != null and lbl_ref.font_size >= 22 and lbl_ref.position.x > 0.5, "the readout is enlarged and out of the swing (font %d, x %.2f)" % [lbl_ref.font_size if lbl_ref != null else -1, lbl_ref.position.x if lbl_ref != null else 0.0])
	check(pend.get_node_or_null("Evidence/Theta") != null, "the predicted theta(t) is drawn")
	var bob: Node3D = pend.find_child("BobSphere", true, false)
	if bob == null:
		# diagnostic (2026-09-10): bare instantiation has BobSphere as a direct child in both
		# configuration orders; in the museum it is absent. Record what stands where.
		var names: Array = []
		for c in pend.get_children(): names.append(c.name + ":" + c.get_class())
		measurements["pendulum_children"] = names
		measurements["bob_var"] = str(pend.get("_bob_sphere"))
		var elsewhere: Array = []
		for n in seg.find_children("*", "", true, false):
			if n.get_script() != null and str(n.get_script().resource_path).ends_with("grab_sphere.gd"):
				elsewhere.append(str(n.get_path()).right(80))
		for n in em.find_children("BobSphere*", "", true, false):
			elsewhere.append("em:" + str(n.get_path()).right(80))
		measurements["grab_spheres_elsewhere"] = elsewhere
		var bv: Variant = pend.get("_bob_sphere")
		if bv is Node:
			var bn: Node = bv
			measurements["bob_in_tree"] = bn.is_inside_tree()
			measurements["bob_parent"] = str(bn.get_parent().get_path()) if bn.get_parent() != null else "none"
			measurements["bob_valid"] = is_instance_valid(bn)
			if bn.is_inside_tree():
				bob = bn   # it exists; it was reparented — follow it
	# THE RELEASE PATH CANNOT BE EXERCISED FROM A SceneTree PROBE (found 2026-09-10 with
	# --log-file): grab_sphere.gd names TextManager and XR Tools' pickable.gd names
	# XRToolsUserSettings at compile time; without the autoloads both fail to COMPILE, the
	# grab sphere instantiates as a bare RigidBody3D, control_pendulum's _create_grabbable_bob
	# aborts on `alter_freeze` and the bob never enters the tree. project.godot declares
	# the required autoloads; verify construction and release through that startup.
	# The swing, crossings and readout remain partial evidence, not a release test.
	var release_testable: bool = bob != null and bob.has_signal("picked_up") and bob.has_signal("dropped")
	if not release_testable:
		var reason := "Required pickup/release was not exercised: bob or pickable signals missing. See engine log and test through project startup with its autoloads."
		measurements["release_path"] = reason
		skipped.append(reason)
		check(false, reason)
	else:
		check(bob.has_signal("picked_up") and bob.has_signal("dropped"), "the bob carries the pickable's picked_up/dropped signals")
	var rest_local: Vector3 = seg.to_local(pend.call("rest_world_position"))
	measurements["rest_point_local"] = [rest_local.x, rest_local.y, rest_local.z]
	check(rest_local.y > 0.6 and rest_local.y < 1.6, "the rest point is at hand height (%.2f m above the deck)" % rest_local.y)
	var L: float = float(pend.get("pendulum_length"))
	for side in [-1.0, 1.0]:
		var release := pend.to_global(Vector3(sin(0.6) * L * side, -cos(0.6) * L, 0.0))
		var rl := seg.to_local(release)
		check(rl.y > 0.5 and rl.y < 1.8, "release position %s is reachable (%.2f m)" % ["left" if side < 0 else "right", rl.y])
		check(not _solid_at(seg, release, 0.09), "release position %s is clear of the hall's collision" % ["left" if side < 0 else "right"])
	# the swing envelope: a box the full width of the swing under the pivot
	var env := BoxShape3D.new()
	env.size = Vector3(2.0 * L + 0.3, L + 0.3, 0.3)
	var q := PhysicsShapeQueryParameters3D.new()
	q.shape = env; q.transform = Transform3D(Basis.IDENTITY, pend.to_global(Vector3(0, -L * 0.5, 0)))
	var hits: Array = seg.get_world_3d().direct_space_state.intersect_shape(q, 8)
	var solid_hits := 0
	for h in hits:
		if h.collider == seg.get_node_or_null("Collision"): solid_hits += 1
	check(solid_hits == 0, "the complete swing is clear of walls and platforms (%d solid hits)" % solid_hits)
	measurements["installation_aabb"] = _aabb(pend)

	# ── 2. the real signal path: pick up, move, drop ──────────────────────────
	var crossings_before_observation: int = int(pend.call("crossings"))
	pend.connect("centre_crossed", func(d: int, w: float): crossings.append({"dir": d, "omega": w, "t": Time.get_ticks_msec() / 1000.0 - t0}))
	t0 = Time.get_ticks_msec() / 1000.0
	if release_testable:
		var first: Dictionary = await _release(pend, bob, 0.6)
		release_exercised = true
		check(float(first.get("release_omega", 0.0)) > 0.0, "a hand moving toward increasing angle releases in that direction")
		check(not bool(pend.call("is_grabbed")), "the artifact answered dropped: not grabbed after release")
		check(absf(float(first.get("angle", 0.0)) - 0.6) < 0.15, "the release angle came from the bob's position (%.2f rad)" % float(first.get("angle", 0.0)))
	# (without a release the pendulum swings from START_ANGLE on its own; the crossings below are that swing's)
	await get_tree().create_timer(4.0).timeout
	var n1 := crossings.size()
	check(n1 >= 2, "at least two centre crossings during the observation (%d)" % n1)
	if n1 >= 2:
		check(int(crossings[0]["dir"]) != int(crossings[1]["dir"]), "the first two crossings travel in opposite directions (%d then %d)" % [int(crossings[0]["dir"]), int(crossings[1]["dir"])])
		check(signf(float(crossings[0]["omega"])) != signf(float(crossings[1]["omega"])), "their angular velocities have opposite signs (%+.2f, %+.2f rad/s)" % [float(crossings[0]["omega"]), float(crossings[1]["omega"])])
	check(int(pend.call("crossings")) - crossings_before_observation == n1, "the count advances by the observed crossings; earlier motion is retained")
	var lbl: Label3D = pend.get_node_or_null("Label3D") if pend.get_node_or_null("Label3D") else null
	for c in pend.get_children():
		if c is Label3D: lbl = c
	check(lbl != null and (lbl.text.contains("ω +") or lbl.text.contains("ω -")), "the readout prints a SIGNED angular velocity")
	# ── 3. release from the other side ────────────────────────────────────────
	if release_testable:
		var before := crossings.size()
		var dir_first: int = int(crossings[0]["dir"]) if n1 > 0 else 0
		await _release(pend, bob, -0.6)
		await get_tree().create_timer(2.5).timeout
		check(crossings.size() > before, "a second release crosses the centre again")
		if crossings.size() > before and n1 > 0:
			check(int(crossings[before]["dir"]) != dir_first, "released from the other side, the first crossing goes the other way")
	# ── 4. the driven cube listens to this pendulum ───────────────────────────
	var cube: Node = null
	for n in seg.find_children("*", "Node3D", true, false):
		if n.get_script() != null and str(n.get_script().resource_path).ends_with("oscillation_controlled_cube.gd"): cube = n; break
	check(cube != null, "oscillation_controlled_cube stands in the hall")
	if cube != null:
		check(cube.get("_pendulum") == pend, "the driven cube found THIS pendulum (one signal, three transformations)")
	measurements["crossings"] = crossings
	measurements["scale"] = [pend.scale.x, pend.scale.y, pend.scale.z]
	check(pend.scale.is_equal_approx(Vector3.ONE), "the subject's scale is what the map asked (1)")

	# ── ACTUAL DESKTOP INPUT (live harness only): the desktop rig's right-click carry ──
	# Recorded separately from the emitted signals above. The rig's carry lifts a
	# pickable in front of the camera; whether the pendulum learns of it (its own
	# picked_up handler) is what this measures. No assertion: it is a finding.
	if _live() and release_testable:
		var drv: Node = load("res://commons/testing/wcn_desktop_driver.gd").new()
		get_tree().root.add_child(drv)   # a SceneTree has no add_child; the port maps root. to get_tree().root.
		var stand: Vector3 = pend.to_global(Vector3(0.0, 0.0, 1.5))
		stand.y = seg.to_global(Vector3(0, 0, 0)).y
		drv.call("spawn", stand, em)
		await get_tree().create_timer(0.5).timeout
		drv.call("aim_at", pend.call("bob_world_position"))
		var seen: Node = await drv.call("hover_target")
		var grabbed_before: bool = bool(pend.call("is_grabbed"))
		var bob_before: Vector3 = pend.call("bob_world_position")
		await drv.call("click", MOUSE_BUTTON_RIGHT)
		for i in range(20): await get_tree().physics_frame
		var grabbed_after: bool = bool(pend.call("is_grabbed"))
		var bob_after: Vector3 = pend.call("bob_world_position")
		await drv.call("click", MOUSE_BUTTON_RIGHT)   # drop, if anything was carried
		for i in range(5): await get_tree().physics_frame
		measurements["desktop_input"] = {"carry_hover": (str(seen.get_path()).right(60) if seen != null else "nothing"),
			"pendulum_grabbed_before": grabbed_before, "pendulum_grabbed_after": grabbed_after,
			"bob_moved_m": snappedf(bob_before.distance_to(bob_after), 0.01),
			"note": "the desktop carry (RMB) is a stand-in for VR grab and does not call the pickable's pick_up; a headset release is a separate lane"}
		if "--capture" in OS.get_cmdline_user_args():
			await get_tree().create_timer(0.3, true, false, true).timeout
			get_viewport().get_texture().get_image().save_png(OUT + "probe_intro_desktop_primary_live.png")
		await drv.call("teardown")
		measurements["desktop_input"]["log"] = drv.get("log")
		measurements["desktop_input"]["walker_cam_guard_stopped"] = drv.get("walker_cam_guard_stopped")
		await get_tree().process_frame
	if "--capture" in OS.get_cmdline_user_args():
		var cam := Camera3D.new(); em.add_child(cam); cam.fov = 60
		cam.global_position = pend.to_global(Vector3(0.9, 0.2, 1.9)); cam.look_at(pend.to_global(Vector3(0, -0.3, 0)))
		for i in range(30): cam.make_current(); await get_tree().process_frame
		await get_tree().create_timer(0.3, true, false, true).timeout
		get_viewport().get_texture().get_image().save_png(OUT + "probe_intro_live.png")
	_finish()

## The pickable's own signal path, emitted programmatically: picked_up, the bob
## carried to the release angle over a few physics frames (so the artifact's
## velocity samples see a hand moving), then dropped.
func _release(pend: Node3D, bob: Node3D, angle: float) -> Dictionary:
	var L: float = float(pend.get("pendulum_length"))
	bob.emit_signal("picked_up", bob)
	await get_tree().physics_frame
	var start: Vector3 = bob.global_position
	var target: Vector3 = pend.to_global(Vector3(sin(angle) * L, -cos(angle) * L, 0.0))
	for i in range(12):
		bob.global_position = start.lerp(target, float(i + 1) / 12.0)
		await get_tree().physics_frame
	bob.global_position = target
	await get_tree().physics_frame
	var a: float = float(pend.call("angle"))
	bob.emit_signal("dropped", bob)
	var release_omega: float = float(pend.call("angular_velocity"))
	await get_tree().physics_frame
	return {"angle": a, "omega": float(pend.call("angular_velocity")), "release_omega": release_omega}

func _solid_at(seg: Node3D, p: Vector3, r: float) -> bool:
	var s := SphereShape3D.new(); s.radius = r
	var q := PhysicsShapeQueryParameters3D.new(); q.shape = s; q.transform = Transform3D(Basis.IDENTITY, p)
	for h in seg.get_world_3d().direct_space_state.intersect_shape(q, 8):
		if h.collider == seg.get_node_or_null("Collision"): return true
	return false

func _aabb(node: Node) -> Array:
	var merged := AABB(); var first := true
	for n in node.find_children("*", "MeshInstance3D", true, false):
		var box: AABB = (n as MeshInstance3D).global_transform * (n as MeshInstance3D).get_aabb()
		merged = box if first else merged.merge(box); first = false
	return [snappedf(merged.size.x, 0.01), snappedf(merged.size.y, 0.01), snappedf(merged.size.z, 0.01)]

func _finish() -> void:
	var report := {"map": MAP, "checks": checks, "failures": failures, "measurements": measurements,
		"control_path": ("picked_up/dropped emitted programmatically on the bob pickable; no tracked hand" if release_exercised else "pickup/release NOT exercised; autonomous motion observations only"),
		"skipped": skipped, "release_exercised": release_exercised,
		"status": ("passed" if failures.is_empty() and release_exercised else "incomplete_or_failed"),
		"headset_verified": false, "engine": Engine.get_version_info().string,
		"physics_fps": Engine.physics_ticks_per_second}
	var f := FileAccess.open(OUT + "probe_intro_live.json", FileAccess.WRITE)
	f.store_string(JSON.stringify(report, "  ")); f.close()
	print("[wcn-intro] ", checks, " checks; ", failures.size(), " failures")
	get_tree().quit(0 if failures.is_empty() else 1)
