## LIVE PORT — generated by tools/port_wcn_probes_live.py from probe_wcn_pendulum.gd. Do not edit;
## edit the SceneTree probe and regenerate. Runs under project startup (probe_live.tscn
## with --probe=pendulum), so the project's autoloads exist and XR Tools pickables compile.
## Outputs carry a _live suffix.
extends Node
## WaveFunctions_Pendulum, batch W1 (doc/research/waves-chance-noise, 2026-09-10):
## does the installed pendulum keep a bounded record of its own past, and can a
## visitor read count, span and interval off the room?
##
## Stands up the ACTUAL museum hall with its artifacts (the pattern of
## probe_wcn_intro.gd), hands the museum the REAL necklace hand file (the
## stamps under wavefunctions|pendulum are keyed to an old pearl name and must
## not claim anything; the map opts into artifact_placement=map besides), finds
## the PendulumWave, and measures the record under the three sampling policies.
## Buttons are pressed by EMITTING the push button's own signal — no tracked hand.
##
##   godot --rendering-method gl_compatibility --path . --xr-mode off --script res://commons/testing/probe_wcn_pendulum.gd -- --capture
##   godot --headless --path . --xr-mode off --script res://commons/testing/probe_wcn_pendulum.gd
##
## Writes res://ada_run/waves_chance_noise/WaveFunctions_Pendulum/probe_pendulum.json
## (and probe_pendulum.png under --capture). Exit code 1 on any failed check.
var checks := 0
var failures: Array[String] = []
var measurements: Dictionary = {}
const MAP := "WaveFunctions_Pendulum"
const OUT := "res://ada_run/waves_chance_noise/WaveFunctions_Pendulum/"
const MAP_CELL := Vector2i(6, 11)

func _ready() -> void: run.call_deferred()

## True under the live harness (probe_live.tscn, project startup with autoloads);
## false under --script, where the desktop rig cannot compile.
func _live() -> bool:
	return str(get_script().resource_path).ends_with("_live.gd")

func check(ok: bool, message: String) -> void:
	checks += 1
	if not ok: failures.append(message)
	print("[wcn-pendulum] ", "PASS " if ok else "FAIL ", message)

func run() -> void:
	if "--capture" in OS.get_cmdline_user_args() and DisplayServer.get_name() == "headless":
		check(false, "PNG capture requires a rendered window; omit --headless, or omit --capture for logic only")
		_finish(); return
	var em: Node3D = load("res://commons/scenes/endless_museum.tscn").instantiate()
	var ctl := "res://ada_run/waves_chance_noise/wcn-probe-control.json"
	em.set("EM_CONTROL", ctl); em.set("_overrides_path", ctl + ".unused")
	em.set("_hand_path", "res://ada_run/necklace_hand.json")   # the REAL hand, on purpose
	em.set("start_chapter", "wavefunctions"); em.set("start_map", MAP)
	var layout: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://commons/data/em_layout.json"))
	layout.get_or_add("stream", {})["bodies"] = 1
	em.set("_layout", layout)
	var f := FileAccess.open(ctl, FileAccess.WRITE)
	f.store_string(JSON.stringify({"first_chapter": "wavefunctions", "dollhouse": 0, "grid_pack": 1})); f.close()
	get_tree().root.add_child(em); get_tree().current_scene = em
	await get_tree().create_timer(1.0).timeout
	em.set_process(false); em.call("flush_stamps")
	var player: Node = em.get("_player")
	if player != null: player.set_process(false); player.set_physics_process(false)
	var seg: Node3D
	for rec: Dictionary in em.get("_segments"):
		if rec.node.get_meta("em_map", "") == MAP: seg = rec.node; break
	check(seg != null, "the hall exists in the active museum")
	if seg == null:
		_finish(); return
	for i in range(30): await get_tree().process_frame
	var vest: int = int(em.get("VESTIBULE_H"))

	# ── 1. built where the map put it, housed ────────────────────────────────
	var pend: Node3D
	var pend_cell: Array = []
	for record: Dictionary in em.get("_edit_records"):
		var node: Node = record.get("node")
		if node != null and seg.is_ancestor_of(node) and node.get_script() != null and str(node.get_script().resource_path).ends_with("PendulumWave.gd"):
			pend = node; pend_cell = record.get("tile_cell", [])
	if pend == null:
		for n in seg.find_children("*", "Node3D", true, false):
			if n.get_script() != null and str(n.get_script().resource_path).ends_with("PendulumWave.gd"): pend = n; break
	check(pend != null, "PendulumWave is built in the hall")
	if pend == null:
		_finish(); return
	if pend_cell.size() >= 2:
		# _edit_records keeps the MAP cell (observed 2026-09-10: [6, 11]); the vestibule offset lives in world z only
		check(int(pend_cell[0]) == MAP_CELL.x and int(pend_cell[1]) == MAP_CELL.y,
			"built at the map's cell (6,11), not a bench bead (got %s)" % str(pend_cell))
	var local_origin: Vector3 = seg.to_local(pend.global_position)
	measurements["origin_local"] = [local_origin.x, local_origin.y, local_origin.z]
	check(absf(local_origin.x - 6.5) < 0.6 and absf(local_origin.z - (11.5 + vest)) < 0.6, "the installation stands on its cell (%.1f, %.1f)" % [local_origin.x, local_origin.z - vest])
	check(pend.get_node_or_null("Frame/PostL") != null and pend.get_node_or_null("Frame/Beam") != null, "the gallows frame is built")
	var readout: Label3D = pend.get_node_or_null("ReadoutCase/Readout")
	check(readout != null, "the cased readout exists")
	var panel: Node = pend.get_node_or_null("Panel")
	check(panel != null, "the sampler panel exists")
	check(panel != null and panel.get_meta("em_local_instrument", false), "the panel is marked a local instrument (its button areas are not the installation's footprint)")
	if readout != null:
		var rh: float = seg.to_local(readout.global_position).y
		measurements["readout_height"] = rh
		check(rh > 1.2 and rh < 1.7, "the readout sits at reading height (%.2f m above the deck)" % rh)
		var rz: float = seg.to_local(readout.global_position).z - vest
		check(rz > 13.5 and rz < 15.5, "the readout stands three metres down the record, south of the bob (z %.1f)" % rz)
		var rx: float = seg.to_local(readout.global_position).x
		check(rx > 7.5, "on the east walkway side (x %.1f)" % rx)
	var btn0: Node = panel.find_child("Btn_0", true, false) if panel != null else null
	if btn0 != null:
		var bh: float = seg.to_local(btn0.global_position).y
		measurements["panel_height"] = bh
		check(bh > 0.9 and bh < 1.45, "the panel buttons are at hand height (%.2f m)" % bh)
	if panel != null:
		# the visual pass of 12 September: the panel faces the east walkway (world +x), where
		# the visitor stands to see the bob, the trail and the buttons together
		var facing: Vector3 = seg.global_transform.basis.inverse() * (panel as Node3D).global_transform.basis.z
		measurements["panel_facing"] = [snappedf(facing.x, 0.01), snappedf(facing.y, 0.01), snappedf(facing.z, 0.01)]
		check(facing.x > 0.9, "the sampler panel faces the east walkway (%s)" % str(measurements["panel_facing"]))
		var px: float = seg.to_local((panel as Node3D).global_position).x
		check(px > 8.0, "the panel stands outboard of the east post (x %.2f)" % px)
	check(pend.get_node_or_null("Runner") != null, "a dark runner lies under the record")
	# the two holes the museum read from the map's 0 cells — the tc cell in the west aisle
	# (2,8) and the teleporter's cell (7,18) — are floored by museum.floor_cells now
	var pspace0 := seg.get_world_3d().direct_space_state
	for hole in [[2.5, 8.5, "the west aisle's tc cell (2,8)"], [7.5, 18.5, "the teleporter's cell (7,18)"]]:
		var rq := PhysicsRayQueryParameters3D.create(seg.to_global(Vector3(hole[0], 3.0, hole[1] + vest)), seg.to_global(Vector3(hole[0], -3.0, hole[1] + vest)))
		var hit: Dictionary = pspace0.intersect_ray(rq)
		var fy: float = seg.to_local(hit["position"]).y if not hit.is_empty() else -99.0
		measurements["floor_" + str(hole[2]).replace(" ", "_").replace("'", "")] = snappedf(fy, 0.001)
		check(abs(fy) < 0.02, "floor under %s (%.2f)" % [hole[2], fy])
	var bob_w: Vector3 = pend.call("bob_world_position")
	var bob_h: float = seg.to_local(bob_w).y
	measurements["bob_rest_height"] = bob_h
	check(bob_h > 0.7 and bob_h < 1.6, "the bob swings at hand-to-eye height (%.2f m)" % bob_h)
	# the swing envelope and the record's lane are clear of the hall's collision
	var L: float = float(pend.get("length"))
	var ph: float = float(pend.get("pivot_height"))
	var env := BoxShape3D.new(); env.size = Vector3(2.0 * L + 0.3, L + 0.3, 0.3)
	var q := PhysicsShapeQueryParameters3D.new(); q.shape = env
	q.transform = Transform3D(Basis.IDENTITY, pend.to_global(Vector3(0, ph - L * 0.5, 0)))
	check(_solid_hits(seg, q) == 0, "the complete swing is clear of walls and platforms")
	var lane := BoxShape3D.new(); lane.size = Vector3(3.0, 0.8, 6.2)
	q.shape = lane; q.transform = Transform3D(Basis.IDENTITY, pend.to_global(Vector3(0, ph - L + 0.4, -3.1)))
	check(_solid_hits(seg, q) == 0, "the six-metre lane the record recedes into is clear of the hall's collision")
	# ...and of everything else with a collider: museum plinths, sculptures, other bodies
	var others: Array = []
	for h in seg.get_world_3d().direct_space_state.intersect_shape(q, 16):
		var c: Node = h.collider
		if c == seg.get_node_or_null("Collision") or pend.is_ancestor_of(c): continue
		others.append(str(c.get_path()).right(70))
	measurements["lane_other_colliders"] = others
	check(others.is_empty(), "nothing else with a collider stands in the record's lane (%s)" % str(others))

	# ── 2. the fine record: count, span, depth, direction ─────────────────────
	pend.call("reset_experiment")
	await get_tree().create_timer(3.0).timeout
	var n3: int = int(pend.call("sample_count"))
	var kept3: float = float(pend.call("retained_seconds"))
	measurements["fine_after_3s"] = {"count": n3, "kept": kept3, "t": float(pend.call("experiment_time"))}
	check(n3 >= 100 and n3 <= 130, "after ~3 s the fine sampler has taken about 120 marks (25 ms target): %d" % n3)
	var observed_gaps: Vector2 = pend.call("recorded_interval_range")
	measurements["fine_actual_gaps_ms"] = [observed_gaps.x * 1000.0, observed_gaps.y * 1000.0]
	if Engine.physics_ticks_per_second == 60:
		check(absf(observed_gaps.x - 1.0 / 60.0) < 0.0001 and absf(observed_gaps.y - 2.0 / 60.0) < 0.0001,
			"25 ms target is visibly quantized to one/two physics ticks")
	check(str(pend.call("readout_text")).contains("target ") and str(pend.call("readout_text")).contains("actual gaps"),
		"the display distinguishes the requested interval from the recorded gaps")
	check(absf(kept3 - 3.0) < 0.4, "and the span kept is the time elapsed (%.2f s)" % kept3)
	await get_tree().create_timer(6.0).timeout
	var n9: int = int(pend.call("sample_count"))
	var kept9: float = float(pend.call("retained_seconds"))
	var depth9: float = float(pend.call("oldest_depth"))
	measurements["fine_after_9s"] = {"count": n9, "kept": kept9, "oldest_depth": depth9}
	check(n9 == 300, "the count stops at the first limit, 300 marks (%d)" % n9)
	check(absf(kept9 - 7.5) < 0.15, "300 marks at the 25 ms target keep about 7.5 s under the 10 s age limit (%.2f s)" % kept9)
	check(absf(depth9 - 4.5) < 0.15, "the oldest mark stands 4.5 m behind the bob: 7.5 s at 0.6 m per s (%.2f m)" % depth9)
	var marks: PackedVector3Array = pend.call("mark_world_positions")
	if marks.size() > 1:
		var newest: Vector3 = seg.to_local(marks[0]); var oldest: Vector3 = seg.to_local(marks[marks.size() - 1])
		measurements["newest_local"] = [newest.x, newest.y, newest.z - vest]
		measurements["oldest_local"] = [oldest.x, oldest.y, oldest.z - vest]
		check(oldest.z > newest.z + 4.0, "the record recedes SOUTH, down the open half toward the exit (rotation 180 honoured)")
		var xs := PackedFloat32Array()
		for m in marks: xs.append(seg.to_local(m).x)
		var lo: float = xs[0]; var hi: float = xs[0]
		for v in xs: lo = minf(lo, v); hi = maxf(hi, v)
		measurements["fine_x_spread"] = hi - lo
		check(hi - lo > 2.0, "the fine record spans the swing (x spread %.2f m)" % (hi - lo))
	var period: float = float(pend.call("period_measured"))
	measurements["period_measured"] = period
	check(period > 2.7 and period < 3.2, "the pendulum has measured its own period from two upward crossings (%.3f s; small-angle %.3f s)" % [period, float(pend.call("small_angle_period"))])
	var interval: float = float(pend.call("current_interval"))
	check(period > 0.0 and absf(period / interval - _marks_per_period(marks, pend)) < 4.0,
		"marks between two same-side crossings ≈ period / target interval (%.1f vs counted %d)" % [period / interval, _marks_per_period(marks, pend)])
	if readout != null:
		measurements["readout_fine"] = readout.text
		check(readout.text.contains("300 marks kept 7.5 s") and readout.text.contains("target 25 ms"), "the readout prints the count, the span and the interval")

	# ── 3. COARSE through the panel's own signal ──────────────────────────────
	var pressed_coarse: bool = _press(panel, "Btn_1")
	check(pressed_coarse, "COARSE pressed by emitting the push button's button_pressed (programmatic, no hand)")
	await get_tree().physics_frame
	check(int(pend.call("sample_count")) <= 1, "switching the sampler starts the record again")
	var angle_before: float = float(pend.get("angle"))
	await get_tree().create_timer(10.5).timeout
	var nc: int = int(pend.call("sample_count"))
	var keptc: float = float(pend.call("retained_seconds"))
	measurements["coarse_after_10.5s"] = {"count": nc, "kept": keptc, "oldest_depth": float(pend.call("oldest_depth"))}
	check(nc >= 48 and nc <= 52, "the coarse sampler never reaches 300: ~50 marks at 200 ms (%d)" % nc)
	check(absf(keptc - 10.0) < 0.25, "and is cut by the second limit, the 10 s age (%.2f s)" % keptc)
	check(absf(float(pend.call("oldest_depth")) - 6.0) < 0.2, "so the oldest mark stands 6 m back (%.2f m)" % float(pend.call("oldest_depth")))
	check(absf(float(pend.call("period_measured")) - period) < 0.02, "the motion was not touched by the switch: the period is the same (%.3f s)" % float(pend.call("period_measured")))

	# ── 4. STROBE: a record at the rhythm of the thing recorded ───────────────
	check(_press(panel, "Btn_2"), "STROBE pressed through its signal")
	await get_tree().create_timer(10.5).timeout
	var ns: int = int(pend.call("sample_count"))
	var smarks: PackedVector3Array = pend.call("mark_world_positions")
	var slo: float = INF; var shi: float = -INF
	for m in smarks:
		var x: float = seg.to_local(m).x; slo = minf(slo, x); shi = maxf(shi, x)
	measurements["strobe"] = {"count": ns, "interval": float(pend.call("current_interval")), "x_spread": (shi - slo) if ns > 0 else 0.0}
	check(ns >= 3 and ns <= 4, "one mark per period: 3–4 marks in 10 s (%d)" % ns)
	check(absf(float(pend.call("current_interval")) - period) < 0.02, "the strobe interval IS the measured period (%.3f s)" % float(pend.call("current_interval")))
	check(ns >= 2 and (shi - slo) < 0.12, "the sampled positions nearly align while the bob moves (x spread %.3f m)" % (shi - slo))

	# ── 5. RESET resets this experiment only ──────────────────────────────────
	var t_before: float = float(pend.call("experiment_time"))
	var engine_ticks_before := Engine.get_physics_frames()
	check(_press(panel, "Btn_3"), "RESET pressed through its signal")
	await get_tree().physics_frame
	check(float(pend.call("experiment_time")) < t_before and float(pend.call("experiment_time")) < 0.1, "the experiment clock returns to zero")
	check(int(pend.call("sample_count")) <= 1, "the record is emptied")
	check(absf(float(pend.get("angle")) - deg_to_rad(float(pend.get("initial_angle")))) < 0.05, "the swing returns to its starting angle")
	check(str(pend.get("sampler")) == "strobe", "the chosen sampler survives a reset (the reset is of the experiment, not the settings)")
	check(Engine.get_physics_frames() > engine_ticks_before, "engine physics ticks advance while the local experiment resets")

	# ── 6. the walkways beside the record ─────────────────────────────────────
	var space := seg.get_world_3d().direct_space_state
	var cap := CapsuleShape3D.new(); cap.radius = 0.22; cap.height = 1.6
	var wq := PhysicsShapeQueryParameters3D.new(); wq.shape = cap
	for route in [["east walkway", Vector3(9.5, 0.81, 10.5), Vector3(0, 0, 9.0)],
			["west walkway", Vector3(3.5, 0.81, 10.5), Vector3(0, 0, 9.0)],
			["to the south door", Vector3(9.5, 0.81, 19.5), Vector3(-3.0, 0, 0)]]:
		wq.transform = Transform3D(Basis.IDENTITY, seg.to_global(Vector3(route[1].x, route[1].y, route[1].z + vest)))
		wq.motion = route[2]
		var frac: float = space.cast_motion(wq)[0]
		measurements["walk_" + str(route[0]).replace(" ", "_")] = frac
		check(frac > 0.99, "a body walks the %s (%.2f of the way)" % [route[0], frac])
	measurements["scale"] = [pend.scale.x, pend.scale.y, pend.scale.z]
	check(pend.scale.is_equal_approx(Vector3.ONE), "the subject's scale is what the map asked (1)")

	# ── ACTUAL DESKTOP INPUT (live harness only: the desktop rig names autoloads) ──
	# The project's desktop rig stands on the east walkway north of the panel post,
	# looks at COARSE and left-clicks through the input pipeline; then walks the
	# walkway on ui_up. Nothing here emits an artifact signal.
	if _live():
		var drv: Node = load("res://commons/testing/wcn_desktop_driver.gd").new()
		get_tree().root.add_child(drv)   # a SceneTree has no add_child; the port maps root. to get_tree().root.
		var btn_coarse: Node = panel.find_child("Btn_1", true, false) if panel != null else null
		var stand: Vector3 = seg.to_global(Vector3(8.3, 0.0, 10.3 + vest))
		drv.call("spawn", stand, em)
		await get_tree().create_timer(0.5).timeout
		var rec: Dictionary = await drv.call("press", btn_coarse, stand) if btn_coarse != null else {}
		await get_tree().physics_frame
		measurements["desktop_input"] = {"press": rec, "sampler_after": str(pend.get("sampler"))}
		check(str(rec.get("hover", "")).contains("Btn_1") or str(rec.get("hover", "")).contains("InteractableAreaButton"), "the desktop pointer had COARSE under the crosshair (%s)" % str(rec.get("hover", "")))
		check(str(pend.get("sampler")) == "coarse", "a left click through the input pipeline switched the sampler to COARSE: actual desktop input, not an emitted signal")
		drv.get("rig").global_position = seg.to_global(Vector3(9.5, 0.05, 10.5 + vest))
		await get_tree().physics_frame
		drv.call("aim_at", seg.to_global(Vector3(9.5, 1.2, 19.0 + vest)))
		var moved: Vector3 = await drv.call("walk", "ui_up", 60)
		var moved_local: Vector3 = seg.global_transform.basis.inverse() * moved
		measurements["desktop_input"]["walk_east_walkway_1s"] = [snappedf(moved_local.x, 0.01), snappedf(moved_local.z, 0.01)]
		check(moved_local.z > 3.5, "the rig walked the east walkway south on ui_up (%.2f m in one second)" % moved_local.z)
		if "--capture" in OS.get_cmdline_user_args():
			print("[wcn-pendulum] capture: the rig's walk view, camera ", str(get_viewport().get_camera_3d().get_path()).right(40) if get_viewport().get_camera_3d() != null else "none")
			for i in range(10): await get_tree().process_frame
			await get_tree().create_timer(0.3, true, false, true).timeout
			get_viewport().get_texture().get_image().save_png(OUT + "probe_pendulum_desktop_walk_live.png")
			print("[wcn-pendulum] capture: saved")
			measurements["desktop_input"]["walk_capture_pose"] = drv.call("pose")
		# what stands between the rig and the south door on this walkway (meshes whose
		# world box crosses x 8.5..10.5, rows 15..20 of the map): the walk capture shows a block
		var on_walkway: Array = []
		var box := AABB(seg.to_global(Vector3(8.5, -0.1, 15.0 + vest)), Vector3(2.0, 3.0, 5.5))
		for mi in seg.find_children("*", "MeshInstance3D", true, false):
			var m3: MeshInstance3D = mi
			if m3.mesh == null: continue
			var wb: AABB = m3.global_transform * m3.get_aabb()
			if wb.intersects(box):
				on_walkway.append([str(m3.get_path()).right(70), [snappedf(wb.position.x, 0.01), snappedf(wb.position.y, 0.01), snappedf(wb.position.z, 0.01)], [snappedf(wb.size.x, 0.01), snappedf(wb.size.y, 0.01), snappedf(wb.size.z, 0.01)]])
		measurements["desktop_input"]["south_walkway_meshes"] = on_walkway
		await drv.call("teardown")
		measurements["desktop_input"]["log"] = drv.get("log")
		measurements["desktop_input"]["walker_cam_guard_stopped"] = drv.get("walker_cam_guard_stopped")
		await get_tree().process_frame
	if "--capture" in OS.get_cmdline_user_args():
		pend.call("set_sampler", "fine")
		await get_tree().create_timer(8.0).timeout
		var cam := Camera3D.new(); em.add_child(cam); cam.fov = 62
		# a real standing view from the east wall (12 September; the old spot at (9.8, 9.6)
		# stood inside the lab table's footprint and photographed its back): the bob and the
		# frame ahead, the record running away to the left, the panel on the near post — a
		# wider lens than the other captures, because the panel is close and to the side
		cam.fov = 80
		cam.global_position = seg.to_global(Vector3(11.5, 1.6, 12.2 + vest)); cam.look_at(seg.to_global(Vector3(6.5, 1.2, 13.0 + vest)))
		for i in range(30): cam.make_current(); await get_tree().process_frame
		await get_tree().create_timer(0.3, true, false, true).timeout
		get_viewport().get_texture().get_image().save_png(OUT + "probe_pendulum_live.png")
		measurements["captures"] = {"primary": _cam_pose(cam)}
		# the cased readout from a visitor's standing distance on the east walkway
		if readout != null:
			var plate: Vector3 = readout.global_position
			cam.global_position = plate + seg.global_transform.basis * Vector3(0.15, 0.12, -1.35)
			cam.look_at(plate)
			for i in range(20): cam.make_current(); await get_tree().process_frame
			await get_tree().create_timer(0.3, true, false, true).timeout
			get_viewport().get_texture().get_image().save_png(OUT + "probe_pendulum_readout_live.png")
			measurements["captures"]["readout"] = _cam_pose(cam)
			measurements["captures"]["readout_plate_world"] = [snappedf(plate.x, 0.01), snappedf(plate.y, 0.01), snappedf(plate.z, 0.01)]
		# the controls from the walkway, a step from the post, with the bob and the near
		# record behind them
		if panel != null:
			cam.fov = 62
			cam.global_position = seg.to_global(Vector3(9.9, 1.55, 12.3 + vest)); cam.look_at((panel as Node3D).global_position + seg.global_transform.basis * Vector3(-0.6, 0.15, 0.3))
			for i in range(20): cam.make_current(); await get_tree().process_frame
			await get_tree().create_timer(0.3, true, false, true).timeout
			get_viewport().get_texture().get_image().save_png(OUT + "probe_pendulum_controls_live.png")
			measurements["captures"]["controls"] = _cam_pose(cam)
	# the museum's own verdict on this body: not a severing seal
	var severed: Array = em.get("_seg_severed") if em.get("_seg_severed") != null else []
	var sev_tokens: Array = []
	for s in severed: sev_tokens.append(str((s as Dictionary).get("token", "")))
	measurements["museum_severed_tokens"] = sev_tokens
	measurements["museum_severed"] = severed          # token + the cells each seal, map coords (x, z-from-segment-base)
	check(not sev_tokens.has("PendulumWave"), "the museum did not report the installation as severing the hall")
	check(sev_tokens.is_empty(), "no body in this hall severs the museum's route (severed: %s)" % str(sev_tokens))
	# the museum's own record of this hall as built: walk grid, seals, severance, bodies
	var rows: Array = em.get("_built") if em.get("_built") != null else []
	var mine: Dictionary = {}
	for r in rows:
		if str((r as Dictionary).get("map", "")) == MAP: mine = r
	if mine.is_empty() and not rows.is_empty(): mine = rows[rows.size() - 1]
	if not mine.is_empty():
		measurements["built_cells"] = mine.get("cells", [])
		measurements["built_seals"] = mine.get("seals", [])
		measurements["built_severed"] = mine.get("severed", [])
		measurements["built_refused"] = mine.get("refused", [])
		var toks: Array = []
		for b in mine.get("bodies", []):
			toks.append([str((b as Dictionary).get("token", "")), (b as Dictionary).get("world", []), (b as Dictionary).get("tile_cell", [])])
		measurements["built_bodies"] = toks
	# ── MUSEUM STREAMING: free this hall through the museum's own streamer, rebuild it ──
	# (last: the segment reference dies here). The bare-root reload probe showed the
	# artifact scenes clean up after themselves; this is the museum doing it.
	var seg_i: int = -1
	var segs: Array = em.get("_segments")
	for i in range(segs.size()):
		if (segs[i] as Dictionary).get("node") == seg: seg_i = i
	if seg_i >= 0:
		var z0_key: float = float((segs[seg_i] as Dictionary).get("z0", -1.0))
		var old_pend: Node = pend
		em.call("_stream_free", seg_i, "south")
		for i in range(5): await get_tree().process_frame
		check(not is_instance_valid(old_pend), "the museum's streamer freed the hall and the pendulum with it")
		var rec_f: Dictionary = {}
		for r in (em.get("_freed") as Array):
			if absf(float((r as Dictionary).get("z0", -2.0)) - z0_key) < 0.5: rec_f = r
		var can_rebuild: bool = not rec_f.is_empty() and not ((rec_f.get("snap", {})) as Dictionary).is_empty()
		measurements["streaming"] = {"freed": not rec_f.is_empty(), "rebuildable": can_rebuild}
		if can_rebuild:
			em.call("_stream_rebuild", rec_f)
			em.call("flush_stamps")
			for i in range(30): await get_tree().process_frame
			var seg2: Node3D = null
			for rec2: Dictionary in em.get("_segments"):
				if rec2.node.get_meta("em_map", "") == MAP: seg2 = rec2.node
			var pend2: Node3D = null
			if seg2 != null:
				for n in seg2.find_children("*", "Node3D", true, false):
					if n.get_script() != null and str(n.get_script().resource_path).ends_with("PendulumWave.gd"): pend2 = n; break
			check(pend2 != null, "the hall rebuilt through the streamer and stands a fresh pendulum")
			if pend2 != null:
				await get_tree().create_timer(1.0).timeout
				check(int(pend2.call("sample_count")) > 20 and pend2.get_node_or_null("Panel") != null and pend2.get_node_or_null("ReadoutCase/Readout") != null, "the rebuilt pendulum records again, with its panel and readout (%d marks)" % int(pend2.call("sample_count")))
				measurements["streaming"]["rebuilt_marks"] = int(pend2.call("sample_count"))
		else:
			measurements["streaming"]["note"] = "no cursor snapshot for the start hall (pre-window hall): the museum's streamer frees it but cannot rebuild it by design"
	_finish()

func _press(panel: Node, btn_name: String) -> bool:
	if panel == null: return false
	var btn: Node = panel.find_child(btn_name, true, false)
	var area: Node = btn.get_node_or_null("InteractableAreaButton") if btn != null else null
	if area == null or not area.has_signal("button_pressed"): return false
	area.emit_signal("button_pressed", area)
	return true

## Count marks between two successive crossings of x=0 in the same direction.
func _marks_per_period(marks: PackedVector3Array, pend: Node3D) -> int:
	var xs: Array[float] = []
	# Cross the pendulum's own x=0, wherever the installation stands in the hall.
	for m in marks: xs.append(pend.to_local(m).x)
	var first := -1
	for i in range(1, xs.size()):
		if xs[i - 1] < 0.0 and xs[i] >= 0.0:
			if first < 0: first = i
			else: return i - first
	return -1

func _solid_hits(seg: Node3D, q: PhysicsShapeQueryParameters3D) -> int:
	var n := 0
	for h in seg.get_world_3d().direct_space_state.intersect_shape(q, 8):
		if h.collider == seg.get_node_or_null("Collision"): n += 1
	return n

func _finish() -> void:
	var report := {"map": MAP, "checks": checks, "failures": failures, "measurements": measurements,
		"control_path": "button_pressed emitted programmatically on the panel's push buttons; no tracked hand",
		"hand_file": "ada_run/necklace_hand.json (real)", "headset_verified": false,
		"engine": Engine.get_version_info().string, "physics_fps": Engine.physics_ticks_per_second}
	var f := FileAccess.open(OUT + "probe_pendulum_live.json", FileAccess.WRITE)
	f.store_string(JSON.stringify(report, "  ")); f.close()
	print("[wcn-pendulum] ", checks, " checks; ", failures.size(), " failures")
	get_tree().quit(0 if failures.is_empty() else 1)

## Which camera the viewport draws from at a capture, and where it stands and looks.
func _cam_pose(cam: Camera3D) -> Dictionary:
	var cur: Camera3D = get_viewport().get_camera_3d()
	var fwd: Vector3 = -cam.global_transform.basis.z
	return {"current_camera": str(cur.get_path()).right(50) if cur != null else "none", "is_ours": cur == cam,
		"at": [snappedf(cam.global_position.x, 0.01), snappedf(cam.global_position.y, 0.01), snappedf(cam.global_position.z, 0.01)],
		"forward": [snappedf(fwd.x, 0.01), snappedf(fwd.y, 0.01), snappedf(fwd.z, 0.01)]}
