extends Node3D
class_name DimensionalAnalogy

# @identity
# essence: five stations on one bench where each figure is literally the previous one dragged along an axis it did not have — a sphere, a sphere swept into a bar, that bar swept into a square, the square swept into a cube, the cube swept into a direction the room does not contain
# desire: to stop the tesseract being a fact recited to the player and make it the fifth step of a gesture they have already watched happen four times
# critical_parameter: `stage` (0..4) — the rung currently being swept; everything below it stands finished, the rung itself is mid-extrusion every frame, and everything above it is an empty marked place on the bench
# triggers: _ready() builds each figure by running the extrusion itself (vertices duplicated at -1 and +1 on a fresh axis, old edges doubled, one new edge per old vertex), then _process() drives the active station's moving copy from -1 to +1 so the sweep is seen and not asserted
# emerges: the counts stop being trivia — 1/2/4/8/16 vertices and 0/1/4/12/32 edges fall out of the same operation five times, and the fourth axis is the only one where the operation outruns the room
# needs: tesseract_bench.gd [present — its _project() is the 4D camera all five stations are seen through, borrowed as a live instance rather than copied]; SphereMesh/CylinderMesh [Godot built-ins]; Grid.gdshader [present]; TextScreen PAD plate [present]
# relationships: the ramp up to tesseract_bench and schlegel_diagram — those two show a finished 4D object, this one shows where such an object comes from, and hands them the same projection so the three read as one apparatus
# truth: nobody has ever seen four dimensions, and nobody needs to. A dimension is not a place, it is a move — repeat the move once past where you can stand and the fourth is as ordinary as the third, which is also the reason it explains nothing away.

## The dimensional ladder as a bench of five sweeps. Every figure here is
## generated by extrusion, not typed in: extruding a point gives a segment,
## extruding a segment gives a square, and the same six lines of code carry on
## into a dimension the bench cannot hold. The fifth station is drawn through
## the very projection tesseract_bench uses, so this is the same 4D camera the
## rest of the higher-dimensions room looks through.

const SHADER_PATH := "res://commons/resourses/shaders/Grid.gdshader"
const TextScreenScript := preload("res://commons/ui/text_screen.gd")
const TesseractBenchScript := preload("res://commons/artifacts/tesseract_bench/tesseract_bench.gd")

const BENCH_W := 2.72
const BENCH_D := 0.46
const BENCH_H := 0.78
const STATION_X := [-1.14, -0.57, 0.0, 0.57, 1.14]
const FIGURE_Y := 1.12
const VERT_R := 0.021
const EDGE_R := 0.007

## Which rung is being swept right now. Stations below it stand finished;
## stations above it are marked but empty, so the bench reads as a ladder with
## a position on it rather than five equal exhibits.
@export_range(0, 4, 1) var stage: int = 4

## Seconds for one sweep of the active station, and the pause at full extent
## before it snaps back to start again.
@export var sweep_seconds: float = 3.2
@export var hold_seconds: float = 1.1

## Passed straight to the borrowed projector. view_w is the 4D camera distance;
## figure_scale sets how big one unit of the lattice reads on the bench.
@export var view_w: float = 3.0
@export var figure_scale: float = 0.17

## Radians/sec of x-w rotation applied to station 4 only. The lower stations
## are held at angle 0 — spinning a 3D cube through the w plane would warp it
## by perspective and say something this bench is not saying yet.
@export var spin_speed: float = 0.45

const NAMES := ["0D  POINT", "1D  SEGMENT", "2D  SQUARE", "3D  CUBE", "4D  TESSERACT"]
const VERT_COUNTS := [1, 2, 4, 8, 16]
const EDGE_COUNTS := [0, 1, 4, 12, 32]

var _built := false
var _created: Array[Node] = []
## Left deliberately untyped. A statically typed Node reference would refuse
## view_w / size_scale / _project at compile time; this borrows the bench's
## camera dynamically, which is exactly what it is.
var _projector = null                # a TesseractBench instance, never added to the tree
var _angle: float = 0.0
var _clock: float = 0.0

# Live nodes for the active station's sweep.
var _sweep_verts: Array[MeshInstance3D] = []
var _sweep_edges: Array[MeshInstance3D] = []
var _sweep_links: Array[MeshInstance3D] = []
var _sweep_base: Array[Vector4] = []
var _sweep_pairs: Array[Vector2i] = []
var _sweep_axis: int = 0


func _ready() -> void:
	_projector = TesseractBenchScript.new()
	_build_all()
	_built = true
	set_process(not Engine.is_editor_hint())


func _exit_tree() -> void:
	if _projector != null and is_instance_valid(_projector):
		_projector.free()
	_projector = null


# --- extrusion ------------------------------------------------------------

## The whole argument, in eleven lines. Start with one vertex at the origin.
## To gain a dimension: copy every vertex to -1 and +1 on a fresh axis, copy
## every edge into both halves, and join each old vertex to its own copy. Run
## it n times and you have the n-cube — 1/2/4/8/16 vertices, 0/1/4/12/32 edges,
## none of them typed in anywhere in this file.
func _figure(dim: int) -> Dictionary:
	var verts: Array[Vector4] = [Vector4.ZERO]
	var edges: Array[Vector2i] = []
	for axis in range(dim):
		var n: int = verts.size()
		var nv: Array[Vector4] = []
		for v in verts:
			var a: Vector4 = v
			nv.append(_shift(a, axis, -1.0))
		for v in verts:
			var b: Vector4 = v
			nv.append(_shift(b, axis, 1.0))
		var ne: Array[Vector2i] = []
		for e in edges:
			var pair: Vector2i = e
			ne.append(pair)
			ne.append(Vector2i(pair.x + n, pair.y + n))
		for i in range(n):
			ne.append(Vector2i(i, i + n))
		verts = nv
		edges = ne
	return {"verts": verts, "edges": edges}


func _shift(v: Vector4, axis: int, amount: float) -> Vector4:
	match axis:
		0: return Vector4(v.x + amount, v.y, v.z, v.w)
		1: return Vector4(v.x, v.y + amount, v.z, v.w)
		2: return Vector4(v.x, v.y, v.z + amount, v.w)
		_: return Vector4(v.x, v.y, v.z, v.w + amount)


## Borrowed camera. The projector is a real TesseractBench with its own
## _project(); we set its knobs, hand it a 4D point and take back a 3D one.
## Reimplementing the perspective divide here would have been four lines and a
## second place for the higher-dimensions room to disagree with itself.
func _project(v: Vector4, angle: float) -> Vector3:
	if _projector == null:
		return Vector3(v.x, v.y, v.z) * figure_scale
	_projector.view_w = view_w
	_projector.size_scale = figure_scale
	_projector._angle = angle
	var out: Vector3 = _projector._project(v)
	return out


# --- build ----------------------------------------------------------------

func _own(n: Node) -> Node:
	_created.append(n)
	add_child(n)
	return n


func _build_all() -> void:
	_sweep_verts.clear()
	_sweep_edges.clear()
	_sweep_links.clear()
	_sweep_base.clear()
	_sweep_pairs.clear()
	_angle = 0.0
	_clock = 0.0

	_add_bench()

	var active: int = clampi(stage, 0, 4)
	for i in range(5):
		var hub := Node3D.new()
		hub.name = "Station%d" % i
		hub.position = Vector3(float(STATION_X[i]), FIGURE_Y, 0.0)
		_own(hub)
		if i < active:
			_build_finished(hub, i)
		elif i == active:
			_build_active(hub, i)
		else:
			_build_placeholder(hub)
		_add_caption(i, i <= active)

	_add_plate()
	_update_sweep()


## A completed figure: every vertex and edge of the n-cube, standing still.
func _build_finished(hub: Node3D, dim: int) -> void:
	var fig := _figure(dim)
	var verts: Array = fig["verts"]
	var edges: Array = fig["edges"]
	var mat := _quiet_mat()
	var pts: Array[Vector3] = []
	for v in verts:
		var p: Vector3 = _project(v, 0.0)
		pts.append(p)
		hub.add_child(_sphere(p, VERT_R, mat))
	for e in edges:
		var pair: Vector2i = e
		hub.add_child(_strut(pts[pair.x], pts[pair.y], EDGE_R, mat))


## The rung being climbed. The figure one dimension down is drawn twice — once
## parked at -1 on the new axis, once travelling from -1 to +1 — with a link
## from each parked vertex to its travelling copy. When the traveller lands,
## the three sets together ARE the finished n-cube; that identity is the whole
## demonstration, so it is built out of the extrusion rather than faked with a
## crossfade between two finished shapes.
func _build_active(hub: Node3D, dim: int) -> void:
	var mat := _live_mat()
	var ghost := _quiet_mat()
	if dim == 0:
		# Nothing to sweep yet. One sphere, which is the honest content of 0D.
		var solo := _sphere(Vector3.ZERO, VERT_R * 1.6, mat)
		hub.add_child(solo)
		_sweep_verts.append(solo)
		_sweep_base.append(Vector4.ZERO)
		_sweep_axis = 0
		return

	var prev := _figure(dim - 1)
	_sweep_base.assign(prev["verts"])
	_sweep_pairs.assign(prev["edges"])
	_sweep_axis = dim - 1

	# parked copy at -1 on the new axis
	var parked: Array[Vector3] = []
	for v in _sweep_base:
		var base: Vector4 = v
		var p: Vector3 = _project(_shift(base, _sweep_axis, -1.0), 0.0)
		parked.append(p)
		hub.add_child(_sphere(p, VERT_R, ghost))
	for e in _sweep_pairs:
		var pair: Vector2i = e
		hub.add_child(_strut(parked[pair.x], parked[pair.y], EDGE_R, ghost))

	# travelling copy — positions rewritten every frame
	for i in range(_sweep_base.size()):
		var node := _sphere(Vector3.ZERO, VERT_R, mat)
		hub.add_child(node)
		_sweep_verts.append(node)
	for i in range(_sweep_pairs.size()):
		var seg := _strut(Vector3(-0.01, 0.0, 0.0), Vector3(0.01, 0.0, 0.0), EDGE_R, mat)
		hub.add_child(seg)
		_sweep_edges.append(seg)
	# the swept links — one per vertex, the edges the new dimension pays for
	for i in range(_sweep_base.size()):
		var link := _strut(Vector3(-0.01, 0.0, 0.0), Vector3(0.01, 0.0, 0.0), EDGE_R, mat)
		hub.add_child(link)
		_sweep_links.append(link)


## A rung not yet reached: a small open ring on the bench, so the ladder shows
## where it continues without pretending the figure is there.
func _build_placeholder(hub: Node3D) -> void:
	var mi := MeshInstance3D.new()
	var torus := TorusMesh.new()
	torus.inner_radius = 0.055
	torus.outer_radius = 0.068
	torus.rings = 12
	mi.mesh = torus
	mi.rotation_degrees = Vector3(90.0, 0.0, 0.0)
	mi.position = Vector3(0.0, -0.30, 0.0)
	mi.material_override = _dim_mat()
	hub.add_child(mi)


func _update_sweep() -> void:
	if _sweep_base.is_empty():
		return
	if _sweep_links.is_empty():
		# stage 0 — nothing is being swept. The point breathes so it is not
		# mistaken for a bead. (Testing _sweep_pairs here would be wrong: at
		# stage 1 the parent figure is a single vertex with no edges at all,
		# and the one link IS the sweep.)
		if not _sweep_verts.is_empty():
			var s: float = 1.0 + 0.18 * sin(_clock * 2.4)
			_sweep_verts[0].scale = Vector3.ONE * s
		return

	var t: float = _phase()
	var offset: float = -1.0 + 2.0 * t
	var moving: Array[Vector3] = []
	var parked: Array[Vector3] = []
	for i in range(_sweep_base.size()):
		var base: Vector4 = _sweep_base[i]
		var p: Vector3 = _project(_shift(base, _sweep_axis, offset), _angle)
		moving.append(p)
		parked.append(_project(_shift(base, _sweep_axis, -1.0), _angle))
		if i < _sweep_verts.size():
			_sweep_verts[i].position = p
	for ei in range(_sweep_edges.size()):
		var pair: Vector2i = _sweep_pairs[ei]
		_lay(_sweep_edges[ei], moving[pair.x], moving[pair.y])
	for li in range(_sweep_links.size()):
		_lay(_sweep_links[li], parked[li], moving[li])


## 0 -> 1 across sweep_seconds, then a flat hold at 1 so the finished figure is
## legible before the sweep restarts.
func _phase() -> float:
	var period: float = maxf(sweep_seconds + hold_seconds, 0.2)
	var u: float = fmod(_clock, period)
	if u >= sweep_seconds:
		return 1.0
	var raw: float = u / maxf(sweep_seconds, 0.01)
	return raw * raw * (3.0 - 2.0 * raw)


func _process(delta: float) -> void:
	if Engine.is_editor_hint():
		return
	_clock += delta
	if stage >= 4:
		_angle += spin_speed * delta
	_update_sweep()


# --- pieces ---------------------------------------------------------------

func _lay(seg: MeshInstance3D, a: Vector3, b: Vector3) -> void:
	var cyl := seg.mesh as CylinderMesh
	if cyl != null:
		cyl.height = maxf(a.distance_to(b), 0.001)
	var dir: Vector3 = (b - a)
	if dir.length() < 0.0001:
		dir = Vector3.UP
	dir = dir.normalized()
	var up := Vector3.UP
	if absf(dir.dot(up)) > 0.999:
		up = Vector3.RIGHT
	var xa: Vector3 = up.cross(dir).normalized()
	var za: Vector3 = dir.cross(xa).normalized()
	seg.transform = Transform3D(Basis(xa, dir, za), (a + b) * 0.5)


func _sphere(pos: Vector3, r: float, mat: Material) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var sm := SphereMesh.new()
	sm.radius = r
	sm.height = r * 2.0
	sm.radial_segments = 12
	sm.rings = 7
	mi.mesh = sm
	mi.position = pos
	mi.material_override = mat
	return mi


func _strut(a: Vector3, b: Vector3, r: float, mat: Material) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var cyl := CylinderMesh.new()
	cyl.top_radius = r
	cyl.bottom_radius = r
	cyl.height = maxf(a.distance_to(b), 0.001)
	cyl.radial_segments = 6
	cyl.rings = 1
	mi.mesh = cyl
	mi.material_override = mat
	_lay(mi, a, b)
	return mi


func _add_bench() -> void:
	var top := MeshInstance3D.new()
	top.name = "BenchTop"
	var box := BoxMesh.new()
	box.size = Vector3(BENCH_W, 0.06, BENCH_D)
	top.mesh = box
	top.position = Vector3(0.0, BENCH_H - 0.03, 0.0)
	top.material_override = _witness_mat()
	_own(top)
	for sx in [-1.0, 1.0]:
		var leg := MeshInstance3D.new()
		var lb := BoxMesh.new()
		lb.size = Vector3(0.10, BENCH_H - 0.06, 0.10)
		leg.mesh = lb
		leg.position = Vector3(float(sx) * (BENCH_W * 0.5 - 0.12), (BENCH_H - 0.06) * 0.5, 0.0)
		leg.material_override = _witness_mat()
		_own(leg)


func _add_caption(i: int, lit: bool) -> void:
	var lb := Label3D.new()
	lb.name = "Caption%d" % i
	lb.text = "%s\n%d vertices  %d edges" % [NAMES[i], VERT_COUNTS[i], EDGE_COUNTS[i]]
	lb.font_size = 26
	lb.pixel_size = 0.0016
	lb.billboard = BaseMaterial3D.BILLBOARD_DISABLED
	lb.modulate = Color(0.70, 0.86, 1.0) if lit else Color(0.32, 0.35, 0.42)
	lb.outline_size = 4
	lb.position = Vector3(float(STATION_X[i]), BENCH_H + 0.12, BENCH_D * 0.5 + 0.01)
	lb.double_sided = false
	_own(lb)


func _add_plate() -> void:
	# Configure BEFORE add_child — TextScreen rebuilds only once in-tree, so
	# driving its setters afterwards costs a rebuild per property.
	var ts := TextScreenScript.new()
	ts.name = "Plate"
	ts.mode = 2                       # Mode.PAD
	ts.width_m = 0.46
	ts.position = Vector3(0.0, BENCH_H + 0.005, -BENCH_D * 0.5 + 0.02)
	if ts.has_method("set_text"):
		ts.set_text("DIMENSIONAL ANALOGY", "each figure is the last one dragged\nalong an axis it did not have")
	_own(ts)


# --- material -------------------------------------------------------------

func _live_mat() -> Material:
	return _grid_material(Color(0.60, 0.72, 0.85), Color(0.45, 0.90, 1.0), 2.4)


func _quiet_mat() -> Material:
	return _grid_material(Color(0.44, 0.48, 0.58), Color(0.50, 0.68, 0.85), 1.0)


func _witness_mat() -> Material:
	return _grid_material(Color(0.28, 0.30, 0.36), Color(0.42, 0.47, 0.57), 0.4)


func _dim_mat() -> Material:
	return _grid_material(Color(0.22, 0.24, 0.29), Color(0.34, 0.38, 0.46), 0.2)


func _grid_material(fill: Color, wire: Color, emit: float) -> Material:
	var shader: Shader = load(SHADER_PATH)
	if shader:
		var m := ShaderMaterial.new()
		m.shader = shader
		m.set_shader_parameter("modelColor", fill)
		m.set_shader_parameter("wireframeColor", wire)
		m.set_shader_parameter("emissionColor", wire)
		m.set_shader_parameter("width", 1.0)
		m.set_shader_parameter("blur", 1.0)
		m.set_shader_parameter("emission_strength", emit)
		m.set_shader_parameter("modelOpacity", 1.0)
		m.set_shader_parameter("wireframeOpacity", 1.0)
		m.set_shader_parameter("globalOpacity", 1.0)
		m.set_shader_parameter("show_interior", true)
		return m
	var fallback := StandardMaterial3D.new()
	fallback.albedo_color = fill
	fallback.roughness = 0.4
	fallback.emission_enabled = true
	fallback.emission = wire
	fallback.emission_energy_multiplier = emit
	return fallback


func _rebuild_now() -> void:
	for c in _created:
		if is_instance_valid(c) and c.get_parent() == self:
			remove_child(c)
			c.queue_free()
	_created.clear()
	_build_all()


## Grid config. Keys: "stage", "view_w", "figure_scale", "sweep_seconds",
## "spin_speed". Only a change that alters geometry triggers a rebuild —
## curation_station hands every artifact it curates {"emissive": false} right
## after framing its labels, and rebuilding on that would throw the framing away.
func apply_grid_config(config_data: Dictionary) -> void:
	var before_stage: int = stage
	var before_view: float = view_w
	var before_scale: float = figure_scale

	if config_data.has("stage"):
		stage = clampi(int(config_data["stage"]), 0, 4)
	if config_data.has("view_w"):
		view_w = maxf(float(config_data["view_w"]), 1.2)
	if config_data.has("figure_scale"):
		figure_scale = maxf(float(config_data["figure_scale"]), 0.02)
	if config_data.has("sweep_seconds"):
		sweep_seconds = maxf(float(config_data["sweep_seconds"]), 0.2)
	if config_data.has("spin_speed"):
		spin_speed = float(config_data["spin_speed"])

	if not _built:
		return
	if stage == before_stage and is_equal_approx(view_w, before_view) \
			and is_equal_approx(figure_scale, before_scale):
		return
	_rebuild_now()
