@tool
extends Node3D
class_name AlessiTree

# @identity
# essence: a procedural Alessi-style holiday tree built from a zigzag profile of revolution + radial stripe coloring — a Christmas tree as the limit case of "stacked cones with vertex colors"
# desire: to be the design_classics kingdom's argument that a beloved object — the tree on the table at every December dinner — is in fact (tier_count, taper_envelope, stripe_count, two_colors); kitsch is just a small parameter set with affective amplification
# critical_parameter: tiers — the int range(3, 12) controlling how many alternating wide/narrow rings stack up the height; bump tiers and the tree gains layers like a real spruce filling out, drop them and it collapses to a sad hat
# triggers: _ready() calls _rebuild(); every @export setter (tiers, base_radius, stripe_count, color_a, color_b, gold_trim, ...) re-triggers _rebuild() so the editor previews live; @tool annotation enables in-editor preview
# emerges: a recognizable Christmas-tree silhouette the player can recolor and restripe — flip color_b from red to teal, multiply stripe_count, and the holiday icon mutates into something that could sit in any aesthetic; the player learns that "Christmas tree" is a parameter range, not a fixed thing
# needs: SurfaceTool [native, has]; StandardMaterial3D with vertex_color_use_as_albedo=true so the alternating stripe colors paint via per-vertex color [has]; zigzag profile generated by alternating wide/narrow at each tier_step [has]; @tool for editor preview [has]
# relationships: a sibling of aalto_vase, eames_chair, noguchi_table in the design_classics primitive_kingdom — each one a procedural restatement of a 20th-century icon; pairs with aalto_vase as the two procedural icons whose silhouettes are *named* (vs. mathematical primitives like bipyramid/arch); the radial-stripe-via-vertex-color trick prefigures the color sequence's vertex-painting techniques
# truth: a tradition is a small parameter vector you agree to hold constant. Change tiers from 5 to 7 and the tree is still Christmas; change color_a to black and it isn't.

## Procedural Alessi-style stacked cone tree with radial stripes
## Based on Alessi holiday decorations

@export var height: float = 1.0:
	set(v):
		height = v
		_rebuild()

@export var base_radius: float = 0.4:
	set(v):
		base_radius = v
		_rebuild()

@export_range(3, 12) var tiers: int = 5:
	set(v):
		tiers = v
		_rebuild()

@export_range(8, 64) var radial_segments: int = 24:
	set(v):
		radial_segments = v
		_rebuild()

@export var stripe_count: int = 12:
	set(v):
		stripe_count = v
		_rebuild()

@export var color_a: Color = Color.WHITE:
	set(v):
		color_a = v
		_rebuild()

@export var color_b: Color = Color(0.9, 0.15, 0.1):
	set(v):
		color_b = v
		_rebuild()

@export var gold_trim: bool = true:
	set(v):
		gold_trim = v
		_rebuild()

var _mesh_instance: MeshInstance3D

func _ready():
	_rebuild()

func _rebuild():
	if _mesh_instance:
		_mesh_instance.queue_free()
	
	_mesh_instance = MeshInstance3D.new()
	add_child(_mesh_instance)
	
	var mesh = _generate_mesh()
	_mesh_instance.mesh = mesh

func _generate_mesh() -> ArrayMesh:
	var st = SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	
	# Generate profile - zigzag pattern
	var profile = []
	var tier_height = height / tiers
	
	for t in range(tiers + 1):
		var y = t * tier_height
		var progress = float(t) / tiers
		
		# Alternate between wide and narrow
		var envelope = 1.0 - progress * 0.7  # Taper toward top
		if t % 2 == 0:
			# Wide point
			profile.append([base_radius * envelope, y])
		else:
			# Narrow point
			profile.append([base_radius * envelope * 0.5, y])
	
	# Top cap
	profile.append([base_radius * 0.1, height])
	
	# Generate mesh by revolving profile
	for p in range(profile.size() - 1):
		var r0 = profile[p][0]
		var y0 = profile[p][1]
		var r1 = profile[p + 1][0]
		var y1 = profile[p + 1][1]
		
		for s in range(radial_segments):
			var theta0 = TAU * s / radial_segments
			var theta1 = TAU * (s + 1) / radial_segments
			
			var stripe_idx = int(s * stripe_count / radial_segments)
			var color = color_a if stripe_idx % 2 == 0 else color_b
			
			# Four vertices of this quad
			var v00 = Vector3(cos(theta0) * r0, y0, sin(theta0) * r0)
			var v10 = Vector3(cos(theta1) * r0, y0, sin(theta1) * r0)
			var v01 = Vector3(cos(theta0) * r1, y1, sin(theta0) * r1)
			var v11 = Vector3(cos(theta1) * r1, y1, sin(theta1) * r1)
			
			# Calculate normal (approximate)
			var n = ((v10 - v00).cross(v01 - v00)).normalized()
			
			st.set_color(color)
			st.set_normal(n)
			
			# Triangle 1
			st.add_vertex(v00)
			st.add_vertex(v01)
			st.add_vertex(v10)
			
			# Triangle 2
			st.add_vertex(v10)
			st.add_vertex(v01)
			st.add_vertex(v11)
	
	# Bottom cap
	var gold = Color(0.85, 0.65, 0.13) if gold_trim else color_a
	for s in range(radial_segments):
		var theta0 = TAU * s / radial_segments
		var theta1 = TAU * (s + 1) / radial_segments
		var r = profile[0][0]
		
		var v0 = Vector3(cos(theta0) * r, 0, sin(theta0) * r)
		var v1 = Vector3(cos(theta1) * r, 0, sin(theta1) * r)
		
		st.set_color(gold)
		st.set_normal(Vector3.DOWN)
		st.add_vertex(Vector3.ZERO)
		st.add_vertex(v1)
		st.add_vertex(v0)
	
	var mesh = st.commit()
	
	# Create material that uses vertex colors
	var mat = StandardMaterial3D.new()
	mat.vertex_color_use_as_albedo = true
	mat.metallic = 0.1
	mat.roughness = 0.3
	
	mesh.surface_set_material(0, mat)
	
	return mesh
