# res://algorithms/proceduralgeneration/wfcRooms/wfc_office_generator.gd
# Runtime WFC solver optimized for office floor plan generation
# Attach to a Node3D in your scene to generate procedural offices
extends Node3D

## Size of the office floor grid
@export var grid_width : int = 8
@export var grid_height : int = 8
@export var tile_size : float = 4.0  # Office tiles are 4m x 4m

## Path to the office tile scene generated by wfc_office_tiles.gd
@export var tiles_scene_path : String = "res://algorithms/proceduralgeneration/wfcRooms/OfficeTiles.tscn"

## Generate on ready?
@export var auto_generate : bool = true

## Maximum iterations to prevent infinite loops
@export var max_iterations : int = 10000

## Seed for reproducible generation (-1 = random)
@export var generation_seed : int = -1

## Office generation settings
@export_group("Office Layout")
@export var force_perimeter_walls : bool = true  # Ensure walls around edges
@export var min_corridor_ratio : float = 0.15     # Minimum % of corridors
@export var max_corridor_ratio : float = 0.35     # Maximum % of corridors

## Internal data
var tile_prototypes : Array[Node3D] = []
var grid : Array = []
var possible : Array = []
var socket_rules : Dictionary = {}

## Tile categories for weighted selection
var corridor_tiles : Array[Node3D] = []
var office_tiles : Array[Node3D] = []
var open_plan_tiles : Array[Node3D] = []
var conference_tiles : Array[Node3D] = []
var cubicle_tiles : Array[Node3D] = []
var transition_tiles : Array[Node3D] = []
var utility_tiles : Array[Node3D] = []
var corner_tiles : Array[Node3D] = []

func _ready():
	if auto_generate:
		generate_office()

## Main generation function
func generate_office() -> bool:
	print("Starting WFC office generation...")

	# Setup random seed
	if generation_seed >= 0:
		seed(generation_seed)
	else:
		randomize()

	# Load tile prototypes
	if not _load_tile_prototypes():
		push_error("Failed to load tile prototypes!")
		return false

	# Initialize grid
	_initialize_grid()

	# Apply boundary constraints (walls on perimeter)
	if force_perimeter_walls:
		_apply_perimeter_constraints()

	# Run WFC algorithm
	var success = _collapse_wave_function()

	if success:
		print("Office generated successfully!")
		_place_tiles_in_world()
		return true
	else:
		push_error("WFC failed to find valid solution - creating fallback")
		_create_fallback_grid()
		return false

## Load all tile prototypes from the generated scene
func _load_tile_prototypes() -> bool:
	var scene = load(tiles_scene_path)
	if not scene:
		push_error("Could not load tiles scene: " + tiles_scene_path)
		push_error("TIP: Run wfc_office_tiles.gd first to generate tiles!")
		push_error("   1. Open wfc_office_tiles.gd in Script Editor")
		push_error("   2. Click File -> Run (Ctrl+Shift+X)")
		push_error("   3. This creates OfficeTiles.tscn")
		_create_fallback_grid()
		return false

	var root = scene.instantiate()

	# Find all tiles (they're in the "tile" group)
	for child in root.get_children():
		if child.is_in_group("tile") and child is Node3D:
			tile_prototypes.append(child)
			# Categorize tiles
			var room_type = child.get_meta("room_type", "")
			match room_type:
				"corridor":
					corridor_tiles.append(child)
				"office":
					office_tiles.append(child)
				"open_plan":
					open_plan_tiles.append(child)
				"conference":
					conference_tiles.append(child)
				"cubicle":
					cubicle_tiles.append(child)
				"transition":
					transition_tiles.append(child)
				"utility":
					utility_tiles.append(child)
				"corner":
					corner_tiles.append(child)
				"reception":
					open_plan_tiles.append(child)  # Treat reception as open plan

	if tile_prototypes.is_empty():
		push_error("No tiles found in scene!")
		root.queue_free()
		return false

	print("Loaded ", tile_prototypes.size(), " tile types")
	print("  - Corridors: ", corridor_tiles.size())
	print("  - Offices: ", office_tiles.size())
	print("  - Open Plan: ", open_plan_tiles.size())
	print("  - Conference: ", conference_tiles.size())
	print("  - Cubicles: ", cubicle_tiles.size())
	print("  - Transitions: ", transition_tiles.size())

	# Build socket compatibility rules
	_build_socket_rules()

	root.queue_free()
	return true

## Build rules for which tiles can be adjacent
func _build_socket_rules():
	socket_rules.clear()

	for tile in tile_prototypes:
		var sockets = tile.get_meta("sockets", {})
		socket_rules[tile.name] = sockets

	print("Built socket rules for ", socket_rules.size(), " tiles")

## Initialize the grid with all possibilities
func _initialize_grid():
	grid = []
	possible = []

	for y in range(grid_height):
		var row = []
		var poss_row = []
		for x in range(grid_width):
			row.append(null)
			# Initially, all tiles are possible at each position
			poss_row.append(tile_prototypes.duplicate())
		grid.append(row)
		possible.append(poss_row)

	print("Initialized grid: ", grid_width, "x", grid_height)

## Apply constraints for perimeter walls
func _apply_perimeter_constraints():
	print("Applying perimeter wall constraints...")

	for y in range(grid_height):
		for x in range(grid_width):
			var constraints = {}

			# North edge needs wall socket on north
			if y == grid_height - 1:
				constraints["N"] = "wall"

			# South edge needs wall socket on south
			if y == 0:
				constraints["S"] = "wall"

			# East edge needs wall socket on east
			if x == grid_width - 1:
				constraints["E"] = "wall"

			# West edge needs wall socket on west
			if x == 0:
				constraints["W"] = "wall"

			# Filter possibilities based on constraints
			if not constraints.is_empty():
				var filtered = []
				for tile in possible[y][x]:
					var sockets = socket_rules.get(tile.name, {})
					var valid = true
					for dir in constraints:
						if sockets.get(dir, "") != constraints[dir]:
							valid = false
							break
					if valid:
						filtered.append(tile)
				possible[y][x] = filtered

				if filtered.is_empty():
					push_warning("No valid tiles for perimeter at (%d, %d)" % [x, y])

## Core WFC algorithm with office-specific weighting
func _collapse_wave_function() -> bool:
	var iterations = 0
	var corridor_count = 0
	var total_cells = grid_width * grid_height

	while not _is_fully_collapsed():
		iterations += 1
		if iterations > max_iterations:
			push_error("Max iterations reached!")
			return false

		# Find cell with minimum entropy
		var coords = _find_min_entropy_cell()
		if coords == null:
			return false

		var x = coords.x
		var y = coords.y

		var poss = possible[y][x]
		if poss.is_empty():
			return false

		# Choose tile with weighted selection
		var chosen_tile = _weighted_select(poss, corridor_count, total_cells)
		grid[y][x] = chosen_tile
		possible[y][x] = []

		# Track corridor ratio
		var room_type = chosen_tile.get_meta("room_type", "")
		if room_type == "corridor":
			corridor_count += 1

		# Propagate constraints
		_propagate_constraints(x, y)

		if iterations % 50 == 0:
			print("Iteration ", iterations, " - ", _count_collapsed(), "/", total_cells, " cells collapsed")

	print("WFC completed in ", iterations, " iterations")
	return true

## Weighted tile selection to balance office layout
func _weighted_select(possibilities: Array, current_corridors: int, total_cells: int) -> Node3D:
	var corridor_ratio = float(current_corridors) / float(total_cells)

	# Adjust weights based on current corridor ratio
	var corridor_weight = 1.0
	if corridor_ratio < min_corridor_ratio:
		corridor_weight = 3.0  # Encourage more corridors
	elif corridor_ratio > max_corridor_ratio:
		corridor_weight = 0.2  # Discourage more corridors

	# Build weighted list
	var weighted = []
	for tile in possibilities:
		var room_type = tile.get_meta("room_type", "")
		var weight = 1.0

		match room_type:
			"corridor":
				weight = corridor_weight
			"transition":
				weight = 1.5  # Slightly favor transitions for connectivity
			"open_plan":
				weight = 1.2
			"office":
				weight = 1.0
			"conference":
				weight = 0.8  # Fewer conference rooms
			"cubicle":
				weight = 1.1
			"utility":
				weight = 0.5  # Fewer utility rooms

		# Add tile multiple times based on weight (simple weighting)
		var count = int(weight * 10)
		for i in count:
			weighted.append(tile)

	if weighted.is_empty():
		return possibilities[randi() % possibilities.size()]

	return weighted[randi() % weighted.size()]

## Find the uncollapsed cell with fewest possibilities
func _find_min_entropy_cell():
	var min_entropy = INF
	var candidates = []

	for y in range(grid_height):
		for x in range(grid_width):
			if grid[y][x] == null:
				var entropy = possible[y][x].size()
				if entropy == 0:
					return null
				if entropy < min_entropy:
					min_entropy = entropy
					candidates = [Vector2i(x, y)]
				elif entropy == min_entropy:
					candidates.append(Vector2i(x, y))

	if candidates.is_empty():
		return null

	return candidates[randi() % candidates.size()]

## Propagate constraints after collapsing a cell
func _propagate_constraints(start_x: int, start_y: int):
	var stack = [Vector2i(start_x, start_y)]

	while not stack.is_empty():
		var coord = stack.pop_back()
		var x = coord.x
		var y = coord.y

		var neighbors = [
			{"pos": Vector2i(x, y + 1), "dir": "N", "opp": "S"},  # North (higher Y in grid = north)
			{"pos": Vector2i(x + 1, y), "dir": "E", "opp": "W"},
			{"pos": Vector2i(x, y - 1), "dir": "S", "opp": "N"},
			{"pos": Vector2i(x - 1, y), "dir": "W", "opp": "E"},
		]

		for neighbor in neighbors:
			var nx = neighbor.pos.x
			var ny = neighbor.pos.y

			if nx < 0 or nx >= grid_width or ny < 0 or ny >= grid_height:
				continue

			if grid[ny][nx] != null:
				continue

			var old_count = possible[ny][nx].size()
			_constrain_cell(nx, ny, x, y, neighbor.dir, neighbor.opp)
			var new_count = possible[ny][nx].size()

			if new_count < old_count:
				stack.append(Vector2i(nx, ny))

## Constrain a cell based on its neighbor
func _constrain_cell(cell_x: int, cell_y: int, neighbor_x: int, neighbor_y: int, direction: String, opposite: String):
	var neighbor_tile = grid[neighbor_y][neighbor_x]

	if neighbor_tile != null:
		var neighbor_sockets = socket_rules.get(neighbor_tile.name, {})
		var required_socket = neighbor_sockets.get(opposite, "")

		var filtered = []
		for tile in possible[cell_y][cell_x]:
			var tile_sockets = socket_rules.get(tile.name, {})
			if tile_sockets.get(direction, "") == required_socket:
				filtered.append(tile)

		possible[cell_y][cell_x] = filtered
	else:
		var neighbor_poss = possible[neighbor_y][neighbor_x]
		var filtered = []

		for tile in possible[cell_y][cell_x]:
			var tile_sockets = socket_rules.get(tile.name, {})
			var my_socket = tile_sockets.get(direction, "")

			var has_compatible = false
			for n_tile in neighbor_poss:
				var n_sockets = socket_rules.get(n_tile.name, {})
				if n_sockets.get(opposite, "") == my_socket:
					has_compatible = true
					break

			if has_compatible:
				filtered.append(tile)

		possible[cell_y][cell_x] = filtered

## Check if all cells are collapsed
func _is_fully_collapsed() -> bool:
	for y in range(grid_height):
		for x in range(grid_width):
			if grid[y][x] == null:
				return false
	return true

## Count collapsed cells
func _count_collapsed() -> int:
	var count = 0
	for y in range(grid_height):
		for x in range(grid_width):
			if grid[y][x] != null:
				count += 1
	return count

## Place the generated tiles in the 3D world
func _place_tiles_in_world():
	# Clear existing children
	for child in get_children():
		if child.is_in_group("generated_tile"):
			child.queue_free()

	# Place tiles
	for y in range(grid_height):
		for x in range(grid_width):
			var tile_proto = grid[y][x]
			if tile_proto == null:
				continue

			var tile = tile_proto.duplicate()
			tile.add_to_group("generated_tile")

			# Position in world (Z is forward in Godot)
			tile.transform.origin = Vector3(x * tile_size, 0, y * tile_size)

			add_child(tile)

	print("Placed ", grid_width * grid_height, " tiles in world")

	# Add ceiling (optional - creates enclosed feeling)
	_add_ceiling()

## Add a ceiling plane over the office
func _add_ceiling():
	var ceiling = CSGBox3D.new()
	ceiling.name = "Ceiling"
	ceiling.size = Vector3(grid_width * tile_size, 0.1, grid_height * tile_size)
	ceiling.transform.origin = Vector3(
		grid_width * tile_size * 0.5 - tile_size * 0.5,
		2.85,  # Just above wall height
		grid_height * tile_size * 0.5 - tile_size * 0.5
	)

	var mat = StandardMaterial3D.new()
	mat.albedo_color = Color(0.95, 0.95, 0.95, 1.0)
	mat.cull_mode = BaseMaterial3D.CULL_FRONT  # Visible from below
	ceiling.material = mat
	ceiling.add_to_group("generated_tile")

	add_child(ceiling)

## Public function to regenerate with new seed
func regenerate(new_seed: int = -1):
	if new_seed >= 0:
		generation_seed = new_seed
	else:
		generation_seed = randi()

	# Clear categories
	corridor_tiles.clear()
	office_tiles.clear()
	open_plan_tiles.clear()
	conference_tiles.clear()
	cubicle_tiles.clear()
	transition_tiles.clear()
	utility_tiles.clear()
	corner_tiles.clear()
	tile_prototypes.clear()

	generate_office()

## Get tile at grid position
func get_tile_at(x: int, y: int) -> Node3D:
	if x < 0 or x >= grid_width or y < 0 or y >= grid_height:
		return null
	return grid[y][x]

## Get room type at grid position
func get_room_type_at(x: int, y: int) -> String:
	var tile = get_tile_at(x, y)
	if tile:
		return tile.get_meta("room_type", "unknown")
	return "empty"

## Debug: Print grid layout
func print_grid():
	print("Office Grid Layout:")
	for y in range(grid_height - 1, -1, -1):  # Print top to bottom
		var row = ""
		for x in range(grid_width):
			var tile = grid[y][x]
			if tile:
				var room_type = tile.get_meta("room_type", "?")
				row += room_type[0].to_upper() + " "
			else:
				row += "? "
		print(row)
	print("Legend: C=corridor, O=office, P=open_plan, F=conference, U=cubicle, T=transition, Y=utility, R=corner")

## Create a simple fallback grid when tiles aren't available
func _create_fallback_grid():
	print("Creating fallback office grid visualization...")

	for y in range(grid_height):
		for x in range(grid_width):
			var box = CSGBox3D.new()
			box.name = "FallbackTile_%d_%d" % [x, y]
			box.size = Vector3(tile_size * 0.95, 0.15, tile_size * 0.95)
			box.transform.origin = Vector3(x * tile_size, 0, y * tile_size)

			var is_perimeter = (x == 0 or x == grid_width - 1 or y == 0 or y == grid_height - 1)
			var mat = StandardMaterial3D.new()
			mat.albedo_color = Color(0.6, 0.6, 0.65) if is_perimeter else Color(0.75, 0.75, 0.8)
			box.material = mat

			box.add_to_group("generated_tile")
			add_child(box)

	var label = Label3D.new()
	label.text = "Fallback Grid - Tiles Not Found\n\n1. Open wfc_office_tiles.gd\n2. Run it (Ctrl+Shift+X)\n3. Reload this scene"
	label.font_size = 28
	label.outline_size = 6
	label.transform.origin = Vector3(grid_width * tile_size * 0.5, 3, -4)
	add_child(label)

	print("Fallback grid created - ", grid_width * grid_height, " tiles")
