extends Node

var text = """
[font_size=28][b]9. The Circle of Fifths as Graph[/b][/font_size]
[i]Harmonic Space is a Network[/i]

[i][color=gray]Summary: The Circle of Fifths is usually presented as a diagram, but mathematically, it is a specific type of Graph: a Cyclic Graph (C12) isomorphic to the modular group Z12. By treating pitch classes as Nodes and intervals as Edges, we can model modulation and harmony as a pathfinding problem.[/color][/i]

[hr]

[b]1. The Nodes: Pitch Classes[/b]

The 12 notes of the chromatic scale are the nodes of our graph.
`{ C, C#, D, D#, E, F, F#, G, G#, A, A#, B }`

In linear chromatic space, C is adjacent to C# (distance 1).
But in [b]Harmonic Space[/b], C is adjacent to G (distance 7, a perfect fifth).

[hr]

[b]2. The Edges: The Generator[/b]

The graph is generated by the rule:
[color=green]`Node(i) connects to Node((i + 7) % 12)`[/color]

This creates a single connected component—a ring.
*   [b]C[/b] -> [b]G[/b] -> [b]D[/b] -> [b]A[/b] -> [b]E[/b] -> [b]B[/b] -> [b]F#[/b] -> [b]C#[/b] -> [b]G#[/b] -> [b]D#[/b] -> [b]A#[/b] -> [b]F[/b] -> [b]C[/b]

Traversing this edge adds one sharp to the key signature.
Traversing backwards (distance -7 or +5) adds one flat.

[hr]

[b]3. The Torus of Thirds[/b]

If we add edges for Major Thirds (distance 4), the graph becomes more complex.
*   C connects to E (Major 3rd)
*   C connects to G (Fifth)

This transforms the 1D Circle into a [b]Tonnetz[/b] (Tone Network)—a 2D lattice wrapped around a torus.
Navigating this graph allows for "Giant Steps" changes (Coltrane) or chromatic mediants.

[hr]

[b]4. Music as Pathfinding[/b]

Composition becomes a navigation problem:
"How do I get from C Major to F# Major?"
*   Shortest path on Chromatic Graph: 6 steps.
*   Shortest path on Fifths Graph: 6 steps (Tritone distance).
*   Shortest path on a Riemannian Graph: 2 steps (PL transformation).

By visualizing harmony as a graph, we can write algorithms that "walk" through key changes, never getting lost, simply following the edges of consonance.
"""

