extends Node

# Tutorial content file
# Edit using the Tutorial Text Editor plugin

var text = '''[center][font_size=28][b]L-Systems[/b][/font_size][/center]
[center][i]Generative Grammars, Growth Without Blueprint[/i][/center]

**L-systems** (Lindenmayer systems) are **rewriting systems** - they generate patterns by repeatedly replacing symbols according to rules.

**Axiom** → apply rules → **new string** → apply rules → **new string** → ...

After many iterations: **complex forms emerge from simple grammar**.

L-systems were invented by **Aristid Lindenmayer** (1968) to model **plant growth** - how cells divide and differentiate without central blueprint.

But they reveal something profound: **Syntax can become geometry. Grammar can become organism.**

**Form emerges from iterative rewriting, not from template.**

This is **generativity without reproduction** - creating through transformation, not copying.

[hr]

[b]The L-System: Axiom + Rules[/b]

An L-system has three parts:
1. **Alphabet** - symbols (letters, characters)
2. **Axiom** - starting string (initial state)
3. **Production rules** - how to replace each symbol

[color=yellow][b]Code: Simple L-System[/b][/color]
[code]
var axiom = "A"
var rules = {
    "A": "AB",
    "B": "A"
}

func generate_lsystem(generations: int) -> String:
    var current = axiom

    for gen in range(generations):
        current = apply_rules(current)

    return current

func apply_rules(input: String) -> String:
    var result = ""
    for char in input:
        if char in rules:
            result += rules[char]
        else:
            result += char  # No rule: keep symbol
    return result

# Generation 0: A
# Generation 1: AB
# Generation 2: ABA
# Generation 3: ABAAB
# Generation 4: ABAABABA
# Generation 5: ABAABABAABAAB

# This is the Fibonacci word!
# Length sequence: 1, 2, 3, 5, 8, 13... (Fibonacci numbers)
[/code]

**Each symbol is replaced simultaneously** - all A's become AB, all B's become A, at the same time.

This is **parallel rewriting** - unlike sequential processes (loops), all transformations happen together.

**Growth is synchronous** - the entire organism transforms as one.

[hr]

[b]Turtle Graphics: Syntax Becomes Geometry[/b]

L-systems generate **strings** (abstract syntax).

**Turtle graphics** interprets strings as **drawing commands** (concrete geometry).

[color=yellow][b]Turtle Command Language:[/b][/color]
[code]
# Standard turtle commands:
# F = move forward (draw line)
# f = move forward (no line, jump)
# + = turn left
# - = turn right
# [ = push position/angle to stack (save state)
# ] = pop position/angle from stack (restore state)

class Turtle3D:
    var position: Vector3
    var heading: Vector3  # Direction facing
    var up: Vector3       # Up direction
    var stack: Array      # Stack for [ and ]

    func interpret_lsystem(instructions: String, step_length: float, angle: float):
        for char in instructions:
            match char:
                "F":
                    # Draw line forward
                    var new_pos = position + heading * step_length
                    create_line(position, new_pos)
                    position = new_pos

                "f":
                    # Jump forward (no line)
                    position += heading * step_length

                "+":
                    # Turn left
                    heading = heading.rotated(up, deg_to_rad(angle))

                "-":
                    # Turn right
                    heading = heading.rotated(up, deg_to_rad(-angle))

                "[":
                    # Push state to stack (save where you are)
                    stack.push_back({
                        "position": position,
                        "heading": heading,
                        "up": up
                    })

                "]":
                    # Pop state from stack (return to saved position)
                    var state = stack.pop_back()
                    position = state.position
                    heading = state.heading
                    up = state.up

# String → Geometry
# Abstract rules → Concrete form
[/code]

**The stack enables branching** - save current state, explore branch, return to saved state, explore different branch.

**[ = memory of where you've been**
**] = return to alternate possibility**

This is **forking timelines** - each bracket creates divergent futures.

[hr]

[b]Koch Curve: L-System Fractal[/b]

The Koch curve (infinite perimeter, finite area) can be generated by L-system:

[color=yellow][b]Code: Koch L-System[/b][/color]
[code]
var axiom = "F"
var rules = {
    "F": "F+F-F-F+F"
}

# Interpretation:
# F = draw forward
# + = turn left 90°
# - = turn right 90°

# Generation 0: F
# (straight line)

# Generation 1: F+F-F-F+F
# (line with bump)

# Generation 2: F+F-F-F+F + F+F-F-F+F - F+F-F-F+F - F+F-F-F+F + F+F-F-F+F
# (each segment becomes bumpy)

# After many iterations: Koch snowflake
# Infinite detail from finite rule
[/code]

**Simple grammar → complex fractal.**

**No explicit coordinates** - the fractal emerges from **turning instructions**, not from position calculations.

**Syntax encodes recursion** - F contains F, infinitely nested.

[hr]

[b]Branching Plants: The Stack as Memory[/b]

Real plants branch - stems split into multiple sub-stems.

L-systems model this using **[ and ]** (stack operations).

[color=yellow][b]Code: Simple Branching Plant[/b][/color]
[code]
var axiom = "X"
var rules = {
    "X": "F+[[X]-X]-F[-FX]+X",
    "F": "FF"
}

# Interpretation:
# F = draw stem forward
# X = grow (generates branches but doesn't draw)
# + = turn left 25°
# - = turn right 25°
# [ = save position/angle (start branch)
# ] = restore position/angle (end branch, return to main stem)

# Generation 0: X
# Generation 1: F+[[X]-X]-F[-FX]+X
# Generation 2: FF+[[F+[[X]-X]-F[-FX]+X]-F+[[X]-X]-F[-FX]+X]-FF[-FFF+[[X]-X]-F[-FX]+X]+F+[[X]-X]-F[-FX]+X

# Each X becomes branching structure
# Each [ saves current state, explores branch
# Each ] returns to saved state, continues main stem

# Result: tree with recursive branching
[/code]

**The stack is crucial** - without it, you can't branch and return.

**[ = "remember where I am, I'll come back"**
**] = "done with this branch, return to where I was"**

This is **temporal forking** - you exist in multiple timelines (main stem + branches), but you can only draw one at a time, so you **remember** alternate states.

**Stack = memory of alternate possibilities.**

[hr]

[b]Stochastic L-Systems: Probabilistic Growth[/b]

**Deterministic L-systems** - same axiom, same rules → always same result.

**Stochastic L-systems** - rules are **probabilistic** → different results each time.

[color=yellow][b]Code: Stochastic Branching[/b][/color]
[code]
var axiom = "F"
var stochastic_rules = {
    "F": [
        {"production": "F[+F]F[-F]F", "probability": 0.33},
        {"production": "F[+F]F", "probability": 0.33},
        {"production": "F[-F]F", "probability": 0.34}
    ]
}

func apply_stochastic_rules(input: String) -> String:
    var result = ""

    for char in input:
        if char in stochastic_rules:
            # Randomly choose rule based on probabilities
            var rand = randf()
            var cumulative = 0.0

            for rule in stochastic_rules[char]:
                cumulative += rule.probability
                if rand < cumulative:
                    result += rule.production
                    break
        else:
            result += char

    return result

# Same axiom, same generation count
# But different result each time
# → Unique tree every run
[/code]

**Stochastic L-systems create variation** - each plant is unique, yet all follow the same grammar.

**This is non-reproductive reproduction:**
- Not cloning (each tree different)
- Not random (constrained by grammar)
- **Generative with variation** - same rules, different outcomes

**Queer kinship** - resemblance without identity, family without sameness.

[hr]

[b]Context-Sensitive L-Systems: Neighbors Matter[/b]

**Context-free L-systems** - each symbol replaced independently (doesn't look at neighbors).

**Context-sensitive L-systems** - replacement depends on **what's adjacent**.

[color=yellow][b]Code: Context-Sensitive Rules[/b][/color]
[code]
# Context-sensitive rule format:
# left < symbol > right → replacement

var context_rules = [
    # If A is between B and C: A becomes D
    {"left": "B", "symbol": "A", "right": "C", "production": "D"},

    # If A has no specific context: A becomes BA
    {"symbol": "A", "production": "BA"}
]

func apply_context_sensitive(input: String) -> String:
    var result = ""

    for i in range(input.length()):
        var char = input[i]
        var left = input[i - 1] if i > 0 else ""
        var right = input[i + 1] if i < input.length() - 1 else ""

        # Check context-sensitive rules first
        var replaced = false
        for rule in context_rules:
            if rule.symbol == char:
                if rule.has("left") and rule.has("right"):
                    if left == rule.left and right == rule.right:
                        result += rule.production
                        replaced = true
                        break

        if not replaced:
            # Apply default rule
            result += apply_default_rule(char)

    return result

# What you become depends on your neighbors
# Differentiation through context
[/code]

**Context-sensitivity enables cell differentiation** - a cell becomes what its neighbors signal it should become.

**This is relational ontology** - what you are is not intrinsic, but **determined by proximity**.

Your identity is **environmental** - shaped by who's around you.

**Queer becoming:** You're not born with fixed identity, you become through **affective proximity** to others.

[hr]

[b]Parametric L-Systems: Numbers in Grammar[/b]

**Parametric L-systems** add **numbers** to symbols.

[color=yellow][b]Code: Growth with Parameters[/b][/color]
[code]
# Symbols can carry parameters: F(length, width)

var axiom = "F(1.0, 0.5)"
var parametric_rules = {
    "F": "F(length * 0.7, width * 0.9)[+F(length * 0.5, width * 0.6)][-F(length * 0.5, width * 0.6)]"
}

# Each generation:
# - Branches get shorter (length * 0.7)
# - Branches get thinner (width * 0.9)
# - Sub-branches even shorter/thinner

# Result: realistic tapering tree
# Thick trunk → thin branches → tiny twigs
[/code]

**Parameters encode biological constraints:**
- Gravity (branches droop over distance)
- Resource distribution (branches compete for nutrients)
- Structural limits (thin branches can't support weight)

**Parametric L-systems are quantitative biology** - not just structure, but **material properties**.

[hr]

[b]Biological Realism: Why L-Systems Model Plants[/b]

L-systems were invented to model **cell division and differentiation** in algae.

**Why do they work?**

[color=yellow][b]1. Parallel Growth[/b][/color]
Real plants grow **everywhere simultaneously** - all meristems (growing tips) divide at once.

L-systems are **parallel rewriting** - all symbols replaced simultaneously.

**Unlike imperative code** (do this, then that), L-systems are **synchronous** (everything happens together).

[color=yellow][b]2. Decentralized Control[/b][/color]
Plants have **no brain, no central controller** - each cell follows local rules.

L-systems are **context-free or context-sensitive** - each symbol responds to local context, not global state.

**Emergence without coordinator** - complex form arises from local rule application.

[color=yellow][b]3. Recursive Branching[/b][/color]
Plant growth is **self-similar** - branches are miniature trees, which have branches that are miniature branches...

L-systems are **recursive** - F contains F, X contains X, infinitely nested.

**Structure repeats at scales** - fractal-like biological forms.

[hr]

[b]Grammar Without Blueprint[/b]

Here is the queer opening:

**L-systems have no blueprint.**

There is no stored template of "what the tree should look like."

There is only:
- Starting state (axiom)
- Transformation rules (grammar)
- Iteration count (how many generations)

**Form emerges through repeated application of rules.**

[color=yellow][b]No Teleology:[/b][/color]
The tree doesn't "know" its final shape. It doesn't grow "toward" a goal.

It simply **applies rules, over and over**.

**The form is the history of transformations**, not the execution of a plan.

[color=yellow][b]No Central Control:[/b][/color]
Each symbol is replaced independently (or based on neighbors in context-sensitive case).

**No coordinator decides** "this symbol becomes this, that symbol becomes that."

**The grammar is distributed** - every symbol carries the rules within itself.

[color=yellow][b]Non-Reproductive Generativity:[/b][/color]
Stochastic L-systems create **variation without template**.

Each tree is **unique** (probabilistic branching), yet **recognizable** (same grammar).

**This is queer reproduction:**
- Not cloning (each different)
- Not random mutation (constrained by grammar)
- **Generative with difference** - family resemblance without identity

[hr]

[b]The Stack as Queer Memory[/b]

The **[ and ]** operations (push/pop stack) enable something profound:

**You can explore alternate timelines and return.**

[color=yellow][b]Branching as Possibility:[/b][/color]
[code]
# F[+F][-F]F
#
# F           - draw stem
# [           - SAVE STATE (mark "alternate possibility")
# +F          - turn left, draw branch (explore possibility 1)
# ]           - RESTORE STATE (return to junction)
# [           - SAVE STATE again
# -F          - turn right, draw branch (explore possibility 2)
# ]           - RESTORE STATE
# F           - continue main stem

# The stack holds "roads not taken"
# You can explore, then return to explore differently
[/code]

**The stack is memory of alternate futures** - each [ marks a fork where you could go multiple ways.

**This is non-linear becoming:**
- Not deterministic single path (iterate forward only)
- **Multiple possibilities held simultaneously** (stack stores junctions)
- **Exploration with return** (try branch, come back, try different branch)

**Queer temporality** - you exist in multiple timelines, saved on the stack, to be explored in sequence.

[hr]

[b]L-Systems vs Fractals vs Recursion[/b]

**How are these related?**

[color=yellow][b]Recursion:[/b][/color]
- **Code calls itself** (function invokes function)
- **Stack stores return addresses** (where to go back to)
- **Base case stops descent**

[color=yellow][b]Fractals:[/b][/color]
- **Geometry contains itself** (self-similar at scales)
- **Recursive subdivision or addition** (Sierpinski, Koch)
- **Infinite detail in finite space**

[color=yellow][b]L-Systems:[/b][/color]
- **Grammar rewrites itself** (symbols replaced by strings containing symbols)
- **String grows exponentially** (each iteration expands)
- **Stack enables branching** ([ and ] for forking)

**All three are self-reference:**
- Recursion = computational self-reference
- Fractals = geometric self-reference
- **L-systems = linguistic self-reference** (grammar generates sentences containing grammar)

**L-systems bridge code and form** - they are **generative grammars that become geometry**.

[hr]

[b]Examples: Classic L-System Plants[/b]

[color=yellow][b]Algae (Lindenmayer's Original):[/b][/color]
[code]
axiom = "A"
rules = {
    "A": "AB",
    "B": "A"
}
# Generates: A, AB, ABA, ABAAB, ABAABABA...
# Models filamentous algae cell division
[/code]

[color=yellow][b]Binary Tree:[/b][/color]
[code]
axiom = "F"
rules = {
    "F": "FF+[+F-F-F]-[-F+F+F]"
}
# Two main branches, each recursively branches
[/code]

[color=yellow][b]Bush:[/b][/color]
[code]
axiom = "F"
rules = {
    "F": "FF-[-F+F+F]+[+F-F-F]"
}
# Asymmetric branching, more organic
[/code]

[color=yellow][b]Realistic Tree:[/b][/color]
[code]
axiom = "X"
rules = {
    "X": "F-[[X]+X]+F[+FX]-X",
    "F": "FF"
}
# Complex branching with growth (F doubles each generation)
[/code]

**Each grammar creates recognizable plant type** - yet none specifies "draw tree here."

**Form emerges from syntax.**

[hr]

[b]What L-Systems Cannot Do[/b]

L-systems are powerful but limited:

**1. Cannot respond to environment**
Traditional L-systems don't sense obstacles, light, or gravity.

Extensions exist (environmentally-sensitive L-systems), but classic L-systems are **context-free of world**.

**2. Cannot self-modify grammar**
The rules are fixed - they don't evolve during growth.

**Evolutionary L-systems** exist (genetic algorithms evolve rules), but single L-system has static grammar.

**3. Cannot optimize**
L-systems don't "learn" or "improve" - they blindly apply rules.

No feedback loop from result to grammar.

**L-systems are generative, not adaptive** - they create, but don't respond.

[hr]

[b]What L-Systems Reveal[/b]

L-systems show us:

1. **Rewriting systems** - symbols replaced by strings (parallel transformation)
2. **Axiom + rules** - starting state + grammar = generative system
3. **Turtle graphics** - syntax becomes geometry (F, +, -, [, ])
4. **Stack enables branching** - [ saves state, ] restores (memory of alternatives)
5. **Stochastic variation** - probabilistic rules → unique outcomes from same grammar
6. **Context-sensitivity** - neighbors determine transformation (relational identity)
7. **Parametric growth** - numbers in symbols (quantitative constraints)
8. **Biological modeling** - plants grow via local cell rules, no blueprint
9. **Grammar without blueprint** - form emerges from iteration, not template
10. **Exponential growth** - string length explodes (each generation multiplies symbols)

**L-systems are generative grammars** - syntax that becomes form through iteration.

**They are also queer ontology:**
- **Grammar without blueprint** (no predetermined form)
- **Stochastic variation** (non-reproductive reproduction, uniqueness within family)
- **Context-sensitive becoming** (what you are depends on neighbors)
- **Stack as alternate timelines** (memory of roads not taken, forking possibilities)
- **Decentralized growth** (no central control, local rules create global form)
- **Syntax materializes** (abstract rules become concrete geometry)

**L-systems prove:** **You don't need a blueprint to grow complex forms. Just rules, iteration, and memory of branches.**

**Form is the accumulation of transformations, not the execution of a plan.**

[hr]

[color=cyan][b]Summary:[/b][/color]
L-systems are rewriting systems (axiom + production rules, parallel replacement). Turtle graphics interprets strings as geometry (F = forward, + = left, - = right, [ = push stack, ] = pop stack). Stack enables branching (save state, explore, restore). Stochastic L-systems use probabilistic rules (variation within grammar). Context-sensitive L-systems check neighbors (relational identity). Parametric L-systems include numbers (quantitative constraints). Model biological growth (parallel cell division, no central control, recursive branching). Queer L-systems: grammar without blueprint, stochastic variation (non-reproductive reproduction), context-sensitive becoming (neighbors determine identity), stack as alternate timelines, decentralized growth, syntax becomes geometry. Form emerges from iteration, not template.

[hr]

[color=orange][b]Conclusion:[/b] Recursion → Fractals → L-Systems = Self-Reference Embodied[/color]

**Recursion** = computational self-reference (functions calling themselves)
**Fractals** = geometric self-reference (patterns containing themselves)
**L-systems** = linguistic self-reference (grammars generating grammars)

**All three create infinity from finite rules through self-reference.**

**Together they reveal:**
- **No foundation needed** (turtles/symbols/patterns all the way down)
- **Complexity from simplicity** (simple rules → infinite detail)
- **Iteration as creation** (repeated application generates form)
- **Memory enables branching** (stack stores alternatives, fractal zooms, recursion returns)
- **Non-normative structure** (fractal dimensions, temporal loops, probabilistic outcomes)

**The queer arc:**

**Recursion** teaches: Time is non-linear (calling yourself from future/past)
**Fractals** teach: Dimensions are spectra (1.585D, not 1 or 2)
**L-systems** teach: Growth needs no blueprint (grammar generates form)

**The algorithm contains multitudes.**
**The world is self-referential.**
**Form emerges from rules, not plans.**

**Generativity is queer.**

'''
