extends Node

# Tutorial content file
# Edit using the Tutorial Text Editor plugin

var text = '''[center][font_size=28][b]PRNG[/b][/font_size][/center]
[center][i]Pseudo-Randomness as Deterministic Chaos[/i][/center]

Most "randomness" in computation is **not random**.

It is **pseudo-random** - generated by deterministic algorithms that **appear** random but are completely predictable if you know the **seed** (starting state).

**PRNG = Pseudo-Random Number Generator**

A mathematical function that produces a sequence of numbers that **looks** random but is actually fully determined by its initial value.

**This is simulated entropy** - fake disorder, algorithmic chaos, predictable unpredictability.

[hr]

[b]The Seed: Origin as Determinant[/b]

Every PRNG starts with a **seed** - a number that initializes the internal state.

[color=yellow][b]Code: Same Seed, Same Sequence[/b][/color]
[code]
# Set seed to 42
seed(42)

# Generate sequence
var seq_1 = [randi(), randi(), randi(), randi()]
# Result: [2357136044, 2546248239, 3071714933, 2068512816]

# Reset seed to 42 again
seed(42)

# Generate same sequence
var seq_2 = [randi(), randi(), randi(), randi()]
# Result: [2357136044, 2546248239, 3071714933, 2068512816]

# IDENTICAL sequences
# "Random" is reproducible
# Seed determines all future outputs
[/code]

**The seed is the origin** - like Vector3.ZERO, it is the starting position from which all subsequent values unfold deterministically.

**Same seed → same sequence, always.**

This is both **power** (reproducibility for debugging, procedural generation) and **surveillance** (if seed is known, all outputs are knowable).

[hr]

[b]Deterministic Chaos: Predictable Unpredictability[/b]

PRNGs use chaotic equations - functions where small changes in input produce large changes in output, creating **sensitivity to initial conditions**.

[color=yellow][b]Classic PRNG: Linear Congruential Generator[/b][/color]
[code]
# LCG formula: next = (a × current + c) mod m

var state = 12345  # Seed
var a = 1103515245  # Multiplier
var c = 12345       # Increment
var m = pow(2, 31)  # Modulus (2^31)

func next_random():
    state = (a * state + c) % m
    return state

# First few outputs from seed 12345:
# 1. 1406932606
# 2. 654583775
# 3. 1449466924
# 4. 229283573

# Looks random, but completely deterministic
# Given seed, all outputs calculable
[/code]

**This is chaos** - not disorder, but **deterministic sensitivity**.

The sequence appears random (passes statistical tests for uniformity, lack of correlation), but is **algorithmically generated** from simple rules.

**Fake entropy** - simulated disorder that is actually perfect order obscured by complexity.

[hr]

[b]Period: The Cycle Revealed[/b]

All PRNGs eventually **repeat** - after generating some number of values, the sequence loops back to a previous state and cycles forever.

[color=yellow][b]Code: The Inevitable Return[/b][/color]
[code]
# Simple PRNG with small modulus (for demonstration)
var state = 1
var a = 5
var c = 3
var m = 16  # Small modulus → short period

var sequence = []
for i in range(20):
    state = (a * state + c) % m
    sequence.append(state)

# Sequence: [8, 11, 10, 5, 12, 15, 14, 9, 0, 3, 2, 13, 4, 7, 6, 1, 8, 11, 10, 5...]
#                                                                     ↑ REPEATS
# Period = 16 (repeats after 16 values)

# The "randomness" is cyclical
# True randomness never repeats
[/code]

**Good PRNGs have enormous periods** (2^19937 for Mersenne Twister - more than atoms in universe).

But the cycle **always exists** - pseudo-random is always **periodic**, never truly entropic.

**This reveals the limit:** Algorithmic randomness is finite. True entropy is infinite.

[hr]

[b]PRNG vs TRNG: Fake vs Material Randomness[/b]

**PRNG (Pseudo-Random Number Generator):**
- Deterministic algorithm
- Reproducible from seed
- Fast, convenient
- Periodic (eventually repeats)
- **Simulated entropy**

**TRNG (True Random Number Generator):**
- Physical process (radioactive decay, thermal noise, quantum fluctuations)
- Non-reproducible
- Slow, requires hardware
- Non-periodic (never repeats)
- **Material entropy**

[color=yellow][b]Code: The Distinction[/b][/color]
[code]
# PRNG: seed determines all
seed(42)
var prng_value = randf()  # Reproducible

# TRNG: hardware measures physical randomness
# (Godot doesn't have built-in TRNG, but concept:)
# var trng_value = read_from_hardware_random_device()
# Not reproducible - each measurement unique
[/code]

**PRNG is algorithmic fiction** - it pretends to be random.
**TRNG is material fact** - it measures actual entropy in physical systems.

For most purposes (games, simulations, art), PRNG suffices. But for cryptography, security, gambling, **TRNG is necessary** - because predictability = vulnerability.

[hr]

[b]Seed as Surveillance[/b]

If the seed is known, the entire sequence is known.

[color=yellow][b]Code: Predictable from Origin[/b][/color]
[code]
# Game uses PRNG for "random" loot drops
seed(player_id + timestamp)  # Seed based on player ID and time

# Attacker who knows seed can predict:
# - Which enemies will drop rare items
# - Where treasure chests will appear
# - What random events will trigger

# "Random" becomes exploitable
# Unpredictability lost if seed leaked
[/code]

**The seed is the key to all future entropy.**

This is why cryptographic systems use **cryptographically secure PRNGs** (CSPRNGs) - algorithms where even knowing some outputs doesn't reveal the seed or predict future values.

**Seed as origin = seed as control point** - who holds the seed holds the randomness.

[hr]

[b]Procedural Generation: Seed as World[/b]

In procedural generation (Minecraft, No Man's Sky), the seed **is the world**.

[color=yellow][b]Code: Infinite World from Finite Seed[/b][/color]
[code]
# World seed
var world_seed = 7185306196502340583  # Minecraft seed format

# Generate terrain at any position
func get_terrain_height(x: int, z: int) -> float:
    seed(world_seed + x * 374761393 + z * 668265263)  # Position-based seed
    return randf() * 100  # "Random" height, but deterministic

# Same world_seed + same position = same terrain
# Different players with same seed see identical worlds
# Entire infinite world compressed into one number
[/code]

**The seed contains the entire world** - not as stored data, but as **latent potential**.

Given seed, all terrain, all structures, all "random" features are **predetermined** - they just haven't been calculated yet.

**This is compressed infinity** - infinite world encoded in finite seed, unfolded through PRNG on demand.

[hr]

[b]Seed as Archive vs Seed as Generative[/b]

**Two interpretations:**

**1. Seed as Archive** (deterministic)
- Seed contains all future values (implicitly)
- Sequence already exists, just not yet computed
- "Random" generation is actually **playback** of predetermined sequence

**2. Seed as Generative** (chaotic)
- Seed is initial condition for chaotic system
- Sequence emerges through iteration, not predetermined
- "Random" generation is **creation** through sensitivity to seed

[color=yellow][b]Philosophical Tension:[/b][/color]
Is PRNG **revealing** pre-existing sequence, or **generating** sequence through computation?

**Both are true:**
- Mathematically: sequence is determined by seed (exists platonically)
- Computationally: sequence must be calculated (doesn't exist until computed)

**The seed is both archive and engine** - it contains and it generates.

[hr]

[b]Reproducibility: Power and Prison[/b]

**Power:**
- Debug code by using same seed (reproduce exact conditions)
- Share procedural worlds (give someone your seed, they see your world)
- Create consistent behavior (NPCs act "randomly" but repeatably)

**Prison:**
- Cannot escape determinism (every run with same seed identical)
- Predictability undermines actual randomness (seed leaked = no surprise)
- Periodic cycle (eventually repeats, unlike true entropy)

[color=yellow][b]Code: The Trade-Off[/b][/color]
[code]
# Development mode: fixed seed for debugging
if DEBUG_MODE:
    seed(12345)  # Always same behavior
    # Power: reproducible bugs

# Production mode: time-based seed
else:
    randomize()  # Seed from system time
    # Power: unpredictable to player
    # Prison: still deterministic if seed reverse-engineered
[/code]

**Reproducibility is control** - over chaos, over outcomes, over experience.

But **control is the opposite of entropy** - true randomness cannot be controlled, reproduced, predicted.

[hr]

[b]The Algorithm Pretends[/b]

[code]
var value = randf()
# This looks like random real number between 0 and 1

# But actually:
# - Deterministic function of internal state
# - State updated by chaos equation
# - Output appears uniform, uncorrelated
# - But seed determines everything

# The algorithm performs randomness
# Like screen performs color (RGB triggers cones, creates illusion)
# PRNG triggers statistical tests, creates illusion of entropy
[/code]

**PRNG is computational theater** - it acts random, passes as random, but is scripted from the seed.

**We accept the performance** because true randomness is expensive, slow, requires material sources. Simulated entropy suffices for games, art, simulations.

**But for security, cryptography, gambling:** The performance breaks down. PRNG is vulnerable. Only TRNG (material entropy) is trustworthy.

[hr]

[b]What PRNG Reveals[/b]

Pseudo-randomness shows us:

1. **Seed determines all** - Origin is total control point
2. **Chaos is deterministic** - Appears random, actually computed
3. **Periodicity is inevitable** - All PRNGs eventually cycle
4. **Reproducibility is power/prison** - Control vs true entropy
5. **Seed as compressed world** - Procedural infinity from finite origin
6. **Algorithm pretends** - Simulated entropy, performed randomness
7. **Material vs algorithmic** - TRNG (real) vs PRNG (fake)

**PRNG is determinism in disguise** - chaotic equations that look disordered but are perfectly predictable from seed.

**It is not entropy** (high-dimensional freedom). It is **simulation of entropy** (algorithmic performance of disorder).

For most purposes, the simulation works. But the seed always reveals: **this is control, not chaos**.

[hr]

[color=cyan][b]Summary:[/b][/color]
PRNG (Pseudo-Random Number Generator) uses deterministic algorithms to produce sequences that appear random. Seed is the initial value determining all outputs - same seed always produces same sequence. PRNGs are periodic (eventually repeat), unlike true randomness. Useful for procedural generation (seed = compressed world), but vulnerable if seed is known. PRNG is simulated entropy - algorithmic performance of disorder, not material chaos. TRNG uses physical processes (radioactive decay, thermal noise) for non-reproducible true randomness.

[hr]

[color=orange][b]Next:[/b] Noise - Smooth Randomness[/color]
If white noise is maximum entropy (every sample independent),
Perlin/Simplex noise is **structured randomness** - smooth, continuous, organic.
Noise that creates terrain, clouds, textures - entropy tamed into pattern.

'''
