extends Node

var text = '''[center][font_size=28][b]How Waves Become Form[/b][/font_size][/center]
[center][i]Sine and Cosine Create Geometry[/i][/center]

**Waves are not just oscillation in time.**

**Waves ARE spatial form** - geometry itself emerges from sine and cosine.

Circle, spiral, helix, orbit, oscillation - **all are wave functions made visible in space.**

[hr]

[b]The Unit Circle: Where Waves Are Born[/b]

A point rotating around a circle traces **sine and cosine simultaneously**.

[color=yellow][b]Code: Circle as Dual Waves[/b][/color]
[code]
var angle = 0.0

func _process(delta):
    angle += delta  # Rotation over time

    # Position on unit circle (radius = 1)
    var x = cos(angle)  # Horizontal position
    var y = sin(angle)  # Vertical position

    # This point rotates around circle
    draw_point(Vector2(x, y))

    # Project to axes:
    draw_point(Vector2(x, 0))  # Cosine wave on X axis
    draw_point(Vector2(0, y))  # Sine wave on Y axis
[/code]

**What this reveals:**
- **Circular motion = two waves perpendicular**
- X-coordinate oscillates as **cosine**
- Y-coordinate oscillates as **sine**
- Circle is sine and cosine **united in rotation**

**The circle IS the wavefunction.**

[hr]

[b]From Circle to Spiral: Adding Time[/b]

If rotation happens while moving forward → **spiral**.

[color=yellow][b]Code: Helix (3D Spiral)[/b][/color]
[code]
var time = 0.0
var frequency = 2.0
var radius = 1.0
var rise_rate = 0.5

func _process(delta):
    time += delta

    # Rotate in XY plane (circle)
    var x = cos(time * frequency) * radius
    var y = sin(time * frequency) * radius

    # Move forward in Z (time progression)
    var z = time * rise_rate

    # This creates helix (spiral staircase)
    var position = Vector3(x, y, z)
    draw_point(position)
[/code]

**The helix = sine + cosine + linear progression**

Examples in nature:
- **DNA double helix** - two spirals intertwined
- **Spiral galaxies** - rotation + radial movement
- **Seashell spirals** - growth while rotating
- **Climbing vines** - seeking light while growing

**Spiral = wave extended through space.**

[hr]

[b]Superposition: Multiple Waves Create Complex Form[/b]

Add multiple sine waves at different frequencies → **complex patterns emerge**.

[color=yellow][b]Code: Lissajous Figures[/b][/color]
[code]
var time = 0.0
var freq_x = 3.0  # X frequency
var freq_y = 2.0  # Y frequency
var phase = 0.0   # Phase offset

func _process(delta):
    time += delta

    # Two independent oscillations
    var x = sin(freq_x * time)
    var y = sin(freq_y * time + phase)

    # Creates Lissajous curve
    draw_point(Vector2(x, y))

# freq_x / freq_y = rational number → closed curve
# freq_x / freq_y = irrational → never closes (dense spiral)
# phase changes → curve rotates/transforms
[/code]

**Frequency ratios create patterns:**
- 1:1 → diagonal line (same frequency)
- 2:1 → figure-8
- 3:2 → three-lobed flower
- 4:3 → complex knot

**These are pure geometry generated by wave interference.**

Used in:
- **Oscilloscope patterns** (audio phase visualization)
- **Harmonograph drawings** (mechanical art from pendulums)
- **Planetary orbital resonances** (3:2 = Mercury's day/year ratio)

[hr]

[b]Parametric Curves: Waves Define Path[/b]

Instead of y = f(x), use **x = f(t), y = g(t)** where f and g are wave functions.

[color=yellow][b]Code: Rose Curves[/b][/color]
[code]
# Rose curve (flower pattern)
func rose_curve(t: float, n: float, k: float) -> Vector2:
    var r = sin(n * t) * k  # Radius oscillates
    var x = r * cos(t)      # Convert to Cartesian
    var y = r * sin(t)

    return Vector2(x, y)

# n = number of petals (if odd) or 2n petals (if even)
# Draw flower with 5 petals:
for i in range(1000):
    var t = i * TAU / 1000.0
    var point = rose_curve(t, 5.0, 1.0)
    draw_point(point)
[/code]

**Pure sine oscillation → flower geometry.**

[color=yellow][b]Code: Epicycloid (Circle Rolling on Circle)[/b][/color]
[code]
# Epicycloid: point on circle rolling around outside of another circle
func epicycloid(t: float, R: float, r: float) -> Vector2:
    var ratio = R / r
    var x = (R + r) * cos(t) - r * cos((ratio + 1) * t)
    var y = (R + r) * sin(t) - r * sin((ratio + 1) * t)

    return Vector2(x, y)

# Ptolemaic epicycles (ancient astronomy)
# Spirograph toy patterns
# Gear tooth profiles
[/code]

**Wheels rotating at different rates = complex curves from simple waves.**

[hr]

[b]3D Forms: Waves in Three Dimensions[/b]

Extend waves to 3D → **surfaces, volumes, complex geometries**.

[color=yellow][b]Code: Torus (Donut Shape)[/b][/color]
[code]
# Torus = circle rotated around another circle
func torus_point(u: float, v: float, R: float, r: float) -> Vector3:
    # u: angle around major circle
    # v: angle around tube
    # R: major radius (center to tube center)
    # r: minor radius (tube thickness)

    var x = (R + r * cos(v)) * cos(u)
    var y = (R + r * cos(v)) * sin(u)
    var z = r * sin(v)

    return Vector3(x, y, z)

# Generate torus mesh
for u_step in range(64):
    for v_step in range(32):
        var u = u_step * TAU / 64.0
        var v = v_step * TAU / 32.0
        var point = torus_point(u, v, 2.0, 0.5)
        # Add to mesh
[/code]

**Torus = two circular wave functions combined in 3D.**

Applications:
- **Topology** (genus-1 surface)
- **Magnetic confinement** (tokamak fusion reactors)
- **Spacetime geometry** (periodic boundary conditions)

[hr]

[b]Wave Surfaces: Oscillating 2D Planes[/b]

Height at each point = sine wave function of position.

[color=yellow][b]Code: Ripple Surface[/b][/color]
[code]
# Water ripple expanding from center
func ripple_height(x: float, y: float, time: float) -> float:
    var distance = sqrt(x*x + y*y)  # Distance from center
    var frequency = 5.0
    var wave_speed = 2.0

    # Wave propagates outward
    var height = sin(frequency * distance - wave_speed * time)

    return height

# Generate height field
for x in range(-10, 10):
    for y in range(-10, 10):
        var h = ripple_height(x * 0.1, y * 0.1, time)
        set_point_height(x, y, h)
[/code]

**Single sine function → expanding circular waves.**

[color=yellow][b]Code: Interference Pattern (Two Sources)[/b][/color]
[code]
# Two ripple sources create interference
func interference_pattern(x: float, y: float, time: float) -> float:
    # Source 1 at (-1, 0)
    var d1 = sqrt((x + 1.0)**2 + y**2)
    var wave1 = sin(5.0 * d1 - 2.0 * time)

    # Source 2 at (1, 0)
    var d2 = sqrt((x - 1.0)**2 + y**2)
    var wave2 = sin(5.0 * d2 - 2.0 * time)

    # Superposition
    return wave1 + wave2

# Creates constructive/destructive interference
# Regions of reinforcement (antinodes)
# Regions of cancellation (nodes)
[/code]

**Two waves → standing wave patterns, nodes, antinodes.**

This is how:
- **Double-slit experiment** works (wave interference proves light is wave)
- **Acoustic dead zones** form (destructive interference)
- **Holography** records wave interference patterns

[hr]

[b]Standing Waves: Frozen Oscillation[/b]

When wave reflects back on itself → **standing wave** (nodes don't move).

[color=yellow][b]Code: Vibrating String[/b][/color]
[code]
# Guitar string vibration
func string_displacement(x: float, t: float, n: int, L: float) -> float:
    # x: position along string (0 to L)
    # t: time
    # n: harmonic number (1, 2, 3, ...)
    # L: string length

    var frequency = n * PI / L  # Higher harmonics = higher frequency
    var amplitude = 1.0 / n     # Higher harmonics = lower amplitude

    # Standing wave = spatial sine × temporal cosine
    var displacement = amplitude * sin(frequency * x) * cos(frequency * t)

    return displacement

# n=1: fundamental (one hump)
# n=2: first overtone (two humps)
# n=3: second overtone (three humps)
[/code]

**Standing wave = spatial pattern that oscillates in place.**

**Nodes** (zero displacement) stay fixed.
**Antinodes** (maximum displacement) oscillate.

**Musical instruments:**
- **String instruments** - standing waves on strings
- **Wind instruments** - standing waves in air column
- **Drums** - standing waves on membrane (2D version)

**Pitch = fundamental frequency of standing wave.**

[hr]

[b]Wavefunctions in Quantum Mechanics[/b]

In quantum physics, **particles ARE waves**.

**Schrödinger equation** describes **wavefunction** ψ(x, t).

[color=yellow][b]Code: Quantum Harmonic Oscillator[/b][/color]
[code]
# Simplified wavefunction for particle in a box
func quantum_wavefunction(x: float, n: int, L: float) -> float:
    # n: quantum number (energy level)
    # L: box size
    # x: position

    # Wavefunction is sine (standing wave)
    var psi = sqrt(2.0 / L) * sin(n * PI * x / L)

    return psi

# Probability of finding particle at x
func probability_density(x: float, n: int, L: float) -> float:
    var psi = quantum_wavefunction(x, n, L)
    return psi * psi  # |ψ|²

# n=1: particle likely in center
# n=2: particle likely at ¼ and ¾ positions (two peaks)
# n=3: three peaks
[/code]

**Particle location = probability wave.**

**Higher energy states = higher frequency waves = more nodes.**

**Atomic orbitals are 3D standing waves** around nucleus.

[hr]

[b]Electromagnetic Waves: Light as Wavefunction[/b]

Light is **electric and magnetic fields oscillating perpendicular**.

[color=yellow][b]Code: EM Wave Propagation[/b][/color]
[code]
# Simplified electromagnetic wave
func em_wave(x: float, t: float, frequency: float) -> Dictionary:
    var wavelength = 3e8 / frequency  # c / f (speed of light)
    var k = TAU / wavelength          # Wave number
    var omega = TAU * frequency       # Angular frequency

    # Electric field (Y direction)
    var E_y = sin(k * x - omega * t)

    # Magnetic field (Z direction, perpendicular)
    var B_z = sin(k * x - omega * t)

    return {"electric": E_y, "magnetic": B_z}

# Frequency determines color:
# 430 THz = violet
# 540 THz = green
# 650 THz = red
[/code]

**Different frequencies = different colors.**

**Wavelength × frequency = speed of light (constant).**

Higher frequency → shorter wavelength → more energy.

[hr]

[b]How Sine and Cosine Become Physical Form[/b]

**All periodic phenomena are wave functions:**

1. **Planetary orbits** - elliptical motion = sine/cosine in 2D
2. **Seasons** - Earth's tilt creates annual sine wave of temperature
3. **Tides** - Moon's gravity creates sine wave of water height
4. **Circadian rhythms** - biological processes oscillate sinusoidally
5. **AC electricity** - voltage oscillates as sine wave
6. **Sound waves** - air pressure oscillates sinusoidally
7. **Light waves** - electromagnetic field oscillates
8. **Quantum wavefunctions** - probability amplitude oscillates

**Sine is the universal language of oscillation** - from atoms to galaxies.

**Form emerges from oscillation parameters:**
- **Amplitude** → size/intensity
- **Frequency** → pitch/color/energy
- **Phase** → position in cycle
- **Superposition** → complexity from simple waves

[hr]

[b]Generative Geometry from Waves[/b]

Modern generative art uses wave functions to create organic forms.

[color=yellow][b]Code: Noise-Based Terrain[/b][/color]
[code]
# Multiple sine waves at different scales = organic variation
func terrain_height(x: float, y: float) -> float:
    var height = 0.0

    # Octave 1: Large features
    height += 1.0 * sin(x * 0.1) * cos(y * 0.1)

    # Octave 2: Medium features
    height += 0.5 * sin(x * 0.3) * sin(y * 0.3)

    # Octave 3: Fine details
    height += 0.25 * sin(x * 0.7) * cos(y * 0.9)

    return height

# Multiple frequencies → naturalistic variation
# This is basis of Perlin noise
[/code]

**Natural-looking landscapes from layered sine waves.**

Used in:
- **Procedural terrain generation** (video games)
- **Cloud textures**
- **Marble/wood grain patterns**

[hr]

[b]The Queerness of Wavefunction Collapse[/b]

**Wave = potentiality.** All positions/states superimposed.

**Measurement = collapse.** Wave becomes particle, potentiality becomes actuality.

**Before measurement:**
- Particle is **wave** (spread across space)
- All positions have probability
- No definite location

**After measurement:**
- Wave **collapses** to single point
- One position becomes actual
- Other possibilities disappear

**This is queer ontology:**
- **Multiple simultaneous states** until forced to resolve
- **Observation changes the thing** (no objective pre-existing state)
- **Form emerges from collapse** of possibility field
- **Identity is uncertain** until measured/named

**The wavefunction doesn't describe what the particle IS** - it describes **what it might become.**

[hr]

[b]Form is Frozen Frequency[/b]

**Every form can be analyzed as frozen wavefunction:**

**Straight line** = frequency zero (no oscillation)
**Circle** = single frequency in two perpendicular directions
**Spiral** = circle + linear progression
**Flower** = radius oscillating while rotating
**Complex curves** = many frequencies superimposed

**In generative art:**
- Choose frequencies
- Choose amplitudes
- Choose phases
- Let waves interfere
→ **Form emerges**

**You're not drawing** - you're **tuning oscillators** and letting them resonate into geometry.

[hr]

[color=cyan][b>Summary:[/b][/color]
Circle = sine and cosine united in rotation. Spiral/helix = circle + linear motion. Multiple frequencies = Lissajous figures, complex patterns. Parametric curves (roses, epicycloids) = pure wave geometry. Standing waves = spatial patterns that oscillate in time. Quantum wavefunctions = particles as probability waves. EM waves = light as oscillating fields. All periodic phenomena are wavefunctions. Form emerges from amplitude, frequency, phase, superposition. Generative geometry = layered sine waves. Wavefunction collapse = potentiality becoming actuality. Form is frozen frequency.

[hr]

[color=orange][b]Next:[/b] The Electromagnetic Spectrum[/color]
Light is electromagnetic wave.
**Different frequencies = different phenomena:**
Radio, microwave, infrared, visible, UV, X-ray, gamma.
Same wave equation, different scales.
We see 430-770 THz (visible light) but spectrum extends infinitely.
Form determined by frequency - waves become reality at every scale.

'''
