# brouwer_choice_sequence.gd
# Brouwer's free choice sequences - unfinished infinite objects

extends Node3D
class_name BrouwerChoiceSequence

# @identity
# essence: a₁, a₂, a₃, ... , ?, ? — each term chosen freely, never completed
# desire: feel the openness of an infinite sequence that is always unfinished
# critical_parameter: time — the sequence unfolds perpetually, dots gently bobbing
# triggers: each dot fades in opacity toward the future; the question mark asserts genuine openness
# emerges: the intuition that infinity is a process, not a completed object
# needs: VR controls [missing] — could add ability to "choose" the next term
# relationships: depends on excluded_middle_demo (LEM rejection enables choice sequences); contrasts constructive_proof (witness vs process)
# truth: an infinite object that is never finished is not incomplete — it is the only honest way to talk about infinity

# ═══════════════════════════════════════════════════════════════════
# STAGE-2 DNA — axis `horizon`
# ═══════════════════════════════════════════════════════════════════

## How far ahead the sequence is drawn, and whether its future is open,
## branching, already determined, or closed off.
##
## The artifact's truth is a CONTRAST claim: an unfinished infinite object is
## honest, which only means anything with the dishonest versions standing in the
## same room. So the axis varies EXTENT and COUNT of the row — never a colour and
## never an alpha. At 0.03 m dots on a 0.70 m row inside a ~1.1 m AABB this is the
## smallest-featured object in its family; an opacity delta here is invisible at
## any framing the capture camera will choose.
##
##   question  the shipped row — 8 dots fading toward an ellipsis and a gold "?"
##   spread    the row forks into Brouwer's spread: a 14-node binary tree of
##             continuations, every one of them still standing there unchosen
##   law       14 dots, full opacity, threaded on a rail, with the rule that
##             generates them printed underneath — nothing was ever chosen
##   closed    the 8 dots stopped by a terminal bar and a closing bracket, the
##             question mark taken away — the completed infinite Brouwer denies
@export_enum("question", "spread", "law", "closed") var horizon: String = "question"

## Allow-list for the axis. Anything unrecognised falls back to the current value
## rather than stranding a placement with a half-built row.
const HORIZONS: PackedStringArray = ["question", "spread", "law", "closed"]

# --- shipped row geometry (identical for every value that draws the base row) ---
const DOT_RADIUS: float = 0.03
const DOT_PITCH: float = 0.10
const ROW_X0: float = -0.35
const ROW_COUNT: int = 8
const DOT_COLOR: Color = Color(0.4, 0.7, 1.0, 1.0)
const COOL_WHITE: Color = Color(0.86, 0.91, 1.0, 1.0)

# --- spread: the branching tree past the eighth dot ---
const BRANCH_RADIUS: float = 0.025
const BRANCH_ALPHA: float = 0.75  # unspecified by the spec; chosen so the fork reads
const ROD_RADIUS: float = 0.004
const BRANCH_X: PackedFloat32Array = [0.45, 0.57, 0.69]
const BRANCH_SPREAD: PackedFloat32Array = [0.06, 0.03, 0.015]
const BRANCH_SIGNS: PackedFloat32Array = [1.0, -1.0]
const SPREAD_Q_X: float = 0.84

# --- law: the lawlike sequence on rails ---
const LAW_COUNT: int = 14           # x = -0.35 .. +0.95 at 0.10 m pitch
const RAIL_RADIUS: float = 0.006
const RAIL_LENGTH: float = 1.40
const PLATE_SIZE: Vector3 = Vector3(0.30, 0.10, 0.02)
const PLATE_POS: Vector3 = Vector3(0.50, -0.10, 0.0)
const LAW_RULE_TEXT: String = "GENERATED BY\na(n) = 2n - 1"

# --- closed: the sequence handed over as a finished object ---
const BAR_SIZE: Vector3 = Vector3(0.02, 0.24, 0.02)
const BAR_X: float = 0.50
const BRACKET_X: float = 0.58

var _dots: Array[MeshInstance3D] = []
## Rest height of each dot. The shipped bob OVERWRITES position.y, which would
## slam the spread's branch dots onto the axis; bobbing around a recorded base
## keeps the tree and leaves the default row (all bases 0.0) untouched.
var _dot_base_y: Array[float] = []
var _label: Label3D
var _time: float = 0.0

## Every node THIS script added. Freeing get_children() instead would destroy the
## label plates, packaging and tag markers the grid parents onto us.
var _built_nodes: Array[Node] = []
var _built: bool = false

func _ready() -> void:
	_build_all()
	_built = true

# ═══════════════════════════════════════════════════════════════════
# BUILD
# ═══════════════════════════════════════════════════════════════════

func _build_all() -> void:
	_create_sequence()
	_create_label()

func _create_sequence() -> void:
	match horizon:
		"spread":
			_build_row(ROW_COUNT, true)
			_build_spread_tree()
			_build_ellipsis(0.5)
			_build_question(SPREAD_Q_X)
		"law":
			_build_row(LAW_COUNT, false)
			_build_rail()
			_build_rule_plate()
		"closed":
			_build_row(ROW_COUNT, true)
			_build_terminal_bar()
			_build_close_bracket()
		_:
			_build_row(ROW_COUNT, true)
			_build_ellipsis(0.5)
			_build_question(0.65)

## The row of terms. `fade` is the shipped alpha ramp 1.0 -> 0.30 across eight
## dots; `law` builds the same dots at full opacity because on a lawlike sequence
## no term is any less settled than the first.
func _build_row(count: int, fade: bool) -> void:
	for i in range(count):
		var alpha: float = 1.0
		if fade:
			alpha = 1.0 - i * 0.1
		var dot: MeshInstance3D = _make_dot(
			Vector3(ROW_X0 + i * DOT_PITCH, 0.0, 0.0), DOT_RADIUS, alpha)
		_dots.append(dot)
		_dot_base_y.append(0.0)

func _make_dot(pos: Vector3, radius: float, alpha: float) -> MeshInstance3D:
	var dot: MeshInstance3D = MeshInstance3D.new()
	var sphere: SphereMesh = SphereMesh.new()
	sphere.radius = radius
	sphere.height = radius * 2.0
	dot.mesh = sphere
	dot.position = pos

	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(DOT_COLOR.r, DOT_COLOR.g, DOT_COLOR.b, alpha)
	mat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	dot.material_override = mat
	_attach(dot)
	return dot

## Brouwer's spread: past the eighth term the row forks, and every continuation
## the sequence did not take is standing there beside the one it did. Three
## levels — 2, 4, 8 nodes — joined back to their parents by thin rods.
func _build_spread_tree() -> void:
	var parents: Array[Vector3] = [Vector3(ROW_X0 + (ROW_COUNT - 1) * DOT_PITCH, 0.0, 0.0)]
	for level in range(BRANCH_X.size()):
		var x: float = BRANCH_X[level]
		var spread: float = BRANCH_SPREAD[level]
		var children: Array[Vector3] = []
		for p in parents:
			for s in BRANCH_SIGNS:
				var c: Vector3 = Vector3(x, p.y + spread * s, 0.0)
				_build_rod(p, c)
				var dot: MeshInstance3D = _make_dot(c, BRANCH_RADIUS, BRANCH_ALPHA)
				_dots.append(dot)
				_dot_base_y.append(c.y)
				children.append(c)
		parents = children

func _build_rod(from_pos: Vector3, to_pos: Vector3) -> void:
	var d: Vector3 = to_pos - from_pos
	var length: float = d.length()
	if length <= 0.0001:
		return
	var rod: MeshInstance3D = MeshInstance3D.new()
	var cyl: CylinderMesh = CylinderMesh.new()
	cyl.top_radius = ROD_RADIUS
	cyl.bottom_radius = ROD_RADIUS
	cyl.height = length
	cyl.radial_segments = 6
	rod.mesh = cyl
	rod.position = from_pos + d * 0.5
	# CylinderMesh runs along +Y; rotate that onto d within the XY plane.
	rod.rotation.z = atan2(-d.x, d.y)

	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(DOT_COLOR.r, DOT_COLOR.g, DOT_COLOR.b, BRANCH_ALPHA)
	mat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	rod.material_override = mat
	_attach(rod)

## law: one rail through all fourteen terms. Nothing was chosen; the sequence
## was already lying on this line before anyone arrived.
func _build_rail() -> void:
	var rail: MeshInstance3D = MeshInstance3D.new()
	var cyl: CylinderMesh = CylinderMesh.new()
	cyl.top_radius = RAIL_RADIUS
	cyl.bottom_radius = RAIL_RADIUS
	cyl.height = RAIL_LENGTH
	cyl.radial_segments = 10
	rail.mesh = cyl
	rail.position = Vector3(ROW_X0 + (LAW_COUNT - 1) * DOT_PITCH * 0.5, 0.0, 0.0)
	rail.rotation.z = PI * 0.5

	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = COOL_WHITE
	rail.material_override = mat
	_attach(rail)

## law: the generating rule, printed. A free choice sequence has no such plate.
func _build_rule_plate() -> void:
	var plate: MeshInstance3D = MeshInstance3D.new()
	var box: BoxMesh = BoxMesh.new()
	box.size = PLATE_SIZE
	plate.mesh = box
	plate.position = PLATE_POS

	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(0.72, 0.76, 0.82, 1.0)
	plate.material_override = mat
	_attach(plate)

	var rule: Label3D = Label3D.new()
	rule.text = LAW_RULE_TEXT
	rule.pixel_size = 0.0015
	rule.font_size = 16
	rule.position = PLATE_POS + Vector3(0.0, 0.0, PLATE_SIZE.z * 0.5 + 0.002)
	rule.modulate = Color(0.10, 0.12, 0.16)
	_attach(rule)

## closed: the sequence stopped dead and handed over.
func _build_terminal_bar() -> void:
	var bar: MeshInstance3D = MeshInstance3D.new()
	var box: BoxMesh = BoxMesh.new()
	box.size = BAR_SIZE
	bar.mesh = box
	bar.position = Vector3(BAR_X, 0.0, 0.0)

	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = COOL_WHITE
	bar.material_override = mat
	_attach(bar)

func _build_close_bracket() -> void:
	var bracket: Label3D = Label3D.new()
	bracket.text = "]"
	bracket.pixel_size = 0.002
	bracket.font_size = 50  # ~0.10 m tall
	bracket.position = Vector3(BRACKET_X, 0.0, 0.0)
	bracket.modulate = COOL_WHITE
	_attach(bracket)

func _build_ellipsis(x: float) -> void:
	var ellipsis: Label3D = Label3D.new()
	ellipsis.text = "..."
	ellipsis.pixel_size = 0.002
	ellipsis.font_size = 20
	ellipsis.position = Vector3(x, 0.0, 0.0)
	_attach(ellipsis)

func _build_question(x: float) -> void:
	var q: Label3D = Label3D.new()
	q.text = "?"
	q.pixel_size = 0.002
	q.font_size = 24
	q.position = Vector3(x, 0.0, 0.0)
	q.modulate = Color(1, 0.8, 0.3)
	_attach(q)

func _create_label() -> void:
	_label = Label3D.new()
	_label.pixel_size = 0.001
	_label.font_size = 11
	_label.text = "CHOICE SEQUENCE\n\nInfinite, but never finished.\nEach term chosen freely.\nThe future is genuinely open."
	_label.position = Vector3(0, -0.2, 0)
	_attach(_label)

func _attach(n: Node) -> void:
	add_child(n)
	_built_nodes.append(n)

func _process(delta):
	_time += delta
	var n: int = mini(_dots.size(), _dot_base_y.size())
	for i in range(n):
		var dot: MeshInstance3D = _dots[i]
		dot.position.y = _dot_base_y[i] + sin(_time * 2.0 + i * 0.5) * 0.02


# --- Grid Integration ---
func apply_grid_config(config_data: Dictionary) -> void:
	var before_horizon: String = horizon
	if config_data.has("horizon"):
		horizon = _pick_axis(str(config_data["horizon"]), HORIZONS, horizon)

	if not _built:
		return
	if horizon == before_horizon:
		# curation_station's {"emissive": false} lands here. Touch nothing: a
		# rebuild would free the labels it framed one line earlier.
		return

	_rebuild_now()
	print("[BrouwerChoiceSequence] Config applied — horizon=%s" % [horizon])


## Accept an axis value only if it names something we actually build. A typo in a
## map token falls back to the current look rather than to an empty row.
func _pick_axis(raw: String, allowed: PackedStringArray, fallback: String) -> String:
	var v: String = raw.to_lower().strip_edges()
	return v if allowed.has(v) else fallback


## Synchronous teardown and rebuild. No call_deferred anywhere in the build path —
## a deferred rebuild leaves _auto_ground_artifact measuring a zero AABB.
func _rebuild_now() -> void:
	for c in _built_nodes:
		if is_instance_valid(c):
			remove_child(c)
			c.queue_free()
	_built_nodes.clear()
	_dots.clear()
	_dot_base_y.clear()
	_label = null
	_build_all()
