"""Compose a MapState into a full map_data.json dict matching the
project's existing schema (e.g. commons/maps/Point_One/map_data.json).

The structure layer values are written as STRINGS (project convention).
Empty utilities/interactables become " ". Required top-level fields
populated with sensible defaults so the map loads in the runtime."""
from __future__ import annotations

from .ops import MapState


def to_map_data_json(state: MapState, name: str, *,
                     description: str = "",
                     compose_mode: str = "map_grammar",
                     config_id: str = "",
                     ops: list | None = None) -> dict:
    rows = state.rows
    cols = state.cols
    structure_str = [[str(v) for v in row] for row in state.structure]
    utilities_str = [[(v if v.strip() else " ") for v in row] for row in state.utilities]
    interact_str = [[(v if v.strip() else " ") for v in row] for row in state.interactables]

    return {
        "map_info": {
            "lookup_name": name,
            "name": name,
            "description": description or f"Auto-composed via map-grammar ({compose_mode}).",
            "version": "1.0",
            "format": "ada-3layer-v1",
            "dimensions": {"width": cols, "depth": rows, "max_height": 5},
            "metadata": {
                "composed_from_dressing_rooms": False,
                "compose_mode": compose_mode,
                "config_id": config_id,
                "ops": ops or [],
            },
        },
        "settings": {
            "auto_reveal_on_entry": True,
            "background": {"type": "sky", "color": [0.10, 0.10, 0.20]},
            "cube_size": 1.0,
            "enable_physics": True,
            "enter_type": "fade",
            # Godot's GridStructureComponent.gd:74 calls .get("enabled", ...)
            # on this — must be a dict, not the string "none". An empty
            # dict (or "enabled: false") gives no animation.
            "grid_animation": {"enabled": False},
            "gutter": 0.0,
            "initial_tile_visibility": "hidden_except_corners",
            "show_grid": True,
        },
        "lighting": {
            "ambient_color": [0.12, 0.13, 0.16],
            "ambient_energy": 0.55,
            "directional_light": {
                "color": [1.0, 0.96, 0.88],
                "energy": 1.2,
                "direction": [-0.5, -1.0, -0.4],
            },
        },
        "utility_definitions": {
            "s": {"type": "spawn", "properties": {"height": 1.5}},
            "t": {
                "type": "teleporter",
                "name": "Next",
                "description": "Continue",
                "properties": {"action": "next_in_sequence"},
            },
        },
        "documentation": {
            "summary": f"{name} (auto)",
            "objective": "Generated by map-grammar auto-research.",
            "layout": f"{cols}×{rows} grid; ops={[o.get('op','?') for o in (ops or [])]}",
        },
        "layers": {
            "structure": structure_str,
            "utilities": utilities_str,
            "interactables": interact_str,
        },
    }
