from pathlib import Path
import json,shutil
O=Path('doc/space/randomness-dna-2026-09-16');S=Path('doc/research/possible-bodies');(S/'randomness-dna').mkdir(exist_ok=True);checks=[]
for hall,token in [('Random_Definition','textile_comparison'),('Random_Mushrooms','couture_comparison')]:
 d=json.loads((O/(hall+'-runtime.json')).read_text(encoding='utf-8'));assert not d['failures'];checks+=d['checks'];assert 'SCRIPT ERROR' not in (O/(hall+'-process.log')).read_text(encoding='utf-8')
 shutil.copy2(O/(hall+'-'+token+'.png'),S/'randomness-dna'/(token+'.png'))
assert all(c['passed'] for c in checks)
(O/'verification.json').write_bytes(json.dumps(dict(checks=checks,passed=len(checks),headset_verified=False),indent=2).encode('utf-8'))
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Chance and repertoire · Ada Research</title><style>body{background:#111d26;color:#f0ece3;font:18px/1.65 system-ui;margin:0}main{max-width:1100px;margin:auto;padding:50px 24px}h1{font-size:56px;line-height:1.1}h2{color:#f3b87d;margin-top:55px}img{width:100%;border-radius:12px}p{max-width:800px}a{color:#93d8d8}</style><main><p>ADA RESEARCH / RANDOMNESS</p><h1>Another draw.<br>Another recipe.</h1><p>Two supporting encounters use existing DNA generators. The main seed-replay experiment and mushroom garden remain in place.</p><h2>Definition: same draws, other marks</h2><img src="randomness-dna/textile_comparison.png" alt="Three seeded textile panels in the museum"><p>Three ten_print_textile instances share seed 41 and stay still. The alphabets differ: diagonals, orthogonals, blocks. NEXT SEED changes all three together; RESET returns to 41. Follow a cell between the panels: a shared draw can acquire another visual meaning.</p><h2>Mushrooms: three individuals, one construction</h2><img src="randomness-dna/couture_comparison.png" alt="Three couture figures on a museum platform"><p>Three dream_couture_beast bodies begin with seeds 41, 42 and 43, hare heads and sheath garments. NEXT SEED produces another trio. GARMENT retains the seeds and cycles sheath, crinoline, quilted, bloom and fringe. The screenshot shows crinoline. RESET restores the starting trio.</p><p>The seed varies proportions, prints and details. The garment control changes the construction instructions. Neither makes these sculptures autonomous agents. The book asks which possibilities the visitor would add to the recipe.</p><h2>Checked in Godot</h2><p>COUNT runtime checks pass, including control reach, three instantiated specimens, shared textile draws and retained couture seeds after garment changes. Gallery entry, exit and side routes have floor support. Headset testing remains.</p><p><a href="http://localhost:3003/book?map=Random_Definition&section=final">Definition text</a> · <a href="http://localhost:3003/book?map=Random_Mushrooms&section=final">Mushrooms text</a></p></main></html>'''.replace('COUNT',str(len(checks)))
(S/'randomness-dna.html').write_bytes(html.encode('utf-8'));print(len(checks),'checks passed')
