extends Node3D
class_name StencilQuarter

## stencil_quarter — a symmetry is a claim about how much you never had to keep.
##
## THE FAMILY, AND IT IS NOT ONE FAMILY. Four artifacts declare the axis `stencil`. Three of
## them share a vocabulary exactly — mirror_cellular_texture_for_3d, mirrored_cellular_automata
## and persian_rug all say motif / quadrant / octant / none (persian_rug swaps octant for
## halfturn). The fourth, gradient_hunter, declares `stencil` with the values ring / pair /
## axial / shell / swarm, which is not a symmetry vocabulary at all — it is an arrangement one.
##
## That is a finding about the corpus before it is a finding about symmetry: **an axis name
## can be shared by artifacts that do not share an axis.** The declaration gate compares each
## block against its own code and passes both, because both are internally honest. Nothing in
## the pipeline compares two artifacts' vocabularies to each other, so `stencil` reads as a
## five-member family in every census and is really a three-member family and a homonym.
##
## THE ARGUMENT. Each value names a fraction of the plane you actually have to store, and the
## rest is generated by reflection: none keeps everything, quadrant keeps a quarter, octant an
## eighth. A symmetry is compression, and the compression ratio is the symmetry group's order.
## The three members that share the vocabulary all treat it as a look. It is a storage claim.
##
## THE BODY, NOT A GAUGE. The `kept` reading does not shade a pie of what is stored. It builds
## ONLY the tile that is stored, at full height, and leaves the generated remainder as a flat
## floor — so the stored fraction is a solid you can walk around and the generated part is
## visibly derivative.

## Which symmetry the pattern is generated under. motif/quadrant/octant/none is the vocabulary
## the three cellular members share; halfturn is persian_rug's fourth, carried because it is
## the one rotation in a family otherwise made of reflections.
@export_enum("none", "halfturn", "quadrant", "octant", "motif") var stencil: String = "quadrant":
	set(v):
		stencil = v
		if is_inside_tree():
			_rebuild()

## What is drawn.
##   pattern — the whole generated field, which is all the members ever show.
##   kept    — only the stored tile stands up; the generated remainder lies flat.
##   seam    — the mirror lines themselves, drawn over the pattern.
@export_enum("pattern", "kept", "seam") var reading: String = "pattern":
	set(v):
		reading = v
		if is_inside_tree():
			_rebuild()

@export var seed_value: int = 20260815
@export var span: float = 0.92

const N := 24
const CELL_H := 0.085

var _built: Array[Node3D] = []


func _ready() -> void:
	_rebuild()


func apply_grid_config(config_data: Dictionary) -> void:
	if config_data.has("stencil"):
		stencil = str(config_data["stencil"])
	if config_data.has("reading"):
		reading = str(config_data["reading"])
	if config_data.has("seed_value"):
		seed_value = int(config_data["seed_value"])
	_rebuild()


func _rebuild() -> void:
	for n in _built:
		if is_instance_valid(n):
			n.queue_free()
	_built.clear()
	var root := Node3D.new()
	root.name = stencil
	add_child(root)
	_built.append(root)

	var rng := RandomNumberGenerator.new()
	rng.seed = seed_value
	# ONE source field for every value, so the variants differ in the FOLD and not in the
	# noise. An unseeded field here would make five values into five different patterns and
	# the whole comparison would be a fact about randf.
	var src: PackedFloat32Array = PackedFloat32Array()
	src.resize(N * N)
	for i in range(N * N):
		src[i] = rng.randf()

	var pitch: float = span / float(N)
	for r in range(N):
		for c in range(N):
			var s: Vector2i = _fold(c, r)
			var v: float = src[s.y * N + s.x]
			if v < 0.42:
				continue
			var stored: bool = (s.x == c and s.y == r)
			if reading == "kept" and not stored:
				# The generated remainder: present, flat, obviously derived.
				root.add_child(_block(c, r, pitch, 0.010, Color(0.40, 0.42, 0.46), 0.0))
				continue
			var h: float = CELL_H * (0.55 + v * 0.75)
			var col: Color = (Color(0.86, 0.74, 0.42) if stored
					else Color(0.52, 0.62, 0.70))
			root.add_child(_block(c, r, pitch, h, col, 0.0))

	if reading == "seam":
		_add_seams(root)


## Where cell (c,r) reads its value from. The fold IS the axis.
func _fold(c: int, r: int) -> Vector2i:
	var half: int = N / 2
	match stencil:
		"none":
			return Vector2i(c, r)
		"halfturn":
			# A rotation, not a reflection — the one member that is not a mirror.
			if r >= half or (r == half - 1 and c >= half):
				return Vector2i(N - 1 - c, N - 1 - r)
			return Vector2i(c, r)
		"quadrant":
			return Vector2i(mini(c, N - 1 - c), mini(r, N - 1 - r))
		"octant":
			var x: int = mini(c, N - 1 - c)
			var y: int = mini(r, N - 1 - r)
			return Vector2i(mini(x, y), maxi(x, y))
		"motif":
			# The strongest claim in the vocabulary: one small tile, repeated. Everything
			# outside the tile is generated, so the stored fraction is a sixteenth.
			var t: int = N / 4
			return Vector2i(c % t, r % t)
	return Vector2i(c, r)


func _add_seams(root: Node3D) -> void:
	var lines: Array = []
	match stencil:
		"quadrant":
			lines = [[Vector2(0.5, 0.0), Vector2(0.5, 1.0)], [Vector2(0.0, 0.5), Vector2(1.0, 0.5)]]
		"octant":
			lines = [[Vector2(0.5, 0.0), Vector2(0.5, 1.0)], [Vector2(0.0, 0.5), Vector2(1.0, 0.5)],
					[Vector2(0.0, 0.0), Vector2(1.0, 1.0)], [Vector2(1.0, 0.0), Vector2(0.0, 1.0)]]
		"halfturn":
			lines = [[Vector2(0.0, 0.5), Vector2(1.0, 0.5)]]
		"motif":
			for k in range(1, 4):
				var f := float(k) / 4.0
				lines.append([Vector2(f, 0.0), Vector2(f, 1.0)])
				lines.append([Vector2(0.0, f), Vector2(1.0, f)])
	for l in lines:
		var a: Vector2 = l[0]
		var b: Vector2 = l[1]
		root.add_child(_rod(
				Vector3((a.x - 0.5) * span, CELL_H * 1.5, (a.y - 0.5) * span),
				Vector3((b.x - 0.5) * span, CELL_H * 1.5, (b.y - 0.5) * span),
				Color(0.90, 0.46, 0.30), 0.005))


func _block(c: int, r: int, pitch: float, h: float, col: Color, emit: float) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = Vector3(pitch * 0.82, h, pitch * 0.82)
	mi.mesh = bm
	mi.position = Vector3((float(c) + 0.5) / float(N) * span - span * 0.5, h * 0.5,
			(float(r) + 0.5) / float(N) * span - span * 0.5)
	mi.material_override = _mat(col, emit)
	return mi


func _rod(a: Vector3, b: Vector3, c: Color, r: float) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var cyl := CylinderMesh.new()
	cyl.top_radius = r
	cyl.bottom_radius = r
	cyl.height = maxf(a.distance_to(b), 0.0001)
	cyl.radial_segments = 5
	cyl.rings = 0
	mi.mesh = cyl
	mi.material_override = _mat(c, 0.45)
	mi.position = (a + b) * 0.5
	var dir: Vector3 = (b - a).normalized()
	if absf(dir.dot(Vector3.UP)) < 0.999:
		mi.look_at_from_position(mi.position, mi.position + dir, Vector3.UP)
		mi.rotate_object_local(Vector3.RIGHT, PI * 0.5)
	return mi


func _mat(c: Color, emit: float) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_color = c
	m.roughness = 0.58
	if emit > 0.0:
		m.emission_enabled = true
		m.emission = c
		m.emission_energy_multiplier = emit
	return m
