extends Node3D

## couture_beast — one dream body as its own DNA artifact (generated by
## tools/dream_bodies_promote.py; edit the builder, not this file).
##
## The sweep sets EXPORTED PROPERTIES on a scene root before _ready and reads them
## back; it cannot call a function. So each family gets this thin scene, whose
## exports are exactly the axes its builder declares in axes(), and whose _ready
## hands them to the builder as opts.
##
## Axes: head (hare, cat, beak, serpent, fan, antler); garment (sheath, crinoline, quilted, bloom, fringe)

const BUILDER := preload("res://commons/artifacts/dream_bodies/bodies/couture_beast.gd")

@export_enum("hare", "cat", "beak", "serpent", "fan", "antler") var head: String = "hare"
@export_enum("sheath", "crinoline", "quilted", "bloom", "fringe") var garment: String = "sheath"
@export var seed: int = 1


func apply_grid_config(config: Dictionary) -> void:
	if config.has("head"):
		head = String(config.get("head", "hare"))
	if config.has("garment"):
		garment = String(config.get("garment", "sheath"))
	if config.has("seed"):
		seed = int(config.get("seed", 1))
	if is_inside_tree():
		_rebuild()


func _ready() -> void:
	_rebuild()


func _rebuild() -> void:
	for c in get_children():
		c.queue_free()
	var root := Node3D.new()
	root.name = "Body"
	add_child(root)
	BUILDER.build(root, seed, {"head": head, "garment": garment})
