extends Node3D

## Stock Stratum — the project's own frequency distribution, read as bedrock.
##
## @identity
## essence: bed_thickness(artifact) proportional to placements(artifact) — the census as sedimentary rock
## desire: to look at a core sample, recognise the furniture of your own world fossilised in it, and see which layer everything else is standing on
## critical_parameter: max_bands — how deep the core is cut. Six bands already reach past 3000 placements; the seventh is a hairline.
## triggers: nothing. It is a specimen already extracted, in a cradle, under glass — the reading is done with your eyes and your neck
## emerges: one band is enormous and it is not a teaching artifact. The thickest deposit in the world is exhibit_furniture, and nobody ever decided that.
## needs: commons/data/placement_census.json [has, generated by tools/build_placement_census.py]; the props themselves, instanced live [has]
## relationships: kin to lineage_vitrine and sturtevant_bench — the third artifact whose subject is this project's own condition. Reads the same census that drives the stage-2 DNA agenda.
## truth: a world's defaults are its bedrock. What gets placed most becomes the ground everything else stands on, and no one ever chose it.
##
## A READYMADE. Nothing in the strata is modelled for this piece: each bed is packed
## with live instances of the actual prop, pulled from the registry at runtime and
## frozen. The surrealism is not invention, it is COMPRESSION — a fire extinguisher is
## an ordinary object until it is a mineral seam, and then it is a fact about the world
## that deposited it.
##
## The bands are ordered by deposit, thickest at the base, so the core reads bottom-up
## the way a real one does: the oldest and heaviest thing is what you are standing on.

const HangarKit = preload("res://commons/artifacts/_hangar/hangar_kit.gd")
const CENSUS := "res://commons/data/placement_census.json"

## How many beds to cut. Kept low on purpose: past six the bands are hairlines and the
## core stops being legible as strata.
@export var max_bands: int = 6
## Instance the real props inside each bed. False leaves the beds as plain mineral —
## which is the honest fallback, not a preference.
@export var live_props: bool = true
## Instances per bed. The bed's THICKNESS carries the count; these are just enough
## for the object to be recognisable in the seam.
@export var props_per_band: int = 3
## How far the core has been drawn out of the floor. 1.0 = fully extracted.
@export var reveal: float = 0.74
@export var core_height: float = 1.15
@export var core_radius: float = 0.17
@export var finish: String = "terminal"
@export var wear: float = 0.10
@export var unit_code: String = "SS-01"

var _ranked: Array = []
var _total: int = 0


func _ready() -> void:
	_load_census()
	_build_cradle()
	_build_core()


func _load_census() -> void:
	if not FileAccess.file_exists(CENSUS):
		return
	var fa := FileAccess.open(CENSUS, FileAccess.READ)
	if fa == null:
		return
	var j := JSON.new()
	if j.parse(fa.get_as_text()) != OK or typeof(j.data) != TYPE_DICTIONARY:
		return
	var d: Dictionary = j.data
	var r: Array = d.get("ranked", [])
	_ranked = r.slice(0, mini(max_bands, r.size()))
	for e in _ranked:
		_total += int((e as Dictionary).get("placements", 0))


# ── the core ─────────────────────────────────────────────────────────────────

func _build_core() -> void:
	if _ranked.is_empty() or _total <= 0:
		var warn := Label3D.new()
		warn.text = "no census —\nrun tools/build_placement_census.py"
		warn.font_size = 22
		warn.pixel_size = 0.001
		warn.modulate = Color(0.92, 0.62, 0.12)
		warn.position = Vector3(0, 0.9, 0)
		add_child(warn)
		return

	var core := Node3D.new()
	core.name = "Core"
	# The specimen is drawn out of the floor, not floating: the unrevealed part is
	# still down there, which is the whole point of a core sample.
	core.position = Vector3(0, core_height * (reveal - 1.0) + 0.06, 0)
	add_child(core)

	var y: float = 0.0
	# Thickest at the BASE. _ranked is ALREADY descending, so it is laid in order and
	# the first bed placed at y=0 is the heaviest deposit. Reversing it here — which the
	# first version did — put the thickest bed on TOP and inverted the whole argument:
	# the thing everything stands on ended up floating above everything.
	for e in _ranked:
		var ent: Dictionary = e
		var n: int = int(ent.get("placements", 0))
		var tok: String = str(ent.get("token", "?"))
		var th: float = maxf(core_height * (float(n) / float(_total)), 0.035)
		_build_band(core, tok, str(ent.get("scene", "")), n, y, th)
		y += th

	# glass tube over the whole column, and a chrome cap — the exhibit register that
	# makes a frequency table look like a mineral specimen
	var glass := StandardMaterial3D.new()
	# Barely there. At 0.10 alpha with a blue cast it washed the beds into one zone —
	# the tube is the exhibit register, not a filter over the evidence.
	glass.albedo_color = Color(0.70, 0.76, 0.84, 0.045)
	glass.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	glass.roughness = 0.06
	glass.cull_mode = BaseMaterial3D.CULL_DISABLED
	var tube := MeshInstance3D.new()
	var cm := CylinderMesh.new()
	cm.top_radius = core_radius + 0.012
	cm.bottom_radius = core_radius + 0.012
	cm.height = y + 0.02
	tube.mesh = cm
	tube.material_override = glass
	tube.position = Vector3(0, y * 0.5, 0)
	core.add_child(tube)

	var chrome := StandardMaterial3D.new()
	chrome.albedo_color = Color(0.82, 0.84, 0.88)
	chrome.metallic = 0.95
	chrome.roughness = 0.12
	var cap := MeshInstance3D.new()
	var cc := CylinderMesh.new()
	cc.top_radius = core_radius + 0.026
	cc.bottom_radius = core_radius + 0.026
	cc.height = 0.045
	cap.mesh = cc
	cap.material_override = chrome
	cap.position = Vector3(0, y + 0.022, 0)
	core.add_child(cap)


## One bed. The mineral slab carries the COUNT as its thickness; the props packed into
## it carry the identity. Both are needed: thickness alone is a bar chart, and props
## alone are a shelf.
func _build_band(host: Node3D, token: String, scene: String, n: int, y: float, th: float) -> void:
	var band := Node3D.new()
	band.name = "Bed_" + token
	band.position = Vector3(0, y + th * 0.5, 0)
	host.add_child(band)

	# Mineral: darker and denser the thicker the deposit, so the base reads as older.
	var t: float = clampf(th / maxf(core_height * 0.35, 0.001), 0.0, 1.0)
	var rock := StandardMaterial3D.new()
	# Wide contrast on purpose: if the beds do not read as distinct beds, thickness
	# carries nothing and the core is just a grey cylinder.
	rock.albedo_color = Color(0.58, 0.55, 0.49).lerp(Color(0.13, 0.12, 0.11), t)
	rock.roughness = 0.95
	rock.metallic = 0.0
	var slab := MeshInstance3D.new()
	var sm := CylinderMesh.new()
	sm.top_radius = core_radius
	sm.bottom_radius = core_radius
	sm.height = th
	sm.radial_segments = 18
	slab.mesh = sm
	slab.material_override = rock
	band.add_child(slab)

	# bedding plane — the hairline that makes it read as deposited, not extruded
	var plane := MeshInstance3D.new()
	var pm := CylinderMesh.new()
	pm.top_radius = core_radius + 0.006
	pm.bottom_radius = core_radius + 0.006
	pm.height = 0.010
	plane.mesh = pm
	plane.material_override = HangarKit.painted_metal(Color(0.09, 0.09, 0.10), wear, 0.3, 0.6)
	plane.position = Vector3(0, th * 0.5, 0)
	band.add_child(plane)

	if live_props and scene != "":
		_embed_props(band, scene, th)

	# the count, stencilled on the tube beside its bed
	var tag: MeshInstance3D = HangarKit.stencil(
		"%s  %d" % [token, n], Vector2(0.30, 0.020), Color(0.86, 0.87, 0.90))
	if tag:
		tag.position = Vector3(0.0, 0.0, core_radius + 0.020)
		band.add_child(tag)


## THE READYMADE STEP. Live instances of the real prop, scaled down, tipped at
## angles, half-sunk in the slab. Frozen so nothing animates — a specimen is still.
func _embed_props(band: Node3D, scene: String, th: float) -> void:
	var ps: PackedScene = load(scene)
	if ps == null:
		return
	var k: int = maxi(props_per_band, 1)
	for i in range(k):
		var inst: Node3D = ps.instantiate()
		if inst == null:
			continue
		for prop in ["auto_drop", "auto_throw", "auto_spin", "auto_run", "animate",
				"rotation_enabled", "show_particles", "show_reference_frame"]:
			if prop in inst:
				inst.set(prop, false)
		var holder := Node3D.new()
		var a: float = TAU * (float(i) / float(k)) + 0.6
		# At the RIM, half-exposed. Sunk in the middle of an opaque slab a prop is
		# invisible and the readymade is lost; a real core shows its inclusions where the
		# bit cut through them. So the props break the cut face, like fossils in section.
		var r: float = core_radius * 0.72
		holder.position = Vector3(cos(a) * r, -th * 0.12, sin(a) * r)
		# tipped, the way anything caught in sediment is tipped
		holder.rotation_degrees = Vector3(
			-24.0 + float(i) * 17.0, rad_to_deg(a), 12.0 - float(i) * 9.0)
		# Small enough to be CAUGHT IN the seam. Bigger and they burst out of the core,
		# which reads as props standing around a tube — the opposite of compression, and
		# the first version did exactly that.
		holder.scale = Vector3.ONE * clampf(th * 0.085, 0.020, 0.048)
		band.add_child(holder)
		holder.add_child(inst)
		# a specimen does not run
		inst.process_mode = Node.PROCESS_MODE_DISABLED


# ── the cradle ───────────────────────────────────────────────────────────────

func _build_cradle() -> void:
	var pal: Dictionary = HangarKit.finish_palette(finish)
	var col_body: Color = pal["body"]
	var col_accent: Color = pal["accent"]
	var shell: StandardMaterial3D = HangarKit.finish_body(finish, col_body, wear)
	var steel: StandardMaterial3D = HangarKit.worn_metal(col_body.lightened(0.10))
	var accent: StandardMaterial3D = HangarKit.emissive(col_accent, 2.2)

	var cab := Node3D.new()
	cab.name = "Cabinet"
	cab.set_meta("housing", true)
	add_child(cab)

	var w: float = core_radius * 2.0 + 0.42
	var d: float = core_radius * 2.0 + 0.36
	# a low plinth with the bore it was drawn from — the hole is part of the exhibit
	cab.add_child(HangarKit.box(Vector3(0, 0.055, 0), Vector3(w, 0.11, d), shell))
	for sx in [-1.0, 1.0]:
		cab.add_child(HangarKit.box(Vector3(sx * (w * 0.5 - 0.02), 0.13, 0),
			Vector3(0.030, 0.05, d), steel))
	cab.add_child(HangarKit.box(Vector3(0, 0.113, d * 0.5 - 0.010),
		Vector3(w * 0.94, 0.005, 0.005), accent))

	# uplight under the core: the specimen is lit from below, like a vitrine
	var lamp := OmniLight3D.new()
	lamp.position = Vector3(0, 0.13, 0)
	lamp.light_energy = 1.6
	lamp.omni_range = 1.4
	lamp.light_color = Color(0.92, 0.90, 0.84)
	cab.add_child(lamp)

	var sign: MeshInstance3D = HangarKit.stencil(
		"CORE · WHAT THIS WORLD IS MADE OF", Vector2(w * 0.86, 0.024),
		col_accent.lightened(0.35))
	if sign:
		sign.position = Vector3(0, 0.075, d * 0.5 + 0.004)
		cab.add_child(sign)
	var code: MeshInstance3D = HangarKit.stencil(
		unit_code, Vector2(0.09, 0.020), col_accent.lightened(0.22))
	if code:
		code.position = Vector3(-w * 0.5 + 0.07, 0.030, d * 0.5 + 0.004)
		cab.add_child(code)


func apply_grid_config(config_data: Dictionary) -> void:
	if config_data.has("max_bands"):
		max_bands = int(config_data["max_bands"])
	if config_data.has("reveal"):
		reveal = float(config_data["reveal"])
	if config_data.has("live_props"):
		live_props = bool(config_data["live_props"])
