from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/lsystems-competition-2026-09-14';RUN=R/'ada_run/competition-review-2026-09-14';M='LSystems_Competition'
def dump(p,d):p.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
r=json.loads((RUN/'run.json').read_text());assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for name in ['entrance','first-turns','winter','controls','grown-pair','original-forest','coral']:
 p=O/f'competition-{name}.png';shutil.copyfile(RUN/M/f'{name}.png',p);assets.append(p.name)
p=O/'competition-before.png';shutil.copyfile(E/f'baseline/{M}/forest-before.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
 for previous in [False,True]:
  p=O/f'competition-{"previous-" if previous else ""}{kind}.md';shutil.copyfile((E/'before' if previous else R)/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
dump(O/'competition-verification.json',r);assets.append('competition-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Who gets the first turn? · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="lsystems-architecture.html">← Architecture</a><a href="/necklace/thread?map=LSystems_Competition&amp;role=primary">Primary artifact / book</a><a href="spine-iteration.html">Our working method</a></nav>
<p class="eyebrow">ADA RESEARCH · L-SYSTEMS / 05 · 14 SEPTEMBER 2026</p><h1>Who gets<br>the first turn?</h1><p class="lead">Two bodies have the same instructions. The second reaches a world the first has already changed.</p>
<div class="facts"><div><strong>3</strong><span>authored works retained</span></div><div><strong>400</strong><span>shared soil cells</span></div><div><strong>2</strong><span>equal starting grammars</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="competition-grown-pair.png" alt="Two branching specimens above a shared tiled soil field inside the Godot museum"><figcaption>A controlled pair at the front; the original five-strategy forest remains behind it. The specimen displays enlarge branch geometry four times. Their actual roots are the close markers in the shared field.</figcaption></figure>
<section><p class="step">01 / SAME INSTRUCTIONS</p><h2>Let each stem take a turn.</h2><p>Both begin with F, diameter 0.02, health 1 and the same rule: <code>F → F[+F]F[-F][F]</code>. STEP lets one tree consume soil and attempt growth. It then gives the turn to the other.</p>
<figure><img loading="lazy" src="competition-first-turns.png" alt="Amber and blue sampling squares overlap on the soil after the first two turns"><figcaption>The initial squares each sample 25 cells; 20 are shared. A first takes 2.250. B then takes 1.980. These are model resource values, not measured grams.</figcaption></figure>
<h2>Change whose turn comes first.</h2><p>ORDER restores the same starting state and gives B the first turn. Take two turns again: the allocation reverses. Both trees still use the same branching rule. After this first pair the remaining field is the same, although the resources went to different trees.</p><blockquote>Its rule is intact; its starting world is already different.</blockquote></section>
<section><p class="step">02 / LOOK UNDER STILLNESS</p><h2>Winter changes the answer.</h2><figure><img loading="lazy" src="competition-winter.png" alt="Winter leaves both specimens as stems while the overlapping soil patch is depleted"><figcaption>SEASON begins a fresh comparison in winter. Consumption still happens, but neither rewriting nor diameter growth is allowed.</figcaption></figure><p>The source consumes nutrients before reaching this condition:</p>
<pre><code>if nutrients &gt; 0.05 and _current_season != Season.WINTER:
    tree.lsystem.generate()
    tree.generation += 1</code></pre><p>A picture of the crown alone would miss the operation in the soil. The field diagram gives us another record to read.</p></section>
<section><p class="step">03 / SEPARATE THE OPERATIONS</p><h2>Time for the field.</h2><p>SOIL advances diffusion and replenishment for one simulated second. It leaves the turn index and selected season unchanged. In this comparison, a tree attempt and a second of field evolution are separate actions. The original forest combines them in its automatic loop.</p><p>The front study stops rewriting after three generations. Further attempts report the cap. This is a construction budget, not proof that the tree matured or the environment reached equilibrium.</p>
<figure><img loading="lazy" src="competition-controls.png" alt="Six reachable physical buttons and a small transparent tilted screen showing the growth gate"><figcaption>STEP · ORDER · SEASON · SOIL · RESET · RULE. ORDER and SEASON start a fresh comparison. RESET returns to spring with A first. All six controls were exercised through the project's desktop pointer.</figcaption></figure></section>
<details><summary>Read the book passage</summary><article class="manuscript">__BOOK__</article></details>
<section><p class="step">04 / KEEP THE COLLECTION</p><h2>The forest remains.</h2><div class="pair"><figure><img loading="lazy" src="competition-before.png" alt="The archived layout assembled in the museum before the repair, with soil visible only through floor holes"><figcaption>Before: Competition was missing from both active museum plans. An isolated reconstruction of its unchanged old map exposed the soil hidden below the floor.</figcaption></figure><figure><img loading="lazy" src="competition-original-forest.png" alt="The original five-strategy forest with visible soil and its parameter controls"><figcaption>After: the original forest, now behind the controlled comparison. Its five strategies and four controls remain. The soil display is above the supporting floor.</figcaption></figure></div>
<figure><img loading="lazy" src="competition-coral.png" alt="Retained branching coral on a plinth"><figcaption>The coral is an independent form generator. It does not take nutrients from this forest. Similar-looking bodies can inhabit different computational relations.</figcaption></figure><p>All three authored artifacts remain. The original floor coordinates are preserved at an offset, with flush covers for its two voids and supporting floor over the old teleporter hole. The earlier map and manuscripts are archived.</p></section>
<section><h2>What was checked?</h2><p>__CHECKS__ checks cover museum instantiation, the compact controls, first-turn allocation, winter consumption, separate soil time, the generation cap, ordinary scene compatibility and the route through the hall. Spring and winter replays agree with the archived growth kernel. No GDScript errors occurred.</p><p>These are actual Godot images and synthetic input through the project's DesktopPlayer pointer and movement. They are not evidence of a human headset visit. Headset reach, readability, comfort and Quest timing remain pending.</p><p>The corrected text distinguishes the implemented soil and approximate crowding from features the old prose claimed: light-seeking, branch collisions, pruning and marine competition are not computed here. No ecological equilibrium, entropy measurement or moral conclusion is claimed by the comparison.</p></section>
<section class="next"><h2>Next: which changes can we ask for?</h2><p><a href="/necklace/thread?map=LSystems_Living&amp;role=primary">LSystems_Living</a> brings us to the genetic tree sculptor. We will inspect the mapping from its controls to a body, and what planting actually makes possible.</p><p><a href="spine-iteration.html">Complete the journey, then return →</a></p></section>
<footer><a href="competition-verification.json">Runtime receipt</a> · <a href="competition-previous-final.md">Previous manuscript</a> · <a href="competition-technical.md">Implementation</a> · <a href="competition-critical.md">Critical questions</a></footer></main></body></html>'''
(O/'lsystems-competition.html').write_bytes(page.replace('__CSS__',css).replace('__BOOK__',book).replace('__CHECKS__',str(r['checks'])).encode());assets.append('lsystems-competition.html')
method=markdown.markdown((O/'spine-iteration.md').read_text(),extensions=['tables','toc'])
(O/'spine-iteration.html').write_bytes(('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>First traverse. Then return. · Ada Research</title><style>'+css+'table{width:100%;border-collapse:collapse;font-size:.9rem}td,th{border-bottom:1px solid #425050;padding:.6rem;text-align:left;vertical-align:top}@media(max-width:650px){table{display:block;overflow-x:auto}}</style></head><body><main><nav><a href="lsystems-competition.html">Competition</a><a href="lsystems-architecture.html">Architecture</a><a href="/museum-progress">Museum progress</a></nav><article class="manuscript">'+method+'</article></main></body></html>').encode())
assets+=['spine-iteration.html','spine-iteration.md']
for src,dst in [(RUN/'run.json',E/'receipt.json'),(RUN/M/'probe_ca_edge_live.json',E/'runtime-report.json'),(RUN/M/'engine.log',E/'engine.log')]:shutil.copyfile(src,dst)
targets=['possible-bodies/'+a for a in assets];dump(E/'publish-targets.json',targets);dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Competition review: {len(targets)} assets; {r["checks"]} runtime checks.')
