from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="QFEP_E_Term"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/qfep-e-term-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]
tokens=[x.strip().split(":",1)[0].split("#",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":14,"depth":14,"max_height":3},"seven_artifacts":len(tokens)==7 and len(set(tokens))==7,"primary_focus":roles.get("entropy_fan")=="primary" and sum(v=="primary" for v in roles.values())==1,"registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid_structure":all(len(data["layers"][k])==14 and len(data["layers"][k][0])==14 for k in ["structure","utilities","interactables"])}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["entropy_fan"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"qfep-e-term-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="e-title e-desc" xmlns="http://www.w3.org/2000/svg"><title id="e-title">A fan of possible futures</title><desc id="e-desc">A branching fan multiplies choices while a logarithm keeps the count readable.</desc><rect width="900" height="280" rx="18" fill="#121827"/><g fill="none" stroke="#85c89a" stroke-width="5"><path d="M130 220L280 160L430 85M280 160L430 145M280 160L430 205M430 85L700 48M430 85L700 100M430 145L700 145M430 145L700 195M430 205L700 245"/><path d="M130 220L280 220L430 205"/></g><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff"><circle cx="130" cy="220" r="14" fill="#e9b86f"/><text x="450" y="45" font-size="22">choices multiply; log(count) compares them</text><text x="450" y="270" font-size="17">an omitted branch is a decision, not an empty space</text></g></svg><figcaption>The fan distinguishes an inventory of possible outcomes from the probabilities assigned to them.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="qfep-e-term-verification.json">Verification record</a></p>'
body='<p class="date">QFEP laboratory · E term · 15 September 2026</p><h1>Counting What Could Happen</h1><p class="lead">Uncertainty can grow because a source is balanced, or because it offers more branches. The fan lets those operations separate.</p><p><a href="/necklace/thread?map=QFEP_E_Term&amp;role=primary">Primary artifact and book</a> · <a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></p>'+diagram+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Inventory before probability</h2><p>The entropy fan is the sole primary artifact. The microstate counter, possibility cloud, particle field, lambda slider, and random cubes remain secondary supports: they make branching countable while keeping probability distinct from the list of available outcomes.</p><p>The next hall, <a href="qfep-lambda-spectrum.html"><strong>QFEP_Lambda_Spectrum</strong></a>, turns the order–chaos weighting into a walkable range.</p>'+score
(O/"qfep-e-term.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Counting What Could Happen · Ada Research</title><style>'+css+'</style><main><nav><a href="qfep-f-term.html">Previous hall</a><a href="qfep-lambda-spectrum.html">Next hall</a><a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["qfep-e-term.html","qfep-e-term-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
