"""Build the illustrated Recursion review from current, accepted Godot evidence."""
from pathlib import Path
import hashlib,html,json,shutil,markdown
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'doc/research/possible-bodies'
BASE=ROOT/'doc/space/recursion-encounter-2026-09-14'
RUN=ROOT/'ada_run/recursion-review-2026-09-14'
def dump(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
receipt=json.loads((RUN/'run.json').read_text(encoding='utf-8'))
assert receipt['exit']==0 and not receipt['failures'] and receipt['sources_unchanged']
assert all(hashlib.sha256((ROOT/p).read_bytes()).hexdigest()==h for p,h in receipt['source_sha256'].items())
assets=[]
for name in ['entrance','collection','one-call-row','four-calls','selected-subdivision','chair-exclusions','chair-built','retained-collection','overview','compact-front']:
 dest=OUT/f'recursion-{name}.png';shutil.copyfile(RUN/'Fractal_Recursion'/f'{name}.png',dest);assets.append(dest.name)
shutil.copyfile(ROOT/'ada_run/recursion-baseline-2026-09-14/Fractal_Recursion/entrance.png',OUT/'recursion-before.png');assets.append('recursion-before.png')
for kind in ['final','technical','critical','summary']:
 name=f'recursion-{kind}.md';shutil.copyfile(ROOT/f'commons/maps/Fractal_Recursion/{kind}.md',OUT/name);assets.append(name)
dump(OUT/'recursion-verification.json',receipt);assets.append('recursion-verification.json')
book=markdown.markdown((ROOT/'commons/maps/Fractal_Recursion/final.md').read_text(encoding='utf-8'),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The cost of again · Ada Research</title><style>
:root{color-scheme:dark;--ink:#f3eee6;--muted:#b8c4ce;--line:#455261;--pink:#ffacd7}*{box-sizing:border-box}body{margin:0;background:#121d2a;color:var(--ink);font:17px/1.65 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:28px 25px 70px}nav{display:flex;gap:24px;flex-wrap:wrap;font-size:14px}a{color:var(--pink)}.eyebrow{font-size:12px;letter-spacing:.16em;color:var(--muted);margin-top:48px}h1{font:clamp(44px,7vw,86px)/1.05 Georgia,serif;margin:22px 0}h2{font:32px/1.2 Georgia,serif;margin:12px 0 20px}h3{font:24px/1.3 Georgia,serif}.lead{font:25px/1.5 Georgia,serif;max-width:850px}.facts{display:flex;gap:26px;flex-wrap:wrap;padding:20px 0;border-block:1px solid var(--line);margin:32px 0}.facts strong{font:35px Georgia,serif;display:block;color:var(--pink)}.facts span{font-size:13px;color:var(--muted)}img{width:100%;height:auto;display:block;border:1px solid var(--line);border-radius:4px}figure{margin:28px 0}figcaption{font-size:14px;color:var(--muted);margin-top:9px}section{margin:50px 0}.pair{display:grid;grid-template-columns:1fr 1fr;gap:24px}.pair>div{padding:22px;background:#1c2d3f;border:1px solid var(--line)}.pair figure{margin:20px -22px 0}.pair img{border-radius:0;border-inline:0}.pair figcaption{padding:0 20px 16px}.step{font:12px monospace;color:var(--pink);letter-spacing:.08em}blockquote{font:30px/1.4 Georgia,serif;border-left:3px solid var(--pink);padding-left:25px;margin:34px 0;max-width:850px}table{border-collapse:collapse;width:100%;font-size:15px}th,td{text-align:left;padding:12px;border-bottom:1px solid var(--line)}th{color:var(--muted)}details{margin:26px 0;border:1px solid var(--line);padding:22px;background:#18283a}summary{cursor:pointer;font-size:20px;color:var(--pink)}article{max-width:780px;margin:30px auto;font:21px/1.7 Georgia,serif}article p:first-child{font-size:30px}code{font-family:monospace;font-size:.82em}pre{overflow-x:auto;background:#0c1621;padding:20px;line-height:1.6}.note{font-size:15px;color:var(--muted)}.next{padding:25px;background:#302638;border-left:3px solid var(--pink)}footer{font-size:14px;margin-top:45px;border-top:1px solid var(--line);padding-top:22px}@media(max-width:700px){main{padding:22px 16px}.pair{grid-template-columns:1fr}.lead{font-size:22px}article{font-size:19px}.facts{gap:18px}th,td{padding:8px;font-size:13px}}
</style></head><body><main><nav><a href="fractal-learning-arc.html#Fractal_Recursion">← The fractal walk</a><a href="/necklace/thread?map=Fractal_Recursion&role=primary">Four primary artifacts / book</a><a href="/museum-progress?sequence=fractals&room=Fractal_Recursion">Museum progress</a></nav>
<p class="eyebrow">ADA RESEARCH · FRACTAL RECURSION · 14 SEPTEMBER 2026</p><h1>The cost of again.</h1><p class="lead">A square calls once. A ring calls four times. A cube divides where we choose. A chair reveals what its recipe excluded. Similar-looking forms can have very different procedures.</p>
<div class="facts"><div><strong>10</strong><span>existing works retained</span></div><div><strong>4</strong><span>desks and primary book passages</span></div><div><strong>93</strong><span>Godot checks passed</span></div><div><strong>1</strong><span>continuous route through the hall</span></div></div>
<figure><img src="recursion-entrance.png" alt="View from the museum entrance toward the four recursion desks and clear middle aisle"><figcaption>Actual Godot capture. Each primary begins with one object and waits for input. The compact desks hold six controls in two rows; the smaller transparent displays keep the specimens visible.</figcaption></figure>
<section><h2>One standing position. Six controls.</h2><p>The desks are now 1.12 metres wide, with three buttons across in two rows. The text screen is 1.18 × 0.36 metres, lightly tinted and transparent. A thin frame and outlined lettering keep the reading legible while the object remains visible behind it.</p><figure><img loading="lazy" src="recursion-compact-front.png" alt="Standing at the compact controls, looking through the transparent text panel toward the subdivided cube"><figcaption>Actual standing-eye capture. The test presses every control from the same centred position; physical reach and readability still need a headset check.</figcaption></figure></section><div class="pair"><div><p class="step">01 / ONE CALL</p><h2>Inside, or beside?</h2><p>MORE adds one square. LAYOUT spreads the same terms into a row. COLLAPSE makes them coincide at the smallest size. The count remains even when the differences become harder to see.</p><figure><img loading="lazy" src="recursion-one-call-row.png" alt="Seven squares laid out beside one another above the first desk"><figcaption>Seven levels, seven squares. The rule and the arrangement can be inspected separately.</figcaption></figure></div><div><p class="step">02 / FOUR CALLS</p><h2>One more costs more.</h2><p>Predict the next count: 1, 5, 21, 85, 341. PACKING changes the child radius while holding depth. At depth five, DUST loses a level to the minimum-radius cutoff. TURN changes the ring planes; stop to restore the frontal comparison.</p><figure><img loading="lazy" src="recursion-four-calls.png" alt="Eighty-five pink rings with the reachable sloped controls below"><figcaption>Depth four, contact packing: the population stays at 85 while the radius changes.</figcaption></figure></div></div>
<section><p class="step">03 / SELECTED SUBDIVISION</p><h2>Where will you spend the next split?</h2><p>Each step replaces one cell with eight. After twelve splits there are 85 cells. Concentrate the work down one corner or spread it across the shallowest cells: the same count buys different distributions of detail.</p><table><thead><tr><th>Selection</th><th>Splits</th><th>Remaining cells</th><th>Deepest level</th></tr></thead><tbody><tr><td>DRILL</td><td>12</td><td>85</td><td>12</td></tr><tr><td>SPREAD</td><td>12</td><td>85</td><td>3</td></tr></tbody></table><figure><img loading="lazy" src="recursion-selected-subdivision.png" alt="The subdivided cube on its plinth, with its selection controls"><figcaption>Recorded state after spreading twelve splits. LOTS offers a seeded population draw; BEGIN repeats that mode from the same beginning.</figcaption></figure><blockquote>More work need not yield more experience. Where would you spend the next split?</blockquote></section>
<section><p class="step">04 / THE AUTHORED CHAIR</p><h2>What did the recipe leave out?</h2><p>After the first cut, GHOST reveals eleven excluded cells beside the sixteen kept ones. The model is also lifted, reshaped and given new armrests. Its code follows five authored stages. Its name alone cannot establish recursion.</p><div class="pair"><figure><img loading="lazy" src="recursion-chair-exclusions.png" alt="The chair's first selection with pale excluded cells restored"><figcaption>First cut, with the excluded cells shown.</figcaption></figure><figure><img loading="lazy" src="recursion-chair-built.png" alt="The completed chair after five manually advanced construction stages"><figcaption>Twenty retained parts after five construction stages.</figcaption></figure></div></section>
<details><summary>Read the new book passage</summary><article>__BOOK__</article><p><a href="recursion-final.md">Manuscript</a> · <a href="recursion-technical.md">Implementation notes</a> · <a href="recursion-critical.md">Critical questions</a></p></details>
<section><h2>The collection stays.</h2><p>The table, staircase, pagoda, sphere, independent screen and synthesis stand remain beyond and beside the four desks. The room gives them space to be examined without making every object evidence for the same claim. The old layout and prose are archived.</p><figure><img loading="lazy" src="recursion-retained-collection.png" alt="The restored pagoda and table standing above the floor in the rear gallery"><figcaption>The supporting collection remains part of the hall. The pagoda is raised clear of the floor; the table is no longer a miniature buried beneath it.</figcaption></figure><details><summary>See the earlier entrance</summary><figure><img loading="lazy" src="recursion-before.png" alt="Baseline capture of the former crowded museum arrangement"><figcaption>Actual baseline capture before this pass. Saved museum placements differed from the map's authored layout.</figcaption></figure></details></section>
<p class="note">93 rendered Godot checks passed, including the current wall text, all ten works, physical desktop-pointer controls, measured populations, seeded replay, stopping limits, chair exclusions and a central aisle walk of more than twelve metres. Input was synthetic through the project's standalone DesktopPlayer rig inside the museum; this does not certify the museum walker's own interaction lane. Headset reach, comfort and performance remain to test. The saved museum hand was preserved.</p>
<section class="next"><h2>Next: where does a branch go?</h2><p>Carry the self-call and its stopping conditions into Recursive Trees. Hold a beginning, follow corresponding forks, then change direction, length and which branches receive further growth.</p><a href="/necklace/thread?map=Fractal_RecursiveTrees&role=primary">Continue to Fractal_RecursiveTrees →</a></section>
<footer><a href="recursion-verification.json">Recorded runtime verification</a> · <a href="fractal-learning-arc.html">Seven-hall learning arc</a> · <a href="menger-flight.html">The Menger flight cube</a></footer></main></body></html>'''.replace('__BOOK__',book).replace('93',str(receipt['checks']))
(OUT/'recursion-encounter.html').write_text(page,encoding='utf-8');assets.append('recursion-encounter.html')
assets+=['fractal-learning-arc.html','fractal-learning-arc.json','fractal-learning-arc.md']
for name,src in [('receipt.json',RUN/'run.json'),('report.json',RUN/'Fractal_Recursion/probe_ca_edge_live.json'),('engine.log',RUN/'Fractal_Recursion/engine.log')]:shutil.copyfile(src,BASE/name)
targets=['possible-bodies/'+a for a in assets];dump(BASE/'publish-targets.json',targets);dump(BASE/'publish-hashes.json',{r:hashlib.sha256((ROOT/'doc/research'/r).read_bytes()).hexdigest() for r in targets})
print(f'Built Recursion review: {len(targets)} assets, {receipt["checks"]} accepted checks.')
