from pathlib import Path
import hashlib,json,re,subprocess,markdown
R=Path.cwd(); M="SpeculativeComputation_Rhizome_Network"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/speculative-rhizome-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
d=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]; t=[x.strip().split(":",1)[0].split("#",1)[0] for row in d["layers"]["interactables"] for x in row if x.strip()]; c={"dimensions":d["map_info"]["dimensions"]=={"width":13,"depth":12,"max_height":5},"two_artifacts":len(t)==2 and len(set(t))==2,"primary":roles.get("rhizome_grower")=="primary" and sum(v=="primary" for v in roles.values())==1,"registers":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid":all(len(d["layers"][k])==12 and len(d["layers"][k][0])==13 for k in ["structure","utilities","interactables"])}
try:c["registry"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True).returncode==0
except OSError:c["registry"]=False
v={"hall":M,"date":"2026-09-15","checks":sum(c.values()),"total_checks":len(c),"failures":[k for k,x in c.items() if not x],"checks_detail":c,"tokens":t,"primary_artifacts":["rhizome_grower"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(v,indent=2),encoding="utf-8");(O/"speculative-rhizome-verification.json").write_text(json.dumps(v,indent=2),encoding="utf-8");css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1];book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
fig='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="r-title r-desc" xmlns="http://www.w3.org/2000/svg"><title id="r-title">Many centres, many paths</title><desc id="r-desc">A branching network connects several chambers without a privileged root.</desc><rect width="900" height="280" rx="18" fill="#121827"/><g stroke="#8fc7d5" stroke-width="6" fill="none"><path d="M140 145L290 75L460 130L650 70L780 155M140 145L300 215L460 130L610 220L780 155M290 75L300 215M650 70L610 220"/></g><g fill="#f0d48c"><circle cx="140" cy="145" r="18"/><circle cx="290" cy="75" r="18"/><circle cx="460" cy="130" r="18"/><circle cx="650" cy="70" r="18"/><circle cx="780" cy="155" r="18"/><circle cx="300" cy="215" r="18"/><circle cx="610" cy="220" r="18"/></g><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff"><text x="450" y="35" font-size="22">connection without a privileged root</text><text x="450" y="265" font-size="17">a path can begin anywhere and still carry a history</text></g></svg><figcaption>The rhizome turns relation into the primary spatial fact.</figcaption></figure>''';score=f'<p>{v["checks"]}/{v["total_checks"]} static checks passed. <a href="speculative-rhizome-verification.json">Verification record</a></p>';body='<p class="date">Speculative computation · Rhizome network · 15 September 2026</p><h1>Where Can a Path Begin?</h1><p class="lead">A network can route around absence without asking one centre for permission.</p><p><a href="/necklace/thread?map=SpeculativeComputation_Rhizome_Network&amp;role=primary">Primary artifact and book</a> · <a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></p>'+fig+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Relation before hierarchy</h2><p>The rhizome grower is the primary artifact; the cave demo remains a secondary spatial witness. Begin at any chamber, follow a branch, and return by another route. The network’s topology is the lesson: connection can be distributed without becoming an invisible hierarchy.</p><p>This closes the speculative computation sequence and hands the spine to the ethics of computation, where we ask who is advantaged by the routes a system makes easy.</p>'+score
(O/"speculative-rhizome.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Where Can a Path Begin? · Ada Research</title><style>'+css+'</style><main><nav><a href="speculative-uncertainty.html">Previous hall</a><a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8");assets=["speculative-rhizome.html","speculative-rhizome-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8");(E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8");print(json.dumps(v))
