from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/lsystems-living-2026-09-14';RUN=R/'ada_run/living-review-2026-09-14';M='LSystems_Living'
def dump(p,d):p.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
r=json.loads((RUN/'run.json').read_text());assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for name in ['entrance','below-threshold','crossing-threshold','controls','planted','retained-collection']:
 p=O/f'living-{name}.png';shutil.copyfile(RUN/M/f'{name}.png',p);assets.append(p.name)
p=O/'living-before.png';shutil.copyfile(E/f'baseline/{M}/sculptor-before.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
 for previous in [False,True]:
  p=O/f'living-{"previous-" if previous else ""}{kind}.md';shutil.copyfile((E/'before' if previous else R)/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
dump(O/'living-verification.json',r);assets.append('living-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What counts as a change? · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="lsystems-competition.html">← Competition</a><a href="/necklace/thread?map=LSystems_Living&amp;role=primary">Primary artifact / book</a><a href="spine-iteration.html">Our working method</a></nav>
<p class="eyebrow">ADA RESEARCH · L-SYSTEMS / 06 · 14 SEPTEMBER 2026</p><h1>What counts<br>as a change?</h1><p class="lead">The number moves. The tree does not. Hold a witness and find the difference the interpreter will admit.</p>
<div class="facts"><div><strong>6</strong><span>original works retained</span></div><div><strong>8</strong><span>exposed genes</span></div><div><strong>200</strong><span>drawing commands allowed</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="living-entrance.png" alt="The Living workbench faces two tree plinths inside the museum"><figcaption>Editing, holding, placing: three ways for a body to persist while a design changes. The earlier collection remains beyond the front study.</figcaption></figure>
<section><p class="step">01 / KEEP A WITNESS</p><h2>Does every edit change the body?</h2><p>RESET starts Depth at 4.000. HOLD leaves a second tree beside the preview. Four MORE presses reach 4.800. The raw value changes each time; the generated branch geometry remains identical.</p><div class="pair"><figure><img loading="lazy" src="living-below-threshold.png" alt="Editing and held trees have the same branch plan below the generation threshold"><figcaption>At 4.800: two rewriting generations, matching the held witness.</figcaption></figure><figure><img loading="lazy" src="living-crossing-threshold.png" alt="The editing tree adds another generation while the held tree stays unchanged"><figcaption>At 5.000: three generations. The witness keeps its earlier form.</figcaption></figure></div><pre><code>var generations: int = clampi(roundi(dna.segments * 0.5), 2, 5)</code></pre><p>The generator halves the raw gene, rounds it to a whole number, then keeps it between two and five. Distinct settings can become one instruction. We can inspect the conversion that makes the difference disappear.</p><blockquote>The number we moved and the instruction the generator received are different records.</blockquote></section>
<section><p class="step">02 / A DIFFERENT KIND OF CHANGE</p><h2>Give Angle a turn.</h2><p>GENE cycles through the eight controls. Angle changes the branch directions without adding a rewriting generation. Forks is rounded and clamped; Arrange selects among three rotation recipes. Similar-looking controls do different kinds of work.</p><figure><img loading="lazy" src="living-controls.png" alt="GENE LESS MORE HOLD PLANT RESET on a compact desk with a small transparent screen"><figcaption>All six physical buttons were operated through the project's DesktopPlayer pointer. The original eight-slider rack and RANDOM are retained at the side.</figcaption></figure><p>The screen reads raw values, compiled generations and forks, requested F/S commands and the drawing budget. At maximum Depth and Forks, the sentence requests 4,964 drawing commands. This preview stops after 200; very short segments may emit no mesh. A completed-looking crown can conceal a cutoff.</p></section>
<section><p class="step">03 / LEAVE A BODY HERE</p><h2>Change your mind. Keep the specimen.</h2><figure><img loading="lazy" src="living-planted.png" alt="A copied tree stands on the floor pad behind the workbench"><figcaption>PLANT copies the current geometry onto this pad. Later edits leave it unchanged. Another PLANT replaces this specimen.</figcaption></figure><p>The exported DNA used to be a live reference to the editable resource. It now receives a deep copy. HOLD and PLANT also finish any pending preview rebuild before making their copies. RESET restores only the editing tree.</p><p>This is a local specimen with visual branches. It does not reshape the floor or draw resources from Competition's soil. The older branching catalyst may use the exported DNA to build a mutated, rescaled, temporary tree elsewhere. That is a separate operation.</p></section>
<details><summary>Read the book passage</summary><article class="manuscript">__BOOK__</article></details>
<section><p class="step">04 / KEEP THE EARLIER WORK</p><h2>Other procedures remain beside it.</h2><div class="pair"><figure><img loading="lazy" src="living-before.png" alt="The original sculptor tucked between raised grid cells before staging"><figcaption>Before: a tiny sculptor among raised cells. The map and older manuscripts are archived.</figcaption></figure><figure><img loading="lazy" src="living-retained-collection.png" alt="The preserved raised terrain and earlier L-system collection behind the new workbench"><figcaption>The old 13×12 terrain, translated within a 19×36 m hall. The tree, coral and three paper studies keep their relative placement. The coral gains support; the old teleporter hole is filled.</figcaption></figure></div><p>The terrain is authored JSON, not the output of this tree grammar. Correcting that earlier claim leaves a useful question open: which mechanisms would let a growing form alter the space it occupies?</p></section>
<section><h2>What was checked?</h2><p>__CHECKS__ runtime checks cover museum instantiation, desktop pointer controls, unchanged geometry below the threshold, the added generation, independent DNA snapshots, fast export during a pending edit, bounded rendering, ordinary scene compatibility and the collision route through the hall. The final run exits cleanly with no GDScript errors.</p><p>These are actual Godot captures with synthetic desktop input. Human headset reach, readability, comfort and Quest timing remain pending. The older secondary interactions have been retained, not individually re-certified in VR.</p></section>
<section class="next"><h2>Next: two marks, many paths.</h2><p><a href="/necklace/thread?map=Assemblage_Same_Desire&amp;role=primary">Assemblage_Same_Desire</a> closes this sequence with a textile. We will distinguish the choices a procedure makes from the routes a reader finds in their arrangement.</p><p><a href="spine-iteration.html">Complete the journey, then return →</a></p></section><footer><a href="living-verification.json">Runtime receipt</a> · <a href="living-previous-final.md">Previous manuscript</a> · <a href="living-technical.md">Implementation</a> · <a href="living-critical.md">Critical questions</a></footer></main></body></html>'''
(O/'lsystems-living.html').write_bytes(page.replace('__CSS__',css).replace('__BOOK__',book).replace('__CHECKS__',str(r['checks'])).encode());assets.append('lsystems-living.html')
method=markdown.markdown((O/'spine-iteration.md').read_text(),extensions=['tables','toc'])
(O/'spine-iteration.html').write_bytes(('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>First traverse. Then return. · Ada Research</title><style>'+css+'table{width:100%;border-collapse:collapse;font-size:.9rem}td,th{border-bottom:1px solid #425050;padding:.6rem;text-align:left;vertical-align:top}@media(max-width:650px){table{display:block;overflow-x:auto}}</style></head><body><main><nav><a href="lsystems-living.html">Living</a><a href="lsystems-competition.html">Competition</a><a href="/museum-progress">Museum progress</a></nav><article class="manuscript">'+method+'</article></main></body></html>').encode())
assets+=['spine-iteration.html','spine-iteration.md']
for src,dst in [(RUN/'run.json',E/'receipt.json'),(RUN/M/'probe_ca_edge_live.json',E/'runtime-report.json'),(RUN/M/'engine.log',E/'engine.log')]:shutil.copyfile(src,dst)
targets=['possible-bodies/'+a for a in assets];dump(E/'publish-targets.json',targets);dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Living review: {len(targets)} assets; {r["checks"]} runtime checks.')
