"""Local illustrated review from a successful, current museum run."""
from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/koch-sierpinski-2026-09-14';RUN=R/'ada_run/koch-review-2026-09-14';M='Fractal_KochSierpinski'
def dump(p,d):p.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
r=json.loads((RUN/'run.json').read_text());report=json.loads((RUN/M/'probe_ca_edge_live.json').read_text())
assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for n in ['entrance','koch-start','koch-detour','koch-snowflake','sierpinski-kept','sierpinski-ghost','sierpinski-negative','measuring-cover','measuring-fit-1','measuring-fit-2','collection','overview']:
 p=O/f'koch-{n}.png';shutil.copyfile(RUN/M/f'{n}.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
 p=O/f'koch-{kind}.md';shutil.copyfile(R/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
 old=E/f'before/commons/maps/{M}/{kind}.md'
 if old.exists():
  p=O/f'koch-previous-{kind}.md';shutil.copyfile(old,p);assets.append(p.name)
dump(O/'koch-verification.json',r);assets.append('koch-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
fits=report['measurements']['fits_coarse_fine_all']
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The boundary takes a detour · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="fractal-learning-arc.html#Fractal_KochSierpinski">← The fractal walk</a><a href="/necklace/thread?map=Fractal_KochSierpinski&role=primary">Three primary artifacts / book</a><a href="/museum-progress?sequence=fractals&room=Fractal_KochSierpinski">Museum progress</a></nav>
<p class="eyebrow">ADA RESEARCH · KOCH / SIERPINSKI · 14 SEPTEMBER 2026</p><h1>The boundary<br>takes a detour.</h1><p class="lead">Keep the endpoints in view. Follow the growing line, turn the removed middles into the work, then change the grid that measures it.</p>
<div class="facts"><div><strong>10</strong><span>existing placements retained</span></div><div><strong>3</strong><span>primary encounters and book passages</span></div><div><strong>8,000</strong><span>held samples at the measuring bench</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="koch-entrance.png" alt="A line and a filled triangle wait behind compact control desks in the museum"><figcaption>Actual Godot capture. Three instruments occupy a study approach before the retained room. Each starts with a question and waits for a button press.</figcaption></figure>
<section><p class="step">01 / FRACTAL_KOCH_CURVE</p><h2>Where could more line go?</h2><p>NEXT replaces each segment with four joined thirds. BACK returns a generation. The ends stay four metres apart while the path grows from four to 12.642 metres. TURN changes which side receives the detour; FORM closes the starting boundary into a triangle.</p>
<div class="pair"><figure><img loading="lazy" src="koch-koch-start.png" alt="A four-metre line before any replacement, behind a six-button desk"><figcaption>One segment. Four metres between its ends and four along its path.</figcaption></figure><figure><img loading="lazy" src="koch-koch-detour.png" alt="The Koch curve at four replacements, with 256 segments and a longer path"><figcaption>Four replacements. 256 segments, 12.642 metres of path. The endpoints have not moved.</figcaption></figure></div>
<figure><img loading="lazy" src="koch-koch-snowflake.png" alt="The first outward replacement of a closed triangle"><figcaption>RESET → FORM → NEXT. The first outward replacement makes twelve segments and a fourteen-metre perimeter. TURN explores the other side.</figcaption></figure>
<blockquote>The count and length survive a reversal. They have not told us everything about the shape.</blockquote><p>RULE reveals the replacement after the encounter. The desk stops at four generations; its finite ribbons let us approach the standard Koch limit without claiming to render an infinite boundary.</p></section>
<section><p class="step">02 / SIERPINSKI_TRIANGLE</p><h2>Which part is the work?</h2><p>NEXT keeps three half-size corners. Their summed area is three quarters of the parent. Four cuts leave 81 triangles occupying about 4.93 square metres of the original 15.59.</p>
<figure><img loading="lazy" src="koch-sierpinski-kept.png" alt="Eighty-one retained triangles with recursive triangular gaps"><figcaption>VIEW: absence. Only the latest kept generation is drawn.</figcaption></figure>
<div class="pair"><figure><img loading="lazy" src="koch-sierpinski-ghost.png" alt="Pale removed middles appear between the retained triangles"><figcaption>VIEW: ghost. Forty removed middles record the four cuts alongside the latest kept triangles.</figcaption></figure><figure><img loading="lazy" src="koch-sierpinski-negative.png" alt="Coloured removed middles alone form an alternative triangular sculpture"><figcaption>VIEW: negative. The removed middles become the visible work. The code still computes the same 81 corner triangles.</figcaption></figure></div>
<blockquote>We did not need a new fractal to find another subject inside it.</blockquote><p>DEPTH changes the drawn thickness. It leaves the planar area unchanged. The sculpture has no collision: an opening in its image is a different claim from a passage in a solid structure.</p></section>
<section><p class="step">03 / BOX_COUNTING_DIMENSION</p><h2>What does this grid miss?</h2><p>This bench owns a separate, reproducible chaos-game sample. FINER and COARSER change the grid over the same 8,000 points. COVER makes every occupied cell visible. A crowded cell and a cell holding one point each count once.</p>
<figure><img loading="lazy" src="koch-measuring-cover.png" alt="A sixteen-by-sixteen grid with coloured occupied cells over the fixed point cloud"><figcaption>A 16×16 grid, 106 occupied cells. The blank neighbouring panel waits for RANGE before showing a fitted result.</figcaption></figure>
<div class="pair"><figure><img loading="lazy" src="koch-measuring-fit-1.png" alt="The point cloud with a regression line fitted to the three coarsest measurements"><figcaption>Coarse three: fitted slope __COARSE__.</figcaption></figure><figure><img loading="lazy" src="koch-measuring-fit-2.png" alt="The same point cloud with the fitted line based on the three finest measurements"><figcaption>Fine three: fitted slope __FINE__. The samples have not moved.</figcaption></figure></div>
<p>The six counts are 4, 14, 40, 106, 324 and 959. Fitting all six gives __ALL__. The ideal triangle's dimension, approximately 1.585, supplies a comparison; no selected finite fit is declared the exact dimension. The plot keeps all six measured points while fitting only the named range.</p>
<blockquote>The unoccupied cells tell us where this reading found no points. They have no authority over what may exist.</blockquote><p>This connects to <em>entropic morality</em> through the distinction between a model's omissions and the conditions it may be used to impose. The hall computes no entropy score. It lets the visitor revise a reading and see one of its limits.</p></section>
<details><summary>Read the book passage</summary><article>__BOOK__</article><p><a href="koch-final.md">Manuscript</a> · <a href="koch-technical.md">Implementation</a> · <a href="koch-critical.md">Critical questions</a> · <a href="koch-tutorial.md">Encounter order</a></p></details>
<section><h2>The earlier room remains.</h2><figure><img loading="lazy" src="koch-collection.png" alt="The retained architecture, recursive specimens and original raised cell in the rear museum room"><figcaption>The original room's enclosure and raised cell remain behind the new study area. The walking route passes around the cell.</figcaption></figure><p>The cabin, bookshelf, bent Koch arch, recursive pyramid, observatory, trace screen and dark sphere remain around the three primaries. The measuring bench had been omitted by the museum loader because its registry entry still marked it unavailable; the tested scene is now enabled.</p><p>The pyramid makes six recursive calls despite its five-copy comments. It remains a specimen of that implementation. The book no longer calls it a four-copy tetrahedron or treats every related form as evidence of the same dimension. <a href="koch-previous-final.md">Earlier prose</a> is preserved with source and map snapshots.</p></section>
<section><h2>What was checked?</h2><p>__CHECKS__ rendered checks cover all ten placements, three six-button desks through physical pointer input, finite counts and lengths, triangle areas and complement views, occupied-cell counts, independent fitting calculations, reproducible reset, ordinary scene modes, visible retained specimens and the route to the exit.</p><p class="note">Synthetic input uses the project's standalone DesktopPlayer rig inside the actual museum. This does not certify the native museum walker's interaction lane. Headset reach, comfort and Quest performance remain pending. The user's open editor, museum and saved hand were preserved.</p></section>
<section class="next"><h2>Next: a hole becomes a place.</h2><p>The Menger sponge carries removal into a volume. Its flight enclosure is already built. Next we develop the comparison between retained cubes, connected holes and passages a finite body can enter.</p><a href="menger-flight.html">The existing Menger flight installation →</a></section>
<footer><a href="koch-verification.json">Runtime receipt</a> · <a href="fractal-learning-arc.html">Seven-hall learning arc</a> · <a href="cantor-encounter.html">Previous: Cantor</a></footer></main></body></html>'''
for k,v in {'__CSS__':css,'__BOOK__':book,'__CHECKS__':str(r['checks']),'__COARSE__':f'{fits[0]:.3f}','__FINE__':f'{fits[1]:.3f}','__ALL__':f'{fits[2]:.3f}'}.items():page=page.replace(k,v)
(O/'koch-sierpinski.html').write_bytes(page.encode());assets.append('koch-sierpinski.html')
assets+=['fractal-learning-arc.html','fractal-learning-arc.json','fractal-learning-arc.md']
for n,src in [('receipt.json',RUN/'run.json'),('report.json',RUN/M/'probe_ca_edge_live.json'),('engine.log',RUN/M/'engine.log')]:shutil.copyfile(src,E/n)
targets=['possible-bodies/'+a for a in assets];dump(E/'publish-targets.json',targets)
dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Koch/Sierpinski review: {len(targets)} files, {r["checks"]} checks.')
