"""Publish the Synthesis encounter and the whole-spine iteration method."""
from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/fractal-synthesis-2026-09-14';RUN=R/'ada_run/synthesis-review-2026-09-14';M='Fractal_Synthesis'
def dump(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
r=json.loads((RUN/'run.json').read_text());assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for n in ['entrance','history','latest','ghost','tree-form','tree-strata','tree-reach','tree-ends','collection','held-fibonacci']:
 p=O/f'synthesis-{n}.png';shutil.copyfile(RUN/M/f'{n}.png',p);assets.append(p.name)
p=O/'synthesis-before.png';shutil.copyfile(E/f'baseline/{M}/entrance.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
 p=O/f'synthesis-{kind}.md';shutil.copyfile(R/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
 p=O/f'synthesis-previous-{kind}.md';shutil.copyfile(E/f'before/commons/maps/{M}/{kind}.md',p);assets.append(p.name)
dump(O/'synthesis-verification.json',r);assets.append('synthesis-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What, exactly, is repeated? · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="fractal-learning-arc.html#Fractal_Synthesis">← Fractal learning arc</a><a href="/necklace/thread?map=Fractal_Synthesis&amp;role=primary">Primary artifacts / book</a><a href="spine-iteration.html">Our working method</a></nav>
<p class="eyebrow">ADA RESEARCH · FRACTAL SYNTHESIS · 14 SEPTEMBER 2026</p><h1>What, exactly,<br>is repeated?</h1><p class="lead">The older rows disappear; the surviving pieces remain. A tree changes its reading without growing another branch. What would you tell the next call?</p>
<div class="facts"><div><strong>10</strong><span>original artifacts retained</span></div><div><strong>2</strong><span>primary book passages</span></div><div><strong>1</strong><span>new gallery fixture</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="synthesis-entrance.png" alt="Inside Fractal Synthesis, a block-tree desk on the left and a Cantor desk on the right"><figcaption>Actual Godot museum capture. Two existing instruments form a comparison, with a clear central route into the retained collection.</figcaption></figure>
<section><p class="step">01 / RECONSTRUCT THE INSTRUCTION</p><h2>More pieces. Less retained length.</h2><p>Describe the next cut before pressing NEXT. Six metres become two pieces of two metres; another cut gives four pieces with a combined length of about 2.667 metres. What did the procedure preserve, and what did it leave out?</p>
<div class="pair"><figure><img loading="lazy" src="synthesis-history.png" alt="Four rows of the Cantor construction including eight surviving bars at cut three"><figcaption>At cut three, eight pieces retain about 1.778 metres. The older rows record how this state was made.</figcaption></figure><figure><img loading="lazy" src="synthesis-latest.png" alt="The same eight current intervals with the older rows hidden"><figcaption>HISTORY hides the record. The current intervals and cut remain unchanged.</figcaption></figure></div>
<figure><img loading="lazy" src="synthesis-ghost.png" alt="Pale middle-thirds drawn between the surviving intervals"><figcaption>GHOST marks newly removed middles. These visual annotations are not surviving intervals or collision bodies.</figcaption></figure>
<blockquote>Making an absence visible does not, by itself, make that place available to stand on.</blockquote><p>Five cuts bound the instrument. RULE supplies the calculation after the comparison. RESET returns the local encounter to its uncut beginning.</p></section>
<section><p class="step">02 / READ THE SAME TREE</p><h2>Find a fork. Keep looking at it.</h2><p>The tree is already generated. Follow one branch through FORM, STRATA, REACH and ENDS. Its recorded levels, accumulated bounds and deepest blocks become visible in different ways. The generated meshes and their transforms stay the same.</p>
<div class="pair"><figure><img loading="lazy" src="synthesis-tree-form.png" alt="The block tree in its ordinary red material"><figcaption>FORM: the existing generated block tree, with its compact desk.</figcaption></figure><figure><img loading="lazy" src="synthesis-tree-strata.png" alt="The same block tree coloured by branch level"><figcaption>STRATA: colour reveals recorded branch levels without regrowing the tree.</figcaption></figure></div>
<div class="pair"><figure><img loading="lazy" src="synthesis-tree-reach.png" alt="Volumes enclosing the accumulated extent of the tree"><figcaption>REACH includes empty space inside its bounds. A bounding volume is not a solid shelter.</figcaption></figure><figure><img loading="lazy" src="synthesis-tree-ends.png" alt="Bounds with added marks at the deepest recorded blocks"><figcaption>ENDS marks deepest block centres. It does not measure biological tips or navigable space.</figcaption></figure></div>
<p>The original source passes a branch, an endpoint, a descendant count and increased depth into the next call. Local random choices give this tree its dimensions and directions. This desk inspects those choices; the next sequence will open the question of rewriting instructions.</p></section>
<details><summary>Read the book passage</summary><article class="manuscript">__BOOK__</article></details>
<section><h2>The collection keeps its place in the inquiry.</h2><figure><img loading="lazy" src="synthesis-collection.png" alt="The rear collection with the raised dark sphere, cloud, attractor and Fibonacci examples"><figcaption>All ten original works remain. The old enclosure and raised sphere cell are preserved behind a twelve-row approach. The unsupported teleporter floor hole is filled.</figcaption></figure>
<div class="pair"><figure><img loading="lazy" src="synthesis-held-fibonacci.png" alt="The retained Fibonacci examples held still for inspection"><figcaption>The Fibonacci views are constructed once from their original procedures. The downward diagram is brought above the floor. This is a held specimen, not a newly developed primary lesson.</figcaption></figure><figure><img loading="lazy" src="synthesis-before.png" alt="The earlier museum entrance with oversized overlapping works and standalone screen overlays"><figcaption>Before this pass: oversized works, excess lighting and screen interfaces over the museum. The baseline capture is archived; that run exceeded its three-minute deadline.</figcaption></figure></div>
<p>The gallery fixture supplies local lighting, a physical comparison prompt and explicitly held secondary specimens. The underlying Cantor, tree and Fibonacci algorithms are preserved. A duplicate Koch script UID was routing the scene to an older copy. The scene now uses its stated source; that source also accepts map configuration before its meshes are ready. The tree's standalone UI now resolves its own root correctly.</p></section>
<section><h2>What was tested?</h2><p>__CHECKS__ checks in the actual museum: both six-button desks through synthetic DesktopPlayer pointer input, interval counts and lengths, history and ghost behavior, unchanged tree geometry, physical button dimensions, held specimens, ordinary and preconfigured Koch modes, and the central walking route through the exit.</p><p>These are desktop checks. Human headset reach, comfort, readability and Quest performance remain pending, as do deeper encounters with the secondary works. The user's editor, live museum and saved hand were preserved. The old unrelated unresolved UID diagnostic remains in the engine log.</p></section>
<section class="next"><h2>Next: give instructions a body.</h2><p>Fractals now has a first pass through all seven halls. Continue to <a href="/necklace/thread?map=LSystems_Grammar_Lab&amp;role=primary">LSystems_Grammar_Lab</a>: distinguish a rewritten string from the geometry used to read it. Its preset called “Koch Curve” uses F → F+F-F-F+F with 90° turns, a different rule from our equilateral snowflake.</p><p>We will complete the whole spine, then return to its transitions and shared problems with a view of the full journey. <a href="spine-iteration.html">The method and next actionable improvements →</a></p></section>
<footer><a href="synthesis-verification.json">Runtime receipt</a> · <a href="synthesis-previous-final.md">Earlier manuscript</a> · <a href="synthesis-technical.md">Implementation</a> · <a href="golden-mapping.html">Previous: Golden Spiral</a></footer></main></body></html>'''
page=page.replace('__CSS__',css).replace('__BOOK__',book).replace('__CHECKS__',str(r['checks']))
(O/'fractal-synthesis.html').write_text(page,encoding='utf-8');assets.append('fractal-synthesis.html')
method=markdown.markdown((O/'spine-iteration.md').read_text(),extensions=['tables'])
(O/'spine-iteration.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>First traverse. Then return. · Ada Research</title><style>'+css+'table{width:100%;border-collapse:collapse;font-size:.9rem}td,th{border-bottom:1px solid #425050;padding:.6rem;text-align:left;vertical-align:top}@media(max-width:650px){table{display:block;overflow-x:auto}}</style></head><body><main><nav><a href="fractal-synthesis.html">Fractal Synthesis</a><a href="fractal-learning-arc.html">Fractal learning arc</a><a href="/museum-progress">Museum progress</a></nav><article class="manuscript">'+method+'</article></main></body></html>',encoding='utf-8')
assets+=['spine-iteration.html','spine-iteration.md','fractal-learning-arc.html','fractal-learning-arc.json','fractal-learning-arc.md','book-red-thread.md']
for src,dst in [(RUN/'run.json',E/'receipt.json'),(RUN/M/'probe_ca_edge_live.json',E/'runtime-report.json'),(RUN/M/'engine.log',E/'engine.log')]:shutil.copyfile(src,dst)
targets=['possible-bodies/'+a for a in assets];dump(E/'publish-targets.json',targets);dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Synthesis review and iteration method: {len(targets)} assets, {r["checks"]} runtime checks.')
