from pathlib import Path
import json,hashlib,shutil,re,markdown
R=Path.cwd();O=R/'doc/research/possible-bodies';E=R/'doc/space/iso-torus-gyroid-2026-09-15';run=R/'ada_run/iso-torus-gyroid-review-2026-09-15';M='ISO_TorusGyroid'
r=json.loads((run/'run.json').read_text());assert r['exit']==0 and r['sources_unchanged'];assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
css=re.search(r'<style>(.*?)</style>',(O/'iso-introduction.html').read_text(),re.S)[1]
assets=['iso-learning-arc.md','iso-learning-arc.html','spine-iteration.md','spine-iteration.html'];figures=''
for name in ['entrance','encounter','specimen','overview']:
 out='iso-torus-gyroid-'+name+'.png';shutil.copyfile(run/M/(name+'.png'),O/out);assets.append(out);figures+=f'<figure><img src="{out}" alt="Actual Godot Torus and Gyroid hall: {name}" loading="lazy"><figcaption>Actual Godot museum capture · {name}. Desktop review; headset review remains pending.</figcaption></figure>'
links=[]
for kind in ['final','technical','critical']:
 for before in [False,True]:
  p=(E/'before' if before else R)/f'commons/maps/{M}/{kind}.md'
  if p.exists():
   out='iso-torus-gyroid-'+('previous-' if before else '')+kind+'.md';shutil.copyfile(p,O/out);assets.append(out);links.append(f'<a href="{out}">{"Previous" if before else "Current"} {kind}</a>')
for src,name in [(run/'run.json','receipt.json'),(run/M/'probe_ca_edge_live.json','runtime-report.json'),(run/M/'engine.log','engine.log')]:shutil.copyfile(src,E/name)
shutil.copyfile(run/'run.json',O/'iso-torus-gyroid-verification.json');assets.append('iso-torus-gyroid-verification.json')
body='<p class="date">Isosurfaces · Hall 4 · 15 September 2026</p><h1>Repetition without separate pieces</h1><p class="lead">A hole can be visible before it is a passage.</p><p>Trace the torus reference, then compare the gyroid field. PERIOD changes repetition; INTRUSION restores erosion, modulation and warp. HOLD keeps independent earlier geometry behind the live specimen. RESET keeps that comparison.</p><p><a href="/necklace/thread?map=ISO_TorusGyroid&role=primary">Both primary artifacts and the book</a> · <a href="iso-learning-arc.html">Learning arc</a></p><details><summary>Read the book passage</summary>'+markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])+'</details>'+figures+'<h2>One path, three body widths</h2><p>The gold line marks a twelve-metre capsule sweep through the live field. PROBE cycles radii 0.20, 0.35 and 0.60 metres at a fixed height of 1.70 metres. Its warm marker and readout locate where actual collision stops that particular sweep. This is not a search for winding routes or a test of the full player controller.</p><p>The installed generator skips collision on meshes above 30,000 triangles. Some variants cross that limit. The desk reports an unavailable test rather than calling a missing collider a clear passage. The held surface is a visual comparison without collision.</p><p>The initial field is unperturbed and extracted at level one. It is a finite sampled trigonometric gyroid level set, not a claim to an exact minimal surface. All three original artifacts and historical floor cells remain, with an independent onward aisle.</p><p>'+str(r['checks'])+' rendered desktop checks passed: actual GPU meshes, controls, period and intrusion choices along the tested path, held geometry, clearance query and onward walking. This is not the full sixteen-combination matrix. Human headset reach, Quest performance and full interior navigation remain pending.</p><p><a href="iso-torus-gyroid-verification.json">Runtime receipt</a></p><p>'+' · '.join(links)+'</p><p>Next: <strong>ISO_Sculpting</strong> — restore the missing museum hall, then write into the field through a local gesture.</p>'
(O/'iso-torus-gyroid.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Repetition without separate pieces · Ada Research</title><style>'+css+'</style><main><nav><a href="iso-introduction.html">Introduction</a><a href="iso-learning-arc.html">Learning arc</a><a href="/museum-progress?sequence=isosurfaces">Museum progress</a></nav>'+body+'</main></html>',encoding='utf-8');assets.append('iso-torus-gyroid.html')
manifest=['possible-bodies/'+a for a in assets];(E/'publish-targets.json').write_text(json.dumps(manifest,indent=2));(E/'publish-hashes.json').write_text(json.dumps({a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in manifest},indent=2))
(R/'ada_run/publish_iso_gyroid.ps1').write_text((R/'ada_run/publish_iso_intro.ps1').read_text().replace('iso-introduction-2026-09-15','iso-torus-gyroid-2026-09-15'),encoding='utf-8')
print('Built',len(assets),'verified review assets.')
