"""Publish source-grounded Golden Spiral evidence after a successful run."""
from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/golden-mapping-2026-09-14';RUN=R/'ada_run/golden-review-2026-09-14';M='Fractal_GoldenSpiral'
def dump(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
r=json.loads((RUN/'run.json').read_text());assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for n in ['entrance','two-seeds','log-height','linear-height','unit-sum','held-examples','branch-example','rectangle-start','rectangle-measured','rectangle-arcs','romanesco','retained-room']:
 p=O/f'golden-study-{n}.png';shutil.copyfile(RUN/M/f'{n}.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
 p=O/f'golden-study-{kind}.md';shutil.copyfile(R/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
 p=O/f'golden-study-previous-{kind}.md';shutil.copyfile(E/f'before/commons/maps/{M}/{kind}.md',p);assets.append(p.name)
dump(O/'golden-study-verification.json',r);assets.append('golden-study-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>A number needs a mapping · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="fractal-learning-arc.html#Fractal_GoldenSpiral">← The fractal walk</a><a href="/necklace/thread?map=Fractal_GoldenSpiral&role=primary">Primary artifacts / book</a><a href="/museum-progress?sequence=fractals&room=Fractal_GoldenSpiral">Museum progress</a></nav>
<p class="eyebrow">ADA RESEARCH · GOLDEN SPIRAL · 14 SEPTEMBER 2026</p><h1>A number needs<br>a mapping.</h1><p class="lead">The numbers stay when the towers change height. The partition stays when the curve disappears. What did the next rule add?</p>
<div class="facts"><div><strong>7</strong><span>existing artifacts retained</span></div><div><strong>2</strong><span>primary book passages</span></div><div><strong>1, 1 → 55</strong><span>ten terms, two height mappings</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="golden-study-entrance.png" alt="The museum approach to a compact desk and two equal Fibonacci towers"><figcaption>Actual Godot capture. The sequence waits for the visitor; the existing spatial examples remain beyond it.</figcaption></figure>
<section><p class="step">01 / PREDICT THE NEXT TERM</p><h2>Two equal beginnings.</h2><p>Read the two ones. Decide what might follow before NEXT reveals another term. Continue to ten values, ending at 55. The labels and positions distinguish a term's address from its value.</p>
<figure><img loading="lazy" src="golden-study-two-seeds.png" alt="Two equal towers labelled one before further terms appear"><figcaption>The starting pair. NEXT and BACK control the number of visible terms.</figcaption></figure>
<h2>The numbers have not changed.</h2><p>HEIGHT switches the same values between the old logarithmic mapping and a fixed five-centimetre unit. The linear view carries addition in height; the logarithmic view keeps the early terms conspicuous while compressing the range.</p>
<div class="pair"><figure><img loading="lazy" src="golden-study-log-height.png" alt="Ten Fibonacci values shown as logarithmic towers"><figcaption>h = 0.5 ln(value) + 0.5 metres. The added base height and compression change how differences appear.</figcaption></figure><figure><img loading="lazy" src="golden-study-linear-height.png" alt="The same ten values represented at five centimetres per unit"><figcaption>Same camera and values: h = 0.05 × value metres. A one becomes easy to overlook.</figcaption></figure></div>
<blockquote>We can lose sight of a small value without removing it from the sequence.</blockquote>
<figure><img loading="lazy" src="golden-study-unit-sum.png" alt="Twenty-one units and thirty-four units stacked beside fifty-five units"><figcaption>SUM: 21 + 34 and 55 reach the same 2.75 m height. This fixed-unit witness stays independent of the tower mapping.</figcaption></figure>
<p>RULE reveals the recurrence after its outcomes have been compared. RESET returns to the two seeds. Neither changing height nor inspecting the sum alters the stored Fibonacci values.</p></section>
<section><p class="step">02 / INSPECT THE ADDED RULES</p><h2>A flower needs more instructions.</h2><p>The artifact's seed arrangement, layered scales, shell-like chambers, helix and branching diagram remain. They are built once and held still on supports. Their plates identify the extra choices of radius, turn, scale and descendants.</p>
<div class="pair"><figure><img loading="lazy" src="golden-study-held-examples.png" alt="Retained seed points, layered scales and shell-like chambers on a supported display"><figcaption>Related appearances use different constructions. No botanical equivalence is assumed.</figcaption></figure><figure><img loading="lazy" src="golden-study-branch-example.png" alt="The original downward branching diagram raised above a plinth"><figcaption>The branch diagram is brought above the floor. Its child count uses F(depth + 1) % 4 + 1.</figcaption></figure></div>
<p>The retained helix multiplies radius by phi per full turn, which differs from a golden logarithmic spiral's quarter-turn multiplier. The label now states the implemented rule. The scene's previously contradictory source path and UID are also aligned with the source it was actually running.</p></section>
<section><p class="step">03 / CUT, MEASURE, THEN DRAW</p><h2>What survives a square?</h2><p>The second desk presents the existing rectangle upright. Predict the remainder, then request one cut at a time. MEASURE labels actual square side lengths and reports the remainder's long/short ratio.</p>
<div class="pair"><figure><img loading="lazy" src="golden-study-rectangle-start.png" alt="A five-metre golden rectangle before cutting"><figcaption>Start: 5 by 5/phi metres.</figcaption></figure><figure><img loading="lazy" src="golden-study-rectangle-measured.png" alt="Five successively smaller squares labelled with measured sides"><figcaption>Five cuts: approximately 3.090, 1.910, 1.180, 0.729 and 0.451 m. Cut numbers increase while side lengths shrink.</figcaption></figure></div>
<p>The squares and the last remainder account for the original area. The remainder changes orientation while retaining a long/short ratio near 1.618034. The increasing Fibonacci labels formerly placed on these squares did not measure their size.</p>
<figure><img loading="lazy" src="golden-study-rectangle-arcs.png" alt="Joined quarter-circle arcs drawn through the measured squares"><figcaption>ARC adds a drawing to the partition. Corrected centres and included endpoints make the circular pieces meet. They are sampled circular arcs, not an exact logarithmic spiral.</figcaption></figure>
<blockquote>The proportion leaves further choices open.</blockquote><p>Turn ARC off and the partition remains. Add more cuts and the smallest features become harder to read. A limit of eight cuts bounds this desk's construction.</p></section>
<details><summary>Read the book passage</summary><article class="manuscript">__BOOK__</article></details>
<section><h2>The room beyond remains.</h2><div class="pair"><figure><img loading="lazy" src="golden-study-retained-room.png" alt="The retained rear museum room with its existing collection and original raised cell"><figcaption>The old 17×15 structure is retained behind the new approach. All seven authored artifacts remain; two now lead the book.</figcaption></figure><figure><img loading="lazy" src="golden-study-romanesco.png" alt="The retained Romanesco made from nested cone generations"><figcaption>Romanesco now attaches each bud to its actual parent. Its constructed resemblance is not a biological explanation.</figcaption></figure></div>
<p>The recursion cabinet existed but was being omitted because its registry did not make it available to maps. It now appears. The terrain, aggregation and dark sphere retain their own roles and behavior. Earlier manuscripts and the complete map are archived.</p></section>
<section><h2>What was checked?</h2><p>__CHECKS__ rendered checks cover all seven placements, both six-button desks through the real DesktopPlayer pointer pipeline, recurrence and mappings, fixed-unit sums, unchanged examples, geometric proportions and area, arc endpoints and bounds, reset, ordinary source modes, nested Romanesco buds and the walking route through the hall.</p><p>All source hashes match the final run. Human headset reach, comfort, readability and Quest frame time remain pending. Synthetic DesktopPlayer input does not certify native museum mouse interaction. The existing editor, live museum and saved hand were preserved. The wider 23-cell hall exceeds the automatic width recommendation to retain the full-sized examples; its route was tested explicitly.</p></section>
<section class="next"><h2>Next: choose a procedure.</h2><p>Fractal Synthesis gathers calls, branching, removal, measurement and numerical history. Before naming the desired shape, describe what one step receives, changes and passes on. That prepares the move into symbolic rewriting in L-systems.</p><a href="/necklace/thread?map=Fractal_Synthesis&role=primary">Continue to Fractal_Synthesis →</a></section>
<footer><a href="golden-study-verification.json">Runtime receipt</a> · <a href="golden-study-previous-final.md">Earlier manuscript</a> · <a href="fractal-learning-arc.html">Seven-hall learning arc</a> · <a href="menger-encounter.html">Previous: Menger</a></footer></main></body></html>'''
page=page.replace('__CSS__',css).replace('__BOOK__',book).replace('__CHECKS__',str(r['checks']))
(O/'golden-mapping.html').write_text(page,encoding='utf-8');assets.append('golden-mapping.html')
for name in ['fractal-learning-arc.html','fractal-learning-arc.json','fractal-learning-arc.md']:assets.append(name)
shutil.copyfile(RUN/'run.json',E/'receipt.json');shutil.copyfile(RUN/M/'probe_ca_edge_live.json',E/'runtime-report.json');shutil.copyfile(RUN/M/'engine.log',E/'engine.log')
targets=['possible-bodies/'+a for a in assets];dump(E/'publish-targets.json',targets);dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Golden Spiral review: {len(targets)} assets, {r["checks"]} checks.')
