"""Build the Growth review from the accepted Godot run and current manuscripts."""
from pathlib import Path
import hashlib,json,re,shutil
import markdown

R=Path(__file__).resolve().parents[1]
O=R/'doc/research/possible-bodies'
E=R/'doc/space/lsystems-growth-2026-09-14'
RUN=R/'ada_run/growth-review-2026-09-14'
M='LSystems_Growth'
def dump(p,d):p.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode('utf-8'))
receipt=json.loads((RUN/'run.json').read_text())
assert receipt['exit']==0 and not receipt['failures'] and receipt['sources_unchanged'] and receipt['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in receipt['source_sha256'].items())
assets=[]
for name in ['entrance','save-state','branch','return','equal-lengths','longer-branches','two-generations','controls','collection']:
    p=O/f'growth-{name}.png';shutil.copyfile(RUN/M/f'{name}.png',p);assets.append(p.name)
p=O/'growth-before.png';shutil.copyfile(E/f'baseline/{M}/entrance.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
    for previous in [False,True]:
        p=O/f'growth-{"previous-" if previous else ""}{kind}.md'
        shutil.copyfile((E/'before' if previous else R)/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
dump(O/'growth-verification.json',receipt);assets.append('growth-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What a branch remembers · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="grammar-lab.html">← Grammar Lab</a><a href="/necklace/thread?map=LSystems_Growth&amp;role=primary">Primary artifact / book</a><a href="spine-iteration.html">Our working method</a></nav>
<p class="eyebrow">ADA RESEARCH · L-SYSTEMS / 02 · 14 SEPTEMBER 2026</p>
<h1>What a branch<br>remembers.</h1><p class="lead">The point returns to the fork. Its branch remains. What was saved, and what was allowed to continue?</p>
<div class="facts"><div><strong>5</strong><span>earlier artifacts retained</span></div><div><strong>1</strong><span>program to follow</span></div><div><strong>6</strong><span>physical desk controls</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="growth-save-state.png" alt="Godot museum, compact desk facing two short upright lines; SAVE changes the next length while both cursor points remain at the fork"><figcaption>The opening bracket saves the travelling state. The point stays put, while the next stride becomes 0.576 metres. An operation has happened without adding a line.</figcaption></figure>
<section><p class="step">01 / FOLLOW THE PROGRAM</p><h2>A departure with a return.</h2><p>One rewrite has produced <code>F[+F]F[-F]F</code>. The first F has drawn a 0.8-metre trunk segment. STEP reveals the next symbol: save, turn, draw, return. HOLD keeps an earlier reading beside the live one.</p>
<div class="pair"><figure><img loading="lazy" src="growth-branch.png" alt="Two matching short branches, both cursor points at their branch tips"><figcaption>After the turn and F, HOLD keeps the point at the branch tip.</figcaption></figure><figure><img loading="lazy" src="growth-return.png" alt="The live cursor returns to the fork, while the held cursor stays at the branch tip"><figcaption>Closing bracket: the live point returns. No return line is drawn and no branch erased.</figcaption></figure></div>
<p>A stack stores position, orientation, length, angle and depth. Its most recent saved record returns first. The next F can continue the trunk with its former heading and 0.8-metre stride. The book stays with this operation long enough to explain how it works and what its record leaves outside.</p>
<blockquote>A return can preserve what happened during a departure while allowing something else to continue.</blockquote></section>
<section><p class="step">02 / PRESS THE NAME OF A VARIABLE</p><h2>Does decay have to shorten?</h2><p>Finish the eleven symbols and HOLD. RATIO changes the live reading from 0.72 to 1.00, then 1.15. The sentence and turning choices stay the same. Both drawings use the original segment endpoints in metres, with no fitting to their plinths.</p>
<div class="pair"><figure><img loading="lazy" src="growth-equal-lengths.png" alt="Live branches with ratio one beside the held tree with shorter branches"><figcaption>Ratio 1.00: the child stride equals its parent's 0.8 metres.</figcaption></figure><figure><img loading="lazy" src="growth-longer-branches.png" alt="Live branches with ratio 1.15 beside the same held reference"><figcaption>Ratio 1.15: the first child stride becomes 0.92 metres. The pink reference retains 0.72.</figcaption></figure></div>
<p>The source says <code>current_length *= length_decay</code>. Its name suggests shortening; the multiplication also permits lengthening. Which proportion made the drawing look like a proper tree?</p></section>
<section><p class="step">03 / LET THE SAME OPERATION ACCUMULATE</p><h2>A branch inside a branch.</h2><figure><img loading="lazy" src="growth-two-generations.png" alt="Tall cyan second-generation tree against an eight-metre ruler beside the short pink first-generation reference"><figcaption>An elevated inspection view inside the actual museum. Two generations give 61 symbols and 25 segments. The trunk reaches 7.2 metres; at ratio 1.15, a twice-nested stride is 1.058 metres. This is no longer a comparison of ratio alone: the live generation has changed too.</figcaption></figure>
<p>STEP reveals records from the actual interpreter. TREE toggles one and two complete rewriting generations. The first investigates an instruction; the second changes the sentence being read. RESET restores the initial line and reference.</p>
<p>These thin branches have no collision surfaces. Their visible reach raises a further question without pretending to answer it: what would we need before they could support or shelter a body?</p></section>
<section><h2>Keep the controls within reach.</h2><figure><img loading="lazy" src="growth-controls.png" alt="Six full-sized push buttons in a compact three-by-two desk with a transparent tilted rule screen"><figcaption>STEP / RATIO / HOLD, then TREE / RESET / RULE. The screen remains small and transparent. The actual DesktopPlayer pointer operated every control; human headset reach remains to be checked.</figcaption></figure><p>The short sentence appears in full. Longer sentences show a local window with an explicit symbol index and total. That text window does not truncate the geometry. A separate allocation budget refuses a whole further generation when necessary.</p></section>
<details><summary>Read the book passage</summary><article class="manuscript">__BOOK__</article></details>
<section><h2>Build on the earlier collection.</h2><div class="pair"><figure><img loading="lazy" src="growth-collection.png" alt="The rear Growth collection and retained corridor structures inside the museum"><figcaption>The four other works remain beyond the new desk: AnimatedTree, ContextSensitiveTree, lsystem_tree and modulor_cypress. Their independent studies remain available for further development.</figcaption></figure><figure><img loading="lazy" src="growth-before.png" alt="Archived view of the previous Growth hall before the new approach and controls"><figcaption>Before this pass. The map, earlier manuscripts and two historical grid versions are archived.</figcaption></figure></div>
<p>The former 13×12 structure is preserved at offset (3,16) in a 19×28 hall. An unused teleporter hole is filled; a tested route goes around the plinths, through the earlier collection and out. The animated tree's stale scene path now names its actual source.</p><p>The earlier writing described a matched corridor-versus-clearing experiment and a neighbouring-symbol rewriting table. The installed sources do not establish those claims. ContextSensitiveTree queries physical obstacles during interpretation. A controlled obstacle comparison is a useful next experiment; it remains distinct from the primary's saved-state lesson.</p></section>
<section><h2>What was verified?</h2><p>__CHECKS__ checks in the actual endless museum: five artifacts, every desk operation through the real pointer, saved state and held geometry, length ratios, unchanged turning directions, common metre scale, nested strides, four ordinary presets, configuration before readiness, complete-generation budgets, empty drawings and the walk through the exit.</p><p>No GDScript errors occurred. An older unrelated unresolved UID diagnostic remains. Headset reach, readability, comfort and Quest timing are pending. The user's editor and saved hand were preserved. These photographs are Godot captures, not proposed renders.</p></section>
<section class="next"><h2>Next: forward can be read sideways.</h2><p><a href="/necklace/thread?map=LSystems_Grammars_And_Curves&amp;role=primary">LSystems_Grammars_And_Curves</a> carries this travelling state to the believing turtle. Keep a sentence, change what a movement instruction does, then look for local correspondence. Step length and display limits need to be distinguished from that change.</p><p>The reusable instrument is a held interpreter trace: actual state, a visible cursor, an unchanged reference and a declared scale. It can clarify other procedural drawings where a finished form conceals how the program got there. <a href="spine-iteration.html#writing-the-book">Stay with the operation →</a></p></section>
<footer><a href="growth-verification.json">Runtime receipt</a> · <a href="growth-previous-final.md">Earlier manuscript</a> · <a href="growth-technical.md">Implementation</a> · <a href="growth-critical.md">Critical questions</a></footer></main></body></html>'''
(O/'lsystems-growth.html').write_bytes(page.replace('__CSS__',css).replace('__BOOK__',book).replace('__CHECKS__',str(receipt['checks'])).encode('utf-8'));assets.append('lsystems-growth.html')
method=markdown.markdown((O/'spine-iteration.md').read_text(),extensions=['tables','toc'])
(O/'spine-iteration.html').write_bytes(('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>First traverse. Then return. · Ada Research</title><style>'+css+'table{width:100%;border-collapse:collapse;font-size:.9rem}td,th{border-bottom:1px solid #425050;padding:.6rem;text-align:left;vertical-align:top}@media(max-width:650px){table{display:block;overflow-x:auto}}</style></head><body><main><nav><a href="lsystems-growth.html">Growth</a><a href="grammar-lab.html">Grammar Lab</a><a href="/museum-progress">Museum progress</a></nav><article class="manuscript">'+method+'</article></main></body></html>').encode('utf-8'))
assets+=['spine-iteration.html','spine-iteration.md','fractal-learning-arc.html','fractal-learning-arc.json','fractal-learning-arc.md']
for src,dst in [(RUN/'run.json',E/'receipt.json'),(RUN/M/'probe_ca_edge_live.json',E/'runtime-report.json'),(RUN/M/'engine.log',E/'engine.log')]:shutil.copyfile(src,dst)
targets=['possible-bodies/'+a for a in assets]
dump(E/'publish-targets.json',targets)
dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Growth review: {len(targets)} assets; {receipt["checks"]} runtime checks.')
