from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/lsystems-architecture-2026-09-14';RUN=R/'ada_run/architecture-review-2026-09-14';M='LSystems_Architecture'
def dump(p,d):p.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
r=json.loads((RUN/'run.json').read_text());assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for name in ['entrance','plan','built','inside','narrow','shared-room','room-inside','controls','original-model','collection']:
 p=O/f'architecture-{name}.png';shutil.copyfile(RUN/M/f'{name}.png',p);assets.append(p.name)
p=O/'architecture-before.png';shutil.copyfile(E/f'baseline/{M}/entrance.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
 for previous in [False,True]:
  p=O/f'architecture-{"previous-" if previous else ""}{kind}.md';shutil.copyfile((E/'before' if previous else R)/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
dump(O/'architecture-verification.json',r);assets.append('architecture-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>When a line acquires walls · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="grammar-curves.html">← Grammars and Curves</a><a href="/necklace/thread?map=LSystems_Architecture&amp;role=primary">Primary artifact / book</a><a href="spine-iteration.html">Our working method</a></nav>
<p class="eyebrow">ADA RESEARCH · L-SYSTEMS / 04 · 14 SEPTEMBER 2026</p><h1>When a line<br>acquires walls.</h1><p class="lead">The line reaches the other side. Your body stops at the entrance. What has to be added before a branching plan becomes a place?</p>
<div class="facts"><div><strong>9</strong><span>authored works retained</span></div><div><strong>4</strong><span>fixed centreline segments</span></div><div><strong>2 → 1</strong><span>room records → address</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="architecture-inside.png" alt="Inside the actual Godot corridor: pale floor, solid low walls and glass around an open junction"><figcaption>Inside the 1.4-metre corridor. Glass gives enclosure without hiding the other branches. The walls are collision surfaces; the junction has no internal partitions.</figcaption></figure>
<section><p class="step">01 / KEEP THE PROGRAM</p><h2>Four moves. Then build.</h2><p>The existing dungeon's branch rule rewrites F once into <code>F[+RF][-RF]F</code>. The actual interpreter supplies four segments and two room records. The lesson maps each unit movement to four metres; it never fits the plan to a display.</p>
<div class="pair"><figure><img loading="lazy" src="architecture-plan.png" alt="Four centrelines and a flat cross-shaped footprint inside a brass frame"><figcaption>PLAN: a footprint you can read while the museum floor supports you. It adds no collision.</figcaption></figure><figure><img loading="lazy" src="architecture-built.png" alt="The same cross with built slabs and glass walls"><figcaption>BUILD: the same records acquire slabs, outside walls and two explicit main openings. Side ends remain closed.</figcaption></figure></div>
<p>Return to the desk outside the brass frame before rebuilding. The controls refuse while someone remains inside; leaving does not trigger a queued change.</p></section>
<section><p class="step">02 / COUNT THE ADDRESSES</p><h2>Two Rs. One shared place.</h2><p>Both bracketed branches start from the saved junction. R records its current position without moving, so the two records coincide. ROOMS adds one 2.8×2.8-metre footprint there. The union retains each occupied cell once.</p>
<pre><code>rooms.append(pos)</code></pre>
<div class="pair"><figure><img loading="lazy" src="architecture-shared-room.png" alt="A square ochre room footprint expands the shared central junction"><figcaption>The grammar has not changed. A footprint policy turns the shared address into a larger place.</figcaption></figure><figure><img loading="lazy" src="architecture-room-inside.png" alt="Eye-height view standing off the centreline inside the enlarged junction"><figcaption>The desktop body can step off the centreline and return to the route. What could this extra room be used for?</figcaption></figure></div>
<p>Walls are placed only at exposed edges of the footprint union. An adjacent occupied cell means that edge is internal:</p><pre><code>if occupied.has(cell + direction): continue</code></pre><p>Door positions, corridor width, wall height and collision are supplied by construction. Naming a segment a corridor does not supply them.</p></section>
<section><p class="step">03 / ASK WHICH BODY</p><h2>A connected line can refuse passage.</h2><figure><img loading="lazy" src="architecture-narrow.png" alt="The same connected cross at forty centimetres clear width"><figcaption>WIDTH keeps the four segments fixed while cycling 1.4 → 2.2 → 0.4 → 1.4 metres. The 0.6-metre desktop capsule stops at the 0.4-metre entrance.</figcaption></figure><blockquote>Every branch still meets the same junction in the plan. The space available to this body has changed.</blockquote><p>This is a measured comparison for the tested desktop body. Other avatars and headset movement need their own checks. More branching would not solve the entrance-width problem.</p></section>
<section><h2>A small desk outside the construction.</h2><figure><img loading="lazy" src="architecture-controls.png" alt="Six physical buttons and a small transparent tilted screen"><figcaption>PLAN · BUILD · WIDTH · ROOMS · RESET · RULE. All six were exercised through the actual DesktopPlayer pointer. RESET restores the opening plan at 1.4 m, with rooms off.</figcaption></figure></section>
<details><summary>Read the book passage</summary><article class="manuscript">__BOOK__</article></details>
<section><p class="step">04 / KEEP THE EXISTING WORK</p><h2>The miniature remains.</h2><div class="pair"><figure><img loading="lazy" src="architecture-before.png" alt="Baseline Architecture hall before the front study was added"><figcaption>Before: all nine tokens were present, including a miniature dungeon. The old text promised construction rules and walkability that this miniature did not implement.</figcaption></figure><figure><img loading="lazy" src="architecture-original-model.png" alt="The retained miniature dungeon on its new rear plinth"><figcaption>Warren, depth three, fitted display: the original miniature retains its grammar and geometry. The full-size lesson uses a separate reading through the same interpreter.</figcaption></figure></div><figure><img loading="lazy" src="architecture-collection.png" alt="Retained Architecture collection inside its original raised layout"><figcaption>Eight other works keep their relative placement and algorithms. The original 13×12 structure is embedded at (3,23) in a 19×39 hall. Rear turning space separates its old wall from the museum's exit frame.</figcaption></figure><p>CityGenerator remains an orthogonal 3D branch structure. The folded dragon path, seed, mesh grammar specimens and catalyst objects are retained for deeper development. The earlier essays and manuscripts remain linked below.</p></section>
<section><h2>What was checked?</h2><p>__CHECKS__ Godot checks cover the nine instances, all controls, fixed records, shared room address, construction states, occupied-space refusals, body-specific narrow/wide passage, an open junction, original miniature compatibility and the complete museum exit route. No GDScript errors occurred. Headset reach, readability, comfort and Quest timing remain pending.</p><p>These are actual Godot captures. Testing used synthetic input through the project's DesktopPlayer pointer and movement; it is not a headset or human walk-through. The museum floor remains under the study in every state.</p></section>
<section class="next"><h2>Next: an instruction meets another world.</h2><p><a href="/necklace/thread?map=LSystems_Competition&amp;role=primary">LSystems_Competition</a> asks what conditions permit the next growth operation. We will inspect those conditions before treating the resulting scene as an ecology.</p><p><a href="spine-iteration.html">Complete the whole journey, then return →</a></p></section>
<footer><a href="architecture-verification.json">Runtime receipt</a> · <a href="architecture-previous-final.md">Previous manuscript</a> · <a href="architecture-technical.md">Implementation</a> · <a href="architecture-critical.md">Critical questions</a></footer></main></body></html>'''
(O/'lsystems-architecture.html').write_bytes(page.replace('__CSS__',css).replace('__BOOK__',book).replace('__CHECKS__',str(r['checks'])).encode());assets.append('lsystems-architecture.html')
method=markdown.markdown((O/'spine-iteration.md').read_text(),extensions=['tables','toc'])
(O/'spine-iteration.html').write_bytes(('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>First traverse. Then return. · Ada Research</title><style>'+css+'table{width:100%;border-collapse:collapse;font-size:.9rem}td,th{border-bottom:1px solid #425050;padding:.6rem;text-align:left;vertical-align:top}@media(max-width:650px){table{display:block;overflow-x:auto}}</style></head><body><main><nav><a href="lsystems-architecture.html">Architecture</a><a href="grammar-curves.html">Grammars and Curves</a><a href="/museum-progress">Museum progress</a></nav><article class="manuscript">'+method+'</article></main></body></html>').encode())
assets+=['spine-iteration.html','spine-iteration.md']
for src,dst in [(RUN/'run.json',E/'receipt.json'),(RUN/M/'probe_ca_edge_live.json',E/'runtime-report.json'),(RUN/M/'engine.log',E/'engine.log')]:shutil.copyfile(src,dst)
targets=['possible-bodies/'+a for a in assets];dump(E/'publish-targets.json',targets);dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Architecture review: {len(targets)} assets; {r["checks"]} runtime checks.')
