from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="QFEP_Lambda_Spectrum"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/qfep-lambda-spectrum-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]
tokens=[x.strip().split(":",1)[0].split("#",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":13,"depth":22,"max_height":3},"ten_artifacts":len(tokens)==10 and len(set(tokens))==10,"primary_focus":roles.get("lambda_hall")=="primary" and sum(v=="primary" for v in roles.values())==1,"registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid_structure":all(len(data["layers"][k])==22 and len(data["layers"][k][0])==13 for k in ["structure","utilities","interactables"])}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["lambda_hall"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"qfep-lambda-spectrum-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="l-title l-desc" xmlns="http://www.w3.org/2000/svg"><title id="l-title">A spectrum from order to chaos</title><desc id="l-desc">A path crosses a regular lattice, a complex middle, and a dispersed field.</desc><rect width="900" height="280" rx="18" fill="#121827"/><g stroke-width="4"><path d="M90 205H810" stroke="#8fc7d5"/><path d="M130 165h150M130 135h150M130 105h150M130 75h150" stroke="#85c89a"/><path d="M390 195l35-90m15 90l35-90m15 90l35-90m15 90l35-90" stroke="#d887b7"/><g stroke="#e9b86f"><path d="M700 80l20 100M750 65l-30 130M790 95l-25 95M835 70l-35 125"/></g></g><circle cx="450" cy="205" r="14" fill="#f0d48c"/><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff"><text x="205" y="245" font-size="18">regular</text><text x="450" y="245" font-size="18">edge</text><text x="770" y="245" font-size="18">dispersed</text><text x="450" y="42" font-size="22">λ is a weighting, not a universal verdict</text></g></svg><figcaption>The hall makes a curatorial spectrum walkable while keeping its chosen middle provisional.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="qfep-lambda-spectrum-verification.json">Verification record</a></p>'
body='<p class="date">QFEP laboratory · Lambda spectrum · 15 September 2026</p><h1>The Path the Hall Recommends</h1><p class="lead">A regular lattice and a dispersed field are easy to name. The interesting work happens where the route between them starts making a preference.</p><p><a href="/necklace/thread?map=QFEP_Lambda_Spectrum&amp;role=primary">Primary artifact and book</a> · <a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></p>'+diagram+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Weighting becomes orientation</h2><p>The lambda hall is the sole primary artifact. Edge particles, the bifurcation walkway, ordered grid, complexity pattern, dissolving form, and phase objects remain secondary supports that let the learner compare anticipation, variation, and return without turning the chosen middle into a law of nature.</p><p>The next hall, <a href="qfep-phi-term.html"><strong>QFEP_Phi_Term</strong></a>, introduces time and asks how a system responds while it changes.</p>'+score
(O/"qfep-lambda-spectrum.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The Path the Hall Recommends · Ada Research</title><style>'+css+'</style><main><nav><a href="qfep-e-term.html">Previous hall</a><a href="qfep-phi-term.html">Next hall</a><a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["qfep-lambda-spectrum.html","qfep-lambda-spectrum-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
