from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="QFEP_Phi_Term"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/qfep-phi-term-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]
tokens=[x.strip().split(":",1)[0].split("#",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":13,"depth":12,"max_height":3},"eight_placements":len(tokens)==8 and len(set(tokens))==7,"primary_focus":roles.get("phi_slider")=="primary" and roles.get("transforming_pattern")=="primary" and sum(v=="primary" for v in roles.values())==2,"registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid_structure":all(len(data["layers"][k])==12 and len(data["layers"][k][0])==13 for k in ["structure","utilities","interactables"])}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["phi_slider","transforming_pattern"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"qfep-phi-term-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="p-title p-desc" xmlns="http://www.w3.org/2000/svg"><title id="p-title">A signed direction of change</title><desc id="p-desc">A slider crosses zero while two patterned traces move in opposite directions.</desc><rect width="900" height="280" rx="18" fill="#121827"/><path d="M120 155H780" stroke="#8fc7d5" stroke-width="8"/><path d="M450 95V215" stroke="#f0d48c" stroke-width="5"/><circle cx="285" cy="155" r="20" fill="#d887b7"/><circle cx="615" cy="155" r="20" fill="#85c89a"/><path d="M140 95q120 80 240 0t240 0t240 0" fill="none" stroke="#d887b7" stroke-width="5"/><path d="M140 215q120-80 240 0t240 0t240 0" fill="none" stroke="#85c89a" stroke-width="5"/><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff"><text x="285" y="190" font-size="18">resist</text><text x="450" y="80" font-size="18">φ = 0</text><text x="615" y="190" font-size="18">welcome</text><text x="450" y="260" font-size="17">a sign gives change direction; it does not name improvement</text></g></svg><figcaption>Signed change can be felt as direction while its value remains open to interpretation.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="qfep-phi-term-verification.json">Verification record</a></p>'
body='<p class="date">QFEP laboratory · Phi term · 15 September 2026</p><h1>Giving Change a Sign</h1><p class="lead">A direction can be encoded without being mistaken for improvement. Cross zero, then watch what the sign makes visible.</p><p><a href="/necklace/thread?map=QFEP_Phi_Term&amp;role=primary">Primary artifacts and book</a> · <a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></p>'+diagram+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Direction before judgement</h2><p>The phi slider and transforming pattern carry the two primary arguments. The rigid sculpture, fluid form, preserved pattern, and lambda promenade remain secondary contrasts. The slider supplies a signed parameter; the pattern supplies a changing trajectory. At present they sit beside one another rather than pretending that one measures the other.</p><p>The next hall, <a href="qfep-edge-of-chaos.html"><strong>QFEP_Edge_Of_Chaos</strong></a>, brings weighting and change together at a boundary.</p>'+score
(O/"qfep-phi-term.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Giving Change a Sign · Ada Research</title><style>'+css+'</style><main><nav><a href="qfep-lambda-spectrum.html">Previous hall</a><a href="qfep-edge-of-chaos.html">Next hall</a><a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["qfep-phi-term.html","qfep-phi-term-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
