from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="QFEP_Sandbox"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/qfep-sandbox-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]
tokens=[x.strip().split(":",1)[0].split("#",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":14,"depth":16,"max_height":4},"six_artifacts":len(tokens)==6 and len(set(tokens))==6,"primary_focus":roles.get("lambda_slider")=="primary" and roles.get("phi_slider")=="primary" and sum(v=="primary" for v in roles.values())==2,"registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"layer_shapes":len(data["layers"]["structure"])==14 and len(data["layers"]["utilities"])==14 and len(data["layers"]["interactables"])==16 and len(data["layers"]["structure"][0])==14}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["lambda_slider","phi_slider"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"qfep-sandbox-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="s-title s-desc" xmlns="http://www.w3.org/2000/svg"><title id="s-title">Two handles, one receiver</title><desc id="s-desc">Lambda and phi controls point toward a reactor whose response must be checked.</desc><rect width="900" height="280" rx="18" fill="#121827"/><circle cx="690" cy="145" r="70" fill="#6c4e9e" stroke="#f0d48c" stroke-width="6"/><circle cx="690" cy="145" r="30" fill="#d887b7"/><path d="M180 95L620 135M180 205L620 155" stroke="#8fc7d5" stroke-width="8"/><circle cx="180" cy="95" r="28" fill="#85c89a"/><circle cx="180" cy="205" r="28" fill="#e9b86f"/><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff"><text x="180" y="100" font-size="18">λ</text><text x="180" y="211" font-size="18">φ</text><text x="690" y="150" font-size="18">receiver</text><text x="450" y="42" font-size="22">a moving handle is not yet a causal connection</text><text x="450" y="260" font-size="17">show the input beside the response before naming the effect</text></g></svg><figcaption>The sandbox makes the missing link visible: controls need a receiver and an observable response.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="qfep-sandbox-verification.json">Verification record</a></p>'
body='<p class="date">QFEP laboratory · Sandbox · 15 September 2026</p><h1>Where the Control Reaches</h1><p class="lead">A handle can move beautifully without governing anything beyond itself. The experiment begins when an input and a response are shown together.</p><p><a href="/necklace/thread?map=QFEP_Sandbox&amp;role=primary">Primary artifacts and book</a> · <a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></p>'+diagram+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Control needs a receiver</h2><p>The lambda and phi sliders are the two primary artifacts. The reactive particles, formula, and reactor remain secondary supports, and the existing text keeps their incomplete linkage visible. Compare one handle at a time, restore the initial state, and record the receiver’s actual input before interpreting its movement.</p><p>The next hall, <a href="qfep-synthesis.html"><strong>QFEP_Synthesis</strong></a>, gathers the terms into a specimen rather than a control panel.</p>'+score
(O/"qfep-sandbox.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Where the Control Reaches · Ada Research</title><style>'+css+'</style><main><nav><a href="qfep-edge-of-chaos.html">Previous hall</a><a href="qfep-synthesis.html">Next hall</a><a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["qfep-sandbox.html","qfep-sandbox-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
