"""Build the Cantor review from the current successful Godot receipt."""
from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/cantor-encounter-2026-09-14';RUN=R/'ada_run/cantor-review-2026-09-14';M='Fractal_CantorSet'
def dump(p,d):p.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
r=json.loads((RUN/'run.json').read_text())
assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for n in ['entrance','intervals-history','latest-only','ghost-history','pagoda-three-cuts','pagoda-latest','narrow-gap','collection']:
 dest=O/f'cantor-{n}.png';shutil.copyfile(RUN/M/f'{n}.png',dest);assets.append(dest.name)
for kind in ['final','technical','critical','tutorial']:
 dest=O/f'cantor-{kind}.md';shutil.copyfile(R/f'commons/maps/{M}/{kind}.md',dest);assets.append(dest.name)
 previous=E/f'before/commons/maps/{M}/{kind}.md'
 if previous.exists():
  old=O/f'cantor-previous-{kind}.md';shutil.copyfile(previous,old);assets.append(old.name)
dump(O/'cantor-verification.json',r);assets.append('cantor-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>More pieces, less material · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="fractal-learning-arc.html#Fractal_CantorSet">← The fractal walk</a><a href="/necklace/thread?map=Fractal_CantorSet&role=primary">Two primary artifacts / book</a><a href="/museum-progress?sequence=fractals&room=Fractal_CantorSet">Museum progress</a></nav>
<p class="eyebrow">ADA RESEARCH · CANTOR SET · 14 SEPTEMBER 2026</p><h1>More pieces,<br>less material.</h1><p class="lead">The trees gave each branch descendants. Now we remove the middle of what we were given. When the openings multiply, which ones still admit a body?</p>
<div class="facts"><div><strong>8</strong><span>existing placements retained</span></div><div><strong>2</strong><span>primary encounters and book passages</span></div><div><strong>6 → 0.790 m</strong><span>kept length after five cuts</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="cantor-entrance.png" alt="The Cantor pagoda on its raised museum deck, approached by two ramps with a small control desk between them"><figcaption>Actual Godot capture. The historic platform and both wedges remain. The pagoda begins with a broad passage under one earlier generation.</figcaption></figure>
<section><p class="step">01 / CANTOR_SET</p><h2>What are we counting?</h2><p>Press NEXT and look for the new gap before counting the pieces. Each surviving interval loses its own middle. BACK returns to the preceding cut; RESET returns to the original bar. The latest row becomes thirty-two pieces with less than a metre of retained length.</p>
<figure><img loading="lazy" src="cantor-intervals-history.png" alt="Six rows of coloured Cantor intervals behind a compact six-button desk and transparent screen"><figcaption>Five cuts, 32 current pieces, 0.790 m kept. With history on, 63 solid bars are visible across all six rows. The display is fuller; the latest interval set retains less length.</figcaption></figure>
<div class="pair"><figure><img loading="lazy" src="cantor-latest-only.png" alt="Only the latest Cantor row remains visible behind the transparent screen"><figcaption>HISTORY off: earlier rows and their collisions disappear. The latest generation is unchanged.</figcaption></figure><figure><img loading="lazy" src="cantor-ghost-history.png" alt="Pale ghost intervals mark the removed middle thirds within the displayed construction history"><figcaption>GHOST with history on: pale marks show the middles newly removed at each generation. They have no collision; inherited gaps remain empty.</figcaption></figure></div>
<blockquote>The room can accumulate a record of something becoming smaller.</blockquote><p>The code divides the current length by three and offsets two new centres by that same third. The lesson stops at five cuts. These finite, thick bars are an instrument for approaching a mathematical limit; they do not display the limit itself.</p></section>
<section><p class="step">02 / EXAMPLE_8_4_CANTOR_PAGODA_VR</p><h2>A gap for whom?</h2><p>Walk through the broad opening. Return to CUT twice, then compare the new openings at the lowest level. The same interval rule now makes walls and overhead history. A visible opening is not yet a promise that this player can pass.</p>
<div class="pair"><figure><img loading="lazy" src="cantor-pagoda-three-cuts.png" alt="The pagoda's lower openings beneath stacked earlier generations"><figcaption>Three cuts: 8 lower blocks, 15 blocks including history. Gaps include 3 m, 1 m and ⅓ m.</figcaption></figure><figure><img loading="lazy" src="cantor-pagoda-latest.png" alt="The latest eight Cantor blocks with the earlier storeys hidden"><figcaption>DEPTH then LATEST: extrusion increases from 2 m to 4 m and the older roofs disappear. The latest X intervals stay the same.</figcaption></figure></div>
<figure><img loading="lazy" src="cantor-narrow-gap.png" alt="A third-metre opening between two pink blocks reveals a tree beyond, but is too narrow for the tested player"><figcaption>The eye can see the tree beyond. The tested 0.6 m-wide player passes through the 3 m and 1 m gaps; the ⅓ m gap blocks it.</figcaption></figure>
<p>DEPTH changes how far we must travel through the opening. LATEST removes the storeys that record previous generations, including their collision. CUT changes the interval construction. These controls separate decisions that the finished shape can make seem inseparable.</p><blockquote>To make a way through, we could widen the opening, change the body, or change which surfaces count as solid.</blockquote><p>More detail has made more openings, many too small for this visitor. The desire to enter can lead us back to the implemented rule. The body, the collision system and the mapping into three dimensions all take part in deciding what becomes accessible.</p></section>
<details><summary>Read the book passage</summary><article>__BOOK__</article><p><a href="cantor-final.md">Manuscript</a> · <a href="cantor-technical.md">Implementation</a> · <a href="cantor-critical.md">Critical questions</a> · <a href="cantor-tutorial.md">Encounter order</a></p></details>
<section><h2>The collection keeps its detours.</h2><p>The linear Nature of Code display, three stochastic trees, fractal cloud and dark sphere remain around the two primaries. Explicit map placement restores the cloud that the earlier museum arrangement had omitted. The original enclosure, deck and two ramps are preserved; the museum covers the legacy exit voids.</p><p>Earlier prose described radial circles that the source did not draw. The revised text follows the actual linear intervals. <a href="cantor-previous-final.md">The earlier book passage</a> and supporting texts are archived with the map and source snapshots.</p></section>
<section><h2>What was checked?</h2><p>__CHECKS__ checks passed in the actual Godot museum: all eight placements, both six-button desks through desktop pointer input, finite counts and widths, history and ghost modes, bounded rebuilds, extrusion and reset, ordinary uninstrumented modes, the ramp, three gap widths and the exit landing.</p><p class="note">The test uses synthetic input through the project's standalone DesktopPlayer rig inside the museum. It does not certify the native museum walker's interaction lane. The duplicate native walker is parked outside the test room. Headset reach, comfort and Quest performance remain to test. The user's editor, open museum and saved hand were preserved.</p></section>
<section class="next"><h2>Next: the boundary takes a detour.</h2><p>Koch and Sierpinski carry the comparison into growing boundaries and removal across a surface. How does another level of detail change what we can measure?</p><a href="/necklace/thread?map=Fractal_KochSierpinski&role=primary">Continue to Fractal_KochSierpinski →</a></section>
<footer><a href="cantor-verification.json">Runtime receipt</a> · <a href="fractal-learning-arc.html">Seven-hall learning arc</a> · <a href="recursive-trees.html">Previous hall: Recursive Trees</a></footer></main></body></html>'''.replace('__CSS__',css).replace('__CHECKS__',str(r['checks'])).replace('__BOOK__',book)
(O/'cantor-encounter.html').write_bytes(page.encode());assets.append('cantor-encounter.html')
assets+=['fractal-learning-arc.html','fractal-learning-arc.json','fractal-learning-arc.md']
for n,src in [('receipt.json',RUN/'run.json'),('report.json',RUN/M/'probe_ca_edge_live.json'),('engine.log',RUN/M/'engine.log')]:shutil.copyfile(src,E/n)
targets=['possible-bodies/'+a for a in assets]
dump(E/'publish-targets.json',targets);dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Cantor review: {len(targets)} files; {r["checks"]} checks.')
