from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="Brouwer_Intuitionism"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/foundations-brouwer-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]; tokens=[x.strip().split(":",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":13,"depth":16,"max_height":3},"eight_artifacts":len(tokens)==8 and len(set(tokens))==8,"primary_focus":roles.get("constructive_proof")=="primary" and roles.get("brouwer_choice_sequence")=="primary","registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"stepping_structure":len(data["layers"]["structure"])==16 and len(data["layers"]["structure"][0])==13}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["constructive_proof","brouwer_choice_sequence"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"foundations-brouwer-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 260" role="img" aria-labelledby="b-title b-desc" xmlns="http://www.w3.org/2000/svg"><title id="b-title">Only what you can construct</title><desc id="b-desc">A gap separates an unbuilt claim from a constructed witness.</desc><rect width="900" height="260" rx="18" fill="#132014"/><g fill="#8ec9c1" font-family="system-ui,sans-serif"><rect x="80" y="54" width="260" height="130" rx="12" fill="none" stroke="#8ec9c1" stroke-width="5"/><text x="210" y="92" text-anchor="middle" font-size="20">CLAIM</text><text x="210" y="132" text-anchor="middle" font-size="17">∃ x · P(x)</text><text x="210" y="164" text-anchor="middle" font-size="14">no witness yet</text><path d="M385 119h130" stroke="#f0bd72" stroke-width="5" stroke-dasharray="12 10"/><text x="450" y="92" text-anchor="middle" font-size="14" fill="#f0bd72">GAP</text><rect x="560" y="54" width="260" height="130" rx="12" fill="#f0bd72" fill-opacity=".82"/><text x="690" y="92" text-anchor="middle" font-size="20" fill="#132014">CONSTRUCTION</text><circle cx="690" cy="140" r="25" fill="#132014"/><text x="690" y="147" text-anchor="middle" font-size="20" fill="#f0bd72">x</text><text x="450" y="225" text-anchor="middle" font-size="18" fill="#eaf4f1">existence begins when the witness is made</text></g></svg><figcaption>Intuitionism treats an existence claim as unfinished until a construction supplies its witness.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="foundations-brouwer-verification.json">Verification record</a></p>'
body="""<p class="date">Foundational crises · Hall 5 · 15 September 2026</p><h1>Only What You Can Construct</h1><p class="lead">After Gödel’s gap, Brouwer changes the rule: an object exists only when a procedure can produce its witness.</p><p><a href="/necklace/thread?map=Brouwer_Intuitionism&amp;role=primary">Primary artifacts and book</a> · <a href="/museum-progress?sequence=foundationscrisis">Museum progress</a></p>"""+diagram+"""<details><summary>Read the book passage</summary>"""+book+"""</details><h2>The gap is a discipline</h2><p>The constructive proof and choice sequence carry the primary argument. The staircase, excluded-middle demo, Cantor bench, and inherited Euclidean claims remain as secondary witnesses, showing what is gained and what is refused when a proof must become a program.</p><p>Brouwer does not repair the earlier crises by selecting a better value. He narrows the vocabulary of existence. The final hall, <strong>Crisis_Synthesis</strong>, will put choice, contradiction, incompleteness, and construction in one room.</p>"""+score
(O/"foundations-brouwer.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Only What You Can Construct · Ada Research</title><style>'+css+'</style><main><nav><a href="foundations-escher.html">Previous hall</a><a href="/museum-progress?sequence=foundationscrisis">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["foundations-brouwer.html","foundations-brouwer-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
