from pathlib import Path
import json,hashlib,shutil,re,markdown
R=Path.cwd();O=R/'doc/research/possible-bodies';E=R/'doc/space/iso-lookup-2026-09-15';run=R/'ada_run/iso-lookup-review-2026-09-15';M='ISO_LookupTable'
r=json.loads((run/'run.json').read_text());assert r['exit']==0 and r['sources_unchanged'];assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
css=re.search(r'<style>(.*?)</style>',(O/'iso-introduction.html').read_text(),re.S)[1]
assets=['iso-learning-arc.md','iso-learning-arc.html','spine-iteration.md','spine-iteration.html'];figures=''
for name in ['entrance','encounter','specimen','overview']:
 out='iso-lookup-'+name+'.png';shutil.copyfile(run/M/(name+'.png'),O/out);assets.append(out);figures+=f'<figure><img src="{out}" alt="Actual Godot lookup hall: {name}" loading="lazy"><figcaption>Actual Godot museum capture · {name}. Desktop review; headset review remains pending.</figcaption></figure>'
links=[]
for kind in ['final','technical','critical']:
 for before in [False,True]:
  p=(E/'before' if before else R)/f'commons/maps/{M}/{kind}.md'
  if p.exists():
   out='iso-lookup-'+('previous-' if before else '')+kind+'.md';shutil.copyfile(p,O/out);assets.append(out);links.append(f'<a href="{out}">{"Previous" if before else "Current"} {kind}</a>')
for src,name in [(run/'run.json','receipt.json'),(run/M/'probe_ca_edge_live.json','runtime-report.json'),(run/M/'engine.log','engine.log')]:shutil.copyfile(src,E/name)
shutil.copyfile(run/'run.json',O/'iso-lookup-verification.json');assets.append('iso-lookup-verification.json')
body='''<p class="date">Isosurfaces · Hall 2 · 15 September 2026</p><h1>Eight samples, one local decision</h1><p class="lead">The classification stays. The edge moves.</p><p>TRACE exposes gold crossing markers. MARGIN changes the values without changing which side of 0.50 each corner occupies. OPERANDS and SURFACE separate the visible inputs from the extracted result; RESET returns the complete comparison.</p><p><a href="/necklace/thread?map=ISO_LookupTable&role=primary">Primary artifact and book</a> · <a href="iso-learning-arc.html">Thirteen-hall learning arc</a></p><details><summary>Read this hall’s book passage</summary>'''+markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])+'</details>'+figures+'''<h2>What the comparison establishes</h2><p>Across all four value pairs, fifteen extractor masks remain identical. Actual edge markers move through .50, .10, .85 and .95 of the edge measured from high toward low; the generated geometry changes. The inherited high-value mask and the extractor’s low-value mask are now both labelled.</p><p>These are fifteen selected arrangements, with neighbouring cells included in the miniatures. They do not demonstrate that every ambiguity is resolved. A grey bead denotes an empty generated mesh, not a tiny extracted surface. The three secondary artifacts remain; the cave’s terrain shader now uses multiplication and addition instead of unsupported fused multiply-add. This may differ in last-bit rounding while preserving its visual calculation.</p><p>41 desktop checks passed: actual pointer presses, interpolation, view changes, supported circulation and onward exit. Headset reach, Quest performance and retained-secondary interactions remain pending.</p><p><a href="iso-lookup-verification.json">Runtime receipt</a></p><p>'''+ ' · '.join(links)+'''</p><p>Next: <strong>ISO_ShapesGallery</strong> — different field descriptions, a shared extraction method.</p>'''
(O/'iso-lookup.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Eight samples · Ada Research</title><style>'+css+'</style><main><nav><a href="iso-introduction.html">Introduction</a><a href="iso-learning-arc.html">Learning arc</a><a href="/museum-progress?sequence=isosurfaces">Museum progress</a></nav>'+body+'</main></html>',encoding='utf-8');assets.append('iso-lookup.html')
manifest=['possible-bodies/'+a for a in assets];(E/'publish-targets.json').write_text(json.dumps(manifest,indent=2));(E/'publish-hashes.json').write_text(json.dumps({a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in manifest},indent=2))
(R/'ada_run/publish_iso_lookup.ps1').write_text((R/'ada_run/publish_iso_intro.ps1').read_text().replace('iso-introduction-2026-09-15','iso-lookup-2026-09-15'),encoding='utf-8')
print('Built',len(assets),'verified review assets.')
