from pathlib import Path
import hashlib,json,re,subprocess,markdown
R=Path.cwd(); M="SpeculativeComputation_Queer_Morphological_Systems"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/speculative-morphological-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
d=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]; t=[x.strip().split(":",1)[0] for row in d["layers"]["interactables"] for x in row if x.strip()]
c={"map_dimensions":d["map_info"]["dimensions"]=={"width":10,"depth":10,"max_height":2},"one_artifact":t==["morphogenesis_bench"],"primary_focus":roles.get("morphogenesis_bench")=="primary","registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid_structure":all(len(d["layers"][k])==10 and len(d["layers"][k][0])==10 for k in ["structure","utilities","interactables"])}
try:c["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True).returncode==0
except OSError:c["registry_resolution"]=False
v={"hall":M,"date":"2026-09-15","checks":sum(c.values()),"total_checks":len(c),"failures":[k for k,x in c.items() if not x],"checks_detail":c,"tokens":t,"primary_artifacts":["morphogenesis_bench"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(v,indent=2),encoding="utf-8");(O/"speculative-morphological-verification.json").write_text(json.dumps(v,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
fig='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="m-title m-desc" xmlns="http://www.w3.org/2000/svg"><title id="m-title">A body from local rules</title><desc id="m-desc">A seed grid grows into a connected morphology through repeated updates.</desc><rect width="900" height="280" rx="18" fill="#121827"/><g fill="#8fc7d5">''' + ''.join(f'<rect x="{120+(i%4)*34}" y="{90+(i//4)*34}" width="28" height="28" rx="5"/>' for i in [0,1,2,4,5,6,9,10,13,14]) + '''</g><path d="M300 140H430" stroke="#f0d48c" stroke-width="7"/><g fill="#d887b7"><circle cx="560" cy="105" r="25"/><circle cx="600" cy="140" r="25"/><circle cx="560" cy="175" r="25"/><circle cx="640" cy="140" r="25"/></g><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff"><text x="190" y="235" font-size="18">seed</text><text x="365" y="120" font-size="16">local rule</text><text x="600" y="235" font-size="18">morphology</text><text x="450" y="42" font-size="22">a body is an accumulated decision</text><text x="450" y="265" font-size="17">keep the history visible</text></g></svg><figcaption>Repeated local updates turn a sparse seed into a body with a traceable history.</figcaption></figure>'''
score=f'<p>{v["checks"]}/{v["total_checks"]} static checks passed. <a href="speculative-morphological-verification.json">Verification record</a></p>'; body='<p class="date">Speculative computation · Morphological systems · 15 September 2026</p><h1>When Does a Body Become a History?</h1><p class="lead">A form emerges through repeated local decisions. The rule and the seed remain visible while the body changes.</p><p><a href="/necklace/thread?map=SpeculativeComputation_Queer_Morphological_Systems&amp;role=primary">Primary artifact and book</a> · <a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></p>'+fig+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Accumulation before identity</h2><p>The morphogenesis bench is the sole artifact in this deliberately small room. Keep the rule, seed, and generation history together so the strange form remains an inspectable process rather than an unexplained style.</p><p>The next hall, <a href="speculative-uncertainty.html"><strong>SpeculativeComputation_Ontological_Uncertainty</strong></a>, asks what remains knowable when a changing body refuses one reading.</p>'+score
(O/"speculative-morphological.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>When Does a Body Become a History? · Ada Research</title><style>'+css+'</style><main><nav><a href="speculative-cyborg.html">Previous hall</a><a href="speculative-uncertainty.html">Next hall</a><a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["speculative-morphological.html","speculative-morphological-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8");(E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8");print(json.dumps(v))
