from pathlib import Path
import json,hashlib,shutil,re,markdown
R=Path.cwd();O=R/'doc/research/possible-bodies';E=R/'doc/space/iso-shapes-2026-09-15';run=R/'ada_run/iso-shapes-review-2026-09-15';M='ISO_ShapesGallery'
r=json.loads((run/'run.json').read_text());assert r['exit']==0 and r['sources_unchanged'];assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
css=re.search(r'<style>(.*?)</style>',(O/'iso-introduction.html').read_text(),re.S)[1]
assets=['iso-learning-arc.md','iso-learning-arc.html','spine-iteration.md','spine-iteration.html'];figures=''
for name in ['entrance','encounter','specimen','overview']:
 out='iso-shapes-'+name+'.png';shutil.copyfile(run/M/(name+'.png'),O/out);assets.append(out);figures+=f'<figure><img src="{out}" alt="Actual Godot shape gallery: {name}" loading="lazy"><figcaption>Actual Godot museum capture · {name}. Desktop review; headset review remains pending.</figcaption></figure>'
links=[]
for kind in ['final','technical','critical']:
 for before in [False,True]:
  p=(E/'before' if before else R)/f'commons/maps/{M}/{kind}.md'
  if p.exists():
   out='iso-shapes-'+('previous-' if before else '')+kind+'.md';shutil.copyfile(p,O/out);assets.append(out);links.append(f'<a href="{out}">{"Previous" if before else "Current"} {kind}</a>')
for src,name in [(run/'run.json','receipt.json'),(run/M/'probe_ca_edge_live.json','runtime-report.json'),(run/M/'engine.log','engine.log')]:shutil.copyfile(src,E/name)
shutil.copyfile(run/'run.json',O/'iso-shapes-verification.json');assets.append('iso-shapes-verification.json')
body='<p class="date">Isosurfaces · Hall 3 · 15 September 2026</p><h1>The same tool makes a cup</h1><p class="lead">Hold a body. Change its description. Look for what remains.</p><p>The existing six-object gallery now has a compact desk: REPERTOIRE, LEVEL, HOLD, CLEAR, RESET and RULE. Two independent held meshes keep the earlier comparison available while the live fields change.</p><p><a href="/necklace/thread?map=ISO_ShapesGallery&role=primary">Primary artifact and book</a> · <a href="iso-learning-arc.html">Learning arc</a></p><details><summary>Read the book passage</summary>'+markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])+'</details>'+figures+'<h2>A disappearance the generator concealed</h2><p>At level minus two, the cup produces zero triangles. The inherited generator replaced that result with a sphere. This hall now keeps a verified empty GPU result empty and labels its place. A failed GPU setup remains a failure; it is not mistaken for meaningful absence.</p><p>The cup already has gaps at level zero. Its wall is thin relative to the 64-sample grid. The book follows that actual discrepancy between the field description and its visible boundary, then asks how recognition differs from possible use.</p><p>All four original artifact instances and every inherited structure cell remain. The six live specimens and two held comparisons have low platforms; the historical collection sits behind the comparison court.</p><p>'+str(r['checks'])+' desktop checks passed: real GPU results, all repertoires and levels, pointer controls, independent held geometry, supported circulation and onward exit. Actual rendered Godot screenshots were inspected. Headset reach, Quest performance and retained-secondary interactions remain pending. Browser interaction review was unavailable; local HTTP delivery is checked separately.</p><p><a href="iso-shapes-verification.json">Runtime receipt</a></p><p>'+' · '.join(links)+'</p><p>Next: <strong>ISO_TorusGyroid</strong> — a handle, a periodic field, and the openings a body can actually enter.</p>'
(O/'iso-shapes.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The same tool makes a cup · Ada Research</title><style>'+css+'</style><main><nav><a href="iso-introduction.html">Introduction</a><a href="iso-learning-arc.html">Learning arc</a><a href="/museum-progress?sequence=isosurfaces">Museum progress</a></nav>'+body+'</main></html>',encoding='utf-8');assets.append('iso-shapes.html')
manifest=['possible-bodies/'+a for a in assets];(E/'publish-targets.json').write_text(json.dumps(manifest,indent=2));(E/'publish-hashes.json').write_text(json.dumps({a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in manifest},indent=2))
(R/'ada_run/publish_iso_shapes.ps1').write_text((R/'ada_run/publish_iso_intro.ps1').read_text().replace('iso-introduction-2026-09-15','iso-shapes-2026-09-15'),encoding='utf-8')
print('Built',len(assets),'verified review assets.')
