from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="SpeculativeComputation_Queer_Cyborg_Subjectivity"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/speculative-cyborg-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]
tokens=[x.strip().split(":",1)[0].split("#",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":10,"depth":10,"max_height":2},"one_artifact":len(tokens)==1 and tokens[0]=="super_drag_mirror","primary_focus":roles.get("super_drag_mirror")=="primary" and sum(v=="primary" for v in roles.values())==1,"registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid_structure":all(len(data["layers"][k])==10 and len(data["layers"][k][0])==10 for k in ["structure","utilities","interactables"])}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["super_drag_mirror"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"speculative-cyborg-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="c-title c-desc" xmlns="http://www.w3.org/2000/svg"><title id="c-title">A body assembled across substrates</title><desc id="c-desc">A mirror holds a changing silhouette while code, fabric, gesture, and interface feed it.</desc><rect width="900" height="280" rx="18" fill="#121827"/><rect x="320" y="38" width="260" height="190" rx="18" fill="#8fc7d5" fill-opacity=".20" stroke="#f0d48c" stroke-width="6"/><path d="M430 185c-28-34-20-72 20-92 40 20 48 58 20 92z" fill="#d887b7"/><circle cx="450" cy="83" r="23" fill="#85c89a"/><path d="M220 75L320 90M220 140L320 140M220 205L320 190M680 75L580 90M680 140L580 140M680 205L580 190" stroke="#f0d48c" stroke-width="5"/><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff"><text x="220" y="55" font-size="18">code</text><text x="220" y="128" font-size="18">fabric</text><text x="220" y="238" font-size="18">gesture</text><text x="680" y="55" font-size="18">camera</text><text x="680" y="128" font-size="18">social reading</text><text x="680" y="238" font-size="18">default</text><text x="450" y="260" font-size="17">the reflection is negotiated, never final</text></g></svg><figcaption>The mirror makes the assembled body visible without promising an authentic body beneath the interface.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="speculative-cyborg-verification.json">Verification record</a></p>'
body='<p class="date">Speculative computation · Cyborg subjectivity · 15 September 2026</p><h1>Who Is the Body That Looks Back?</h1><p class="lead">A mirror returns the body the system knows how to render, and leaves the rest available for composition.</p><p><a href="/necklace/thread?map=SpeculativeComputation_Queer_Cyborg_Subjectivity&amp;role=primary">Primary artifact and book</a> · <a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></p>'+diagram+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Assembly before identity</h2><p>The super drag mirror is the sole artifact in this deliberately small room. Its outfit, posture, material, and interface parameters should update the same player state, so the reflection is an accountable view of the body in play. A combination without a preset name is the key experiment.</p><p>The next hall, <a href="speculative-morphological.html"><strong>SpeculativeComputation_Queer_Morphological_Systems</strong></a>, lets the changing system itself become the body.</p>'+score
(O/"speculative-cyborg.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Who Is the Body That Looks Back? · Ada Research</title><style>'+css+'</style><main><nav><a href="speculative-evolutionary.html">Previous hall</a><a href="speculative-morphological.html">Next hall</a><a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["speculative-cyborg.html","speculative-cyborg-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
