from pathlib import Path
import json,hashlib,shutil,re,markdown
R=Path.cwd();O=R/'doc/research/possible-bodies';E=R/'doc/space/iso-sculpting-2026-09-15';run=R/'ada_run/iso-sculpting-review-2026-09-15';M='ISO_Sculpting'
r=json.loads((run/'run.json').read_text());assert r['exit']==0 and r['sources_unchanged'];assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
css=re.search(r'<style>(.*?)</style>',(O/'iso-introduction.html').read_text(),re.S)[1]
assets=['iso-learning-arc.md','iso-learning-arc.html','spine-iteration.md','spine-iteration.html'];figures=''
for name in ['entrance','encounter','specimen','overview']:
 out='iso-sculpting-'+name+'.png';shutil.copyfile(run/M/(name+'.png'),O/out);assets.append(out);figures+=f'<figure><img src="{out}" alt="Actual Godot Sculpting hall: {name}" loading="lazy"><figcaption>Actual Godot museum capture · {name}. Desktop review; headset review remains pending.</figcaption></figure>'
links=[]
for kind in ['final','technical','critical']:
 for before in [False,True]:
  p=(E/'before' if before else R)/f'commons/maps/{M}/{kind}.md'
  if p.exists():
   out='iso-sculpting-'+('previous-' if before else '')+kind+'.md';shutil.copyfile(p,O/out);assets.append(out);links.append(f'<a href="{out}">{"Previous" if before else "Current"} {kind}</a>')
for src,name in [(run/'run.json','receipt.json'),(run/M/'probe_ca_edge_live.json','runtime-report.json'),(run/M/'engine.log','engine.log')]:shutil.copyfile(src,E/name)
shutil.copyfile(run/'run.json',O/'iso-sculpting-verification.json');assets.append('iso-sculpting-verification.json')
body='<p class="date">Isosurfaces · Hall 5 · 15 September 2026</p><h1>Add a contribution</h1><p class="lead">The gesture writes a field. The extractor finds its boundary.</p><p>Sculpting is restored between Torus / Gyroid and Flat Terrain. PAIR brings two equal deposits closer. ADD and ERASE act at the same marked point; HOLD keeps the earlier surface beside the live volume. The existing controller brush remains available for local gestures.</p><p><a href="/necklace/thread?map=ISO_Sculpting&role=primary">Primary artifact and book</a> · <a href="iso-learning-arc.html">Learning arc</a></p><details><summary>Read the book passage</summary>'+markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])+'</details>'+figures+'<h2>A cut is a contribution too</h2><p>The old ERASE path discarded the negative radius and added material. The repaired brush carries its sign into the shader. Positive strokes smooth-union the field; negative strokes cut it. They are evaluated in recorded order, so a later additive gesture can fill an earlier cut. Complete erasure clears both the mesh and its old collision.</p><p>The lesson uses level zero, a two-metre volume and 64 samples per axis. Its initial pair has radii of 0.30 m and centre separation of 0.90 m; PAIR chooses 0.65 m and 0.45 m next. The fixed desk target and quarter-metre brush make comparison repeatable. RESET keeps the held geometry.</p><p>The original fountain and all historical floor cells remain. Eight halls are now active in the museum, with five further curriculum halls still awaiting restoration.</p><p>'+str(r['checks'])+' rendered desktop checks passed, including actual pointer presses, mesh-volume change after subtraction, refill, complete erasure, controller-coordinate conversion and onward walking. These do not certify a human headset session or Quest performance. The retained animated fountain remains costly and needs a performance pass. The held mesh has no collision.</p><p><a href="iso-sculpting-verification.json">Runtime receipt</a></p><p>'+' · '.join(links)+'</p><p>Next: <strong>ISO_FlatTerrain</strong> — what can a volume describe that one height per position cannot?</p>'
(O/'iso-sculpting.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Add a contribution · Ada Research</title><style>'+css+'</style><main><nav><a href="iso-introduction.html">Introduction</a><a href="iso-learning-arc.html">Learning arc</a><a href="/museum-progress?sequence=isosurfaces">Museum progress</a></nav>'+body+'</main></html>',encoding='utf-8');assets.append('iso-sculpting.html')
manifest=['possible-bodies/'+a for a in assets];(E/'publish-targets.json').write_text(json.dumps(manifest,indent=2));(E/'publish-hashes.json').write_text(json.dumps({a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in manifest},indent=2))
(R/'ada_run/publish_iso_sculpt.ps1').write_text((R/'ada_run/publish_iso_intro.ps1').read_text().replace('iso-introduction-2026-09-15','iso-sculpting-2026-09-15'),encoding='utf-8')
print('Built',len(assets),'verified review assets.')
