from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="Godel_Incompleteness"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/foundations-godel-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]; tokens=[x.strip().split(":",1)[0].split("#",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":15,"depth":16,"max_height":3},"ten_artifacts":len(tokens)==10 and len(set(tokens))==10,"primary_focus":roles.get("godel_sentence_machine")=="primary" and roles.get("provability_sorter")=="primary","registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"bordered_structure":len(data["layers"]["structure"])==16 and len(data["layers"]["structure"][0])==15}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["godel_sentence_machine","provability_sorter"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"foundations-godel-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 270" role="img" aria-labelledby="g-title g-desc" xmlns="http://www.w3.org/2000/svg"><title id="g-title">True but unprovable</title><desc id="g-desc">A formal system boundary contains provable statements while a true statement sits across an unreachable gap.</desc><rect width="900" height="270" rx="18" fill="#101d38"/><rect x="70" y="45" width="430" height="160" rx="12" fill="none" stroke="#8ec9c1" stroke-width="6"/><text x="285" y="72" text-anchor="middle" fill="#eaf4f1" font-family="system-ui" font-size="18">FORMAL SYSTEM</text><g fill="#5f8890"><rect x="110" y="105" width="72" height="48" rx="6"/><rect x="200" y="105" width="72" height="48" rx="6"/><rect x="290" y="105" width="72" height="48" rx="6"/><rect x="380" y="105" width="72" height="48" rx="6"/></g><text x="285" y="185" text-anchor="middle" fill="#8ec9c1" font-family="system-ui" font-size="15">provable region</text><path d="M540 125h130" stroke="#f58b8b" stroke-width="4" stroke-dasharray="10 10"/><circle cx="760" cy="125" r="54" fill="#f58b8b" fill-opacity=".85"/><text x="760" y="120" text-anchor="middle" fill="#171329" font-family="system-ui" font-size="17">G</text><text x="760" y="145" text-anchor="middle" fill="#171329" font-family="system-ui" font-size="13">TRUE</text><text x="760" y="218" text-anchor="middle" fill="#eaf4f1" font-family="system-ui" font-size="17">UNREACHABLE</text></svg><figcaption>The gap is not an error in the proof machine. It is the limit the machine proves about itself.</figcaption></figure>'''
score = f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="foundations-godel-verification.json">Verification record</a></p>'
body = """<p class="date">Foundational crises · Hall 3 · 15 September 2026</p><h1>True But Unprovable</h1><p class="lead">A consistent system can describe arithmetic, name its own proofs, and still contain a truth it cannot reach.</p><p><a href="/necklace/thread?map=Godel_Incompleteness&amp;role=primary">Primary artifacts and book</a> · <a href="/museum-progress?sequence=foundationscrisis">Museum progress</a></p>""" + diagram + """<details><summary>Read the book passage</summary>""" + book + """</details><h2>The gap is the architecture</h2><p>The sentence machine and provability sorter carry the book's two movements: self-reference becomes a construction, then the construction becomes a boundary between what a system can prove and what is true in its intended interpretation. The other artifacts keep the distinction between a stopped search, a verified proof, and an unreachable truth visible.</p><p>Russell forced a restriction to preserve consistency. Gödel shows that consistency itself leaves a remainder. The next hall, <strong>Escher_Impossible</strong>, changes from logical reachability to spatial coherence.</p>""" + score
(O/"foundations-godel.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>True But Unprovable · Ada Research</title><style>'+css+'</style><main><nav><a href="foundations-russell.html">Previous hall</a><a href="/museum-progress?sequence=foundationscrisis">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["foundations-godel.html","foundations-godel-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
