from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="SpeculativeComputation_Evolutionary_Algorithms"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/speculative-evolutionary-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]
tokens=[x.strip().split(":",1)[0].split("#",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":10,"depth":10,"max_height":2},"one_artifact":len(tokens)==1 and tokens[0]=="evolutionary_algorithms","primary_focus":roles.get("evolutionary_algorithms")=="primary" and sum(v=="primary" for v in roles.values())==1,"registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid_structure":all(len(data["layers"][k])==10 and len(data["layers"][k][0])==10 for k in ["structure","utilities","interactables"])}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["evolutionary_algorithms"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"speculative-evolutionary-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="e-title e-desc" xmlns="http://www.w3.org/2000/svg"><title id="e-title">A population under selection</title><desc id="e-desc">Candidate forms pass through a fitness gate, while discarded forms remain visible as a remainder.</desc><rect width="900" height="280" rx="18" fill="#121827"/><g fill="#8fc7d5"><circle cx="130" cy="85" r="20"/><circle cx="130" cy="140" r="20"/><circle cx="130" cy="195" r="20"/></g><path d="M180 140H330" stroke="#f0d48c" stroke-width="7"/><rect x="330" y="70" width="150" height="140" rx="14" fill="#85c89a"/><path d="M480 140H650" stroke="#f0d48c" stroke-width="7"/><g fill="#d887b7"><circle cx="700" cy="105" r="20"/><circle cx="755" cy="140" r="20"/><circle cx="700" cy="175" r="20"/></g><path d="M405 70V40" stroke="#f5f0ff" stroke-width="4"/><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff"><text x="130" y="245" font-size="18">candidates</text><text x="405" y="140" font-size="18" fill="#121827">fitness</text><text x="730" y="245" font-size="18">survivors</text><text x="450" y="35" font-size="16">criterion</text><text x="450" y="270" font-size="17">the discarded forms are part of the result</text></g></svg><figcaption>Selection makes a criterion consequential by deciding which variations receive another generation.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="speculative-evolutionary-verification.json">Verification record</a></p>'
body='<p class="date">Speculative computation · Evolutionary algorithms · 15 September 2026</p><h1>What Survives Your Criterion?</h1><p class="lead">An evolutionary algorithm does not find the best body in the abstract. It repeats a decision about what deserves another generation.</p><p><a href="/necklace/thread?map=SpeculativeComputation_Evolutionary_Algorithms&amp;role=primary">Primary artifact and book</a> · <a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></p>'+diagram+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Selection is a world-making act</h2><p>The evolutionary algorithms workbench is the sole artifact in this deliberately small room. Its population, fitness criterion, mutation rate, and seed should stay visible together. The next run can change the criterion and show that “improvement” belongs to the evaluator, not to the form alone.</p><p>The next hall, <a href="speculative-cyborg.html"><strong>SpeculativeComputation_Queer_Cyborg_Subjectivity</strong></a>, carries this question from populations to bodies.</p>'+score
(O/"speculative-evolutionary.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What Survives Your Criterion? · Ada Research</title><style>'+css+'</style><main><nav><a href="qfep-synthesis.html">Previous sequence</a><a href="speculative-cyborg.html">Next hall</a><a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["speculative-evolutionary.html","speculative-evolutionary-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
