from pathlib import Path
import json,hashlib,shutil,html,re,markdown
R=Path(__file__).resolve().parents[1];RUN=R/'ada_run/ca-edge-review-2026-09-14';OUT=R/'doc/research/possible-bodies';E=R/'doc/space/ca-edge-review-2026-09-14';M=R/'commons/maps/CA_EdgeOfChaos'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,s):
 t=p.with_name(p.name+'.tmp');t.write_text(s,encoding='utf-8');t.replace(p)
receipt=json.loads((RUN/'run.json').read_text());report=json.loads((RUN/'CA_EdgeOfChaos/probe_ca_edge_live.json').read_text())
assert receipt['exit']==0 and not report['failures'] and receipt['sources_unchanged'] and receipt['original_hand_unchanged']
assert all(sha(R/p)==h for p,h in receipt['source_sha256'].items())
assert 'SCRIPT ERROR' not in (RUN/'CA_EdgeOfChaos/engine.log').read_text(errors='replace')
OUT.mkdir(parents=True,exist_ok=True);E.mkdir(parents=True,exist_ok=True);assets=[]
def copy(src,name):
 dst=OUT/name;shutil.copy2(src,dst);assets.append(dst)
for name in ['entrance','slices','floor','readout','controls','retained-gallery','whole-hall']:copy(RUN/f'CA_EdgeOfChaos/{name}.png',f'ca-edge-{name}.png')
copy(RUN/'oracle.json','ca-edge-data.json');copy(RUN/'CA_EdgeOfChaos/probe_ca_edge_live.json','ca-edge-verification.json');copy(R/'tools/ca_edge_review.js','ca-edge-review.js')
for name in ['final','technical','tutorial','critical','field_notes']:copy(M/f'{name}.md',f'ca-edge-{name}.md')
for src,name in [(RUN/'run.json','receipt.json'),(RUN/'CA_EdgeOfChaos/probe_ca_edge_live.json','report.json'),(RUN/'CA_EdgeOfChaos/engine.log','engine.log')]:shutil.copy2(src,E/name)
book_source=re.sub(r'<!--.*?-->','',(M/'final.md').read_text(),flags=re.S).split('\n',1)[1]
paragraphs=[markdown.markdown(book_source,extensions=['fenced_code'])]
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>How far does one difference go? · Ada Research</title>
<style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#122a31;color:#f0eadb;font:18px/1.7 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:38px 24px 90px}a{color:#f1bbd3}nav{font-size:14px;display:flex;gap:22px;flex-wrap:wrap}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.14}h1{font-size:clamp(44px,7vw,76px);max-width:850px}h2{font-size:36px;margin-top:65px}p{max-width:830px}figure{margin:30px 0}img{display:block;width:100%;border-radius:8px}figcaption,.small{font-size:14px;color:#c3ceca}section{margin-top:45px}button,select{background:#26454c;border:1px solid #6f8c91;color:inherit;padding:12px;border-radius:4px;font:inherit}select{display:block;width:100%;font-size:16px}button{cursor:pointer}button:disabled{opacity:.4}input{width:100%;accent-color:#e9bad1}label{display:block;margin:25px 0 10px}.fields{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.fields canvas{width:100%;height:auto;display:block;border:1px solid #527278}.fields figure{margin:15px 0}#history{width:100%;height:auto}#reading{padding:18px;border-left:3px solid #efb9d2;background:#24444b;margin:22px 0}article{max-width:830px}details{padding:18px;background:#203e45;border-radius:6px}summary{cursor:pointer}code{font-size:.85em}table{border-collapse:collapse;width:100%}td,th{padding:12px;text-align:left;border-bottom:1px solid #52656b}blockquote{border-left:3px solid #e2b4d1;padding-left:24px;font:26px/1.6 Georgia,serif}@media(max-width:650px){main{padding:24px 16px}h2{font-size:30px}.fields{gap:7px}td,th{padding:8px;font-size:14px}}</style>
<main><nav><a href="ca-volume-lab.html">← 3D form laboratory</a><a href="learning-ladder.html">Learning ladder</a><a href="/necklace/thread?map=CA_EdgeOfChaos&role=primary">Primary / book</a></nav>
<p class="small">ADA RESEARCH / CELLULAR AUTOMATA / 14 SEPTEMBER 2026</p><h1>How far does one difference go?</h1><p>Two almost identical volumes. One address holds a value one greater than its counterpart. Follow the trace before deciding what kind of world it belongs to.</p>
<figure><img src="ca-edge-entrance.png" alt="Paired cellular volumes, console and wall slices inside the endless museum"><figcaption>Actual Godot capture: the paired study inside CA_EdgeOfChaos. Fractional storage, scattered beginning, pull 0.25, drive zero, update 5.</figcaption></figure>
<blockquote>More places carry it. Less of it remains at any one place.</blockquote>
<h2>Try the comparison.</h2><p>Choose the uniform beginning with integer storage, return to G0, then STEP. Repeat with fractions. The inputs and neighbour rule are the same; what the number may retain changes.</p>
<label for="case">Recorded experiment</label><select id="case" aria-label="Recorded experiment"></select>
<label for="time">Generation / time <span id="generation"></span></label><input id="time" aria-label="Generation" type="range" min="0" max="20" value="5" step="1"><button id="first">FIRST</button> <button id="step">STEP</button>
<div id="reading" aria-live="polite"></div><canvas id="history" width="720" height="225" aria-label="Separate histories of affected addresses and maximum difference"></canvas>
<label for="depth">Spatial Z slice <span id="slice"></span></label><input id="depth" aria-label="Spatial Z slice" type="range" min="0" max="10" value="5" step="1">
<div class="fields"><figure><canvas class="field" width="330" height="330" aria-label="Volume A selected slice"></canvas><figcaption>A / reference run</figcaption></figure><figure><canvas class="field" width="330" height="330" aria-label="Volume B selected slice"></canvas><figcaption>B / comparison run</figcaption></figure><figure><canvas class="field" width="330" height="330" aria-label="Magnified absolute difference slice"></canvas><figcaption>|A − B| / magnified difference</figcaption></figure></div><p id="gain" class="small"></p><p class="small">These diagrams read the recorded arrays, checked against Godot at every address through G20. The photographs show their captioned moments; they do not follow these controls. The playable museum also lets you vary pull and drive independently.</p>
<h2>The room carries the measurement.</h2><figure><img src="ca-edge-floor.png" loading="lazy" alt="Difference image on the fixed floor between the two volumes"><figcaption>The selected spatial difference slice also dresses the floor. The floor remains solid; colour changes do not claim a change in support.</figcaption></figure>
<figure><img src="ca-edge-slices.png" loading="lazy" alt="Three brass-framed wall cases showing A, B and their difference"><figcaption>The same Z address in both volumes. The third case uses the gain printed on the console.</figcaption></figure>
<p>At update 20, the fractional comparison reaches all 1,331 addresses above the declared tolerance while its maximum falls to about 0.014. With no pull and no drive, the original local difference remains one. Stillness can retain a memory that smoothing loses.</p>
<h2>Twelve controls, one held comparison.</h2><figure><img src="ca-edge-controls.png" loading="lazy" alt="Reachable control panel on a plinth"><figcaption>STEP / +10 / REPLAY / ONE CELL; PULL −/+; DRIVE −/+; SEED / STORE / Z SLICE / COAT.</figcaption></figure><p>Parameter changes reconstruct both beginnings. ONE CELL switches between a matched control and a single intervention. Z SLICE and COAT leave the simulation unchanged. +10 advances a bounded batch; the workshop stops at update 100.</p>
<figure><img src="ca-edge-readout.png" loading="lazy" alt="Readout showing G20, affected count, maximum difference and visual gain"><figcaption>Extent and magnitude remain separate readings. A bright diagram alone cannot establish amplification.</figcaption></figure>
<h2>All five works remain.</h2><figure><img src="ca-edge-whole-hall.png" loading="lazy" alt="Overview of the expanded hall with study and rear collection"><figcaption>The study opens a 19 × 30 m hall. The screen, disease model, fog field and crack propagation remain in the rear gallery.</figcaption></figure>
<p>The disease update now computes four rows per display frame, publishing only after the complete 64³ generation is ready. Its existing sampled display remains. The fog has a labelled central-slice preview in the compatibility renderer; volume rendering needs Forward+. These supporting works still warrant their own interaction and headset reviews.</p>
<h2>A passage for the book.</h2><article>BOOK</article>
<h2>The name remains a question.</h2><p>The historical edge-of-chaos claim has also been tested and challenged. <a href="https://csc.ucdavis.edu/~evca/Papers/rev-edge.html">Mitchell, Hraber and Crutchfield (1993)</a> obtained different results in an evolutionary CA experiment and questioned the earlier interpretation. Here, the local averaging model measures neither a universal critical point nor thermodynamic entropy. QFEP supplies questions about persistence and suppression; the instrument supplies specific, limited evidence.</p>
<details><summary>Implementation, verification and limits</summary><p>CHECKS rendered Godot checks pass, including seven complete numerical comparisons through 21 generations, GPU colour/texture checks, twelve real desktop pointer actions, two body walks, and equivalence of scheduled and original disease transitions. This uses synthetic input through the real desktop rig; headset testing is deferred. The pre-edit baseline timed out; it produced no reliable before image.</p><p><a href="ca-edge-technical.md">Technical chapter</a> · <a href="ca-edge-tutorial.md">Tutorial</a> · <a href="ca-edge-critical.md">Critical text</a> · <a href="ca-edge-final.md">final.md</a> · <a href="ca-edge-verification.json">Runtime evidence</a></p><p>Source: algorithms/cellularautomata/ca_showcase/difference_model.gd and difference_study.gd. Reproduce with ada_run/review_ca_edge.py. Original layouts and text are archived in doc/space/ca-edge-review-2026-09-14/before.</p></details>
<h2>Next: the instruction to repeat.</h2><p><a href="/necklace/thread?map=Fractal_Recursion&role=primary">Fractal_Recursion</a> follows in the active museum. Local exchange has assembled form. Now a procedure will explicitly ask for another instance of itself.</p></main><script type="module" src="ca-edge-review.js"></script></html>'''.replace('BOOK',''.join(paragraphs)).replace('CHECKS',str(report['checks']))
p=OUT/'ca-edge-difference.html';write(p,page);assets.append(p)
page=page.replace('</style>','pre{overflow-x:auto;padding:18px;background:#0b1e25;border-radius:6px;font:14px/1.6 monospace}</style>')
write(p,page)
assets.extend(OUT/('learning-ladder.'+ext) for ext in ['html','md','json'])
targets=[p.relative_to(R/'doc/research').as_posix() for p in assets]
write(E/'publish-targets.json',json.dumps(targets,indent=2));write(E/'publish-hashes.json',json.dumps({p:sha(R/'doc/research'/p) for p in targets},indent=2))
write(E/'README.md',f'''# CA_EdgeOfChaos — 14 September 2026

Five authored artifacts retained, primary self_organization_ca unchanged. The 19×30 hall stages a paired 11³ study with matched forcing, independently adjustable pull/drive, integer/fractional storage, three spatial slices and a shared difference floor. Both museum rows updated; route and hand unchanged. Original compact grid and old prose archived in before/.

Final runtime: PID {receipt['pid']}, {report['checks']} passing checks. Baseline PID 25092 timed out after 180 seconds; no valid before image. Fog shader unsupported in compatibility was replaced there by an explicit slice view. Existing unrelated startup missing UID remains. No runtime script errors in accepted run.

The disease scheduler retains all 64³ states, reads the frozen generation for four rows per frame, and commits after 1,024 frames. Comparison against its original full-step method with matched random draws passes. The sampled four-cell display still omits unsampled addresses and has not been pedagogically redeveloped. Forward+ fog and headset testing remain deferred.

The primary's seven comparisons check every address at G0..20 against independent NumPy padded-array arithmetic. Count tolerance is 1e-6; maximum and mean differences are separate. The difference display adapts its gain and prints it. The fractional convex-average update with matched drive and clipping is non-expansive in maximum difference; widespread influence is not proof of chaos. Integer truncation introduces an additional threshold. The new study uses explicit deterministic forcing, not an iid or physical noise claim.

Actual desktop inputs operate all twelve controls; fixed support permits both tested walks. Validation does not establish comfort or performance on a headset. All other hall works remain active in the runtime review. Next main hall: Fractal_Recursion. No agents dispatched; editor 40112 preserved.
''')
print(f'Built {len(assets)} assets; {report["checks"]} rendered checks.')
