"""Build a review of the actual restored hall and its interpreter comparison."""
from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/grammar-curves-2026-09-14';RUN=R/'ada_run/curves-review-2026-09-14';M='LSystems_Grammars_And_Curves'
def dump(p,d):p.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
r=json.loads((RUN/'run.json').read_text())
assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for name in ['entrance','first-step','first-fork','three-readings','two-generations','controls','original-study','collection','curves']:
 p=O/f'interpreter-{name}.png';shutil.copyfile(RUN/M/f'{name}.png',p);assets.append(p.name)
p=O/'interpreter-before.png';shutil.copyfile(E/f'baseline/{M}/entrance.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
 for previous in [False,True]:
  p=O/f'interpreter-{"previous-" if previous else ""}{kind}.md';shutil.copyfile((E/'before' if previous else R)/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
dump(O/'interpreter-verification.json',r);assets.append('interpreter-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>When forward goes sideways · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="lsystems-growth.html">← Growth</a><a href="/necklace/thread?map=LSystems_Grammars_And_Curves&amp;role=primary">Primary artifact / book</a><a href="spine-iteration.html">Our working method</a></nav>
<p class="eyebrow">ADA RESEARCH · L-SYSTEMS / 03 · 14 SEPTEMBER 2026</p><h1>When forward<br>goes sideways.</h1><p class="lead">The gold arrow points up. The white arrow points across. F has acquired another reading. Which relations have travelled with it?</p>
<div class="facts"><div><strong>5</strong><span>authored works now present</span></div><div><strong>3</strong><span>synchronized readers</span></div><div><strong>0.32 m</strong><span>the same stride</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="interpreter-two-generations.png" alt="Actual Godot museum: green upright tree, amber wider tree and blue sideways tree with a compact control desk"><figcaption>Two generations, 172 symbols, 64 segments in every reading. Green: 25 degrees. Amber: 45 degrees. Blue: 25 degrees with the x/y direction components exchanged. All use the same metre scale.</figcaption></figure>
<section><p class="step">01 / BEGIN WITH ONE INSTRUCTION</p><h2>Two arrows disagree.</h2><p>At RESET, all three readers take the same first F upwards. READ F changes only the blue reader. Its stored heading stays up; its interpreted drawing direction goes across. ANGLE changes only the middle reader's turn setting. Its first F stays put: a changed angle has to reach a turning instruction before it affects the drawing.</p>
<div class="pair"><figure><img loading="lazy" src="interpreter-first-step.png" alt="First F upward in the reference and middle reading, horizontally in the blue reading"><figcaption>One symbol exposes the direction exchange before a whole form conceals it.</figcaption></figure><figure><img loading="lazy" src="interpreter-first-fork.png" alt="Three readers at the same first branch instruction"><figcaption>At symbol six, corresponding branch positions begin to separate. The readers have processed the same symbols.</figcaption></figure></div>
<p>STEP advances all three traces together. The short sentence is <code>FF+[+F-F-F]-[-F+F+F]</code>: twenty symbols and eight drawing instructions. Brackets save and restore the position and heading we followed in Growth.</p></section>
<section><p class="step">02 / LOOK FOR WHAT SURVIVES</p><h2>A reflection, discovered through a walk.</h2><figure><img loading="lazy" src="interpreter-three-readings.png" alt="The completed first generation in the three interpretations"><figcaption>Eight segments in each. Follow a blue fork back to its green counterpart. The cases mark a common scale; no drawing has been fitted to its allotted width.</figcaption></figure>
<pre><code>var dir := Vector2(cos(heading), sin(heading))
if sideways:
    dir = Vector2(dir.y, dir.x)</code></pre>
<p>Exchanging x and y uniformly reflects every recorded position across x=y, relative to its origin. Lengths, angles and branch connections survive. An unfamiliar outline does not by itself establish a new topology. READ F can undo the exchange while leaving the reference unchanged.</p><blockquote>A reflection can overturn our expectation of uprightness while retaining this much structure.</blockquote>
<p>TREE carries the same operation into a second generation. STEP reveals recorded interpreter states, not a computer paused between calculations. The branches remain drawings without collision surfaces. Their relation to an inhabiting body is the next question to build.</p></section>
<section><h2>A compact desk.</h2><figure><img loading="lazy" src="interpreter-controls.png" alt="Six full-sized buttons labeled STEP READ F ANGLE TREE RESET RULE beneath a small transparent screen"><figcaption>Six controls, a small tilted transparent pane, and full-sized touch targets. Every button was exercised through the actual DesktopPlayer pointer.</figcaption></figure><p>The reference stays at 25 degrees. ANGLE cycles the middle reading through 25 / 45 / 90 degrees; READ F changes the blue interpretation. TREE toggles one/two generations and shows their complete readings. RESET returns to the opening. After the last symbol, STEP returns to START.</p></section>
<details><summary>Read the book passage</summary><article class="manuscript">__BOOK__</article></details>
<section><p class="step">03 / RESTORE THE WORK THAT WAS MISSING</p><h2>The book's turtle was absent.</h2><div class="pair"><figure><img loading="lazy" src="interpreter-before.png" alt="Baseline museum with floor curves and Hilbert geometry but no believing turtle"><figcaption>Baseline: four works instantiated. The believing turtle existed in the map and source but lacked map_ready in the registry, so the museum skipped it.</figcaption></figure><figure><img loading="lazy" src="interpreter-original-study.png" alt="Restored original believing-turtle lectern, alphabet, generation bars, three smaller drawings, stack plates and stochastic pair"><figcaption>The original study remains behind the new desk. Its different strides, 261-segment prefixes and static peak-stack summary are now named.</figcaption></figure></div>
<p>All five authored artifacts now load. The original 13×12 structure, including its raised cell, is embedded at (3,16) in a 19×28 hall. An obsolete teleporter hole is filled. The four other placements retain their relative arrangement; Hilbert's scene now explicitly names its real script path.</p>
<div class="pair"><figure><img loading="lazy" src="interpreter-collection.png" alt="Retained grammar and curve collection inside the museum"><figcaption>The derivation station, floor curves, volumetric path and tube tree remain independent studies.</figcaption></figure><figure><img loading="lazy" src="interpreter-curves.png" alt="The existing floor gallery's Hilbert Peano and Moore patterns"><figcaption>Finite curves, independently fitted panels. The fourth-generation Hilbert path visits 256 distinct grid vertices; that does not mean every point of a continuous region.</figcaption></figure></div></section>
<section><h2>What was checked?</h2><p>__CHECKS__ Godot checks cover the restored registry placement, all six controls, actual state correspondence, equal lengths, reversibility, both generations, displayed bounds, original studies, finite Hilbert count and a complete route through the exit. No GDScript errors occurred. An older unrelated unresolved UID diagnostic remains.</p><p>Headset reach, readability, comfort and Quest timing remain pending. Deeper curve coverage/closure comparisons and visitor-authored interpretations belong to the next iteration. These images are actual Godot captures.</p></section>
<section class="next"><h2>Next: when a line becomes a corridor.</h2><p><a href="/necklace/thread?map=LSystems_Architecture&amp;role=primary">LSystems_Architecture</a> adds width, walls and uses to interpreted records. What must a branching plan provide before a body can follow it, pause there or return?</p><p><a href="spine-iteration.html">Complete the journey, then rewrite →</a> The current manuscript is accurate enough to test and open enough to develop after we have seen the whole spine.</p></section>
<footer><a href="interpreter-verification.json">Runtime receipt</a> · <a href="interpreter-previous-final.md">Previous manuscript</a> · <a href="interpreter-technical.md">Implementation</a> · <a href="interpreter-critical.md">Critical questions</a></footer></main></body></html>'''
(O/'grammar-curves.html').write_bytes(page.replace('__CSS__',css).replace('__BOOK__',book).replace('__CHECKS__',str(r['checks'])).encode());assets.append('grammar-curves.html')
method=markdown.markdown((O/'spine-iteration.md').read_text(),extensions=['tables','toc'])
(O/'spine-iteration.html').write_bytes(('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>First traverse. Then return. · Ada Research</title><style>'+css+'table{width:100%;border-collapse:collapse;font-size:.9rem}td,th{border-bottom:1px solid #425050;padding:.6rem;text-align:left;vertical-align:top}@media(max-width:650px){table{display:block;overflow-x:auto}}</style></head><body><main><nav><a href="grammar-curves.html">Grammars and Curves</a><a href="lsystems-growth.html">Growth</a><a href="/museum-progress">Museum progress</a></nav><article class="manuscript">'+method+'</article></main></body></html>').encode())
assets+=['spine-iteration.html','spine-iteration.md','fractal-learning-arc.html','fractal-learning-arc.json','fractal-learning-arc.md']
for src,dst in [(RUN/'run.json',E/'receipt.json'),(RUN/M/'probe_ca_edge_live.json',E/'runtime-report.json'),(RUN/M/'engine.log',E/'engine.log')]:shutil.copyfile(src,dst)
targets=['possible-bodies/'+a for a in assets];dump(E/'publish-targets.json',targets);dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Curves review: {len(targets)} assets; {r["checks"]} runtime checks.')
