from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="QFEP_Synthesis"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/qfep-synthesis-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]
tokens=[x.strip().split(":",1)[0].split("#",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":14,"depth":14,"max_height":3},"ten_artifacts":len(tokens)==10 and len(set(tokens))==10,"primary_focus":roles.get("queer_morphology_specimen")=="primary" and sum(v=="primary" for v in roles.values())==1,"registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid_structure":all(len(data["layers"][k])==14 and len(data["layers"][k][0])==14 for k in ["structure","utilities","interactables"])}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["queer_morphology_specimen"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"qfep-synthesis-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="s-title s-desc" xmlns="http://www.w3.org/2000/svg"><title id="s-title">A body made by four terms</title><desc id="s-desc">Four colored controls surround a responsive specimen whose shape keeps changing.</desc><rect width="900" height="280" rx="18" fill="#121827"/><path d="M190 70L450 140M710 70L450 140M190 220L450 140M710 220L450 140" stroke="#8fc7d5" stroke-width="5"/><circle cx="190" cy="70" r="38" fill="#e9b86f"/><circle cx="710" cy="70" r="38" fill="#77b9d6"/><circle cx="190" cy="220" r="38" fill="#d887b7"/><circle cx="710" cy="220" r="38" fill="#85c89a"/><path d="M450 72c60 15 86 54 62 91-19 30-74 45-111 12-38-35-22-87 49-103z" fill="#f0d48c" stroke="#f5f0ff" stroke-width="5"/><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#121827"><text x="190" y="76" font-size="18">F</text><text x="710" y="76" font-size="18">E</text><text x="190" y="226" font-size="18">λ</text><text x="710" y="226" font-size="18">φ</text></g><text x="450" y="42" font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff" font-size="22">the formula becomes a body</text><text x="450" y="260" font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff" font-size="17">change can preserve a form without fixing it</text></svg><figcaption>The specimen turns QFEP’s vocabulary into a question about continuity, resistance, and variation.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="qfep-synthesis-verification.json">Verification record</a></p>'
body='<p class="date">QFEP laboratory · Synthesis · 15 September 2026</p><h1>What Should This Body Keep?</h1><p class="lead">The formula is no longer only a console or a route. It is a body whose continuity depends on how its terms are combined.</p><p><a href="/necklace/thread?map=QFEP_Synthesis&amp;role=primary">Primary artifact and book</a> · <a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></p>'+diagram+'<details><summary>Read the book passage</summary>'+book+'</details><h2>A working synthesis</h2><p>The queer morphology specimen is the sole primary artifact. The four term spheres, formula, entropy ceiling, meter, and grasp cabinet remain secondary supports that let a visitor trace what is being preserved, what is dissipating, and what is changing. The specimen’s sliders make the ontology operational: stiffness, pressure, damping, and drag are authored mappings, not universal measurements.</p><p>This closes the QFEP laboratory sequence and opens the post-crisis question: whose distinctions does a model make visible, and whose does it compress?</p>'+score
(O/"qfep-synthesis.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What Should This Body Keep? · Ada Research</title><style>'+css+'</style><main><nav><a href="qfep-sandbox.html">Previous hall</a><a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["qfep-synthesis.html","qfep-synthesis-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
