"""Build the illustrated 3D CA workshop review from source-checked runtime evidence."""
from pathlib import Path
import ast,hashlib,json,shutil
R=Path(__file__).resolve().parents[1];RUN=R/'ada_run/ca-volume-review-2026-09-14';O=R/'doc/research/possible-bodies';E=R/'doc/space/ca-volume-review-2026-09-14'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,s):
    p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+'.tmp');t.write_bytes((s.strip()+'\n').encode());t.replace(p)
receipt=json.loads((RUN/'receipt.json').read_text());report=json.loads((RUN/'report.json').read_text())
assert receipt['exit']==0 and not receipt['failures'] and receipt['sources_unchanged'] and receipt['museum_and_hand_unchanged']
assert all(sha(R/p)==h for p,h in receipt['source_sha256'].items()),'Stale capture'
assert all(sha(R/p)==h for p,h in receipt['museum_guard_sha256'].items()),'Main museum changed'
engine=(RUN/'engine.log').read_text(encoding='utf-8',errors='replace');assert 'SCRIPT ERROR:' not in engine and 'Parse Error:' not in engine
for p in RUN.glob('*.png'):shutil.copy2(p,O/('ca-volume-'+p.name))
shutil.copy2(R/'tools/ca_volume_review.js',O/'ca-volume-review.js')
save(O/'ca-volume-data.json',(RUN/'oracle.json').read_text())
save(O/'ca-volume-verification.json',json.dumps(report,indent=2))
for n in ['receipt.json','report.json','states.json']:save(E/n,(RUN/n).read_text())
css=next(ast.literal_eval(n.value) for n in ast.parse((R/'tools/build_ca_history_review.py').read_text()).body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='css' for t in n.targets))
css+='''canvas{display:block;width:100%;height:auto;border:1px solid #4c6e71;border-radius:8px}.inspector{display:grid;grid-template-columns:1.7fr 1fr;gap:20px}.instrument{padding:18px;background:#203e43;border-left:3px solid #efb5cd;font-variant-numeric:tabular-nums}.rowlabel{display:block;font-size:14px;color:#bdd3cd;margin:20px 0 8px}input[type=range]{width:100%;accent-color:#e4adca}.question{font:27px/1.4 Georgia,serif;max-width:800px}pre{overflow:auto;padding:20px;background:#19373c;font-size:14px}pre code{overflow-wrap:normal}.walks{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.walks h3{margin-bottom:8px}.walks p{font-size:15px}button:disabled{opacity:.45;cursor:default}.controls{align-items:center}output{font-variant-numeric:tabular-nums}button:focus-visible,input:focus-visible{outline:3px solid #f0cba6;outline-offset:4px}@media(max-width:720px){.inspector,.walks{grid-template-columns:1fr}}'''
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>A volume can become a room · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="ca-form-strategies.html">← Walk inside a history</a><a href="ca-soft-rules.html">Cellular exchange</a><a href="learning-ladder.html">Learning ladder</a></nav>
<div class="eyebrow">3D cellular form laboratory / three seeds × three material mappings</div><h1>A volume can become a room.</h1><p class="lead">The neighbourhood now extends above, below, ahead and behind. Let the cells decide where to persist. Then choose what a cell becomes for a body.</p>
<p class="status">Built in Godot · __CHECKS__ rendered checks passed · actual desktop movement and twelve pointer controls. Headset review remains for later.</p>
<section><p class="question">Keep the cells. Change the material. Is the opening still the same opening?</p>
<span class="rowlabel">Choose the beginning</span><div class="controls"><button data-seed="0" aria-pressed="true">One cluster</button><button data-seed="1" aria-pressed="false">Scattered cells</button><button data-seed="2" aria-pressed="false">Two clusters</button></div>
<span class="rowlabel">Choose what becomes material</span><div class="controls"><button data-view="0" aria-pressed="false">Solid</button><button data-view="1" aria-pressed="false">Frame</button><button data-view="2" aria-pressed="true">Shell</button></div>
<p id="mapping-note"></p><figure><img id="photo" src="ca-volume-seed-0-view-2.png" alt="Actual Godot cellular shell after six updates"><figcaption id="photo-caption">Actual Godot / growth rule at G6.</figcaption></figure>
<p>The compact seed grows from 27 to 132 cells in six updates. Two clusters grow from 54 to 249. The scattered beginning grows from 258 to 764. Their differences come from the initial arrangement under the same rule. No arch is drawn into these seeds, and no corridor is reserved.</p></section>
<section><h2>Time is separate from depth.</h2><p>In the previous experiment, Z recorded generations of a 2D section. Here X, Y and Z are all spatial addresses. Every update reads the full previous 13³ volume. A site counts the 26 surrounding positions, including diagonals.</p>
<div class="controls"><button data-rule="0" aria-pressed="true">Growth rule</button><button data-rule="1" aria-pressed="false">Turnover rule</button></div><p id="rule-reading"></p>
<p id="reading" class="instrument" aria-live="polite">Loading recorded states…</p>
<label class="rowlabel" for="generation">Generation / time</label><input id="generation" type="range" min="0" max="6" value="6" step="1"><div class="controls"><button id="first">FIRST</button><button id="step" disabled>STEP</button><output id="generation-value" for="generation">G6 / 6</output></div>
<div class="inspector"><article><h3>The recorded volume</h3><canvas id="volume" width="700" height="510" aria-label="Rotatable diagram of the recorded 3D cellular state"></canvas><label class="rowlabel" for="angle">Turn the view</label><input id="angle" type="range" min="-180" max="180" value="40" step="1"></article>
<article><h3>A spatial section</h3><canvas id="slice" width="380" height="450" aria-label="XY occupancy slice at the selected spatial Z address"></canvas><label class="rowlabel" for="z-slice">Z address / space</label><input id="z-slice" type="range" min="0" max="12" value="6" step="1"><output id="slice-value" for="z-slice">Z = 6 / 12</output></article></div>
<p class="small">The diagrams inspect recorded cell arrays, checked against Godot. The photograph above stays at growth-rule G6. Shell and frame diagrams simplify the actual beams and folded panels; they do not calculate body clearance. The Z slider changes your section, while the time slider changes the cellular state. The desktop workshop can advance to G16.</p>
<p class="question">Choose one cluster and the turnover rule. Press FIRST, then STEP twice. The empty volume is a result too. What had allowed the cluster to persist?</p></section>
<section><h2>Three materials. One held beginning.</h2><p>For the physical comparison, we hold the original 27-cell block still and walk the same line at x = 2 m. The visitor is 1.8 m tall and 0.6 m wide. The block begins at z = 10 m and ends at z = 16 m.</p>
<div class="walks"><article><h3>Solid</h3><img src="ca-volume-walk-view-0.png" alt="Actual view of the solid cellular block stopping the desktop visitor"><p>The body stops at z ≈ __SOLID__ m, before the occupied block.</p></article><article><h3>Frame</h3><img src="ca-volume-walk-view-1.png" alt="Actual eye-height view through pink structural bars after crossing the held seed"><p>The body crosses the block and reaches z ≈ __FRAME__ m.</p></article><article><h3>Shell</h3><img src="ca-volume-walk-view-2.png" alt="Actual shell interior where an opening admits the visitor but a further panel stops them"><p>The body enters a deliberate aperture and stops at a panel at z ≈ __SHELL__ m.</p></article></div>
<p>The state contains the same 27 occupied sites throughout. In frame mode, unique edges of the exposed faces become 8 cm bars. Shell mode adds panels that fold 18 cm out from each face; side faces whose address sum is divisible by three remain open. Those apertures are an authored policy. The collision follows the visible material.</p>
<figure><img src="ca-volume-grown-interior.png" alt="Actual desktop eye-height view reached by walking beneath the grown six-generation shell"><figcaption>A separate physical walk reaches an opening beneath the grown G6 shell. The probe confirms actual form collision overhead; this is not a claim that every chamber is reachable.</figcaption></figure></section>
<section><h2>Where should sine enter?</h2><div class="gallery"><figure><img src="ca-volume-two-clusters-bent.png" alt="Actual two-cluster shell with sine bending its spatial coordinates"><figcaption>BEND: same 249 occupied sites at G6, changed coordinates.</figcaption></figure><figure><img src="ca-volume-two-clusters-sine.png" alt="Actual two-cluster shell produced with sine-modulated birth conditions"><figcaption>SINE: birth conditions vary with height and generation. __SINE_COUNT__ occupied sites at G6.</figcaption></figure></div>
<p>BEND shifts X with spatial Z. SINE shifts the required birth count by up to two neighbours according to Y and time. One changes the architecture around a held state; the other changes the next state. Both are available on the console.</p>
<details><summary>Rules, cuts and the limits of this material</summary><pre><code># Growth rule: read 26 neighbours from the previous volume.
next_cell = neighbours &gt;= 4 if current_cell else neighbours == 4

# Turnover rule changes both survival and birth conditions.
next_cell = (4 &lt;= neighbours and neighbours &lt;= 7) if current_cell else neighbours == 5

# Optional shift applied to the birth condition only.
shift = int(floor(2 * sin(TAU * y / 13 + generation * PI / 4) + 0.5))

# Optional coordinate bend. The cell state remains intact.
x = x + 1.5 * sin(TAU * z / 26)</code></pre><p>The numerical boundary is fixed at 13³; neighbours beyond it are empty. Each cell spans 2 m. Geometry is held while you walk and can change only after stepping outside the marked domain. The workshop floor supports the visitor; it is not a row of protected living cells. There is no simulated gravity or structural engineering in the cellular material.</p>
<p>CUT removes the negative-X part of the displayed geometry, retains the cellular state and reports how many cells remain visible. It is an inspection opening, not an opening that evolved. REPLAY reconstructs the current generation from the same seed, rule and sine setting. FIRST returns to G0. No cells are held alive by either rule.</p>
<figure><img src="ca-volume-two-clusters-cut.png" alt="Actual faceted cellular shell with an explicitly selected inspection cut"><figcaption>The cut makes a section available while preserving the state used for the next update.</figcaption></figure>
<p>The instrument counts connected components through shared faces. The CA reads all 26 neighbours. Cells can therefore influence one another diagonally while belonging to separate face-connected components. Neither count alone proves a continuous route for a body.</p></details></section>
<section class="reading"><h2>What did the room inherit?</h2><p>A block stands in your way. Its addresses are occupied. You press FRAME. The number does not fall, but the way opens.</p><p>The cell was never the concrete. It was a decision we gave a body to.</p><p>Put panels back on the frame. Some openings remain. You enter one and find another surface ahead. From outside, the object looked porous. From here, porosity has a direction and a distance.</p><p>Now return to the beginning and change the rule. Two steps later, nothing remains. The empty space did not need a door. It also lost the thing that could have sheltered you.</p></section>
<section><h2>From chosen rules to learned rules</h2><p>The paper you brought in learns probabilistic cellular transitions from examples of 3D shapes. Its shape representation uses surface voxels. That is a later comparison for this workshop: what changes when we choose training examples as well as a starting state? <a href="https://ar5iv.labs.arxiv.org/html/2103.04130">Zhang et al., Learning to Generate 3D Shapes with Generative Cellular Automata</a>.</p><p>This laboratory uses two explicit, hand-authored rules. It has not trained or reproduced the paper's model. The official repository contains GCA and its later continuous extension: <a href="https://github.com/96lives/gca">authors' implementation</a>.</p></section>
<section><h2>Walk the laboratory</h2><figure><img src="ca-volume-console.png" alt="Twelve real Godot controls mounted below a readable cellular instrument"><figcaption>SEED · RULE · STEP · +4 / SOLID · FRAME · SHELL · CUT / SINE · BEND · REPLAY · FIRST.</figcaption></figure><p>Open <code>res://commons/artifacts/ca_volume_lab/workshop.tscn</code> in Godot and run that scene. WASD or arrows move; the mouse looks; click the console. Escape releases or recaptures the pointer. The gallery keeps its own clear lighting so the whole form is visible.</p><p class="small">Standalone experiment; the active museum sequence and CA_SoftRules book/primary alignment remain unchanged. Headset performance and comfort are not yet verified. The largest captured shell uses __MAX_TRIS__ triangles; its recorded rebuild took about __MAX_MS__ ms on this desktop. Rebuilds occur at the console, not while someone occupies the volume.</p><details><summary>Verification</summary><p>__CHECKS__ Godot checks pass: every state through six generations for three seeds and two rules, a sine case, spatial Z influence, preserved state under all three mappings, displayed/collision triangle agreement, three matched physical walks, an entry beneath the grown shell, removal of geometry on extinction, actual input through all twelve controls, and the occupied-volume guard.</p><p><a href="ca-volume-verification.json">Runtime measurements and walks</a> · <a href="ca-volume-data.json">Recorded cellular arrays</a> · <a href="ca-volume-notes.md">Methods and next experiments</a></p></details></section>
<footer class="small">Ada Research / 14 September 2026. Continue the form comparison here; the next main hall remains CA_EdgeOfChaos.</footer></main><script src="ca-volume-review.js"></script></body></html>'''
walks={w['view']:w['finish_z'] for w in report['measurements']['walks']};states=json.loads((RUN/'states.json').read_text())
replacements={'__CSS__':css,'__CHECKS__':str(receipt['checks']),'__SOLID__':f'{walks[0]:.2f}','__FRAME__':f'{walks[1]:.2f}','__SHELL__':f'{walks[2]:.2f}','__SINE_COUNT__':str(states['sine']['report']['occupied']),'__MAX_TRIS__':f"{max(f['triangles'] for f in report['measurements']['forms']):,}",'__MAX_MS__':str(round(max(f['build_ms'] for f in report['measurements']['forms'])))}
for key,value in replacements.items():html=html.replace(key,value)
save(O/'ca-volume-lab.html',html)
notes='''# A volume can become a room — 14 September 2026

User approved a genuine 3D form laboratory with multiple seeds and solid/frame/shell mappings, following six architectural references and Zhang et al. (2021): https://ar5iv.labs.arxiv.org/html/2103.04130 . This implementation uses authored rules, not a trained GCA model.

Scene: res://commons/artifacts/ca_volume_lab/workshop.tscn. Reusable registered artifact: ca_volume_lab. No main sequence, map, hand, primary or book changes. The previous 2D-history vault remains intact.

State: 13³ binary sites, synchronous updates, 26-neighbour Moore neighbourhood, empty exterior, no protected alive cells. Every spatial cell is 2 m. Time is separate and capped at 16 updates in the interactive Godot workshop. All births read only the previous volume. Three explicit seeds: ground-based 3³ cluster (27); hash-scattered 38%-threshold cells in a 9³ region (258 actual); two separated 3³ clusters (54). Ground is an authored gallery floor, not a CA survival override.

Growth rule: B4/S4..26. Turnover rule: B5/S4..7. The latter changes both birth and survival conditions; it is not a single-parameter causal isolation. Under growth, G6 counts are 132,764,249. Turnover extinguishes the compact and paired seeds by G2 but preserves evolving activity in the scattered seed. Optional sine adds floor(2sin(2πy/13 + gπ/4)+.5) to the birth count. Optional bend shifts x by 1.5sin(2πz/26) and does not edit the state.

Mappings: solid exposes the occupied/empty boundary of filled cells. Frame retains unique boundary edges as 8 cm square bars; the cell interiors cease to be material. Shell adds 18 cm-outward folded panels and deliberately omits side panels where (x+y+z)%3==0; horizontal panels remain. These openings are mapping policy, not emergent vacancies. All physics triangles come from the same displayed geometry. CUT removes negative-X geometry and retains the cellular state. Empty state removes both mesh and collision.

Physical comparison at G0 uses the same 27 occupied cells, same route x=2 m, and the actual 1.8 m-tall/0.6 m-wide desktop capsule. Solid stops near z=9.70; frame crosses to z=17.50; shell enters and stops near z=15.75. A further ground walk reaches beneath the grown G6 shell, confirmed by collision overhead. This is not a comprehensive navigation proof for all seeds/generations/mappings. Face-connected component counts are separate from the 26-neighbour influence graph and from body clearance.

The clear gallery lighting disables the carried light's distance fog only on the workshop's player instance. Main player behaviour remains unchanged. Changes are refused while any recognized visitor is inside the marked domain. This addresses geometry replacement, not headset comfort. Headset testing remains deferred. The largest captured mesh is roughly 71k triangles; desktop rebuilds are measured in the report and do not establish Quest performance.

Read-only remote diagrams expose actual arrays through G6 and distinguish the time slider from the spatial Z slice. Diagrams simplify physical beams/facets; the separate labelled photographs show the real G6 growth specimens. Reproduce using python -X utf8 ada_run/review_ca_volume.py, then python -X utf8 tools/build_ca_volume_review.py. The isolated runner preserves the editor and owns only its hidden muted process. The existing missing-UID startup diagnostic is unrelated; no runtime script errors occurred in the accepted run.

Next experiments: compare isolated survival changes; vary cell scale to test which bodies pass; select and test connected interior routes in the evolved forms; preserve extinction as a result; compare explicit rules to a learned transition model only after choosing and documenting a training corpus. A body-dependent route measure is different from a claim of thermodynamic entropy or unlimited morphogenesis.
'''
save(O/'ca-volume-notes.md',notes);save(E/'README.md',notes+'\n\nRuntime checks: '+str(receipt['checks'])+'. See receipt.json, report.json, states.json and publication/browser verification.\n')
manifest=sorted(p.relative_to(R/'doc/research').as_posix() for p in O.glob('ca-volume-*') if p.suffix in ['.html','.png','.json','.js','.md'])
save(E/'publish-targets.json',json.dumps(manifest,indent=2));save(E/'publish-hashes.json',json.dumps({p:sha(R/'doc/research'/p) for p in manifest},indent=2))
save(R/'ada_run/publish_ca_volume.ps1',(R/'ada_run/publish_ca_forms.ps1').read_text().replace('ca-forms-review-2026-09-14','ca-volume-review-2026-09-14'))
print('Built',len(manifest),'verified review assets.')
