from pathlib import Path
import hashlib,json,re,subprocess,markdown
R=Path.cwd(); M="SpeculativeComputation_Ontological_Uncertainty"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/speculative-uncertainty-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
d=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]; t=[x.strip().split(":",1)[0] for row in d["layers"]["interactables"] for x in row if x.strip()]; c={"dimensions":d["map_info"]["dimensions"]=={"width":10,"depth":10,"max_height":2},"one_artifact":t==["possibility_space_cloud"],"primary":roles.get("possibility_space_cloud")=="primary","registers":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid":all(len(d["layers"][k])==10 and len(d["layers"][k][0])==10 for k in ["structure","utilities","interactables"])}
try:c["registry"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True).returncode==0
except OSError:c["registry"]=False
v={"hall":M,"date":"2026-09-15","checks":sum(c.values()),"total_checks":len(c),"failures":[k for k,x in c.items() if not x],"checks_detail":c,"tokens":t,"primary_artifacts":["possibility_space_cloud"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(v,indent=2),encoding="utf-8");(O/"speculative-uncertainty-verification.json").write_text(json.dumps(v,indent=2),encoding="utf-8"); css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
fig='''<figure><svg viewBox="0 0 900 260" role="img" aria-labelledby="u-title u-desc" xmlns="http://www.w3.org/2000/svg"><title id="u-title">A field of possible readings</title><desc id="u-desc">Several translucent contours overlap before a threshold selects one.</desc><rect width="900" height="260" rx="18" fill="#121827"/><ellipse cx="450" cy="130" rx="260" ry="80" fill="#8fc7d5" fill-opacity=".25" stroke="#8fc7d5" stroke-width="5"/><ellipse cx="450" cy="130" rx="180" ry="105" fill="#d887b7" fill-opacity=".25" stroke="#d887b7" stroke-width="5"/><ellipse cx="450" cy="130" rx="100" ry="55" fill="#f0d48c" fill-opacity=".35" stroke="#f0d48c" stroke-width="5"/><text x="450" y="35" font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff" font-size="22">the undecided interval stays visible</text><text x="450" y="235" font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff" font-size="17">a threshold is a decision about what can count</text></svg><figcaption>The cloud keeps multiple classifications available long enough to compare their consequences.</figcaption></figure>'''; score=f'<p>{v["checks"]}/{v["total_checks"]} static checks passed. <a href="speculative-uncertainty-verification.json">Verification record</a></p>'; body='<p class="date">Speculative computation · Ontological uncertainty · 15 September 2026</p><h1>What Remains When the Name Is Withheld?</h1><p class="lead">A body can carry several descriptions at once. The possibility field keeps them visible before a selector makes one official.</p><p><a href="/necklace/thread?map=SpeculativeComputation_Ontological_Uncertainty&amp;role=primary">Primary artifact and book</a> · <a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></p>'+fig+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Uncertainty as a duration</h2><p>The possibility cloud is the sole artifact in this deliberately small room. Its threshold, seed, and classifications should remain visible so an undecided sample is not mistaken for an empty one.</p><p>The next hall, <a href="speculative-rhizome.html"><strong>SpeculativeComputation_Rhizome_Network</strong></a>, replaces one centre with many connected paths.</p>'+score
(O/"speculative-uncertainty.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What Remains When the Name Is Withheld? · Ada Research</title><style>'+css+'</style><main><nav><a href="speculative-morphological.html">Previous hall</a><a href="speculative-rhizome.html">Next hall</a><a href="/museum-progress?sequence=speculativecomputation">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8"); assets=["speculative-uncertainty.html","speculative-uncertainty-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8");(E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8");print(json.dumps(v))
