# Build the image-led Claude improvement brief from isolated captures.
from pathlib import Path
import json,html,re,hashlib,sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from recover_spine_platforms import write,save_json
ROOT=Path(__file__).resolve().parent.parent
GUIDE=ROOT/'doc/research/waves-chance-noise'
RUNS=ROOT/'ada_run/visual_review_20260912'
def main():
 plan=json.loads((GUIDE/'visual-review-plan.json').read_text(encoding='utf-8'))
 manifest={r['map']:r for r in json.loads((RUNS/'manifest.json').read_text(encoding='utf-8'))}
 cards=[]; evidence=[]; exports=[]; e=html.escape
 brief=['# Claude: improve what the museum images reveal','','Palle requested inside views of all the wavefunction and randomness halls you have worked on, and requests for improvement. Astra made an isolated serial capture pass on 12 September; any unavailable fresh view is explicitly labelled as an earlier capture. The featured views were inspected.','', '[Open the illustrated brief](http://localhost:3003/research/waves-chance-noise/visual-review.html).','', '## Working order','','Start with the blocked Synthesis Lab console, the hidden hand space in Effect Sound and the Pendulum panel facing away from its main view. Then address Intro contrast, Sine Space text fitting, Remove tray visibility and the Walk tank. Follow with the remaining readability requests. Fold Mushrooms feedback into current R4 work rather than restarting it.','', 'Make one consequential improvement per room before expanding the installation. Choose local materials, proportions, lighting and arrangement. Preserve meaningful strange bodies, the recovered platforms, newer partitions and museum route. Identify an obstruction before moving it; do not empty the museum for a clean photograph. Preserve running clocks and the invisible-point rule.','', 'Return matched before/after arrival, operating and consequence views. Check animation extremes. If a supplied probe view cannot be reached by the player, explain and capture the real standing view. Keep hand targets and the evidence they affect visible together. Images cannot prove hearing or headset reach.','', 'Keep final.md and primary/book roles aligned when behavior or staging changes, retaining the discovery voice. A long parameter inventory belongs in technical.md; the visible instrument should prioritise information useful to the current choice.','', '## Generalise from a working local improvement','','- Readable cased controls: consistent contrast and useful units, with each room keeping its own character. Start with the washed-out cream panels; avoid an untested global lighting change.','- Protect the operating view through nearby movement. A floor route can be open while the evidence is hidden.','- Put information beside the hand space rather than in front of it.','- Give tiny samples a deliberate inspection position; magnification must keep the same data and identify the displayed subset.','', '## Runtime findings from this capture pass','']
 for row in plan['rooms']:
  name=row['map'];rec=manifest.get(name);folder=RUNS/name;fresh=bool(rec and rec.get('images'))
  if not fresh:folder=ROOT/'ada_run/waves_chance_noise'/name
  images=sorted(folder.glob('*.png'))
  if not fresh:
   live=[p for p in images if p.stem.endswith('_live')]
   images=live or images
  report={}
  if fresh and rec.get('reports'):report=json.loads((folder/rec['reports'][0]).read_text(encoding='utf-8'))
  log=(folder/'runner.log').read_text(encoding='utf-8',errors='replace') if (folder/'runner.log').exists() else ''
  exits=re.findall(r'child exited (\d+)',log);actual_exit=int(exits[-1]) if exits else (rec or {}).get('exit')
  checks=report.get('checks');fails=report.get('failures',[])
  if fails or actual_exit not in (0,None):brief.append('- '+name+': '+str(checks)+' assertions; '+str(len(fails))+' failed; engine child exit '+str(actual_exit)+'. '+('; '.join(fails) if fails else 'Assertions passing does not make the shutdown successful.'))
  selected=[folder/f for f in row['preferred_images'] if (folder/f).exists()]
  if not selected:selected=images[:2]
  remaining=[p for p in images if p not in selected];figs=[];irs=[]
  for p in selected+remaining:
   out='visual-'+name+'-'+p.name;data=p.read_bytes();write(GUIDE/'images'/out,data);exports.append('images/'+out)
   desc=p.stem.replace('probe_','').replace('_',' ')
   figs.append('<figure><a href="images/'+out+'" target="_blank"><img src="images/'+out+'" loading="lazy" alt="'+e(name+': '+desc)+'"></a><figcaption>'+e(desc)+' · <a href="images/'+out+'" target="_blank">original PNG</a></figcaption></figure>')
   irs.append({'file':'images/'+out,'source':p.relative_to(ROOT).as_posix(),'sha256':hashlib.sha256(data).hexdigest(),'featured':p in selected})
  badge='Fresh 12 September' if fresh else 'Earlier saved capture; fresh run unavailable'
  if name=='Random_Mushrooms' and (checks is None or checks<=3):badge+=' · survey, not completion'
  runtime=(str(checks)+' checks / '+str(len(fails))+' failed · engine exit '+str(actual_exit)) if checks is not None else 'Earlier view; no new run result claimed'
  c='<section class="room" id="'+name+'" data-sequence="'+row['sequence']+'" data-priority="'+str(row['priority'])+'"><p class="eyebrow">'+e(name)+' · '+e(badge)+'</p><h2>'+e(row['title'])+'</h2><span class="badge">'+('First: visibility and operation' if row['priority']==1 else 'Next: refinement')+'</span><p class="runtime">'+e(runtime)+'</p>'
  if fails:c+='<p class="warning">'+e('; '.join(fails))+'</p>'
  if actual_exit not in (0,None):c+='<p class="warning">Images were saved before an unsuccessful process exit. Runtime acceptance remains open.</p>'
  c+='<div class="featured">'+''.join(figs[:len(selected)])+'</div><div class="requests">'
  for label,key in [('What the images show','observed'),('Ask Claude','request'),('Keep','preserve'),('Show the improvement','acceptance')]:c+='<p><b>'+label+'.</b> '+e(row[key])+'</p>'
  c+='</div>'
  if remaining:c+='<details><summary>'+str(len(remaining))+' more views</summary><div class="featured">'+''.join(figs[len(selected):])+'</div></details>'
  c+='<p><a href="/necklace/thread?map='+name+'&amp;role=primary">Primary artifacts and book</a> · <a href="#top">Room list</a></p></section>';cards.append(c)
  evidence.append({'map':name,'fresh':fresh,'capture':rec,'engine_child_exit':actual_exit,'checks':checks,'failures':fails,'images':irs})
 brief+=['','Investigate these findings and repeat affected checks after repair; do not suppress assertions. No new listener or headset evidence was produced. These reruns used isolated copies of the existing live probes and a snapshot of the saved hand/progress file. Original report fields may still call that file real; the capture manifest identifies the isolated run. Assertion failures need reproduction before assigning a cause.','', '## Room instructions','']
 for r in plan['rooms']:
  brief+=['### '+r['map']+' — '+r['title'],'','[Images](http://localhost:3003/research/waves-chance-noise/visual-review.html#'+r['map']+')','','**Observed:** '+r['observed'],'','**Improve:** '+r['request'],'','**Keep:** '+r['preserve'],'','**Show it works:** '+r['acceptance'],'']
 brief+=['## Return and commit','','Return one visual-pass handback with matched before/after views, changed files, the rooms actually completed, targeted checks and remaining observations. Existing authorization for coherent commits of completed scoped work continues; check what is already committed and leave unrelated changes out. No forum message is requested. This brief is an image-led assignment, not acceptance of unfinished runtime work.','']
 text='\n'.join(brief);write(GUIDE/'VISUAL_IMPROVEMENTS.md',text.encode());write(ROOT/'doc/book/handoffs/fable-wcn-visual-improvements-2026-09-12.md',text.encode())
 save_json(GUIDE/'visual-review-evidence.json',evidence)
 nav=''.join('<a href="#'+r['map']+'">'+e(r['map'].replace('WaveFunctions_','').replace('Random_','Random '))+'</a>' for r in plan['rooms'])
 n=sum(len(r['images']) for r in evidence);fresh_n=sum(r['fresh'] for r in evidence)
 page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inside the rooms · Ada Research</title><style>*{box-sizing:border-box}body{margin:0;background:#f3efe6;color:#25282d;font:18px/1.65 system-ui,sans-serif}main{max-width:1220px;margin:auto;padding:32px 26px 70px}h1,h2{font-family:Georgia,serif;line-height:1.1}h1{font-size:clamp(44px,6vw,78px)}h2{font-size:34px}a{color:#862851;text-underline-offset:3px}nav{display:flex;flex-wrap:wrap;gap:12px 22px}.eyebrow,.runtime,figcaption{font-size:13px;color:#5b6068}.intro{font:24px/1.5 Georgia,serif;max-width:900px}.room{margin:32px 0;padding:26px;background:#fffdf8;border:1px solid #d8cfc4;border-radius:8px;scroll-margin-top:20px}.featured{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-top:20px}figure{margin:0}img{width:100%;height:auto;border-radius:4px;display:block}.requests{max-width:980px}.requests p{margin:18px 0}.requests p:nth-child(2){border-left:4px solid #862851;padding-left:18px}.badge{font-size:12px;border:1px solid #aa718a;border-radius:20px;padding:4px 12px}.warning{background:#fff1d7;padding:12px;font-size:14px}.filters{display:flex;flex-wrap:wrap;gap:20px;padding:20px 0}label{font-size:14px}select{display:block;padding:8px;font:16px system-ui;background:white;border:1px solid #9e9b97;border-radius:4px}summary{cursor:pointer;padding:16px 0;font-size:15px}.hidden{display:none}@media(max-width:760px){main{padding:20px 14px}.room{padding:18px}.featured{grid-template-columns:1fr}h2{font-size:29px}}</style></head><body><main id="top"><nav><a href="index.html">Room plans</a><a href="VISUAL_IMPROVEMENTS.md">Claude's assignment</a><a href="book-voice.html">Book voice</a></nav><p class="eyebrow">Ada Research · 12 September 2026 · images from inside the museum</p><h1>Let the artifact<br>come into view.</h1><p class="intro">A control can work while hiding what it changes. A number can be correct and too small to read. These images ask what the visitor can discover from the place where they stand.</p>'''
 page+='<p><b>'+str(len(evidence))+' rooms · '+str(n)+' original captures · '+str(fresh_n)+' rooms freshly captured.</b> All six wavefunction halls and six randomness halls with Claude work or a survey. Unworked rooms and extensions are outside this set. Featured views were inspected; further views are available for comparison.</p><p>Each card gives one consequential improvement, what to preserve, and evidence to return. Full-size PNGs are unchanged. These are desktop museum renders; images cannot establish headset reach or what a person hears. Failed checks and unsuccessful exits remain visible.</p><nav aria-label="Rooms">'+nav+'</nav><div class="filters"><label>Sequence<select id="sequence"><option value="">All rooms</option><option value="wavefunctions">Wavefunctions</option><option value="randomness">Randomness</option></select></label><label>Priority<select id="priority"><option value="">All improvements</option><option value="1">Visibility and operation first</option><option value="2">Refinements</option></select></label></div><p id="shown" class="runtime"></p>'+''.join(cards)
 page+='<nav><a href="VISUAL_IMPROVEMENTS.md">Full handoff</a><a href="visual-review-evidence.json">Provenance and run results</a></nav></main><script>const rooms=[...document.querySelectorAll(".room")],seq=document.querySelector("#sequence"),pri=document.querySelector("#priority");function filter(){let n=0;for(const r of rooms){const show=(!seq.value||r.dataset.sequence===seq.value)&&(!pri.value||r.dataset.priority===pri.value);r.classList.toggle("hidden",!show);n+=show}document.querySelector("#shown").textContent=n+" of "+rooms.length+" rooms shown"}seq.addEventListener("change",filter);pri.addEventListener("change",filter);function reveal(){const r=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(r&&r.classList.contains("room")){seq.value="";pri.value="";filter();r.scrollIntoView({block:"start"})}}window.addEventListener("hashchange",reveal);filter();reveal();</script></body></html>'
 write(GUIDE/'visual-review.html',page.encode());exports+=['VISUAL_IMPROVEMENTS.md','visual-review-plan.json','visual-review.html','visual-review-evidence.json'];save_json(RUNS/'publish-files.json',exports)
 print(json.dumps({'rooms':len(evidence),'fresh':fresh_n,'images':n}))
if __name__=='__main__':main()
