#!/usr/bin/env python3
"""
build_gallery_loader_demo.py
=============================

Builds a tiny test map `Gallery_Loader_Demo` showing three DNA findings
placed via the federated approach: each finding uses its grammar's
EXISTING builder artifact directly via tokens generated by
tools/promote_to_artifact.py — no central wrapper.

  facade-gallery / classical              → facade_builder:0:0#preset:classical
  primitive-stack-gallery / <best-of-id>  → composition_artifact:...
  lsystem-gallery / <best-of-id>          → image_billboard:... (no live builder yet)

This is the "long-run" path: each artifact stays canonical, the Python
helper generates tokens, image_billboard handles galleries without a
live builder. No gallery_loader. No dispatch table in GDScript.
"""

from __future__ import annotations
import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))
from measure_artifact_aabbs import _find_godot                       # noqa: E402
from promote_to_artifact import resolve, make_token                  # noqa: E402

ENC = REPO.parent / "ada_encyclopedia"
MAP_NAME = "Gallery_Loader_Demo"
MAP_DIR = REPO / "commons" / "maps" / MAP_NAME

# Pick best-of entries spanning grammars. Each uses the existing
# per-grammar artifact wrapper via tokens generated by promote_to_artifact.py.
# Galleries without a wrapper fall through to image_billboard.
SLOTS = [
    {"cell": (3, 3),  "gallery": "mesh-grammar-gallery",    "entry_id": "gen00_petals",                 "label": "Mesh: Petals"},
    {"cell": (3, 8),  "gallery": "primitive-stack-gallery", "entry_id": "ps07_kras_slon_round",         "label": "Prim Stack"},
    {"cell": (3, 13), "gallery": "lsystem-gallery",         "entry_id": "ls21_cpfg_weeping_plant",      "label": "L-system"},
    {"cell": (7, 3),  "gallery": "pattern-gallery",         "entry_id": "pt04_p6m_persian",             "label": "Pattern"},
    {"cell": (7, 8),  "gallery": "rd-gallery",              "entry_id": "rd13_lambda_hex_heightmap",    "label": "RD"},
    {"cell": (7, 13), "gallery": "mesh-grammar-gallery",    "entry_id": "gen00_mushroom",               "label": "Mesh: Mushroom"},
]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--no-godot", action="store_true",
                    help="Write the map; skip the Godot render.")
    args = ap.parse_args()

    rows, cols = 12, 18
    structure = [["1" for _ in range(cols)] for _ in range(rows)]
    utilities = [[" " for _ in range(cols)] for _ in range(rows)]
    interactables = [[" " for _ in range(cols)] for _ in range(rows)]
    utilities[0][cols // 2] = "sp"
    utilities[rows - 1][cols // 2] = "t"

    # Each slot: tokens generated by promote_to_artifact.py — picks the
    # grammar's existing builder artifact (facade_builder, composition_artifact,
    # image_billboard fallback), not a central dispatcher.
    for s in SLOTS:
        r, c = s["cell"]
        artifact, params, render_mode = resolve(s["gallery"], s["entry_id"])
        interactables[r][c] = make_token(artifact, params)
        print(f"  {s['gallery']}/{s['entry_id']:30s} -> {render_mode:5s} via {artifact}")

    # Bonus: delegate_to via registry — promoted finding without token tail.
    # Promote one of the mesh_grammar slots to a registry entry so the demo
    # also exercises the delegate_to path without needing facade.
    interactables[10][cols // 2] = "dna_mesh_grammar_gen00_petals:0:0"
    print(f"  registry-delegate: dna_mesh_grammar_gen00_petals -> mesh_grammar_artifact via delegate_to")

    md = {
        "map_info": {
            "name": MAP_NAME, "lookup_name": MAP_NAME,
            "description": (
                "Demo: three gallery_loader artifacts side by side, each "
                "rendering a different best-of entry. Proves the dispatch "
                "wrapper works end-to-end. Walk left → right: L-system "
                "tree, facade preview, graph preview."
            ),
            "format": "json", "version": "1.0",
            "dimensions": {"width": cols, "depth": rows, "max_height": 3},
            "metadata": {
                "source": "build_gallery_loader_demo.py",
                "demonstrates": "gallery_loader dispatch via (gallery, entry_id)",
            },
        },
        "layers": {
            "structure": structure, "utilities": utilities,
            "interactables": interactables,
        },
        "settings": {
            "cube_size": 1, "gutter": 0, "show_grid": True,
            "background": {"type": "sky", "color": [0.07, 0.08, 0.12]},
            "grid_animation": {"enabled": False},
        },
        "utility_definitions": {
            "sp": {"type": "spawn"}, "t": {"type": "teleporter"},
        },
    }

    MAP_DIR.mkdir(parents=True, exist_ok=True)
    (MAP_DIR / "map_data.json").write_text(
        json.dumps(md, indent="\t", ensure_ascii=False) + "\n", encoding="utf-8")
    (MAP_DIR / "blurb.md").write_text(
        f"# {MAP_NAME}\n\nDemo of gallery_loader dispatch — three best-of "
        f"findings rendered side by side from one registry entry.\n",
        encoding="utf-8")
    # Drop the per-slot registry — the parameters travel in the token now.
    old_reg = REPO / "commons" / "artifacts" / "registry" / "gallery_loader_demo.json"
    if old_reg.exists():
        old_reg.unlink()

    print(f"Wrote map:      {MAP_DIR.relative_to(REPO)}/")
    print()
    print(f"Three.js view:  http://localhost:3003/map-3d/{MAP_NAME}")

    if args.no_godot:
        return

    godot = _find_godot()
    if not godot:
        print("\nNo Godot — skipping render. Set GODOT_EXE to capture.")
        return

    # gallery_loader IS an artifact — don't suppress artifact spawning here.
    # (Previous capture pipelines set artifacts_enabled=false for clean grid
    # shots; that flag is sticky and would silently kill our render.)
    flags_path = REPO / "ada_run" / "runtime_flags.json"
    flags_path.parent.mkdir(parents=True, exist_ok=True)
    prior = {}
    if flags_path.exists():
        try:
            prior = json.loads(flags_path.read_text(encoding="utf-8"))
        except Exception:
            prior = {}
    flags = dict(prior)
    flags["biome_enabled"] = False           # clean background
    flags["artifacts_enabled"] = True        # MUST be true for gallery_loader
    flags["_capture_active"] = True
    flags_path.write_text(json.dumps(flags, indent=2) + "\n", encoding="utf-8")

    cap_out = ENC / "public" / "captures" / "maps"
    cap_out.mkdir(parents=True, exist_ok=True)
    cmd = [
        godot, "--path", str(REPO), "--xr-mode", "off", "--no-window",
        "--script", "res://commons/testing/capture_multi_angle.gd", "--",
        "--mode=map", f"--target={MAP_NAME}",
        f"--out={cap_out.as_posix()}",
        "--wait=4",
    ]
    print(f"\nRunning Godot capture…")
    proc = subprocess.run(cmd, cwd=str(REPO), timeout=180, capture_output=True)
    if proc.returncode != 0:
        print(f"  FAILED rc={proc.returncode}")
        if proc.stderr:
            print(f"  stderr tail: {proc.stderr.decode('utf-8', errors='ignore')[-500:]}")
        return

    src = cap_out / MAP_NAME
    if not src.exists():
        print(f"  No captures at {src}")
        return
    pngs = list(src.glob("*.png"))
    print(f"\nRendered {len(pngs)} angles:")
    for p in pngs:
        print(f"  http://localhost:3003/captures/maps/{MAP_NAME}/{p.name}")


if __name__ == "__main__":
    main()
