"""Illustrated Menger encounter from a successful current museum run."""
from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/menger-encounter-2026-09-14';RUN=R/'ada_run/menger-encounter-review-2026-09-14';M='Fractal_MengerSponge'
def dump(p,d):p.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
r=json.loads((RUN/'run.json').read_text());report=json.loads((RUN/M/'probe_ca_edge_live.json').read_text())
assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for n in ['entrance','uncut','first-cut','second-cut','removed-volume','desk','at-opening','above-sponge','small-opening','enclosure']:
 p=O/f'menger-study-{n}.png';shutil.copyfile(RUN/M/f'{n}.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
 p=O/f'menger-study-{kind}.md';shutil.copyfile(R/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
 old=E/f'before/commons/maps/{M}/{kind}.md'
 if old.exists():
  p=O/f'menger-study-previous-{kind}.md';shutil.copyfile(old,p);assets.append(p.name)
dump(O/'menger-study-verification.json',r);assets.append('menger-study-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>A hole becomes a place · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="fractal-learning-arc.html#Fractal_MengerSponge">← The fractal walk</a><a href="/necklace/thread?map=Fractal_MengerSponge&role=primary">Primary artifact / book</a><a href="/museum-progress?sequence=fractals&room=Fractal_MengerSponge">Museum progress</a></nav>
<p class="eyebrow">ADA RESEARCH · MENGER SPONGE · 14 SEPTEMBER 2026</p><h1>A hole becomes<br>a place.</h1><p class="lead">The next cut makes more openings. Borrow flight, follow one through, then find a passage the eye can enter before the body can.</p>
<div class="facts"><div><strong>5</strong><span>existing placements retained</span></div><div><strong>1</strong><span>primary / continuous book passage</span></div><div><strong>729 → 400 m³</strong><span>retained volume across two cuts</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="menger-study-entrance.png" alt="A glass flight enclosure around the nine-metre Menger sponge with a doorway at floor level"><figcaption>Actual Godot capture after two cuts. The existing flight enclosure remains, with a compact teaching desk beside its front entrance.</figcaption></figure>
<section><p class="step">01 / LOOK BEFORE THE CUT</p><h2>The cube has no entrance.</h2><p>The room now begins with the uncut cube. Press NEXT at the desk. A square opening appears; looking through reveals a crossing inside. Another NEXT repeats the selection within each retained block.</p>
<div class="pair"><figure><img loading="lazy" src="menger-study-uncut.png" alt="The uncut nine-metre cube before removal"><figcaption>Cut 0: one nine-metre cube, 729 m³ retained.</figcaption></figure><figure><img loading="lazy" src="menger-study-first-cut.png" alt="The first Menger cut opens three intersecting passages through the cube"><figcaption>Cut 1, same view: twenty three-metre cubes, 540 m³ retained.</figcaption></figure></div>
<p>At cut 2, four hundred one-metre cubes retain 400 m³. The outer bounds still measure nine metres in each direction. Object count increases while retained volume falls.</p>
<blockquote>More objects have been made to represent less material.</blockquote><p>The source addresses a 3×3×3 grid. It removes the centre and six face centres, leaving twenty cells to receive the next call. RULE brings the operation into the encounter after we have compared its effects.</p></section>
<section><p class="step">02 / READ THE REMOVAL</p><h2>What the body borrows.</h2><p>FRAME holds the outside of the original cube in view. GHOST marks the removed volume: seven large cells from the first cut and 140 smaller ones from the second. Changing these views preserves every solid cube.</p>
<div class="pair"><figure><img loading="lazy" src="menger-study-second-cut.png" alt="Second-generation Menger sponge with its nine-metre outer boundary marked"><figcaption>Two cuts, solid geometry. The outer frame does not add collision.</figcaption></figure><figure><img loading="lazy" src="menger-study-removed-volume.png" alt="Pale ghost cubes mark the cross-shaped volume removed from the sponge"><figcaption>The same view with GHOST. The 147 recorded removals total 329 m³. Their pale meshes have no collision.</figcaption></figure></div>
<blockquote>The removed volumes may become somewhere to be.</blockquote><p>Leave two cuts showing, then enter the ground frame. The glass enclosure lends flight. Look and use WASD, Space and Ctrl on desktop; in VR, tilt the left controller and use its stick. Release to hover. Descend to either ground door to leave.</p></section>
<section><p class="step">03 / ENTER AND COMPARE</p><h2>A connection for which body?</h2><figure><img loading="lazy" src="menger-study-at-opening.png" alt="A view from the museum walker approaching the large central passage while flying"><figcaption>The native museum walker rises to the three-metre central passage. Its solid capsule remains active.</figcaption></figure>
<div class="pair"><figure><img loading="lazy" src="menger-study-above-sponge.png" alt="The sponge viewed from above during flight inside the glass cube"><figcaption>Flying changes which openings can be reached and how they overlap in projection.</figcaption></figure><figure><img loading="lazy" src="menger-study-small-opening.png" alt="Looking through a one-metre axial opening in the sponge"><figcaption>A ray crosses this one-metre tunnel. The tested standing capsule cannot enter it.</figcaption></figure></div>
<p>The native museum capsule is 1.5 m high and 0.64 m wide. Flight gives it access to the large opening without changing those dimensions or making walls permeable. XR body dimensions depend on the tracked visitor; this desktop test does not stand in for every body.</p><blockquote>There was a connection in the geometry. There was not yet a route for every body.</blockquote><p>A third cut would ask for eight thousand retained cubes, with edges a third of a metre long and smaller openings again. Whether that would improve an encounter remains a question. The displayed finite sponge retains positive volume; the infinite construction's zero-volume limit is not what we are touching.</p></section>
<section><h2>The last shape has an inhabitant.</h2><figure><img loading="lazy" src="menger-study-desk.png" alt="A compact six-button desk outside the flight volume with a small transparent tilted screen"><figcaption>NEXT, BACK, GHOST, FRAME, RESET and RULE are reachable from one standing position outside the enclosure.</figcaption></figure><p>NEXT, BACK and RESET refuse a solid rebuild while a visitor is inside. Leaving does not execute a delayed change; another press is needed. GHOST and FRAME remain available because they do not alter collision.</p><p>This carries the discussion of <em>entropic morality</em> into one concrete dependency: someone at a control desk can propose a revision while another body relies on the current arrangement. The interlock preserves that visitor's present route out. It is a limited implemented condition, not a claim that the installation has resolved every question of authority or access.</p></section>
<details><summary>Read the book passage</summary><article>__BOOK__</article><p><a href="menger-study-final.md">Manuscript</a> · <a href="menger-study-technical.md">Implementation</a> · <a href="menger-study-critical.md">Critical questions</a> · <a href="menger-study-tutorial.md">Encounter order</a></p></details>
<section><h2>The surrounding work remains.</h2><p>The aggregation study, catalyst prompter, catalyst vent and dark sphere remain in their authored cells. The map structure, basin, floor coverage and twelve-metre flight enclosure are retained. The neighbouring aggregation has its own random walks and attachment rule; this desk does not control it.</p><p>The earlier flight manuscript is preserved. Supporting technical and critical texts that still described recursive trees have been archived and replaced with accounts of this room. <a href="menger-study-previous-final.md">Earlier manuscript</a> · <a href="menger-flight.html">Earlier flight installation review</a>.</p></section>
<section><h2>What was checked?</h2><p>__CHECKS__ checks passed: all five placements; six desk controls through the real desktop pointer pipeline; 1/20/400 cubes, their size and volume; unchanged outer bounds; ghost and frame views; bounded rebuilds; occupied-room refusal; native museum keyboard flight through and around the sponge; roof and side collision; exit and resumed gravity; synthetic XR controller ascent, hover and release; and the small tunnel that carries a ray but refuses the standing capsule.</p><p class="note">The desk uses synthetic input through the project's standalone DesktopPlayer inside the actual museum. Native museum flight and the XR movement adapter are checked separately. This does not certify native mouse interaction with the desk or a person's headset experience. Headset reach, comfort and Quest frame time remain pending. The user's open editor, museum and saved hand were preserved.</p></section>
<section class="next"><h2>Next: a number needs a mapping.</h2><p>Golden Spiral moves from twenty descendants to a recurrence that receives the preceding two quantities. How does that numerical relationship become a form, and what does the visual mapping let us compare?</p><a href="/necklace/thread?map=Fractal_GoldenSpiral&role=primary">Continue to Fractal_GoldenSpiral →</a></section>
<footer><a href="menger-study-verification.json">Runtime receipt</a> · <a href="fractal-learning-arc.html">Seven-hall learning arc</a> · <a href="koch-sierpinski.html">Previous: Koch / Sierpinski</a></footer></main></body></html>'''
page=page.replace('__CSS__',css).replace('__CHECKS__',str(r['checks'])).replace('__BOOK__',book)
(O/'menger-encounter.html').write_bytes(page.encode());assets.append('menger-encounter.html')
assets+=['fractal-learning-arc.html','fractal-learning-arc.json','fractal-learning-arc.md']
# The earlier page remains a record of that stage, with a link to the new one.
p=O/'menger-flight.html';s=p.read_text()
if 'The teaching encounter has since been developed' not in s:
 s=s.replace('<main>','<main><p class="note">The teaching encounter has since been developed: <a href="menger-encounter.html">a compact desk, finite cuts and a comparison of body access</a>. This page records the earlier flight installation.</p>',1)
 p.write_bytes(s.encode())
assets.append('menger-flight.html')
for n,src in [('receipt.json',RUN/'run.json'),('report.json',RUN/M/'probe_ca_edge_live.json'),('engine.log',RUN/M/'engine.log')]:shutil.copyfile(src,E/n)
targets=['possible-bodies/'+a for a in assets];dump(E/'publish-targets.json',targets)
dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Menger encounter: {len(targets)} files, {r["checks"]} checks.')
