from pathlib import Path
import json, hashlib, markdown

R=Path(__file__).resolve().parents[1]
E=R/'doc/space/pg-floor-audit-2026-09-14'
O=R/'doc/research/possible-bodies'
a=json.loads((E/'audit.json').read_text())
for rel,h in a['plans_after_sha256'].items():
    assert hashlib.sha256((R/rel).read_bytes()).hexdigest()==h,rel
for row in a['maps']:
    assert hashlib.sha256((R/f'commons/maps/{row["map"]}/map_data.json').read_bytes()).hexdigest()==row['source_sha256']

notes={
'PG_Genetic_Evolution':'The source already has a continuous floor. Its 25 numeric height-3 cells still become full museum walls under the default threshold. Inspect the ramps and the population footprint before staging the encounter. The actual artifact scores generated geometry; it does not supply the locomotion arena described in the older tutorial.',
'PG_Space_Colonization':'Listed in sequence and book; absent from map_authored and both active plans. Its 43 old voids and the decision to restore its place in the route need an explicit review.',
'PG_Percolation_Network':'No remaining source zeros. The 102 height-2 cells already have a wall-height threshold of 3, so they become raised decks. Verify their approaches and artifact height in the encounter.',
'PG_Branching_Growth':'23 inherited voids, plus nine numeric height-3 cells currently read as walls. The organic-space artifact has collision code, but that does not establish support across these particular map cells.',
'PG_Caves_Mazes':'32 inherited voids. The cave builds solid-cell colliders and the maze builds path-floor colliders; both are scaled to 0.5 in this map. Inspect their actual footprints and entrances. The old teleporter at (13,9) also sits on a zero.',
'PG_Sculpted_Forms':'42 inherited voids. Cube mound has its own ground body, but its coverage must be measured after placement. A generated shape is not automatically a supporting surface. The old teleporter at (11,11) also sits on a zero.',
'PG_Mirrored_Patterns':'34 inherited voids. Establish whether the reflected and rhizomatic forms are viewed, entered, or both; then test the relevant support. The old teleporter at (10,8) also sits on a zero.'}

rows=''.join(f'<tr><td><a href="#map-review" data-map="{r["map"]}">{r["map"]}</a></td><td>{r["cached_voids"] if r["active"] else "off route"}</td><td>{r["source_voids"]}</td><td>{len(r["cache_changes"])}</td></tr>' for r in a['maps'])
data=json.dumps([dict(r,note=notes[r['map']]) for r in a['maps']],ensure_ascii=False).replace('</','<\\/')
css='''*{box-sizing:border-box}body{margin:0;background:#111e28;color:#e6e1d5;font:17px/1.6 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:36px 25px 70px}a{color:#ecabc8}nav{display:flex;flex-wrap:wrap;gap:24px;font-size:14px}h1{font:clamp(40px,6vw,76px)/1.03 Georgia,serif;max-width:760px}h2{font:32px/1.2 Georgia,serif}.lead{font-size:22px;max-width:850px}.eyebrow{margin-top:45px;color:#b6c9c4;letter-spacing:.1em;font-size:12px}section{margin-top:48px}.cards,.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card,figure{margin:0;padding:22px;background:#1c2e3c;border:1px solid #3b505c;border-radius:8px}.card strong{display:block;font-size:28px}.card p{margin-bottom:0}code{color:#eac1d5}table{width:100%;border-collapse:collapse;font-size:15px}th,td{border-bottom:1px solid #425663;text-align:left;padding:12px 8px}.table-wrap{overflow:auto}select{max-width:100%;padding:12px;border:1px solid #69818c;background:#1c2e3c;color:#fff;font-size:16px;border-radius:4px}label{display:block;margin-bottom:8px}svg{display:block;width:100%;max-height:460px;margin:16px auto;background:#0c151e}figcaption{font-size:14px;color:#d1d8d7}.legend{display:flex;gap:18px;flex-wrap:wrap;font-size:14px}.dot{display:inline-block;width:13px;height:13px;margin-right:6px}.note{border-left:3px solid #dfa1bd;padding-left:20px}.small,footer{font-size:14px;color:#bfccca}footer{margin-top:50px}@media(max-width:700px){.pair,.cards{grid-template-columns:1fr}main{padding:22px 16px}td,th{padding:8px 5px}}'''
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What holds the floor? · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="assemblage-same-desire.html">← Assemblage</a><a href="spine-iteration.html">Working method</a><a href="/museum-progress?sequence=proceduralgeneration">Sequence progress</a></nav>
<p class="eyebrow">PROCEDURAL GENERATION · FLOOR AUDIT · 14 SEPTEMBER 2026</p><h1>What holds<br>the floor?</h1><p class="lead">A zero is an absence of grid structure. It is not a floor at zero height. Carrying that absence into the museum requires us to ask what will support the body there.</p>
<div class="cards"><div class="card"><strong>56 stale holes corrected</strong><p>Both saved plans contained 56 zero cells that the current maps already describe as floor. Seven stale wall cells also become the source-defined floor: 63 tile corrections per plan.</p></div><div class="card"><strong>131 source gaps to review</strong><p>All are inherited from the July grid layouts across six active halls. Their age establishes provenance, not that an artifact now supplies a floor there.</p></div></div>
<section><h2>Three records can disagree.</h2><p>The source <code>map_data.json</code> describes the room. The portable <code>em_plan.json</code> contains a saved interpretation. A map-authored hall normally rereads its source when Godot builds it, then applies museum staging and saved rulings. A pushed <code>user://</code> map can override the packaged source. The plan alone is therefore insufficient evidence of the floor in a running headset.</p><p>This repair synchronizes only the saved tile and its floor count. It preserves every source map, artifact placement, role, route and curation record. Runtime collision and headset verification remain pending.</p></section>
<section><h2>The current sequence</h2><div class="table-wrap"><table><thead><tr><th>Hall</th><th>Saved zeros before</th><th>Source zeros</th><th>Saved tile corrections</th></tr></thead><tbody>__ROWS__</tbody></table></div><p class="small">Space Colonization is listed in the seven-map sequence but absent from the six-map active museum declaration. This audit records the discrepancy; it does not silently change the route.</p></section>
<section id="map-review"><h2>Compare the floor records</h2><label for="hall">Hall</label><select id="hall">__OPTIONS__</select><p id="note" class="note"></p><label for="left-mode">Left comparison</label><select id="left-mode"><option value="cached_tile">Saved museum plan before correction</option><option value="historical_structure">July grid structure</option><option value="current_structure">Current grid structure</option></select><div class="pair" style="margin-top:20px"><figure><div id="before"></div><figcaption id="before-caption"></figcaption></figure><figure><div id="current"></div><figcaption>Current source interpreted as museum tiles. Artifact footprints, ramps, raised-deck heights and saved runtime rulings require separate checks.</figcaption></figure></div><p class="legend"><span><i class="dot" style="background:#ac496c"></i>0 · no grid floor</span><span><i class="dot" style="background:#e0d3ac"></i>1 · floor</span><span><i class="dot" style="background:#637484"></i>wall</span><span><i class="dot" style="background:#63b9b3"></i>numeric height in grid view</span></p><p class="small">Hover a cell for its x,z address and encoded value. In the museum interpretation, numeric heights at or above that map's wall threshold are shown as walls. Lower raised decks are encoded as floor with a separate height record.</p></section>
<section><h2>Before we write the next hall</h2><ol><li><strong>Name who supplies support:</strong> museum slab, authored platform, an artifact's collider, or an intentional void.</li><li><strong>Stage the generated space:</strong> define its footprint, a clear museum margin and an entrance/exit. Keep the circulation route usable independently of random outcomes unless the encounter explicitly tests that dependence.</li><li><strong>Check the actual body:</strong> measure artifact placement and scale, then test collision at entrances, controls, void edges and the onward route.</li><li><strong>Record exceptions in the map:</strong> use explicit platforms and the correct wall threshold; use <code>museum.floor_cells</code> for specific museum covers when the legacy grid must retain a zero. Do not globally redefine zero.</li><li><strong>Write from that result:</strong> distinguish a generated image, generated geometry and a space that actually carries a body.</li></ol></section>
<section><h2>First: Genetic Evolution</h2><p>The source currently has no zero cells, so its floor should not be rebuilt from the stale plan's 53 holes. The next review must resolve 25 numeric height-3 cells that the default museum rule interprets as walls, inspect its wedges, and fit the population display and controls.</p><p>The implementation evaluates geometric targets such as volume, height and symmetry. It does not run the walking-creature trial described by the earlier tutorial. This is exactly why the floor, artifact and text need to be examined together before we continue.</p></section>
<footer><a href="pg-floor-audit.json">Audit, cells and source hashes</a> · <a href="pg-floor-audit.md">Research note</a> · Static source/history and plan checks completed; this page is a data comparison, not a Godot screenshot or a completed walkability test.</footer>
</main><script>const maps=__DATA__;const hall=document.getElementById('hall'),mode=document.getElementById('left-mode');function draw(tile,raw){if(!tile)return '<p>This hall has no active saved museum plan.</p>';const h=tile.length,w=Math.max(...tile.map(r=>r.length)),s=22;let out='<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Floor cell comparison" viewBox="0 0 '+(w*s)+' '+(h*s)+'">';tile.forEach((row,z)=>row.forEach((v,x)=>{v=String(v);const col=v==='0'?'#ac496c':v==='w'||(!raw&&v==='4')?'#637484':v==='1'?'#e0d3ac':'#63b9b3';out+='<rect x="'+(x*s)+'" y="'+(z*s)+'" width="21" height="21" fill="'+col+'"><title>('+x+','+z+') = '+v+'</title></rect>';if(v!=='1')out+='<text x="'+(x*s+11)+'" y="'+(z*s+15)+'" text-anchor="middle" font-size="11" fill="#111e28" pointer-events="none">'+v+'</text>';}));return out+'</svg>';}function render(){const m=maps.find(m=>m.map===hall.value);document.getElementById('note').textContent=m.note;document.getElementById('before').innerHTML=draw(m[mode.value],mode.value!=='cached_tile');document.getElementById('current').innerHTML=draw(m.current_tile,false);document.getElementById('before-caption').textContent=mode.selectedOptions[0].textContent+' · '+m.map;}hall.onchange=render;mode.onchange=render;document.querySelectorAll('[data-map]').forEach(a=>a.onclick=()=>{hall.value=a.dataset.map;render();});render();</script></body></html>'''
page=page.replace('__CSS__',css).replace('__ROWS__',rows).replace('__OPTIONS__',''.join(f'<option>{r["map"]}</option>' for r in a['maps'])).replace('__DATA__',data)
(O/'pg-floor-audit.html').write_bytes(page.encode())
(O/'pg-floor-audit.json').write_bytes((E/'audit.json').read_bytes())
note='''# What holds the floor?

14 September 2026. A source and history audit before procedural generation.

`0` means no grid structure. `1` supplies the ordinary floor. Numeric higher values describe stacks in the grid, but the museum uses `wall_height` (default 2) to decide whether they become walls or raised decks. `w` is an explicit wall. A generated object does not automatically replace missing support.

Both portable plans had 56 zero cells where the current maps specify floor, plus seven stale wall cells: 63 tile corrections per plan. Only tile and interior_count changed. Every source map, artifact placement, role and route is preserved. Map-authored Godot halls normally reread source maps at build time, so these cache repairs are not evidence that 56 actual runtime holes were filled.

The six active maps retain 131 source zeros. Every one matches a zero in the July grid after accounting for the later perimeter offset. Those gaps need a bodily review before acceptance. Three old teleporter zeros survive at Caves (13,9), Sculpted Forms (11,11), and Mirrored Patterns (10,8); the museum manages its own transport, so the old utility is not itself a reason to leave a hole. Specific covers can use museum.floor_cells while preserving grid data.

Space Colonization has 43 additional source zeros and remains in the sequence/book, but is absent from map_authored and both active plans. Record and resolve that route discrepancy separately.

Genetic Evolution now has no source zeros; its 25 numeric height-3 cells still become full walls under the default threshold. Review those platforms and wedges, fit the population footprint and expose the actual scoring operation. The actual code scores geometric targets, not locomotion in the physical arena described by the earlier tutorial.

Before each hall: name the support owner; stage museum circulation and generated space separately; inspect source, placement, scale and collider; test entrance, controls, edges and onward route; then write the book. Preserve an intentional void with an explicit reason and a tested route. Runtime collision and headset tests have not been performed by this audit.
'''
(O/'pg-floor-audit.md').write_bytes(note.encode())
(E/'README.md').write_bytes((note+'\nEvidence: audit.json records exact cells, history and hashes. before/ archives both original plans and all seven current maps. historical/ contains the July maps. tools/audit_pg_floors.py is read-only by default; its explicit --repair-cache mode refuses to overwrite this archive. No engine or artifact code changed.\n').encode())
p=O/'spine-iteration.md';s=p.read_text()
addition='''**Floor review comes first:** [What holds the floor?](pg-floor-audit.html) records the source/history audit. Both portable plans are synchronized; source zeros remain unresolved architectural choices. Before the PG encounter, identify museum support, generated support and intentional absence; inspect raised heights versus walls, ramps, controls and the route through the hall. Genetic Evolution has no source zeros but 25 height-3 cells read as walls. Its actual fitness measures geometry, not locomotion. Space Colonization is in the sequence/book but absent from the active museum route. Resolve these discrepancies explicitly as we develop the chapter.

'''
if addition not in s:s=s.replace('## Current next action\n\n','## Current next action\n\n'+addition);p.write_bytes(s.encode())
method=markdown.markdown(s,extensions=['tables'])
(O/'spine-iteration.html').write_bytes(('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>First traverse. Then return.</title><style>'+css+'</style></head><body><main><nav><a href="pg-floor-audit.html">Floor review</a><a href="assemblage-same-desire.html">Assemblage</a></nav>'+method+'</main></body></html>').encode())
assets=['pg-floor-audit.html','pg-floor-audit.json','pg-floor-audit.md','spine-iteration.html','spine-iteration.md']
targets=['possible-bodies/'+p for p in assets]
(E/'publish-targets.json').write_bytes((json.dumps(targets,indent=2)+'\n').encode())
(E/'publish-hashes.json').write_bytes((json.dumps({p:hashlib.sha256((R/'doc/research'/p).read_bytes()).hexdigest() for p in targets},indent=2)+'\n').encode())
print('Built floor audit, interactive cell comparison and working method.')
