from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R = Path.cwd(); M = "Russell_Paradox"; MAP = R / "commons/maps" / M
O = R / "doc/research/possible-bodies"; E = R / "doc/space/foundations-russell-2026-09-15"; E.mkdir(parents=True, exist_ok=True)
data = json.loads((MAP / "map_data.json").read_text(encoding="utf-8")); roles = json.loads((R / "commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]
tokens = [x.strip().split(":",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks = {"map_dimensions": data["map_info"]["dimensions"] == {"width":13,"depth":14,"max_height":3}, "six_artifacts": len(tokens)==6 and len(set(tokens))==6, "primary_focus": roles.get("russell_set_box")=="primary" and roles.get("barber_paradox")=="primary", "registers_present": all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]), "nested_structure": len(data["layers"]["structure"])==14 and len(data["layers"]["structure"][0])==13}
try:
    checks["registry_resolution"] = subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode == 0
except OSError: checks["registry_resolution"] = False
verification = {"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["russell_set_box","barber_paradox"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"foundations-russell-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css = re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book = markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram = '''<figure><svg viewBox="0 0 900 260" role="img" aria-labelledby="r-title r-desc" xmlns="http://www.w3.org/2000/svg"><title id="r-title">The self-containing set</title><desc id="r-desc">Nested boxes lead to a central question that alternates between yes and no.</desc><rect width="900" height="260" rx="18" fill="#171329"/><g fill="none" stroke="#8ec9c1" stroke-width="5"><rect x="80" y="38" width="240" height="180" rx="12"/><rect x="125" y="70" width="150" height="116" rx="10"/><rect x="158" y="98" width="84" height="60" rx="8" stroke="#f58b8b"/></g><g fill="#eaf4f1" font-family="system-ui,sans-serif" text-anchor="middle"><text x="200" y="132" font-size="18">R</text><text x="560" y="102" font-size="24">R ∈ R ?</text><text x="560" y="150" font-size="20" fill="#f58b8b">YES → NO → YES → NO …</text><text x="560" y="198" font-size="16" fill="#8ec9c1">self-reference + negation</text></g><path d="M350 128h125" stroke="#f58b8b" stroke-width="4" stroke-dasharray="10 10"/></svg><figcaption>The question is not waiting for a value. Its rule changes the answer that value would give.</figcaption></figure>'''
body = ('<p class="date">Foundational crises · Hall 2 · 15 September 2026</p><h1>The Self-Containing Set</h1><p class="lead">A rule gathers every set that does not contain itself. The moment the rule asks about its own membership, the answer turns back on itself.</p><p><a href="/necklace/thread?map=Russell_Paradox&amp;role=primary">Primary artifacts and book</a> · <a href="/museum-progress?sequence=foundationscrisis">Museum progress</a></p>' + diagram + '<details><summary>Read the book passage</summary>' + book + '</details><h2>Containment becomes the contradiction</h2><p>The primary box and barber carry the same problem in two forms: an object that cannot be placed in its own classification. The liar, self-membership set, Hilbert hotel, and Euclid plaque remain as secondary witnesses, separating contradiction from a merely surprising infinity.</p><p>The hall turns the Foundations Crisis from choice to breakdown. There is no curvature value that repairs the set; the repair is to limit which descriptions are allowed to form sets. Next is <strong>Godel_Incompleteness</strong>, where a system can remain consistent and still fail to reach a truth about itself.</p>' + f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="foundations-russell-verification.json">Verification record</a></p>')
(O/"foundations-russell.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The Self-Containing Set · Ada Research</title><style>'+css+'</style><main><nav><a href="foundations-non-euclidean.html">Previous hall</a><a href="/museum-progress?sequence=foundationscrisis">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["foundations-russell.html","foundations-russell-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
