"""Publish the first L-systems encounter from real Godot evidence."""
from pathlib import Path
import hashlib,json,re,shutil
import markdown
R=Path(__file__).resolve().parents[1];O=R/'doc/research/possible-bodies';E=R/'doc/space/grammar-lab-2026-09-14';RUN=R/'ada_run/grammar-review-2026-09-14';M='LSystems_Grammar_Lab'
def dump(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
r=json.loads((RUN/'run.json').read_text());assert r['exit']==0 and not r['failures'] and r['sources_unchanged'] and r['original_hand_unchanged']
assert all(hashlib.sha256((R/p).read_bytes()).hexdigest()==h for p,h in r['source_sha256'].items())
assets=[]
for n in ['entrance','same-reading','same-sentence','new-sentence','controls','four-generations','sierpinski','plant','collection']:
 p=O/f'grammar-{n}.png';shutil.copyfile(RUN/M/f'{n}.png',p);assets.append(p.name)
p=O/'grammar-before.png';shutil.copyfile(E/f'baseline/{M}/entrance.png',p);assets.append(p.name)
for kind in ['final','technical','critical','tutorial']:
 for old in [False,True]:
  p=O/f'grammar-{"previous-" if old else ""}{kind}.md'
  shutil.copyfile((E/'before' if old else R)/f'commons/maps/{M}/{kind}.md',p);assets.append(p.name)
dump(O/'grammar-verification.json',r);assets.append('grammar-verification.json')
css=re.search(r'<style>(.*?)</style>',(O/'recursion-encounter.html').read_text(),re.S).group(1)
book=markdown.markdown((R/f'commons/maps/{M}/final.md').read_text(),extensions=['fenced_code'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The same sentence, another body · Ada Research</title><style>__CSS__</style></head><body><main>
<nav><a href="fractal-synthesis.html">← Fractal Synthesis</a><a href="/necklace/thread?map=LSystems_Grammar_Lab&amp;role=primary">Primary artifact / book</a><a href="spine-iteration.html">Our working method</a></nav>
<p class="eyebrow">ADA RESEARCH · L-SYSTEMS / 01 · 14 SEPTEMBER 2026</p>
<h1>The same sentence,<br>another body.</h1><p class="lead">Keep the letters. Change the turn. Follow the first bend across two drawings. What, exactly, has changed?</p>
<div class="facts"><div><strong>8</strong><span>earlier artifacts retained</span></div><div><strong>1</strong><span>primary, with two readings</span></div><div><strong>6</strong><span>physical desk controls</span></div><div><strong>__CHECKS__</strong><span>Godot checks passed</span></div></div>
<figure><img src="grammar-same-sentence.png" alt="Actual Godot museum: cyan live and pink held drawings of the same nine-symbol sentence at 120 and 90 degrees"><figcaption>Same sentence, different turning angles. The cyan live reading changes; the pink held snapshot keeps its earlier geometry. Each drawing is fitted to its display.</figcaption></figure>
<section><p class="step">01 / REWRITE, THEN READ</p><h2>First one F. Then five.</h2><p>NEXT replaces the initial F with <code>F+F-F-F+F</code>. Count five drawing instructions and four turning signs. HOLD copies that sentence and its actual geometry. TURN changes the live angle without rewriting.</p>
<div class="pair"><figure><img loading="lazy" src="grammar-entrance.png" alt="The two initial F segments above plinths, with the compact desk in front"><figcaption>Generation zero: one F and one segment in each reading.</figcaption></figure><figure><img loading="lazy" src="grammar-same-reading.png" alt="Two matching five-segment drawings at 90 degrees"><figcaption>After NEXT and HOLD: nine symbols, five segments, the same 90-degree reading.</figcaption></figure></div>
<figure><img loading="lazy" src="grammar-new-sentence.png" alt="A more elaborate live drawing beside the held first generation"><figcaption>Another NEXT at the new angle gives 49 symbols and 25 drawn segments. The held first generation remains beside it. The relation now reads DIFFERENT SENTENCES.</figcaption></figure>
<blockquote>HOLD gives us time beside a previous reading.</blockquote><p>The old fractal construction has become two distinct operations: rewriting symbols and interpreting their movement. The preset called Koch Curve uses a different replacement from our earlier equilateral snowflake. Its familiar name does not replace the work of reading its rule.</p></section>
<section><p class="step">02 / AN UNDRAWN SYMBOL</p><h2>An X, and no line.</h2><p>RESET, then PRESET three times reaches Plant at generation zero. X belongs to the rewriting alphabet; this turtle gives it no drawing action. NEXT produces F commands around X symbols. The absence of a line did not mean nothing could happen next.</p>
<div class="pair"><figure><img loading="lazy" src="grammar-plant.png" alt="Live and held Plant drawings with three segments, read at 30 and 25 degrees"><figcaption>Plant after one rewrite, HOLD and TURN. The brackets save and restore the turtle state; X symbols remain in the sentence.</figcaption></figure><figure><img loading="lazy" src="grammar-sierpinski.png" alt="The Sierpinski preset after its first rewrite at 120 degrees"><figcaption>Sierpinski's declared 120-degree angle now reaches the drawing. The old 90-degree limit clipped it.</figcaption></figure></div>
<p>These are planar drawings inside a three-dimensional room. Changing a turn does not automatically create a walkable branch or a connected junction where lines cross. Wanting to inhabit a drawing introduces another body and another set of requirements.</p></section>
<section><p class="step">03 / A LIMIT THAT NAMES ITSELF</p><h2>Read the rule after the difference.</h2><figure><img loading="lazy" src="grammar-controls.png" alt="Close view of six full-sized buttons and a small transparent tilted rule readout"><figcaption>NEXT / TURN / HOLD, then PRESET / RESET / RULE. The six targets fit within one standing position. This capture uses synthetic desktop pointer input; human headset reach remains to be tested.</figcaption></figure>
<figure><img loading="lazy" src="grammar-four-generations.png" alt="A dense fourth-generation live drawing beside a held early reading"><figcaption>Four requested generations: 1,249 symbols, 625 drawn segments. Display fitting keeps the whole outline within its allotted size; the printed prefix identifies its 120-symbol limit.</figcaption></figure>
<p>The lesson accepts at most 4,096 symbols. If the next replacement would exceed that budget, the editor retains the last complete generation and reports the requested and effective counts. It does not slice through a sentence halfway through a branch. The ordinary editor keeps its larger budget and sliders.</p><p>Seven presets remain a starting collection. Typing a new production at the physical desk is a later improvement. The custom-rule programming API has been repaired so that a supplied rule is no longer overwritten by the Binary Tree preset.</p></section>
<details><summary>Read the book passage</summary><article class="manuscript">__BOOK__</article></details>
<section><h2>The previous work remains available.</h2><div class="pair"><figure><img loading="lazy" src="grammar-collection.png" alt="The retained city grammar, string study, trees, bench and dark sphere in the rear collection"><figcaption>All eight earlier artifacts remain. Their own studies do not claim to share the editor's live sentence.</figcaption></figure><figure><img loading="lazy" src="grammar-before.png" alt="The archived earlier Grammar Lab entrance"><figcaption>Before this pass. The old map, manuscripts and pre-museum grid are archived for comparison.</figcaption></figure></div>
<p>A fourteen-row approach and side margins stage the primary. The earlier raised teaching platform and its central gap survive behind it. The unused teleporter hole is filled and the oversized science screen reduced. Walk around either end of the plinths, then rejoin the old central passage. One complete route was tested through the rear exit.</p></section>
<section><h2>What was tested?</h2><p>__CHECKS__ checks in the actual endless museum: all six controls through DesktopPlayer pointer input; held geometry and unchanged sentence while turning; generation counts; the invisible X; all seven ordinary presets; the custom-rule API; complete-generation budget handling; empty drawings; physical control size and height; and the walk to the exit.</p><p>No GDScript errors occurred. An older unrelated unresolved UID diagnostic remains. Human headset reach, comfort, readability and Quest frame time are pending. The retained secondary works have further encounters to develop. The user's open editor, live museum and saved hand were preserved.</p></section>
<section class="next"><h2>Next: what a branch inherits.</h2><p><a href="/necklace/thread?map=LSystems_Growth&amp;role=primary">LSystems_Growth</a> carries the saved turtle state forward. What happens when a nested branch changes length, then the interpreter returns to another branch? We will inspect the actual stack and compare a controlled change before writing its encounter.</p><p>The reusable improvement is a held reference: copy the actual data and geometry, name the changed variable, and disclose any fitting. It can help later field, grammar and body comparisons, provided each preserves its own conditions. <a href="spine-iteration.html">Complete the spine, then return →</a></p></section>
<footer><a href="grammar-verification.json">Runtime receipt</a> · <a href="grammar-previous-final.md">Earlier manuscript</a> · <a href="grammar-technical.md">Implementation</a> · <a href="grammar-critical.md">Critical questions</a></footer></main></body></html>'''
(O/'grammar-lab.html').write_text(page.replace('__CSS__',css).replace('__BOOK__',book).replace('__CHECKS__',str(r['checks'])),encoding='utf-8');assets.append('grammar-lab.html')
method=markdown.markdown((O/'spine-iteration.md').read_text(),extensions=['tables','toc'])
(O/'spine-iteration.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>First traverse. Then return. · Ada Research</title><style>'+css+'table{width:100%;border-collapse:collapse;font-size:.9rem}td,th{border-bottom:1px solid #425050;padding:.6rem;text-align:left;vertical-align:top}@media(max-width:650px){table{display:block;overflow-x:auto}}</style></head><body><main><nav><a href="grammar-lab.html">Grammar Lab</a><a href="fractal-learning-arc.html">Fractal learning arc</a><a href="/museum-progress">Museum progress</a></nav><article class="manuscript">'+method+'</article></main></body></html>',encoding='utf-8')
assets+=['spine-iteration.html','spine-iteration.md','fractal-learning-arc.html','fractal-learning-arc.json','fractal-learning-arc.md']
for src,dst in [(RUN/'run.json',E/'receipt.json'),(RUN/M/'probe_ca_edge_live.json',E/'runtime-report.json'),(RUN/M/'engine.log',E/'engine.log')]:shutil.copyfile(src,dst)
targets=['possible-bodies/'+a for a in assets];dump(E/'publish-targets.json',targets);dump(E/'publish-hashes.json',{a:hashlib.sha256((R/'doc/research'/a).read_bytes()).hexdigest() for a in targets})
print(f'Built Grammar Lab review: {len(targets)} assets; {r["checks"]} runtime checks.')
