from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="Escher_Impossible"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/foundations-escher-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]; tokens=[x.strip().split(":",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":13,"depth":14,"max_height":4},"four_artifacts":len(tokens)==4 and len(set(tokens))==4,"primary_focus":roles.get("escher_staircase")=="primary" and roles.get("penrose_triangle")=="primary","registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"ascending_loop":len(data["layers"]["structure"])==14 and len(data["layers"]["structure"][0])==13}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["escher_staircase","penrose_triangle"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"foundations-escher-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 270" role="img" aria-labelledby="e-title e-desc" xmlns="http://www.w3.org/2000/svg"><title id="e-title">Locally valid, globally impossible</title><desc id="e-desc">A staircase rises around a loop and returns to its starting height.</desc><rect width="900" height="270" rx="18" fill="#171329"/><path d="M120 205h180v-35h150v-35h150v-35h180" fill="none" stroke="#8ec9c1" stroke-width="22" stroke-linejoin="round"/><path d="M780 100v35H600v35H450v35H300v35H120" fill="none" stroke="#f58b8b" stroke-width="8" stroke-dasharray="10 10" stroke-linejoin="round"/><g fill="#eaf4f1" font-family="system-ui,sans-serif"><text x="450" y="45" text-anchor="middle" font-size="22">EVERY STEP CHECKS</text><text x="450" y="250" text-anchor="middle" font-size="18" fill="#f58b8b">THE LOOP DOES NOT</text></g></svg><figcaption>Local validity accumulates into a global impossibility at the closing step.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="foundations-escher-verification.json">Verification record</a></p>'
body="""<p class="date">Foundational crises · Hall 4 · 15 September 2026</p><h1>Locally Valid, Globally Impossible</h1><p class="lead">Each stair is ordinary. The completed loop is not. The contradiction appears only when local proofs are asked to share one world.</p><p><a href="/necklace/thread?map=Escher_Impossible&amp;role=primary">Primary artifacts and book</a> · <a href="/museum-progress?sequence=foundationscrisis">Museum progress</a></p>"""+diagram+"""<details><summary>Read the book passage</summary>"""+book+"""</details><h2>The viewpoint is part of the proof</h2><p>The staircase and Penrose triangle carry the book's primary argument. Around them, the trident and Magritte pipe separate an impossible assembly from a coherent representation that only becomes misleading when we confuse sign with thing.</p><p>Russell found a contradiction in containment; Gödel found a remainder in proof. Escher lets the body feel the same structure: every local check can pass while the whole refuses to close. Next is <strong>Brouwer_Intuitionism</strong>, where construction becomes the proposed escape.</p>"""+score
(O/"foundations-escher.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Locally Valid, Globally Impossible · Ada Research</title><style>'+css+'</style><main><nav><a href="foundations-godel.html">Previous hall</a><a href="/museum-progress?sequence=foundationscrisis">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["foundations-escher.html","foundations-escher-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
