from pathlib import Path
import hashlib, json, re, subprocess
import markdown

R=Path.cwd(); M="QFEP_Edge_Of_Chaos"; MAP=R/"commons/maps"/M; O=R/"doc/research/possible-bodies"; E=R/"doc/space/qfep-edge-of-chaos-2026-09-15"; E.mkdir(parents=True,exist_ok=True)
data=json.loads((MAP/"map_data.json").read_text(encoding="utf-8")); roles=json.loads((R/"commons/data/artifact_roles.json").read_text(encoding="utf-8"))["roles"][M]
tokens=[x.strip().split(":",1)[0].split("#",1)[0] for row in data["layers"]["interactables"] for x in row if x.strip()]
checks={"map_dimensions":data["map_info"]["dimensions"]=={"width":16,"depth":15,"max_height":4},"six_artifacts":len(tokens)==6 and len(set(tokens))==6,"primary_focus":roles.get("edge_of_chaos_unlocked")=="primary" and sum(v=="primary" for v in roles.values())==1,"registers_present":all((MAP/n).exists() for n in ["final.md","tutorial.md","technical.md","critical.md"]),"grid_structure":all(len(data["layers"][k])==15 and len(data["layers"][k][0])==16 for k in ["structure","utilities","interactables"])}
try: checks["registry_resolution"]=subprocess.run(["python","tools/check_map_tokens.py","--json"],capture_output=True,text=True,check=False).returncode==0
except OSError: checks["registry_resolution"]=False
verification={"hall":M,"date":"2026-09-15","checks":sum(checks.values()),"total_checks":len(checks),"failures":[k for k,v in checks.items() if not v],"checks_detail":checks,"tokens":tokens,"primary_artifacts":["edge_of_chaos_unlocked"],"source_sha256":{str((MAP/n).relative_to(R)):hashlib.sha256((MAP/n).read_bytes()).hexdigest() for n in ["map_data.json","final.md","tutorial.md","technical.md","critical.md"]}}
(E/"verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8"); (O/"qfep-edge-of-chaos-verification.json").write_text(json.dumps(verification,indent=2),encoding="utf-8")
css=re.search(r"<style>(.*?)</style>",(O/"iso-introduction.html").read_text(encoding="utf-8"),re.S)[1]; book=markdown.markdown((MAP/"final.md").read_text(encoding="utf-8"),extensions=["fenced_code"])
diagram='''<figure><svg viewBox="0 0 900 280" role="img" aria-labelledby="c-title c-desc" xmlns="http://www.w3.org/2000/svg"><title id="c-title">The edge between settling and scattering</title><desc id="c-desc">A parameter rail crosses stable, transitional and chaotic fields.</desc><rect width="900" height="280" rx="18" fill="#121827"/><path d="M100 185H800" stroke="#8fc7d5" stroke-width="8"/><rect x="130" y="105" width="170" height="58" rx="10" fill="#85c89a"/><rect x="365" y="75" width="170" height="88" rx="10" fill="#f0d48c"/><rect x="600" y="105" width="170" height="58" rx="10" fill="#d887b7"/><path d="M145 130h140M380 120l30-20m20 55l30-35m20 35l30-55m125 30h20m20-25h20m20 30h20m20-35h20" stroke="#171326" stroke-width="6"/><circle cx="450" cy="185" r="15" fill="#f5f0ff"/><g font-family="system-ui,sans-serif" text-anchor="middle" fill="#f5f0ff"><text x="215" y="205" font-size="18">stable</text><text x="450" y="205" font-size="18">edge</text><text x="685" y="205" font-size="18">chaotic</text><text x="450" y="42" font-size="22">a transition needs a defined observable</text><text x="450" y="260" font-size="17">the picture is evidence to examine, not a verdict</text></g></svg><figcaption>The edge is a testable transition only when the variable, timestep, and observable are held accountable.</figcaption></figure>'''
score=f'<p>{verification["checks"]}/{verification["total_checks"]} static checks passed. <a href="qfep-edge-of-chaos-verification.json">Verification record</a></p>'
body='<p class="date">QFEP laboratory · Edge of chaos · 15 September 2026</p><h1>A Pattern and the Way We Drive It</h1><p class="lead">A changing image does not tell us by itself whether the model or the calculation made it change. Hold the experiment steady long enough to find out.</p><p><a href="/necklace/thread?map=QFEP_Edge_Of_Chaos&amp;role=primary">Primary artifact and book</a> · <a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></p>'+diagram+'<details><summary>Read the book passage</summary>'+book+'</details><h2>Transition requires a witness</h2><p>The edge-of-chaos display is the sole primary artifact. Emergence zone, Turing pattern, edge core, and lambda slider remain secondary supports that make persistence, diffusion, and reseeding visible without declaring a universal critical point. The map’s own text names timestep and observable as the next repair.</p><p>The next hall, <a href="qfep-sandbox.html"><strong>QFEP_Sandbox</strong></a>, distributes control across several objects and asks which ones actually receive a change.</p>'+score
(O/"qfep-edge-of-chaos.html").write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>A Pattern and the Way We Drive It · Ada Research</title><style>'+css+'</style><main><nav><a href="qfep-phi-term.html">Previous hall</a><a href="qfep-sandbox.html">Next hall</a><a href="/museum-progress?sequence=qfeplaboratory">Museum progress</a></nav>'+body+'</main></html>',encoding="utf-8")
assets=["qfep-edge-of-chaos.html","qfep-edge-of-chaos-verification.json"]; (E/"publish-targets.json").write_text(json.dumps(["possible-bodies/"+a for a in assets],indent=2),encoding="utf-8"); (E/"publish-hashes.json").write_text(json.dumps({"possible-bodies/"+a:hashlib.sha256((O/a).read_bytes()).hexdigest() for a in assets},indent=2),encoding="utf-8"); print(json.dumps(verification))
