#!/usr/bin/env python3
"""lay_necklace.py - the generator (#4): a sequence's three orders -> a 2D map.

The whole pipeline closes here. three_orders gives the weighted optimized order + which pearls are
SPINE (the three orders agree) vs BRANCH (they fight). The size oracle (commons/data/artifact_sizes
.json, the same one gaze_ride uses) gives footprints. We lay the SPINE as a central corridor from
spawn to teleport, each pearl spaced by its own size; the BRANCHES become ALCOVES flanking the
corridor at their order position - the side-pools the 1D line couldn't hold. The map is the
optimized outcome of the pedagogical / ontological / critical orders, passed through the spatial gate.

Usage:  python tools/lay_necklace.py <sequence> [--max N] [--wp 1 --wo 1 --wc 1]
Writes  commons/maps/<Seq>_Necklace/map_data.json
"""
import json, os, sys, argparse
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from three_orders import compute

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRANCH = 0.45


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("seq")
    ap.add_argument("--max", type=int, default=16, help="cap pearls placed (keeps the corridor bounded)")
    ap.add_argument("--wp", type=float, default=1.0)
    ap.add_argument("--wo", type=float, default=1.0)
    ap.add_argument("--wc", type=float, default=1.0)
    a = ap.parse_args()

    d = compute(a.seq, min_pearls=3)
    if not d:
        print("no data for", a.seq)
        return
    n = d["n"]
    ws = (a.wp + a.wo + a.wc) or 1.0
    consensus = [(a.wp * d["ped"][i] + a.wo * d["onto"][i] + a.wc * d["crit"][i]) / ws for i in range(n)]
    order = sorted(range(n), key=lambda i: consensus[i])
    pearls = [d["pearls"][i] for i in order][: a.max]
    spread = {d["pearls"][i]: d["spread"][i] for i in range(n)}

    sz = json.load(open(os.path.join(ROOT, "commons", "data", "artifact_sizes.json"), encoding="utf-8")).get("sizes", {})

    def base(p):
        return float((sz.get(p) or {}).get("base_m", 1.0) or 1.0)

    ALCOVE = 4          # how far an alcove sits off the corridor centre
    MARGIN = 3          # corridor half-width clearance
    GAP = 2             # walk gap between spine pearls (cells)
    cx = ALCOVE + MARGIN
    W = cx + ALCOVE + MARGIN + 1

    occupied = set()

    def place(x, z, grid, token):
        while (x, z) in occupied:                    # nudge +z until the exact cell is free
            z += 1
        occupied.add((x, z))
        grid.setdefault(z, {})[x] = token
        return z

    cells = {}        # z -> {x: token}
    spine_zs = []
    z = 2
    side = 1
    last_base = 0.0
    n_spine = n_branch = 0
    for p in pearls:
        if spread[p] < BRANCH:                       # SPINE -> the corridor, spaced by size
            z += max(1, int(round(last_base / 2 + base(p) / 2))) + GAP
            z = place(cx, z, cells, p)
            spine_zs.append(z)
            last_base = base(p)
            n_spine += 1
        else:                                        # BRANCH -> an alcove beside the corridor
            zz = spine_zs[-1] if spine_zs else z
            place(cx + side * ALCOVE, zz, cells, p)
            side = -side
            n_branch += 1

    depth = z + 4
    inter = [[" "] * W for _ in range(depth)]
    struct = [["1"] * W for _ in range(depth)]
    util = [[" "] * W for _ in range(depth)]
    for zz, row in cells.items():
        if 0 <= zz < depth:
            for x, tok in row.items():
                if 0 <= x < W:
                    inter[zz][x] = tok

    util[1][cx] = "s"                                # spawn front-centre, facing up the corridor
    tz = depth - 2
    util[tz][cx] = "t"                               # teleport at the far end, on a void (convention)
    struct[tz][cx] = "0"

    md = {
        "layers": {"interactables": inter, "structure": struct, "utilities": util},
        "lighting": {"ambient_color": [0.6, 0.62, 0.68], "ambient_energy": 1.2,
                     "directional_light": {"color": [1.0, 0.97, 0.92], "direction": [-0.4, -0.8, -0.3],
                                           "enabled": True, "energy": 1.0}},
        "map_info": {
            "description": "Generated by lay_necklace.py from the three orders of '%s' (weights p%.1f o%.1f c%.1f). "
                           "Spine pearls (the orders agree) form the central corridor spawn->teleport, spaced by size; "
                           "branch pearls (the orders fight) sit in alcoves flanking it - the side-pools the 1D line "
                           "couldn't hold." % (a.seq, a.wp, a.wo, a.wc),
            "dimensions": {"width": float(W), "depth": float(depth), "max_height": 3.0},
            "format": "json", "lookup_name": "%s_Necklace" % a.seq.capitalize(),
            "name": "%s Necklace" % d.get("name", a.seq), "title": "%s - necklace" % a.seq, "version": "1.0"},
        "settings": {"background": {"color": [0.18, 0.2, 0.28], "type": "sky"},
                     "cube_size": 1.0, "enable_physics": True, "gutter": 0.0, "show_grid": True},
        "utility_definitions": {"t": {"description": "Return to the lab", "name": "Exit",
                                      "properties": {"action": "next_in_sequence"}, "type": "teleporter"}},
    }
    name = "%s_Necklace" % a.seq.capitalize()
    out = os.path.join(ROOT, "commons", "maps", name)
    os.makedirs(out, exist_ok=True)
    json.dump(md, open(os.path.join(out, "map_data.json"), "w", encoding="utf-8"), indent="\t")
    print("wrote %s : %dx%d  |  %d spine (corridor) + %d branch (alcoves)  of %d placed (%d in sequence)"
          % (name, W, depth, n_spine, n_branch, len(pearls), n))


if __name__ == "__main__":
    main()
