"""Write the best placement for each top strategy as an actual Godot map.

Reads doc/placement_research/results.json, picks the top 3 strategies
(by score), writes commons/maps/Placement_<Strategy>/map_data.json so they
can be walked in VR and captured with the standard pipeline.

Run:
  python tools/placement_to_map.py            # writes top 3
  python tools/placement_to_map.py --all      # writes all 10

Capture (per map):
  godot_console --path . --xr-mode off --no-window \
    --script res://commons/testing/capture_multi_angle.gd -- \
    --mode=map --target=Placement_Hybrid
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "doc" / "placement_research" / "results.json"
MAPS_DIR = ROOT / "commons" / "maps"


def build_map_data(strategy: str, room: dict, placements: list[dict],
                   artifact_defs: list[dict]) -> dict:
    """Convert placement → 3-layer map_data.json."""
    width = room["width"]
    depth = room["depth"]

    # Build empty layers
    structure = [["2"] * width for _ in range(depth)]   # floor everywhere
    utilities = [[" "] * width for _ in range(depth)]
    interactables = [[" "] * width for _ in range(depth)]

    # Place spawn + teleporter
    utilities[room["spawn_row"]][room["spawn_col"]] = "sp"
    utilities[room["teleporter_row"]][room["teleporter_col"]] = "t"

    # Place artifacts — use the lookup_name directly in interactables layer
    # Each artifact placed at its (row, col) top-left corner — for now we just
    # put one token at that cell; the GridSystem doesn't multi-cell render
    # artifacts on the artifact layer (the spatial_needs describes intent, not
    # rendering). The footprint shows up as clearance/empty cells around it.
    for p in placements:
        r, c = p["row"], p["col"]
        if 0 <= r < depth and 0 <= c < width:
            # rotation 180 = face the spawn (back-centre)
            interactables[r][c] = f"{p['artifact']}:180:0.0"

    return {
        "map_info": {
            "name": f"Placement_{strategy.replace('_', ' ').title().replace(' ', '_')}",
            "lookup_name": f"Placement_{strategy.replace('_', ' ').title().replace(' ', '_')}",
            "description": (
                f"Placement auto-research — best result for the '{strategy}' "
                f"strategy. Generated by tools/placement_research.py + "
                f"tools/placement_to_map.py from the 4-artifact test scenario. "
                f"This map exists so the abstract placement scores can be "
                f"walked and eye-checked."
            ),
            "version": "0.1-auto-research",
            "format": "json",
            "created_from": "tools/placement_research.py 2026-05-15",
            "dimensions": {
                "width": width,
                "depth": depth,
                "max_height": 3
            },
            "metadata": {
                "category": "research_artifact",
                "estimated_time": "1 minute",
                "auto_research_strategy": strategy,
            },
            "title": f"Placement: {strategy}"
        },
        "utility_definitions": {
            "sp": {"name": "Spawn", "description": "Player spawn point", "type": "spawn"},
            "t":  {"name": "Exit Portal",
                   "description": "Step here to leave",
                   "type": "teleporter",
                   "properties": {"action": "next_in_sequence"}}
        },
        "documentation": {
            "summary": f"Placement_{strategy} — auto-research output map",
            "layout": (
                f"{width}×{depth} room. Spawn at back-centre "
                f"(row {room['spawn_row']}, col {room['spawn_col']}), "
                f"teleporter at front-centre "
                f"(row {room['teleporter_row']}, col {room['teleporter_col']}). "
                f"Four artifacts placed by the '{strategy}' strategy at the "
                f"positions listed in doc/placement_research/results.json."
            ),
            "objective": "Walk the room and eye-check the placement.",
            "key_elements": [
                f"Spawn at ({room['spawn_row']}, {room['spawn_col']})",
                f"Teleporter at ({room['teleporter_row']}, {room['teleporter_col']}),",
                *[f"{p['artifact']} at ({p['row']}, {p['col']})" for p in placements],
            ]
        },
        "lighting": {
            "ambient_color": [0.30, 0.32, 0.40],
            "ambient_energy": 0.9,
            "directional_light": {
                "enabled": True,
                "direction": [-0.3, -1.0, -0.2],
                "energy": 0.7
            }
        },
        "settings": {
            "player_spawn_height": 0.5,
            "floor_tile_size": 1.0
        },
        "layers": {
            "structure": structure,
            "utilities": utilities,
            "interactables": interactables,
        },
    }


def write_intent_md(strategy: str, score: float, placements: list[dict],
                    metrics: dict, dest: Path) -> None:
    lines = []
    lines.append(f"Concept: A {len(placements)}-artifact map produced by the "
                 f"`{strategy}` placement strategy during placement auto-research. "
                 f"The strategy scored **{score:.3f}** on the constraint-satisfaction "
                 f"scorer; this map exists so that abstract score can be eye-checked.")
    lines.append("")
    lines.append(f"Actualizes: A research artifact. Not part of the curriculum spine. "
                 f"Lives alongside other Placement_* maps so different strategies' "
                 f"outputs can be compared side-by-side in VR.")
    lines.append("")
    lines.append(f"Sequence role: None — this is a free-floating research map. "
                 f"Generated by `tools/placement_research.py` and written by "
                 f"`tools/placement_to_map.py` on 2026-05-15.")
    lines.append("")
    lines.append("Technical angle: Strategy outputs (row, col) per artifact; the writer "
                 "places each as `<lookup_name>:180:0.0` in the interactables layer. "
                 "Footprint and clearance are virtual (encoded in `spatial_needs`) — the "
                 "scorer measured them, the map walks them as empty cells around each "
                 "token. No structure modifications.")
    lines.append("")
    lines.append("Critical angle: The placement was chosen by an automated scorer that "
                 "knows 10 constraint metrics. Walking it tells you which metrics translate "
                 "to legible spatial experience and which don't.")
    lines.append("")
    lines.append("Key artifacts:")
    for p in placements:
        lines.append(f"- {p['artifact']} at ({p['row']}, {p['col']})")
    lines.append("")
    lines.append("Score breakdown:")
    short_keys = {
        "footprint_in_bounds": "footprint",
        "no_overlap": "no_overlap",
        "clearance_satisfied": "clearance",
        "wall_backing_satisfied": "wall_backing",
        "isolation_satisfied": "isolation",
        "cluster_satisfied": "cluster",
        "preferred_zone_match": "zone",
        "reachability": "reachability",
        "spawn_walkable": "spawn_walkable",
        "teleporter_walkable": "teleporter_walkable",
    }
    for k, label in short_keys.items():
        v = metrics.get(k, 0.0)
        lines.append(f"- {label}: {v:.2f}")
    lines.append("")
    lines.append("Gap: This map is a witness, not an argument. The map_grammar audit will "
                 "score it; image-feedback in VR will reveal whether the constraint scorer's "
                 "best is also the player's best.")
    dest.write_text("\n".join(lines), encoding="utf-8")


def write_blurb_md(strategy: str, score: float, dest: Path) -> None:
    text = (
        f"A 10×6 room with four artifacts placed by the `{strategy}` strategy. "
        f"Walk in at the back. The teleporter is straight ahead. Between you and "
        f"the exit: four artifacts arranged where the auto-research scorer's "
        f"weighted total said the placement scored best ({score:.3f}/1.000).\n\n"
        f"This is a research witness, not a teaching room. The placement was chosen "
        f"by a Python scorer that measures ten constraint metrics — footprint, "
        f"clearance, wall-backing, isolation, cluster proximity, preferred zone, "
        f"reachability, spawn-walkability. Walking this room tells you what those "
        f"numbers feel like underfoot.\n\n"
        f"Compare it to `Placement_Hybrid` or `Placement_Random` to see the strategy "
        f"differences in 3D. The same four artifacts, same room — different "
        f"placement engines.\n"
    )
    dest.write_text(text, encoding="utf-8")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--all", action="store_true", help="write all strategies, not just top 3")
    args = p.parse_args()

    with open(RESULTS, "r", encoding="utf-8") as f:
        data = json.load(f)

    room = data["room"]
    artifacts = data["artifacts"]

    # Rank by best score
    ranked = sorted(data["best_placements"].items(), key=lambda kv: -kv[1]["score"])
    if not args.all:
        ranked = ranked[:3]

    written = []
    for strategy, bp in ranked:
        map_name = f"Placement_{strategy.replace('_', ' ').title().replace(' ', '_')}"
        out_dir = MAPS_DIR / map_name
        out_dir.mkdir(exist_ok=True)

        map_data = build_map_data(strategy, room, bp["placements"], artifacts)
        (out_dir / "map_data.json").write_text(
            json.dumps(map_data, indent="\t"), encoding="utf-8")

        # Get per-metric scores
        metrics = data["summary"][strategy]["per_metric"]
        metrics["total"] = data["summary"][strategy]["best"]
        write_intent_md(strategy, bp["score"], bp["placements"], metrics, out_dir / "intent.md")
        write_blurb_md(strategy, bp["score"], out_dir / "blurb.md")
        written.append((strategy, map_name, bp["score"]))

    print(f"wrote {len(written)} maps:")
    for s, name, score in written:
        print(f"  commons/maps/{name}/   ({s} · score={score:.3f})")
    print()
    print("capture in Godot (single map):")
    if written:
        n = written[0][1]
        print(f"  godot_console --path . --xr-mode off --no-window \\")
        print(f"    --script res://commons/testing/capture_multi_angle.gd -- \\")
        print(f"    --mode=map --target={n}")


if __name__ == "__main__":
    main()
