"""Port the five Waves/Chance/Noise SceneTree probes to Node scripts that run under
project startup (commons/testing/probe_live.tscn), so the project's autoloads exist
and XR Tools pickables compile. The SceneTree originals stay as they are; the ports
are regenerated from them by this script and carry a header saying so.

  python tools/port_wcn_probes_live.py

Writes commons/testing/probe_wcn_<name>_live.gd for intro, random_definition,
noise_pair, pendulum, sine_space. Output files get a _live suffix (JSON and PNGs)
so the SceneTree results are never overwritten by a live run.
"""
import io, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NAMES = ['intro', 'random_definition', 'noise_pair', 'pendulum', 'sine_space', 'effect_sound', 'air_music', 'synthesis_lab', 'entropy', 'remove', 'walk', 'gaussian', 'mushrooms', 'game', 'points']
JSON_NAMES = {'intro': 'probe_intro', 'random_definition': 'probe_random_definition',
              'noise_pair': 'probe_noise_pair', 'pendulum': 'probe_pendulum', 'sine_space': 'probe_sine_space',
              'effect_sound': 'probe_effect_sound', 'air_music': 'probe_air_music', 'synthesis_lab': 'probe_synthesis_lab', 'entropy': 'probe_entropy', 'remove': 'probe_remove', 'walk': 'probe_walk', 'gaussian': 'probe_gaussian', 'mushrooms': 'probe_mushrooms', 'game': 'probe_game', 'points': 'probe_points'}

SUBS = [
    (r'^extends SceneTree\s*$', 'extends Node'),
    (r'^func _initialize\(\) -> void: run\.call_deferred\(\)\s*$', 'func _ready() -> void: run.call_deferred()'),
    (r'\broot\.add_child\(', 'get_tree().root.add_child('),
    (r'\broot\.get_texture\(\)', 'get_viewport().get_texture()'),
    (r'\broot\.get_camera_3d\(\)', 'get_viewport().get_camera_3d()'),
    (r'\broot\.get_child_count\(\)', 'get_tree().root.get_child_count()'),
    (r'\broot\.find_children\(', 'get_tree().root.find_children('),
    (r'\bawait process_frame\b', 'await get_tree().process_frame'),
    (r'\bawait physics_frame\b', 'await get_tree().physics_frame'),
    (r'(?<![\w.])create_timer\(', 'get_tree().create_timer('),
    (r'(?<![\w.])current_scene = em\b', 'get_tree().current_scene = em'),
    (r'(?<![\w.])quit\(', 'get_tree().quit('),
    (r'(?<![\w.])node_added\.connect\(', 'get_tree().node_added.connect('),
    (r'(?<![\w.])node_removed\.connect\(', 'get_tree().node_removed.connect('),
]

HEADER = '''## LIVE PORT — generated by tools/port_wcn_probes_live.py from {src}. Do not edit;
## edit the SceneTree probe and regenerate. Runs under project startup (probe_live.tscn
## with --probe={name}), so the project's autoloads exist and XR Tools pickables compile.
## Outputs carry a _live suffix.
'''

def port(name: str) -> Path:
    src = ROOT / 'commons/testing' / f'probe_wcn_{name}.gd'
    dst = ROOT / 'commons/testing' / f'probe_wcn_{name}_live.gd'
    text = io.open(src, encoding='utf-8').read()
    out_lines = []
    for line in text.splitlines():
        for pat, rep in SUBS:
            line = re.sub(pat, rep, line)
        out_lines.append(line)
    s = '\n'.join(out_lines) + '\n'
    base = JSON_NAMES[name]
    s = s.replace(f'"{base}.json"', f'"{base}_live.json"')
    s = re.sub(r'"(' + re.escape(base) + r'[A-Za-z_]*)\.png"', r'"\1_live.png"', s)
    assert 'extends Node' in s and 'SceneTree' not in s.split('\n', 1)[0], name
    assert 'await process_frame' not in s and 'await physics_frame' not in s, name
    # a bare `root.` that no rule rewrote is a parse error under a Node
    # (2026-09-10: root.get_camera_3d cost a run)
    leftover = re.findall(r'(?<![\w.])root\.[A-Za-z_]+', s)
    assert not leftover, (name, leftover)
    io.open(dst, 'w', encoding='utf-8', newline='\n').write(HEADER.format(src=src.name, name=name) + s)
    return dst

if __name__ == '__main__':
    for n in NAMES:
        p = port(n)
        print('wrote', p.relative_to(ROOT))
