# double_snake_meander.gd
# Greek key meander generated by TWO mirrored self-avoiding walks that dance
# around each other.  Snake A traces the dark meander line on the outer edge,
# Snake B traces the mirrored light counter-meander on the inner edge.
# Their interlocking territories — separated by a thin grout line — produce
# the classic Greek key pattern.
#
# The key insight: if you color the dark meander line as Snake A's territory and
# the light background as Snake B's territory, then B's shape is ALSO a meander
# — the vertical mirror of A.  The two snakes' territories interlock perfectly,
# filling the entire border strip with no gaps.
#
# @identity
#   essence: two mirrored self-avoiding walks whose territories interlock into the Greek key
#   desire: players see that the meander is not one line but the RELATIONSHIP between two
#   critical_parameter: band_width (b) controls the line thickness; border_depth = 4*b
#   triggers: instantiation or apply_grid_config
#   emerges: understanding that symmetry and opposition create pattern
#   needs: [implemented] dual snake territory bitmap, tiling, ArrayMesh
#   relationships: exact_meander_floor (single-line approach), meander_threshold_floor (tiled approach)
#   truth: the meander is a conversation between two walks

extends Node3D
class_name DoubleSnakeMeander

const MosaicPalette = preload("res://commons/artifacts/pompeii_mosaic_floor/mosaic_palette.gd")

@export var floor_size: Vector2 = Vector2(1.2, 0.9)
@export var band_width: int = 5
@export var grid_cells: int = 80
@export var dot_spacing: int = 4
@export var color_dark: Color = MosaicPalette.DARK
@export var color_light: Color = MosaicPalette.LIGHT
@export var grout_color: Color = MosaicPalette.GROUT
@export_range(0.0, 0.1) var grout_width_fraction: float = 0.02
@export_range(0.0, 1.0) var wear_level: float = 0.3

var _mi: MeshInstance3D
var _body: StaticBody3D

# Derived from band_width
var _border_depth: int
var _period: int


func _ready() -> void:
	_build()


func apply_grid_config(config: Dictionary) -> void:
	var fs = config.get("floor_size", null)
	if fs is Array and fs.size() >= 2:
		floor_size = Vector2(float(fs[0]), float(fs[1]))
	band_width = int(config.get("band_width", band_width))
	grid_cells = int(config.get("grid_cells", grid_cells))
	dot_spacing = int(config.get("dot_spacing", dot_spacing))
	wear_level = float(config.get("wear_level", wear_level))
	_build()


func _build() -> void:
	if _mi:
		_mi.queue_free()
		_mi = null
	if _body:
		_body.queue_free()
		_body = null

	var b := band_width
	# Border depth = 4*b (fits exactly one spiral depth)
	# Period = 4*b (one complete key unit width)
	_border_depth = 4 * b
	_period = 4 * b
	var d := _border_depth

	var aspect := floor_size.x / floor_size.y
	var gh := grid_cells
	var gw := int(round(gh * aspect))
	if gw < d * 2 + _period:
		gw = d * 2 + _period
	if gh < d * 2 + _period:
		gh = d * 2 + _period

	var px_m := floor_size.y / float(gh)
	var fw := gw * px_m
	var fh := gh * px_m

	# Build pixel grid
	var grid := []
	for r in gh:
		var row := []
		row.resize(gw)
		row.fill(0)
		grid.append(row)

	# Build the key tile: d rows x period cols
	# 1 = Snake A territory (dark), 2 = Snake B territory (light)
	var tile := _build_key_tile(d, b)

	# Tile each border
	_tile_bottom(grid, gw, gh, d, tile)
	_tile_top(grid, gw, gh, d, tile)
	_tile_left(grid, gw, gh, d, tile)
	_tile_right(grid, gw, gh, d, tile)

	# Corners: solid dark
	for r in range(0, d):
		for c in range(0, d):
			grid[r][c] = 1
	for r in range(0, d):
		for c in range(gw - d, gw):
			grid[r][c] = 1
	for r in range(gh - d, gh):
		for c in range(0, d):
			grid[r][c] = 1
	for r in range(gh - d, gh):
		for c in range(gw - d, gw):
			grid[r][c] = 1

	# Build mesh
	var dark_verts := PackedVector3Array()
	var light_verts := PackedVector3Array()
	var grout_verts := PackedVector3Array()

	for r in gh:
		for c in gw:
			var in_border := (r < d or r >= gh - d or c < d or c >= gw - d)
			if not in_border:
				continue
			var wx := c * px_m
			var wz := r * px_m
			if grid[r][c] == 2:
				light_verts = _add_rect(light_verts, wx, wz, px_m, px_m)
			else:
				dark_verts = _add_rect(dark_verts, wx, wz, px_m, px_m)

	# Dark interior
	var fx0 := d
	var fy0 := d
	var fx1 := gw - d
	var fy1 := gh - d
	for r in range(fy0, fy1):
		for c in range(fx0, fx1):
			dark_verts = _add_rect(dark_verts, c * px_m, r * px_m, px_m, px_m)

	# Polka dots
	var field_w := fx1 - fx0
	var field_h := fy1 - fy0
	var dots_x := int(field_w / dot_spacing)
	var dots_z := int(field_h / dot_spacing)
	var margin_x := (field_w - dots_x * dot_spacing) * 0.5
	var margin_z := (field_h - dots_z * dot_spacing) * 0.5
	for dz in range(dots_z):
		for dx in range(dots_x):
			var base_px := margin_x + (dx + 0.5) * dot_spacing
			var base_pz := margin_z + (dz + 0.5) * dot_spacing
			var jx := (_hash_2d(dx, dz) - 0.5) * 0.8
			var jz := (_hash_2d(dx + 97, dz + 53) - 0.5) * 0.8
			var px_x := clampf(fx0 + base_px + jx, fx0 + 0.5, fx1 - 1.5)
			var px_z := clampf(fy0 + base_pz + jz, fy0 + 0.5, fy1 - 1.5)
			light_verts = _add_rect(light_verts, px_x * px_m, px_z * px_m, px_m, px_m)

	# Grout
	if grout_width_fraction > 0.001:
		var grout_w := px_m * grout_width_fraction * 10.0
		var half := grout_w * 0.5
		for gy in range(0, gh + 1):
			grout_verts = _add_rect(grout_verts, 0.0, gy * px_m - half, fw, grout_w)
		for gx in range(0, gw + 1):
			grout_verts = _add_rect(grout_verts, gx * px_m - half, 0.0, grout_w, fh)

	for i in dark_verts.size():
		dark_verts[i].y = 0.0
	for i in light_verts.size():
		light_verts[i].y = 0.001
	for i in grout_verts.size():
		grout_verts[i].y = -0.001

	var arr_mesh := ArrayMesh.new()
	if dark_verts.size() > 0:
		var arrays := []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = dark_verts
		arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		arr_mesh.surface_set_material(arr_mesh.get_surface_count() - 1, MosaicPalette.create_material(color_dark, wear_level))
	if light_verts.size() > 0:
		var arrays := []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = light_verts
		arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		arr_mesh.surface_set_material(arr_mesh.get_surface_count() - 1, MosaicPalette.create_material(color_light, wear_level))
	if grout_verts.size() > 0:
		var arrays := []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = grout_verts
		arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		arr_mesh.surface_set_material(arr_mesh.get_surface_count() - 1, MosaicPalette.create_material(grout_color, wear_level))

	_mi = MeshInstance3D.new()
	_mi.mesh = arr_mesh
	_mi.position = Vector3(-fw * 0.5, 0.005, -fh * 0.5)
	add_child(_mi)

	_body = StaticBody3D.new()
	var col := CollisionShape3D.new()
	var box := BoxShape3D.new()
	box.size = Vector3(fw, 0.01, fh)
	col.shape = box
	_body.add_child(col)
	_body.position = Vector3(0, 0.005, 0)
	add_child(_body)

	print("[DoubleSnakeMeander] Built %dx%d grid, border=%d, band=%d, period=%d" % [gw, gh, d, b, _period])


# ──────────────────────────────────────────────────────────────
# The dual-snake key tile
# ──────────────────────────────────────────────────────────────
#
# One tile is d rows x (4*b) cols.  d = 4*b, so the tile is square.
# Row 0 = outer edge (e.g. bottom of floor), row d-1 = inner edge.
#
# Snake A (dark, val=1) traces a clockwise angular spiral from the outer edge.
# Snake B (light, val=2) fills everything Snake A doesn't — and when you look
# at B's territory alone, it forms a counter-clockwise angular spiral from
# the inner edge.  B IS A's vertical mirror.
#
# With b=3, d=12, period=12:
#
#   Row 0  (outer): 1 1 1 1 1 1 1 1 1 2 2 2
#   Row 1          : 1 1 1 1 1 1 1 1 1 2 2 2
#   Row 2          : 1 1 1 1 1 1 1 1 1 2 2 2
#   Row 3          : 1 1 1 2 2 2 1 1 1 2 2 2
#   Row 4          : 1 1 1 2 2 2 1 1 1 2 2 2
#   Row 5          : 1 1 1 2 2 2 1 1 1 2 2 2
#   Row 6          : 1 1 1 2 2 2 1 1 1 1 1 1
#   Row 7          : 1 1 1 2 2 2 1 1 1 1 1 1
#   Row 8          : 1 1 1 2 2 2 1 1 1 1 1 1
#   Row 9          : 1 1 1 2 2 2 2 2 2 2 2 2
#   Row 10         : 1 1 1 2 2 2 2 2 2 2 2 2
#   Row 11 (inner) : 1 1 1 2 2 2 2 2 2 2 2 2
#
# Snake A territory: left bar (cols 0-2, all rows) + outer run (cols 3-8, rows 0-2)
#   + right arm (cols 6-8, rows 3-8) + inner hook (cols 6-11, rows 6-8).
# Snake B territory: the complement — also a spiral but from the inner edge.
#
# When tiled, Snake A's left bar connects to the previous tile's inner hook,
# and the pattern produces the classic Greek key meander.

func _build_key_tile(d: int, b: int) -> Array:
	var period := 4 * b
	var tile := []
	for r in d:
		var row := []
		row.resize(period)
		# Default to Snake B (2)
		row.fill(2)
		tile.append(row)

	# Snake A territory (1):
	# Left vertical bar: cols 0..b-1, ALL rows
	for r in range(d):
		for c in range(b):
			tile[r][c] = 1

	# Outer horizontal run: rows 0..b-1, cols b..3b-1
	for r in range(b):
		for c in range(b, 3 * b):
			tile[r][c] = 1

	# Right vertical arm: rows b..3b-1, cols 2b..3b-1
	for r in range(b, 3 * b):
		for c in range(2 * b, 3 * b):
			tile[r][c] = 1

	# Inner hook horizontal: rows 2b..3b-1, cols 3b..4b-1
	for r in range(2 * b, 3 * b):
		for c in range(3 * b, 4 * b):
			tile[r][c] = 1

	# Everything else is already Snake B (2) from the fill.
	# Let's verify B's territory is also a spiral:
	# B has: right bar (cols 3b..4b-1, rows 3b..4b-1... no)
	# B territory = all cells with value 2:
	#   Rows 0..b-1, cols 3b..4b-1 (outer right)
	#   Rows b..2b-1, cols b..2b-1 (center square)
	#   Rows b..2b-1, cols 3b..4b-1 (right strip)
	#   Rows 2b..3b-1, cols b..2b-1 (inner center)
	#   Rows 3b..4b-1, cols b..4b-1 (inner run)
	#
	# B's connected territory across tile boundaries:
	# When tiled, B at cols 3b..4b-1 of tile N connects to B at cols b..2b-1
	# of tile N+1 via the inner run (rows 3b..4b-1).
	# B's shape: inner bar (rows 3b..4b-1, cols b..4b-1) connects to
	# left-center (rows b..3b-1, cols b..2b-1) which connects to
	# outer right (rows 0..b-1, cols 3b..4b-1) of the PREVIOUS tile.
	# This IS a spiral from the inner edge — the mirror of A.

	return tile


# ──────────────────────────────────────────────────────────────
# Tiling each border
# ──────────────────────────────────────────────────────────────

func _tile_bottom(grid: Array, gw: int, gh: int, d: int, tile: Array) -> void:
	# Bottom border: rows gh-d..gh-1, cols d..gw-d-1
	# Row 0 of tile = outer edge = row gh-1 of grid (bottommost)
	# So tile row r -> grid row (gh - 1 - r) ... wait, depends on convention.
	# Row 0 = outer edge. For bottom border, outer = large row number.
	# So tile[r][c] -> grid[gh - d + r][col]
	# But row 0 should be at the bottom (outer edge = row gh-1).
	# tile[0] is outer -> grid[gh-1]
	# tile[d-1] is inner -> grid[gh-d]
	# So: tile[r] -> grid[gh - 1 - r]
	var c_start := d
	var c_end := gw - d
	for c_off in range(c_end - c_start):
		var tc := c_off % _period
		var gc := c_start + c_off
		for r in range(d):
			var gr := gh - 1 - r
			grid[gr][gc] = tile[r][tc]


func _tile_top(grid: Array, gw: int, gh: int, d: int, tile: Array) -> void:
	# Top border: rows 0..d-1, cols d..gw-d-1
	# Outer edge = row 0 (top). Mirror of bottom.
	# tile[0] is outer -> grid[0]
	# tile[d-1] is inner -> grid[d-1]
	# For the mirror effect on the meander: swap A/B territories (vertical mirror)
	# tile[r] -> tile[d-1-r] with A<->B swap
	var c_start := d
	var c_end := gw - d
	for c_off in range(c_end - c_start):
		var tc := c_off % _period
		var gc := c_start + c_off
		for r in range(d):
			var gr := r
			var src: int = tile[d - 1 - r][tc]
			# Swap A and B for the mirror
			if src == 1:
				grid[gr][gc] = 2
			else:
				grid[gr][gc] = 1


func _tile_left(grid: Array, gw: int, gh: int, d: int, tile: Array) -> void:
	# Left border: cols 0..d-1, rows d..gh-d-1
	# Rotate tile 90 degrees CW.
	# tile[r][c] (r=row in tile, c=col in tile period)
	# After 90 CW rotation: tile_row -> col (measured from outer), tile_col -> row
	# Outer edge for left border = col 0.
	# tile[0] (outer) -> gc=0
	# tile[d-1] (inner) -> gc=d-1
	# tile row r -> gc = r (no wait, outer = col 0, so r=0 -> gc=0)
	# tile col c -> gr offset along border
	var r_start := d
	var r_end := gh - d
	for r_off in range(r_end - r_start):
		var tc := r_off % _period
		var gr := r_start + r_off
		for r in range(d):
			var gc := r  # outer at col 0
			grid[gr][gc] = tile[r][tc]


func _tile_right(grid: Array, gw: int, gh: int, d: int, tile: Array) -> void:
	# Right border: cols gw-d..gw-1, rows d..gh-d-1
	# Outer edge = col gw-1.
	# tile[0] (outer) -> gc = gw-1
	# tile[d-1] (inner) -> gc = gw-d
	# So tile row r -> gc = gw - 1 - r
	# Reverse direction along border + swap A/B for mirror
	var r_start := d
	var r_end := gh - d
	for r_off in range(r_end - r_start):
		var tc := r_off % _period
		var gr := r_end - 1 - r_off  # reverse direction
		for r in range(d):
			var gc := gw - 1 - r
			var src: int = tile[r][tc]
			# Swap for mirror
			if src == 1:
				grid[gr][gc] = 2
			else:
				grid[gr][gc] = 1


# ──────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────

func _add_rect(verts: PackedVector3Array, x: float, z: float, w: float, h: float) -> PackedVector3Array:
	verts.append(Vector3(x, 0, z))
	verts.append(Vector3(x + w, 0, z))
	verts.append(Vector3(x + w, 0, z + h))
	verts.append(Vector3(x, 0, z))
	verts.append(Vector3(x + w, 0, z + h))
	verts.append(Vector3(x, 0, z + h))
	return verts


func _hash_2d(x: int, y: int) -> float:
	var n := x * 374761393 + y * 668265263
	n = (n ^ (n >> 13)) * 1274126177
	n = n ^ (n >> 16)
	return float(n & 0x7FFFFFFF) / float(0x7FFFFFFF)
