# double_snake_meander.gd
# Greek key meander generated by TWO mirrored self-avoiding walks that dance
# around each other.  Snake A hugs the outer edge, Snake B hugs the inner edge.
# Their interlocking territories produce the classic meander pattern.
#
# @identity
#   essence: two mirrored self-avoiding walks whose territories interlock into the Greek key
#   desire: players see that the meander is not one line but the RELATIONSHIP between two
#   critical_parameter: border_depth and band_width control the spiral proportions
#   triggers: instantiation or apply_grid_config
#   emerges: understanding that symmetry and opposition create pattern
#   needs: [implemented] dual snake tracing, flood fill territory, ArrayMesh
#   relationships: exact_meander_floor (single-line approach), meander_threshold_floor (tiled approach)
#   truth: the meander is a conversation between two walks

extends Node3D
class_name DoubleSnakeMeander

const MosaicPalette = preload("res://commons/artifacts/pompeii_mosaic_floor/mosaic_palette.gd")

@export var floor_size: Vector2 = Vector2(1.2, 0.9)
@export var border_depth: int = 20
@export var band_width: int = 3
@export var grid_cells: int = 100
@export var dot_spacing: int = 4
@export var color_dark: Color = MosaicPalette.DARK
@export var color_light: Color = MosaicPalette.LIGHT
@export var grout_color: Color = MosaicPalette.GROUT
@export_range(0.0, 0.1) var grout_width_fraction: float = 0.02
@export_range(0.0, 1.0) var wear_level: float = 0.3

var _mi: MeshInstance3D
var _body: StaticBody3D


func _ready() -> void:
	_build()


func apply_grid_config(config: Dictionary) -> void:
	var fs = config.get("floor_size", null)
	if fs is Array and fs.size() >= 2:
		floor_size = Vector2(float(fs[0]), float(fs[1]))
	border_depth = int(config.get("border_depth", border_depth))
	band_width = int(config.get("band_width", band_width))
	grid_cells = int(config.get("grid_cells", grid_cells))
	dot_spacing = int(config.get("dot_spacing", dot_spacing))
	wear_level = float(config.get("wear_level", wear_level))
	_build()


func _build() -> void:
	if _mi:
		_mi.queue_free()
		_mi = null
	if _body:
		_body.queue_free()
		_body = null

	var b := band_width
	var d := border_depth

	# Total grid dimensions
	var aspect := floor_size.x / floor_size.y
	var gh := grid_cells
	var gw := int(round(gh * aspect))

	# Ensure gw, gh are large enough for border
	if gw < d * 2 + 4 or gh < d * 2 + 4:
		gw = maxi(gw, d * 2 + 4)
		gh = maxi(gh, d * 2 + 4)

	var px_m := floor_size.y / float(gh)
	var fw := gw * px_m
	var fh := gh * px_m

	# Build the pixel grid: 0=unassigned, 1=snake_A (dark), 2=snake_B (light)
	var grid := []
	for r in gh:
		var row := []
		row.resize(gw)
		row.fill(0)
		grid.append(row)

	# --- Generate meander for each border side ---
	# Bottom border: rows (gh - d) to (gh - 1)
	_draw_bottom_border(grid, gw, gh, d, b)
	# Top border: rows 0 to (d - 1)
	_draw_top_border(grid, gw, gh, d, b)
	# Left border: cols 0 to (d - 1)
	_draw_left_border(grid, gw, gh, d, b)
	# Right border: cols (gw - d) to (gw - 1)
	_draw_right_border(grid, gw, gh, d, b)

	# --- Corners: solid dark ---
	_fill_grid_rect(grid, gw, gh, 0, 0, d, d, 1)
	_fill_grid_rect(grid, gw, gh, 0, gw - d, d, d, 1)
	_fill_grid_rect(grid, gw, gh, gh - d, 0, d, d, 1)
	_fill_grid_rect(grid, gw, gh, gh - d, gw - d, d, d, 1)

	# --- Build mesh ---
	var dark_verts := PackedVector3Array()
	var light_verts := PackedVector3Array()
	var grout_verts := PackedVector3Array()

	# Border pixels from grid
	for r in gh:
		for c in gw:
			var in_border := (r < d or r >= gh - d or c < d or c >= gw - d)
			if not in_border:
				continue
			var wx := c * px_m
			var wz := r * px_m
			if grid[r][c] == 2:
				light_verts = _add_rect(light_verts, wx, wz, px_m, px_m)
			else:
				dark_verts = _add_rect(dark_verts, wx, wz, px_m, px_m)

	# Dark interior field
	var fx0 := d
	var fy0 := d
	var fx1 := gw - d
	var fy1 := gh - d
	for r in range(fy0, fy1):
		for c in range(fx0, fx1):
			dark_verts = _add_rect(dark_verts, c * px_m, r * px_m, px_m, px_m)

	# Polka dots in the field
	var field_w := fx1 - fx0
	var field_h := fy1 - fy0
	var dots_x := int(field_w / dot_spacing)
	var dots_z := int(field_h / dot_spacing)
	var margin_x := (field_w - dots_x * dot_spacing) * 0.5
	var margin_z := (field_h - dots_z * dot_spacing) * 0.5
	for dz in range(dots_z):
		for dx in range(dots_x):
			var base_px := margin_x + (dx + 0.5) * dot_spacing
			var base_pz := margin_z + (dz + 0.5) * dot_spacing
			var jx := (_hash_2d(dx, dz) - 0.5) * 0.8
			var jz := (_hash_2d(dx + 97, dz + 53) - 0.5) * 0.8
			var px_x := clampf(fx0 + base_px + jx, fx0 + 0.5, fx1 - 1.5)
			var px_z := clampf(fy0 + base_pz + jz, fy0 + 0.5, fy1 - 1.5)
			light_verts = _add_rect(light_verts, px_x * px_m, px_z * px_m, px_m, px_m)

	# Grout lines
	if grout_width_fraction > 0.001:
		var grout_w := px_m * grout_width_fraction * 10.0
		var half := grout_w * 0.5
		for gy in range(0, gh + 1):
			grout_verts = _add_rect(grout_verts, 0.0, gy * px_m - half, fw, grout_w)
		for gx in range(0, gw + 1):
			grout_verts = _add_rect(grout_verts, gx * px_m - half, 0.0, grout_w, fh)

	# Y offsets to prevent z-fighting
	for i in dark_verts.size():
		dark_verts[i].y = 0.0
	for i in light_verts.size():
		light_verts[i].y = 0.001
	for i in grout_verts.size():
		grout_verts[i].y = -0.001

	# ArrayMesh
	var arr_mesh := ArrayMesh.new()
	if dark_verts.size() > 0:
		var arrays := []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = dark_verts
		arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		arr_mesh.surface_set_material(arr_mesh.get_surface_count() - 1, MosaicPalette.create_material(color_dark, wear_level))
	if light_verts.size() > 0:
		var arrays := []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = light_verts
		arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		arr_mesh.surface_set_material(arr_mesh.get_surface_count() - 1, MosaicPalette.create_material(color_light, wear_level))
	if grout_verts.size() > 0:
		var arrays := []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = grout_verts
		arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		arr_mesh.surface_set_material(arr_mesh.get_surface_count() - 1, MosaicPalette.create_material(grout_color, wear_level))

	_mi = MeshInstance3D.new()
	_mi.mesh = arr_mesh
	_mi.position = Vector3(-fw * 0.5, 0.005, -fh * 0.5)
	add_child(_mi)

	_body = StaticBody3D.new()
	var col := CollisionShape3D.new()
	var box := BoxShape3D.new()
	box.size = Vector3(fw, 0.01, fh)
	col.shape = box
	_body.add_child(col)
	_body.position = Vector3(0, 0.005, 0)
	add_child(_body)

	print("[DoubleSnakeMeander] Built %dx%d grid, border=%d, band=%d" % [gw, gh, d, b])


# ──────────────────────────────────────────────────────────────
# Snake path generation for horizontal borders
# ──────────────────────────────────────────────────────────────
# One key unit for Snake A (the outer/dark snake) on the bottom border:
#
# The border strip is d rows tall, running left to right.
# Row 0 is the outermost (bottom of screen), row d-1 is innermost.
#
# Snake A starts at the outer edge (row 0) and traces:
#   1. RIGHT b cells (along outer edge)
#   2. UP d-1 cells (full height to inner edge)
#   3. RIGHT b cells (along inner edge)
#   4. DOWN (d - 1 - 2*b) cells (partial return)
#   5. LEFT b cells (hook back)
#   6. DOWN remaining to outer edge
#   7. RIGHT b cells (exit to next key)
#
# Snake B is the exact vertical mirror: starts at inner edge (row d-1).
# Where A goes UP, B goes DOWN at the same X.
#
# The period of one key unit = 4*b cells wide.
# After tracing both snakes on a pixel grid, we flood-fill territories.

func _trace_snake_a_key(grid: Array, gw: int, _gh: int, r_base: int, c_start: int, d: int, b: int, flip_v: bool) -> int:
	# Traces one key unit of Snake A in the bottom border strip.
	# r_base: top row of the border strip in grid coords
	# c_start: starting column
	# d: border depth (number of rows)
	# b: band width
	# flip_v: if true, mirror vertically (for top border)
	# Returns: the column after this key unit
	#
	# We paint a thick line (b pixels wide) along the snake path.
	# Snake A territory = 1 (dark)

	var val := 1  # Snake A = dark
	var c := c_start

	# Helper to set a cell with optional vertical flip
	var _set := func(row_in_strip: int, col: int) -> void:
		if col < 0 or col >= gw:
			return
		var actual_r: int
		if flip_v:
			actual_r = r_base + (d - 1 - row_in_strip)
		else:
			actual_r = r_base + row_in_strip
		if actual_r >= 0 and actual_r < _gh:
			grid[actual_r][col] = val

	# The inner depth for the hook: how far back the hook goes
	var hook_depth := d - 1 - 2 * b
	if hook_depth < b:
		hook_depth = b

	# Segment 1: RIGHT b along outer edge (row 0..b-1)
	for dx in range(b):
		for dy in range(b):
			_set.call(dy, c + dx)
	c += b

	# Segment 2: UP full height — left wall of key (rows 0..d-1)
	for dy in range(d):
		for dx in range(b):
			_set.call(dy, c - b + dx)

	# Segment 3: RIGHT b along inner edge (rows d-b..d-1)
	for dx in range(b):
		for dy in range(b):
			_set.call(d - 1 - dy, c + dx)
	c += b

	# Segment 4: DOWN partial — inner right wall (rows d-1 down to 2*b)
	for dy in range(d - 2 * b):
		for dx in range(b):
			_set.call(d - 1 - dy, c - b + dx)

	# Segment 5: LEFT b — inner hook horizontal (rows 2*b..3*b-1... well, b rows at row 2*b)
	for dx in range(b):
		for dy in range(b):
			_set.call(2 * b + dy, c - b - dx)

	# Segment 6: DOWN to outer edge from the hook (rows b..2*b)
	# Actually we need to go from row 2*b down to row 0
	for dy in range(2 * b):
		for dx in range(b):
			_set.call(dy, c - 2 * b + dx)

	# Segment 7: RIGHT b — exit to next key
	for dx in range(b):
		for dy in range(b):
			_set.call(dy, c + dx)
	c += b

	return c


func _trace_snake_b_key(grid: Array, gw: int, _gh: int, r_base: int, c_start: int, d: int, b: int, flip_v: bool) -> int:
	# Snake B is the vertical mirror of Snake A.
	# Snake B territory = 2 (light)
	# B starts at the inner edge (row d-1) and mirrors A's path.

	var val := 2  # Snake B = light
	var c := c_start

	var _set := func(row_in_strip: int, col: int) -> void:
		if col < 0 or col >= gw:
			return
		var actual_r: int
		if flip_v:
			actual_r = r_base + (d - 1 - row_in_strip)
		else:
			actual_r = r_base + row_in_strip
		if actual_r >= 0 and actual_r < _gh:
			# Only set if not already claimed by Snake A
			if grid[actual_r][col] == 0:
				grid[actual_r][col] = val

	# Mirror: where A uses row r, B uses row (d-1-r)
	var mirror := func(r: int) -> int:
		return d - 1 - r

	# Segment 1: RIGHT b along inner edge (rows d-1..d-b)
	for dx in range(b):
		for dy in range(b):
			_set.call(mirror.call(dy), c + dx)
	c += b

	# Segment 2: DOWN full height — left wall of B's key
	for dy in range(d):
		for dx in range(b):
			_set.call(mirror.call(dy), c - b + dx)

	# Segment 3: RIGHT b along outer edge
	for dx in range(b):
		for dy in range(b):
			_set.call(mirror.call(d - 1 - dy), c + dx)
	c += b

	# Segment 4: UP partial — inner wall
	for dy in range(d - 2 * b):
		for dx in range(b):
			_set.call(mirror.call(d - 1 - dy), c - b + dx)

	# Segment 5: LEFT b — inner hook
	for dx in range(b):
		for dy in range(b):
			_set.call(mirror.call(2 * b + dy), c - b - dx)

	# Segment 6: UP to inner edge from hook
	for dy in range(2 * b):
		for dx in range(b):
			_set.call(mirror.call(dy), c - 2 * b + dx)

	# Segment 7: RIGHT b — exit
	for dx in range(b):
		for dy in range(b):
			_set.call(mirror.call(dy), c + dx)
	c += b

	return c


# ──────────────────────────────────────────────────────────────
# Border drawing: trace both snakes along each side
# ──────────────────────────────────────────────────────────────

func _draw_bottom_border(grid: Array, gw: int, gh: int, d: int, b: int) -> void:
	var r_base := gh - d
	var key_period := 4 * b
	var run_start := d  # skip corner
	var run_end := gw - d

	# First: paint outer rail (b rows) as dark, inner rail as dark
	_fill_grid_rect(grid, gw, gh, gh - b, run_start, b, run_end - run_start, 1)
	_fill_grid_rect(grid, gw, gh, gh - d, run_start, b, run_end - run_start, 1)

	# Trace Snake A keys along the bottom
	var c := run_start
	while c + key_period <= run_end:
		c = _trace_snake_a_key(grid, gw, gh, r_base, c, d, b, false)

	# Trace Snake B keys (offset by half period for interlocking)
	c = run_start + 2 * b
	while c + key_period <= run_end:
		c = _trace_snake_b_key(grid, gw, gh, r_base, c, d, b, false)

	# Fill remaining unassigned border cells
	_fill_unassigned_border_strip(grid, gw, gh, r_base, d, run_start, run_end)


func _draw_top_border(grid: Array, gw: int, gh: int, d: int, b: int) -> void:
	var r_base := 0
	var key_period := 4 * b
	var run_start := d
	var run_end := gw - d

	# Outer and inner rails
	_fill_grid_rect(grid, gw, gh, 0, run_start, b, run_end - run_start, 1)
	_fill_grid_rect(grid, gw, gh, d - b, run_start, b, run_end - run_start, 1)

	# Snake A (flipped vertically for top)
	var c := run_start
	while c + key_period <= run_end:
		c = _trace_snake_a_key(grid, gw, gh, r_base, c, d, b, true)

	# Snake B
	c = run_start + 2 * b
	while c + key_period <= run_end:
		c = _trace_snake_b_key(grid, gw, gh, r_base, c, d, b, true)

	_fill_unassigned_border_strip(grid, gw, gh, r_base, d, run_start, run_end)


func _draw_left_border(grid: Array, gw: int, gh: int, d: int, b: int) -> void:
	# For left/right borders, we generate a horizontal strip then rotate into place.
	var run_start := d
	var run_end := gh - d
	var run_len := run_end - run_start
	var key_period := 4 * b

	# Create a temporary horizontal strip
	var strip := []
	for r in d:
		var row := []
		row.resize(run_len)
		row.fill(0)
		strip.append(row)

	# Trace snakes on the strip
	var c := 0
	while c + key_period <= run_len:
		c = _trace_strip_snake_a(strip, run_len, d, c, b)
	c = 2 * b
	while c + key_period <= run_len:
		c = _trace_strip_snake_b(strip, run_len, d, c, b)

	# Fill rails on strip
	for sc in range(run_len):
		for sr in range(b):
			strip[sr][sc] = 1 if strip[sr][sc] == 0 else strip[sr][sc]
			strip[d - 1 - sr][sc] = 1 if strip[d - 1 - sr][sc] == 0 else strip[d - 1 - sr][sc]

	# Fill unassigned on strip
	for sr in d:
		for sc in run_len:
			if strip[sr][sc] == 0:
				strip[sr][sc] = 1 if sr < d / 2 else 2

	# Rotate 90 CW and place: strip(sr, sc) -> grid(run_start + sc, d - 1 - sr)
	for sr in d:
		for sc in run_len:
			var gr := run_start + sc
			var gc := d - 1 - sr
			if gr < gh and gc < gw:
				grid[gr][gc] = strip[sr][sc]


func _draw_right_border(grid: Array, gw: int, gh: int, d: int, b: int) -> void:
	var run_start := d
	var run_end := gh - d
	var run_len := run_end - run_start
	var key_period := 4 * b

	var strip := []
	for r in d:
		var row := []
		row.resize(run_len)
		row.fill(0)
		strip.append(row)

	var c := 0
	while c + key_period <= run_len:
		c = _trace_strip_snake_a(strip, run_len, d, c, b)
	c = 2 * b
	while c + key_period <= run_len:
		c = _trace_strip_snake_b(strip, run_len, d, c, b)

	for sc in range(run_len):
		for sr in range(b):
			strip[sr][sc] = 1 if strip[sr][sc] == 0 else strip[sr][sc]
			strip[d - 1 - sr][sc] = 1 if strip[d - 1 - sr][sc] == 0 else strip[d - 1 - sr][sc]

	for sr in d:
		for sc in run_len:
			if strip[sr][sc] == 0:
				strip[sr][sc] = 1 if sr < d / 2 else 2

	# Rotate 90 CCW and place: strip(sr, sc) -> grid(run_start + run_len - 1 - sc, gw - d + sr)
	for sr in d:
		for sc in run_len:
			var gr := run_start + run_len - 1 - sc
			var gc := gw - d + sr
			if gr >= 0 and gr < gh and gc < gw:
				grid[gr][gc] = strip[sr][sc]


# ──────────────────────────────────────────────────────────────
# Strip-based snake tracing (for rotation to vertical borders)
# ──────────────────────────────────────────────────────────────

func _trace_strip_snake_a(strip: Array, strip_w: int, d: int, c_start: int, b: int) -> int:
	var c := c_start

	var _set := func(row: int, col: int) -> void:
		if col < 0 or col >= strip_w or row < 0 or row >= d:
			return
		strip[row][col] = 1

	# Segment 1: RIGHT b along outer edge (rows 0..b-1)
	for dx in range(b):
		for dy in range(b):
			_set.call(dy, c + dx)
	c += b

	# Segment 2: Full height vertical wall
	for dy in range(d):
		for dx in range(b):
			_set.call(dy, c - b + dx)

	# Segment 3: RIGHT b along inner edge
	for dx in range(b):
		for dy in range(b):
			_set.call(d - 1 - dy, c + dx)
	c += b

	# Segment 4: DOWN partial from inner edge
	for dy in range(d - 2 * b):
		for dx in range(b):
			_set.call(d - 1 - dy, c - b + dx)

	# Segment 5: LEFT b hook
	for dx in range(b):
		for dy in range(b):
			_set.call(2 * b + dy, c - b - dx)

	# Segment 6: DOWN to outer edge
	for dy in range(2 * b):
		for dx in range(b):
			_set.call(dy, c - 2 * b + dx)

	# Segment 7: RIGHT b exit
	for dx in range(b):
		for dy in range(b):
			_set.call(dy, c + dx)
	c += b

	return c


func _trace_strip_snake_b(strip: Array, strip_w: int, d: int, c_start: int, b: int) -> int:
	var c := c_start

	var _set := func(row: int, col: int) -> void:
		if col < 0 or col >= strip_w or row < 0 or row >= d:
			return
		if strip[row][col] == 0:
			strip[row][col] = 2

	var mirror := func(r: int) -> int:
		return d - 1 - r

	# Segment 1: RIGHT b along inner edge
	for dx in range(b):
		for dy in range(b):
			_set.call(mirror.call(dy), c + dx)
	c += b

	# Segment 2: Full height vertical wall
	for dy in range(d):
		for dx in range(b):
			_set.call(mirror.call(dy), c - b + dx)

	# Segment 3: RIGHT b along outer edge
	for dx in range(b):
		for dy in range(b):
			_set.call(mirror.call(d - 1 - dy), c + dx)
	c += b

	# Segment 4: UP partial
	for dy in range(d - 2 * b):
		for dx in range(b):
			_set.call(mirror.call(d - 1 - dy), c - b + dx)

	# Segment 5: LEFT b hook
	for dx in range(b):
		for dy in range(b):
			_set.call(mirror.call(2 * b + dy), c - b - dx)

	# Segment 6: UP to inner edge
	for dy in range(2 * b):
		for dx in range(b):
			_set.call(mirror.call(dy), c - 2 * b + dx)

	# Segment 7: RIGHT b exit
	for dx in range(b):
		for dy in range(b):
			_set.call(mirror.call(dy), c + dx)
	c += b

	return c


# ──────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────

func _fill_unassigned_border_strip(grid: Array, gw: int, gh: int, r_base: int, d: int, c_start: int, c_end: int) -> void:
	# Any unassigned cell: assign based on proximity to outer vs inner edge
	for r in range(r_base, mini(r_base + d, gh)):
		var row_in_strip := r - r_base
		for c in range(c_start, mini(c_end, gw)):
			if grid[r][c] == 0:
				# Closer to outer edge = dark (A), closer to inner = light (B)
				if row_in_strip < d / 2:
					grid[r][c] = 1
				else:
					grid[r][c] = 2


func _fill_grid_rect(grid: Array, gw: int, gh: int, r0: int, c0: int, h: int, w: int, val: int) -> void:
	for r in range(maxi(0, r0), mini(r0 + h, gh)):
		for c in range(maxi(0, c0), mini(c0 + w, gw)):
			if grid[r][c] == 0:
				grid[r][c] = val


func _add_rect(verts: PackedVector3Array, x: float, z: float, w: float, h: float) -> PackedVector3Array:
	verts.append(Vector3(x, 0, z))
	verts.append(Vector3(x + w, 0, z))
	verts.append(Vector3(x + w, 0, z + h))
	verts.append(Vector3(x, 0, z))
	verts.append(Vector3(x + w, 0, z + h))
	verts.append(Vector3(x, 0, z + h))
	return verts


func _hash_2d(x: int, y: int) -> float:
	var n := x * 374761393 + y * 668265263
	n = (n ^ (n >> 13)) * 1274126177
	n = n ^ (n >> 16)
	return float(n & 0x7FFFFFFF) / float(0x7FFFFFFF)
